-- ============================================================
-- 초등 예문 UPDATE SQL
-- Supabase SQL Editor에서 실행하세요
-- elem_3: 180개 / elem_4: 200개 / elem_5: 220개 / elem_6: 200개
-- ============================================================

-- [elem_3] 초등 3학년 (5~8단어, 매우 쉬운 문장)
UPDATE words SET example_sentence = 'I like to play with you.' WHERE word = 'you' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat bread in the morning.' WHERE word = 'bread' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We have art class on Thursday.' WHERE word = 'Thursday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'They play in the park.' WHERE word = 'they' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The doctor helps sick people.' WHERE word = 'doctor' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The grass is green and soft.' WHERE word = 'grass' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Please open the door for me.' WHERE word = 'door' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I run fast in the park.' WHERE word = 'run' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The leaves fall in fall.' WHERE word = 'fall' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This year I am nine.' WHERE word = 'year' AND level = 'elem_3';
UPDATE words SET example_sentence = 'That is his red bag.' WHERE word = 'his' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Today is a sunny day.' WHERE word = 'today' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have one big dog.' WHERE word = 'one' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We sing songs on Tuesday.' WHERE word = 'Tuesday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My dog likes to run.' WHERE word = 'dog' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My name is Junho.' WHERE word = 'name' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wear blue pants today.' WHERE word = 'pants' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We eat pizza on Friday.' WHERE word = 'Friday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'She is my best friend.' WHERE word = 'friend' AND level = 'elem_3';
UPDATE words SET example_sentence = 'She is my big sister.' WHERE word = 'she' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have two cats at home.' WHERE word = 'have' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We play by the river.' WHERE word = 'river' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I can see a star at night.' WHERE word = 'star' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat rice in the morning.' WHERE word = 'morning' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Please help me with this.' WHERE word = 'please' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I go home after school.' WHERE word = 'home' AND level = 'elem_3';
UPDATE words SET example_sentence = 'It is very hot today.' WHERE word = 'hot' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We have fun this week.' WHERE word = 'week' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I play with my friend.' WHERE word = 'play' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Today is my birthday!' WHERE word = 'birthday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The baby is very small.' WHERE word = 'baby' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We rest on Saturday.' WHERE word = 'Saturday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'That is her pink bag.' WHERE word = 'her' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I draw a nice picture.' WHERE word = 'picture' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Come here and sit down.' WHERE word = 'come' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Put the food on the plate.' WHERE word = 'plate' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Can you help me, please?' WHERE word = 'help' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The cat is white and soft.' WHERE word = 'white' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I go to school by bus.' WHERE word = 'go' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My sister likes to sing.' WHERE word = 'sister' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have four books.' WHERE word = 'four' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I like apples and bananas.' WHERE word = 'like' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The slow turtle walks.' WHERE word = 'slow' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The moon shines at night.' WHERE word = 'night' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The green tree is big.' WHERE word = 'green' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My mother cooks good food.' WHERE word = 'mother' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I like the yellow flower.' WHERE word = 'yellow' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I put on my shoes.' WHERE word = 'shoes' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We swim in the summer.' WHERE word = 'summer' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat rice for lunch.' WHERE word = 'eat' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I can speak English.' WHERE word = 'speak' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My foot hurts a little.' WHERE word = 'foot' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Open your mouth wide.' WHERE word = 'mouth' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My room is very clean.' WHERE word = 'room' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I drink cold water.' WHERE word = 'water' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wear my warm coat.' WHERE word = 'coat' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The book is on the table.' WHERE word = 'table' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I am sorry I am late.' WHERE word = 'sorry' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Let''s make a big cake.' WHERE word = 'make' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I can count to nine.' WHERE word = 'nine' AND level = 'elem_3';
UPDATE words SET example_sentence = 'What is your name?' WHERE word = 'your' AND level = 'elem_3';
UPDATE words SET example_sentence = 'There are seven days.' WHERE word = 'seven' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I walk to school every day.' WHERE word = 'walk' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Sit on the chair, please.' WHERE word = 'chair' AND level = 'elem_3';
UPDATE words SET example_sentence = 'It is cold in winter.' WHERE word = 'cold' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wash my head every day.' WHERE word = 'head' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I am eight years old.' WHERE word = 'eight' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The sun is very hot.' WHERE word = 'sun' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I move my arm up.' WHERE word = 'arm' AND level = 'elem_3';
UPDATE words SET example_sentence = 'She goes to the hospital.' WHERE word = 'hospital' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I read books in the afternoon.' WHERE word = 'afternoon' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My cat sleeps on the bed.' WHERE word = 'cat' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Look at that big bird!' WHERE word = 'that' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This gift is for you.' WHERE word = 'gift' AND level = 'elem_3';
UPDATE words SET example_sentence = 'You are a good boy.' WHERE word = 'good' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The tree is very tall.' WHERE word = 'tree' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I clean my room today.' WHERE word = 'clean' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Bye! See you tomorrow!' WHERE word = 'bye' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I read a book every day.' WHERE word = 'read' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have a red ball.' WHERE word = 'red' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I take the bus to school.' WHERE word = 'bus' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We have English class today.' WHERE word = 'class' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My leg is very long.' WHERE word = 'leg' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I love my family so much.' WHERE word = 'family' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I ride my bike to the park.' WHERE word = 'bike' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wash my hands with soap.' WHERE word = 'wash' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I am happy today!' WHERE word = 'happy' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I go to school at eight.' WHERE word = 'school' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have six toy cars.' WHERE word = 'six' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Look at the clock on the wall.' WHERE word = 'clock' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I love my mom and dad.' WHERE word = 'love' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I kick the ball hard.' WHERE word = 'ball' AND level = 'elem_3';
UPDATE words SET example_sentence = 'It is a good day today.' WHERE word = 'day' AND level = 'elem_3';
UPDATE words SET example_sentence = 'No, I do not want it.' WHERE word = 'no' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Close your eye and sleep.' WHERE word = 'eye' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The sky is blue today.' WHERE word = 'blue' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I play in the rain.' WHERE word = 'rain' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I am a student at school.' WHERE word = 'student' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Hold my hand, please.' WHERE word = 'hand' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We go to church on Sunday.' WHERE word = 'Sunday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Take this book with you.' WHERE word = 'take' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I play soccer on Wednesday.' WHERE word = 'Wednesday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The dog has big ears.' WHERE word = 'ear' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The moon is big tonight.' WHERE word = 'moon' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The mountain is very high.' WHERE word = 'mountain' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I give mom a flower.' WHERE word = 'flower' AND level = 'elem_3';
UPDATE words SET example_sentence = 'It snows a lot in winter.' WHERE word = 'winter' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Yes, I like ice cream.' WHERE word = 'yes' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My father is very tall.' WHERE word = 'father' AND level = 'elem_3';
UPDATE words SET example_sentence = 'What is your age?' WHERE word = 'age' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I sleep at nine every night.' WHERE word = 'sleep' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I see a fish in the water.' WHERE word = 'fish' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I like to listen to music.' WHERE word = 'music' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This month is very cold.' WHERE word = 'month' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wear a blue shirt today.' WHERE word = 'shirt' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The nurse is very kind.' WHERE word = 'nurse' AND level = 'elem_3';
UPDATE words SET example_sentence = 'That is a bad idea.' WHERE word = 'bad' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I write with a pen.' WHERE word = 'pen' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Look at the big bird!' WHERE word = 'look' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have two hands.' WHERE word = 'two' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We go to the store.' WHERE word = 'store' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat a red apple.' WHERE word = 'apple' AND level = 'elem_3';
UPDATE words SET example_sentence = 'A white cloud is in the sky.' WHERE word = 'cloud' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Monday is the first day.' WHERE word = 'Monday' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We are friends.' WHERE word = 'we' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have three cats.' WHERE word = 'three' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My teacher is very nice.' WHERE word = 'teacher' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat rice every day.' WHERE word = 'rice' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I swim in the sea.' WHERE word = 'sea' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We play in the park.' WHERE word = 'park' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My desk is very clean.' WHERE word = 'desk' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The car goes very fast.' WHERE word = 'fast' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I play with my toy car.' WHERE word = 'toy' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I read a fun book.' WHERE word = 'book' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I feel sad when it rains.' WHERE word = 'sad' AND level = 'elem_3';
UPDATE words SET example_sentence = 'A bird sits on the tree.' WHERE word = 'bird' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The snow is white and cold.' WHERE word = 'snow' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I drink milk from a cup.' WHERE word = 'cup' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have five fingers.' WHERE word = 'five' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Open the window, please.' WHERE word = 'window' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Stand up and say hello.' WHERE word = 'stand' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My dad has a big car.' WHERE word = 'car' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I drink water every day.' WHERE word = 'drink' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We go to the zoo today.' WHERE word = 'zoo' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have a big dog.' WHERE word = 'big' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The sky is blue and nice.' WHERE word = 'sky' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I eat a banana for lunch.' WHERE word = 'banana' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I have a black cat.' WHERE word = 'black' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My bag is red and big.' WHERE word = 'bag' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Flowers grow in spring.' WHERE word = 'spring' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Close the door, please.' WHERE word = 'close' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I will see you tomorrow.' WHERE word = 'tomorrow' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Sit down on the chair.' WHERE word = 'sit' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Thanks for the gift!' WHERE word = 'thanks' AND level = 'elem_3';
UPDATE words SET example_sentence = 'She has a pretty smile.' WHERE word = 'smile' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Listen to the teacher.' WHERE word = 'listen' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This is my red ball.' WHERE word = 'my' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The wind blows very hard.' WHERE word = 'wind' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We see cows on the farm.' WHERE word = 'farm' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This food is very good.' WHERE word = 'food' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Open the book to page one.' WHERE word = 'open' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I write my name on it.' WHERE word = 'write' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I see a bird in the tree.' WHERE word = 'see' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I drink milk every morning.' WHERE word = 'milk' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This game is very fun.' WHERE word = 'game' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I give a gift to my friend.' WHERE word = 'give' AND level = 'elem_3';
UPDATE words SET example_sentence = 'The baby is very small.' WHERE word = 'small' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I sleep on my bed.' WHERE word = 'bed' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I need a new pencil.' WHERE word = 'pencil' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We eat dinner in the evening.' WHERE word = 'evening' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I can count to ten.' WHERE word = 'ten' AND level = 'elem_3';
UPDATE words SET example_sentence = 'We sing a happy song.' WHERE word = 'song' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I wear a red hat.' WHERE word = 'hat' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My nose is very cold.' WHERE word = 'nose' AND level = 'elem_3';
UPDATE words SET example_sentence = 'He is my best friend.' WHERE word = 'he' AND level = 'elem_3';
UPDATE words SET example_sentence = 'This is my new book.' WHERE word = 'this' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I am a student.' WHERE word = 'I' AND level = 'elem_3';
UPDATE words SET example_sentence = 'Hello! How are you today?' WHERE word = 'hello' AND level = 'elem_3';
UPDATE words SET example_sentence = 'I jump up and down.' WHERE word = 'jump' AND level = 'elem_3';
UPDATE words SET example_sentence = 'My brother plays with me.' WHERE word = 'brother' AND level = 'elem_3';

-- [elem_4] 초등 4학년 (6~10단어)
UPDATE words SET example_sentence = 'She likes to dance with her friends.' WHERE word = 'dance' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The north side of the city is cold.' WHERE word = 'north' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We do not go to school on a holiday.' WHERE word = 'holiday' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I wear my school uniform every day.' WHERE word = 'uniform' AND level = 'elem_4';
UPDATE words SET example_sentence = 'That toy is too expensive for me.' WHERE word = 'expensive' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We have enough food for everyone.' WHERE word = 'enough' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She is a very kind person.' WHERE word = 'kind' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My family goes to church on Sunday.' WHERE word = 'church' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Flowers bloom in the springtime.' WHERE word = 'springtime' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We laugh when we hear a funny story.' WHERE word = 'laugh' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The children run around the playground.' WHERE word = 'around' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I need a piece of paper to draw.' WHERE word = 'paper' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We saw a big castle on the hill.' WHERE word = 'castle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This song is very popular at school.' WHERE word = 'popular' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I wear my blue jacket when it is cold.' WHERE word = 'jacket' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My favorite singer is on TV today.' WHERE word = 'singer' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We cheer for our team at the game.' WHERE word = 'cheer' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The farmer grows food on the farm.' WHERE word = 'farmer' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I want a robot for my birthday.' WHERE word = 'robot' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The elephant is the biggest animal here.' WHERE word = 'elephant' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I like to wear my blue jeans.' WHERE word = 'jeans' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The white rabbit runs very fast.' WHERE word = 'rabbit' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I collect stamps from many countries.' WHERE word = 'collect' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Birds fly south in the winter.' WHERE word = 'south' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This math problem is very easy.' WHERE word = 'easy' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I cannot decide which color to pick.' WHERE word = 'decide' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This pencil is cheap but very good.' WHERE word = 'cheap' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I ate half of the pizza.' WHERE word = 'half' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We eat dinner at six every day.' WHERE word = 'dinner' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The artist painted a beautiful picture.' WHERE word = 'artist' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My shoes are different from yours.' WHERE word = 'different' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The waiter brings us our food.' WHERE word = 'waiter' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I go shopping with my mom.' WHERE word = 'shopping' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The cat hides in the corner of the room.' WHERE word = 'corner' AND level = 'elem_4';
UPDATE words SET example_sentence = 'How much does this book cost?' WHERE word = 'cost' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Today is a very special day for me.' WHERE word = 'special' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She wears a pretty silver ring.' WHERE word = 'silver' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The red balloon flew up into the sky.' WHERE word = 'balloon' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Can you count from one to ten?' WHERE word = 'count' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We stayed at a nice hotel by the sea.' WHERE word = 'hotel' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The garden is full of colorful flowers.' WHERE word = 'colorful' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went to a fun festival last week.' WHERE word = 'festival' AND level = 'elem_4';
UPDATE words SET example_sentence = 'A pretty butterfly sat on the flower.' WHERE word = 'butterfly' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The children play outside after school.' WHERE word = 'outside' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I eat eggs and toast for breakfast.' WHERE word = 'breakfast' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The weather can change very quickly.' WHERE word = 'change' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The lake is very deep in the middle.' WHERE word = 'deep' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Many animals live in the jungle.' WHERE word = 'jungle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The weather is sunny and warm today.' WHERE word = 'weather' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Watch out! There is danger ahead.' WHERE word = 'danger' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I look at myself in the mirror.' WHERE word = 'mirror' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Eating fruit is very healthy for you.' WHERE word = 'healthy' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We watched the game at the stadium.' WHERE word = 'stadium' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My neighbor is very friendly to us.' WHERE word = 'friendly' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This is the best day of my life!' WHERE word = 'best' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Are you ready for the test?' WHERE word = 'ready' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My parent came to school today.' WHERE word = 'parent' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I put the photos in my album.' WHERE word = 'album' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Please bring your book to class.' WHERE word = 'bring' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The mountain is very high.' WHERE word = 'high' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She is a member of the art club.' WHERE word = 'member' AND level = 'elem_4';
UPDATE words SET example_sentence = 'He is the best player on the team.' WHERE word = 'player' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I enjoy reading books after dinner.' WHERE word = 'enjoy' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The kangaroo can jump very far.' WHERE word = 'kangaroo' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I eat my food with a fork.' WHERE word = 'fork' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I took a nice photo with my camera.' WHERE word = 'camera' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My uncle lives in a big city.' WHERE word = 'uncle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Please carry this box for me.' WHERE word = 'carry' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The ocean is very big and blue.' WHERE word = 'ocean' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The queen lives in a big castle.' WHERE word = 'queen' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The police officer helped the children.' WHERE word = 'police' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The giraffe has a very long neck.' WHERE word = 'giraffe' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This book is very useful for me.' WHERE word = 'useful' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went fishing at the lake.' WHERE word = 'lake' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The pilot flies the plane in the sky.' WHERE word = 'pilot' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I love to see the beauty of nature.' WHERE word = 'nature' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I bought a ticket for the movie.' WHERE word = 'ticket' AND level = 'elem_4';
UPDATE words SET example_sentence = 'He used a ladder to climb the wall.' WHERE word = 'ladder' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I need to finish my homework now.' WHERE word = 'finish' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I am so excited about the trip!' WHERE word = 'excited' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I want to be a doctor in the future.' WHERE word = 'future' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Do you have a match to start a fire?' WHERE word = 'match' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Please be quiet in the library.' WHERE word = 'quiet' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We walked across the long bridge.' WHERE word = 'bridge' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I am very hungry after school.' WHERE word = 'hungry' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Take an umbrella because it may rain.' WHERE word = 'umbrella' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She plays the piano very well.' WHERE word = 'piano' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This bag is too heavy for me.' WHERE word = 'heavy' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I wear warm gloves in winter.' WHERE word = 'glove' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My dad works in a big office.' WHERE word = 'office' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My heart beats fast when I run.' WHERE word = 'heart' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The sailor travels across the sea.' WHERE word = 'sailor' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I made a list of things to buy.' WHERE word = 'list' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My cousin came to visit us today.' WHERE word = 'cousin' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I love eating chocolate cake.' WHERE word = 'chocolate' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The lion is the king of the animals.' WHERE word = 'lion' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I do not like to be alone at night.' WHERE word = 'alone' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The chef made a very good dinner.' WHERE word = 'chef' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I hope it will be sunny tomorrow.' WHERE word = 'hope' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Let''s build a house with blocks.' WHERE word = 'build' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I lost the key to my room.' WHERE word = 'key' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I check the calendar every morning.' WHERE word = 'calendar' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We climb the hill to see the view.' WHERE word = 'climb' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I have a great idea for the project.' WHERE word = 'idea' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We made a snowman in the yard.' WHERE word = 'snowman' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I read a funny comic book today.' WHERE word = 'comic' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I am almost done with my homework.' WHERE word = 'almost' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Wear your raincoat because it is raining.' WHERE word = 'raincoat' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The horse runs fast in the field.' WHERE word = 'horse' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I borrow books from the library.' WHERE word = 'library' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This is a birthday present for you.' WHERE word = 'present' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The big bear sleeps in a cave.' WHERE word = 'bear' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I drink orange juice every morning.' WHERE word = 'orange' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We had a fun party at school.' WHERE word = 'party' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I want to become a teacher.' WHERE word = 'become' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The leaves turn red in autumn.' WHERE word = 'autumn' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I drink water from the bottle.' WHERE word = 'bottle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'He is a gentle and kind boy.' WHERE word = 'gentle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The park is in the center of the city.' WHERE word = 'center' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I sent a postcard to my friend.' WHERE word = 'postcard' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Seoul is a very big city.' WHERE word = 'city' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Sit in the middle of the room.' WHERE word = 'middle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I want to learn how to cook.' WHERE word = 'learn' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went to the airport to fly.' WHERE word = 'airport' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I waited for one hour.' WHERE word = 'hour' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Wash your hands before you eat.' WHERE word = 'before' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went to the beach for vacation.' WHERE word = 'vacation' AND level = 'elem_4';
UPDATE words SET example_sentence = 'A guest is coming to our house.' WHERE word = 'guest' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I wait for the bus at the station.' WHERE word = 'station' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The little bird sings in the tree.' WHERE word = 'little' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My friend is always very helpful.' WHERE word = 'helpful' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We buy food at the supermarket.' WHERE word = 'supermarket' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She has a beautiful voice.' WHERE word = 'voice' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We go to the market on Saturday.' WHERE word = 'market' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My favorite animal is the dog.' WHERE word = 'animal' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Do not be angry at your friend.' WHERE word = 'angry' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I often visit my grandparents.' WHERE word = 'often' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The tiger is strong and fast.' WHERE word = 'tiger' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My neighbor has a cute dog.' WHERE word = 'neighbor' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The ring is made of gold.' WHERE word = 'gold' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This one is better than that one.' WHERE word = 'better' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Can you keep a secret?' WHERE word = 'secret' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The cat is inside the box.' WHERE word = 'inside' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She is the leader of our team.' WHERE word = 'leader' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We go to camp in the summer.' WHERE word = 'camp' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The bird sits on the roof.' WHERE word = 'roof' AND level = 'elem_4';
UPDATE words SET example_sentence = 'His daughter is five years old.' WHERE word = 'daughter' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I can hear the birds singing.' WHERE word = 'hear' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The sheep has soft white wool.' WHERE word = 'sheep' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went to a beautiful island.' WHERE word = 'island' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I sit on the bench in the park.' WHERE word = 'bench' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The earth goes around the sun.' WHERE word = 'earth' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Reading every day is a good habit.' WHERE word = 'habit' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Many cars are made in the factory.' WHERE word = 'factory' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I buy bread at the bakery.' WHERE word = 'bakery' AND level = 'elem_4';
UPDATE words SET example_sentence = 'This cake is very delicious.' WHERE word = 'delicious' AND level = 'elem_4';
UPDATE words SET example_sentence = 'A visitor came to our school today.' WHERE word = 'visitor' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Mars is a red planet.' WHERE word = 'planet' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The teacher will guide us on the trip.' WHERE word = 'guide' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The box is empty now.' WHERE word = 'empty' AND level = 'elem_4';
UPDATE words SET example_sentence = 'It is cloudy today so bring an umbrella.' WHERE word = 'cloudy' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We ride a boat on the river.' WHERE word = 'boat' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We eat lunch in the hall.' WHERE word = 'hall' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The sun is very bright today.' WHERE word = 'bright' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We eat dinner at the restaurant.' WHERE word = 'restaurant' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I have to leave now. Bye!' WHERE word = 'leave' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My grandma lives in a small village.' WHERE word = 'village' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The brave firefighter saved the cat.' WHERE word = 'firefighter' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My shoes are dirty from the mud.' WHERE word = 'dirty' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Be careful when you cross the street.' WHERE word = 'careful' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I came in first place in the race!' WHERE word = 'first' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We went to the art museum today.' WHERE word = 'museum' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Anyone can join our club.' WHERE word = 'anyone' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Tell me a funny story, please.' WHERE word = 'story' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My mom cooks in the kitchen.' WHERE word = 'kitchen' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Spring is my favorite season.' WHERE word = 'season' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We grow flowers in the garden.' WHERE word = 'garden' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We climbed up the green hill.' WHERE word = 'hill' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The toys are in the basement.' WHERE word = 'basement' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Turn on the lamp, please.' WHERE word = 'lamp' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I like to eat jelly after lunch.' WHERE word = 'jelly' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My dream is to travel the world.' WHERE word = 'dream' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Let''s clap our hands for the singer.' WHERE word = 'clap' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We walked through the dark forest.' WHERE word = 'forest' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She is very quick at running.' WHERE word = 'quick' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I wake up early every morning.' WHERE word = 'early' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The actor was very funny in the movie.' WHERE word = 'actor' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The dolphin jumps out of the water.' WHERE word = 'dolphin' AND level = 'elem_4';
UPDATE words SET example_sentence = 'Draw a big circle on the paper.' WHERE word = 'circle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The painter made a picture of the sea.' WHERE word = 'painter' AND level = 'elem_4';
UPDATE words SET example_sentence = 'A big crowd came to watch the game.' WHERE word = 'crowd' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I want to travel to many places.' WHERE word = 'travel' AND level = 'elem_4';
UPDATE words SET example_sentence = 'My goal is to read one book a week.' WHERE word = 'goal' AND level = 'elem_4';
UPDATE words SET example_sentence = 'I feel nervous before a big test.' WHERE word = 'nervous' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The bus driver was very kind to us.' WHERE word = 'driver' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We play on the beach in summer.' WHERE word = 'beach' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She put a candle on the birthday cake.' WHERE word = 'candle' AND level = 'elem_4';
UPDATE words SET example_sentence = 'The cows eat grass in the field.' WHERE word = 'field' AND level = 'elem_4';
UPDATE words SET example_sentence = 'We walked along the river today.' WHERE word = 'along' AND level = 'elem_4';
UPDATE words SET example_sentence = 'She is a famous singer in Korea.' WHERE word = 'famous' AND level = 'elem_4';

-- [elem_5] 초등 5학년 (8~12단어)
UPDATE words SET example_sentence = 'I like science class because we do fun tests.' WHERE word = 'science' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We decorate the classroom for the school party.' WHERE word = 'decorate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A tiny microchip is inside every computer.' WHERE word = 'microchip' AND level = 'elem_5';
UPDATE words SET example_sentence = 'She got a perfect score on the math test.' WHERE word = 'perfect' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I jog around the park every morning.' WHERE word = 'jog' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I bought a new pair of shoes yesterday.' WHERE word = 'pair' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I keep my money in a small wallet.' WHERE word = 'wallet' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A big package came to our house today.' WHERE word = 'package' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Many people are against cutting down trees.' WHERE word = 'against' AND level = 'elem_5';
UPDATE words SET example_sentence = 'These two books are very similar to each other.' WHERE word = 'similar' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The old tree is still alive after the storm.' WHERE word = 'alive' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The firefighter was a real hero to the town.' WHERE word = 'hero' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please clean the floor before mom comes home.' WHERE word = 'floor' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We saw a zebra with black and white stripes.' WHERE word = 'zebra' AND level = 'elem_5';
UPDATE words SET example_sentence = 'She plays a song on the xylophone in music class.' WHERE word = 'xylophone' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The climate of this area is warm all year.' WHERE word = 'climate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We used a telescope to look at the stars.' WHERE word = 'telescope' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The mailman will deliver the box to our house.' WHERE word = 'deliver' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The sun gives us light and power.' WHERE word = 'power' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should continue reading until we finish the book.' WHERE word = 'continue' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Many children in the world suffer from hunger.' WHERE word = 'hunger' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should use less plastic to save the earth.' WHERE word = 'plastic' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Can you locate Korea on the world map?' WHERE word = 'locate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please describe what you see in the picture.' WHERE word = 'describe' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The number of students will increase next year.' WHERE word = 'increase' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The whale is a huge animal that lives in the sea.' WHERE word = 'huge' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We celebrate my birthday with a big cake.' WHERE word = 'celebrate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I need to solve this math problem before class.' WHERE word = 'solve' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The doctor checked my blood at the hospital.' WHERE word = 'blood' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We live together as members of a society.' WHERE word = 'society' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Do dinosaurs still exist on our planet?' WHERE word = 'exist' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The bird tried to escape from the cage.' WHERE word = 'escape' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We walked across the bridge to get to school.' WHERE word = 'across' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Every citizen should follow the rules of the country.' WHERE word = 'citizen' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Can you tell the difference between these two colors?' WHERE word = 'difference' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I always remember my grandmother''s warm smile.' WHERE word = 'remember' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Korea is a small but strong nation.' WHERE word = 'nation' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Write the figure on the board clearly.' WHERE word = 'figure' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I like the flower pattern on your shirt.' WHERE word = 'pattern' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The southern part of the country is warmer.' WHERE word = 'southern' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You need to learn the basic rules first.' WHERE word = 'basic' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The enemy tried to attack the castle at night.' WHERE word = 'attack' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Everyone in the world wants peace.' WHERE word = 'peace' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The magician showed us an amazing trick.' WHERE word = 'trick' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please throw the trash in the trash can.' WHERE word = 'trash' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We heard loud thunder during the storm.' WHERE word = 'thunder' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We use a ruler to measure the length of things.' WHERE word = 'measure' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The volcano can send out fire and smoke.' WHERE word = 'volcano' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Close your eyes and imagine a blue sky.' WHERE word = 'imagine' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We need to go in the right direction.' WHERE word = 'direction' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This book does not belong to me.' WHERE word = 'belong' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Only a few people remain in the room.' WHERE word = 'remain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The height of the building is fifty meters.' WHERE word = 'height' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The sudden rain made everyone run inside.' WHERE word = 'sudden' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please focus on the lesson and listen well.' WHERE word = 'focus' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Scientists discover new things about the world.' WHERE word = 'discover' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The soft carpet feels nice under my feet.' WHERE word = 'carpet' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A giant wave crashed on the beach.' WHERE word = 'giant' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The western sky turns red at sunset.' WHERE word = 'western' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We take the train to go to the city.' WHERE word = 'train' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Can you translate this English sentence into Korean?' WHERE word = 'translate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'There are almost eight billion people on Earth.' WHERE word = 'billion' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The heat from the sun warms the ground.' WHERE word = 'heat' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The curious boy asked many questions.' WHERE word = 'curious' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The ball went through the open window.' WHERE word = 'through' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We must protect the forest from fire.' WHERE word = 'protect' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Wild animals live in the deep forest.' WHERE word = 'wild' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The car industry makes many new cars each year.' WHERE word = 'industry' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The soldiers defend their country from danger.' WHERE word = 'defend' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please separate the white clothes from the colors.' WHERE word = 'separate' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We enter the classroom before the bell rings.' WHERE word = 'enter' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The house has been vacant for two years.' WHERE word = 'vacant' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We built a fence around the garden.' WHERE word = 'fence' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Exercise has a good effect on our health.' WHERE word = 'effect' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I read many books during the summer break.' WHERE word = 'during' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A phone is a useful device for talking to people.' WHERE word = 'device' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You have to make a choice between the two.' WHERE word = 'choice' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We prepare everything the night before the trip.' WHERE word = 'prepare' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This question is very difficult to answer.' WHERE word = 'difficult' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The solar system has eight planets.' WHERE word = 'solar' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The two friends argue about which game to play.' WHERE word = 'argue' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The river is very wide in this area.' WHERE word = 'wide' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Every country has its own special culture.' WHERE word = 'culture' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This region gets a lot of rain in summer.' WHERE word = 'region' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We divide the cake into six equal pieces.' WHERE word = 'divide' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I want to reach the top of the mountain.' WHERE word = 'reach' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I am certain that we will win the game.' WHERE word = 'certain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Water can be in a liquid or solid state.' WHERE word = 'state' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The ball rolled on the ground and stopped.' WHERE word = 'ground' AND level = 'elem_5';
UPDATE words SET example_sentence = 'An honest person always tells the truth.' WHERE word = 'honest' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The teacher asked me to report what I learned.' WHERE word = 'report' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The cause of the fire was a broken wire.' WHERE word = 'cause' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A large amount of water is in the lake.' WHERE word = 'amount' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The rapid train goes very fast to the city.' WHERE word = 'rapid' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should consider others before we act.' WHERE word = 'consider' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We need to reduce the use of paper.' WHERE word = 'reduce' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A group of students went on a field trip.' WHERE word = 'group' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Do not stand too close to the edge.' WHERE word = 'edge' AND level = 'elem_5';
UPDATE words SET example_sentence = 'My grandmother is a very wise woman.' WHERE word = 'wise' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I want to invite all my friends to the party.' WHERE word = 'invite' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The sun gives us energy and light.' WHERE word = 'energy' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Today was just an ordinary day at school.' WHERE word = 'ordinary' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The brain is the part of the body that thinks.' WHERE word = 'brain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The two armies fought a big battle.' WHERE word = 'battle' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Wait here until I come back.' WHERE word = 'until' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The rain caused a long delay for the bus.' WHERE word = 'delay' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The cat is sleeping under the table.' WHERE word = 'under' AND level = 'elem_5';
UPDATE words SET example_sentence = 'What type of music do you like best?' WHERE word = 'type' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The youth club meets every Saturday.' WHERE word = 'youth' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The ice is very thin so be careful.' WHERE word = 'thin' AND level = 'elem_5';
UPDATE words SET example_sentence = 'She finished her homework quickly today.' WHERE word = 'quickly' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The design of this building is very modern.' WHERE word = 'design' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Do not judge people by how they look.' WHERE word = 'judge' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The dog ran toward its owner happily.' WHERE word = 'toward' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We had to cancel the game because of rain.' WHERE word = 'cancel' AND level = 'elem_5';
UPDATE words SET example_sentence = 'There are various kinds of fish in the sea.' WHERE word = 'various' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I do not understand this math problem.' WHERE word = 'understand' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The stars appear in the sky at night.' WHERE word = 'appear' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should treat everyone with kindness.' WHERE word = 'treat' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The sign warns people about the danger ahead.' WHERE word = 'warn' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I wake up at seven as usual.' WHERE word = 'usual' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The best feature of this phone is the camera.' WHERE word = 'feature' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The beauty of the sunset took my breath away.' WHERE word = 'beauty' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Come sit beside me on the bench.' WHERE word = 'beside' AND level = 'elem_5';
UPDATE words SET example_sentence = 'He ate double the amount of food today.' WHERE word = 'double' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We found a fossil of a fish in the rock.' WHERE word = 'fossil' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The turtle moved slowly across the road.' WHERE word = 'turtle' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I trust my best friend with my secret.' WHERE word = 'trust' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The teacher asked a hard question in class.' WHERE word = 'question' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Let us compare the sizes of these two boxes.' WHERE word = 'compare' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The speed of the train is very fast.' WHERE word = 'speed' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please select one book from the shelf.' WHERE word = 'select' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Children depend on their parents for food.' WHERE word = 'depend' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I saved the image on my computer.' WHERE word = 'image' AND level = 'elem_5';
UPDATE words SET example_sentence = 'People vote to choose their leader.' WHERE word = 'vote' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Farmers grow grain like rice and wheat.' WHERE word = 'grain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should take care of our environment.' WHERE word = 'environment' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The thick wall keeps the cold out.' WHERE word = 'thick' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I felt a sharp pain in my leg.' WHERE word = 'pain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please follow the rules at all times.' WHERE word = 'follow' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We stayed there for a short period of time.' WHERE word = 'period' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The result of the test will come out tomorrow.' WHERE word = 'result' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This news is known worldwide.' WHERE word = 'worldwide' AND level = 'elem_5';
UPDATE words SET example_sentence = 'In addition to math, I like science too.' WHERE word = 'addition' AND level = 'elem_5';
UPDATE words SET example_sentence = 'What material is this table made of?' WHERE word = 'material' AND level = 'elem_5';
UPDATE words SET example_sentence = 'My dad parks the car in the garage.' WHERE word = 'garage' AND level = 'elem_5';
UPDATE words SET example_sentence = 'What is that round object on the table?' WHERE word = 'object' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We had a wonderful time at the beach.' WHERE word = 'wonderful' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Is your answer correct or wrong?' WHERE word = 'correct' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You need to control the ball with your foot.' WHERE word = 'control' AND level = 'elem_5';
UPDATE words SET example_sentence = 'My favorite character in the book is the prince.' WHERE word = 'character' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We can see the whole city from the tower.' WHERE word = 'tower' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I am in the fifth grade at my school.' WHERE word = 'grade' AND level = 'elem_5';
UPDATE words SET example_sentence = 'It takes a lot of effort to learn a new thing.' WHERE word = 'effort' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Everyone has their own opinion about the movie.' WHERE word = 'opinion' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Always tell the truth and do not lie.' WHERE word = 'truth' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I need to complete my project by Friday.' WHERE word = 'complete' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Can you guess how many candies are in the jar?' WHERE word = 'guess' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A car accident happened on the road this morning.' WHERE word = 'accident' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Warming is a global problem that we all face.' WHERE word = 'global' AND level = 'elem_5';
UPDATE words SET example_sentence = 'There is a better method to solve this problem.' WHERE word = 'method' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Be careful when you handle the hot pot.' WHERE word = 'handle' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This is a serious matter so please listen.' WHERE word = 'serious' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I want to return home before it gets dark.' WHERE word = 'return' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I will receive a gift on my birthday.' WHERE word = 'receive' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Washing hands can prevent many kinds of sickness.' WHERE word = 'prevent' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The captain of the ship guided us safely.' WHERE word = 'captain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Please repeat the sentence one more time.' WHERE word = 'repeat' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The old house has a wooden floor.' WHERE word = 'wooden' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The temperature is below zero today.' WHERE word = 'below' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I can catch the ball with one hand.' WHERE word = 'catch' AND level = 'elem_5';
UPDATE words SET example_sentence = 'She can manage a team of ten people well.' WHERE word = 'manage' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I had trouble finding the right answer.' WHERE word = 'trouble' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We connect the two wires to make it work.' WHERE word = 'connect' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We need to repair the broken window.' WHERE word = 'repair' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Do not touch the hot stove with your hand.' WHERE word = 'touch' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Good health is more important than money.' WHERE word = 'health' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I need to organize my desk before I study.' WHERE word = 'organize' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The huge glacier melts because of warm weather.' WHERE word = 'glacier' AND level = 'elem_5';
UPDATE words SET example_sentence = 'My parents allow me to play after homework.' WHERE word = 'allow' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We water the plant every morning.' WHERE word = 'plant' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The baby fell asleep on the soft bed.' WHERE word = 'asleep' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The students perform a play on the stage.' WHERE word = 'perform' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should avoid eating too much candy.' WHERE word = 'avoid' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I eat lunch at twelve every day.' WHERE word = 'lunch' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Water will freeze when it gets very cold.' WHERE word = 'freeze' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Reading a book can be a great adventure.' WHERE word = 'adventure' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The dog broke free from the chain.' WHERE word = 'chain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I have already finished my homework today.' WHERE word = 'already' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should accept other people''s ideas.' WHERE word = 'accept' AND level = 'elem_5';
UPDATE words SET example_sentence = 'My teacher gave me good advice about studying.' WHERE word = 'advice' AND level = 'elem_5';
UPDATE words SET example_sentence = 'This farm can produce a lot of milk.' WHERE word = 'produce' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I want to explore the deep sea someday.' WHERE word = 'explore' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The car has a very strong engine.' WHERE word = 'engine' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Write the correct number on the board.' WHERE word = 'number' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Bad things can occur when we are not careful.' WHERE word = 'occur' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The cloud has the shape of a rabbit.' WHERE word = 'shape' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The distance from home to school is two miles.' WHERE word = 'distance' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Every human needs food, water, and sleep.' WHERE word = 'human' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You can find good books anywhere these days.' WHERE word = 'anywhere' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The sick boy felt very weak today.' WHERE word = 'weak' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The grand palace had hundreds of rooms.' WHERE word = 'grand' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I tidy my room every morning before school.' WHERE word = 'tidy' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A strong storm is coming this afternoon.' WHERE word = 'storm' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Tell me the exact time of the meeting.' WHERE word = 'exact' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A dog will guard the house at night.' WHERE word = 'guard' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Gravity is the force that pulls us down.' WHERE word = 'gravity' AND level = 'elem_5';
UPDATE words SET example_sentence = 'A big wave hit the boat on the sea.' WHERE word = 'wave' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We should respect our parents and teachers.' WHERE word = 'respect' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Tell me every detail about what happened.' WHERE word = 'detail' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I was lucky to find a seat on the bus.' WHERE word = 'lucky' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I walked to school instead of taking the bus.' WHERE word = 'instead' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You can choose either the red or the blue one.' WHERE word = 'either' AND level = 'elem_5';
UPDATE words SET example_sentence = 'The washing machine helps us clean our clothes.' WHERE word = 'machine' AND level = 'elem_5';
UPDATE words SET example_sentence = 'You need strength to move heavy things.' WHERE word = 'strength' AND level = 'elem_5';
UPDATE words SET example_sentence = 'I wonder what the weather will be like tomorrow.' WHERE word = 'wonder' AND level = 'elem_5';
UPDATE words SET example_sentence = 'There is no extra charge for the water.' WHERE word = 'charge' AND level = 'elem_5';
UPDATE words SET example_sentence = 'What will happen if we miss the bus?' WHERE word = 'happen' AND level = 'elem_5';
UPDATE words SET example_sentence = 'Let me explain how this game works.' WHERE word = 'explain' AND level = 'elem_5';
UPDATE words SET example_sentence = 'We planted a seed in the garden today.' WHERE word = 'seed' AND level = 'elem_5';

-- [elem_6] 초등 6학년 (8~14단어)
UPDATE words SET example_sentence = 'Online shopping has become a growing trend in recent years.' WHERE word = 'trend' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The forest ecosystem includes animals, plants, and insects.' WHERE word = 'ecosystem' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We must ensure that everyone gets a fair chance.' WHERE word = 'ensure' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It took him a long time to recover from the illness.' WHERE word = 'recover' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Children tend to learn languages faster than adults.' WHERE word = 'tend' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please include your name on the top of the page.' WHERE word = 'include' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Workers will construct a new bridge over the river.' WHERE word = 'construct' AND level = 'elem_6';
UPDATE words SET example_sentence = 'My first task today is to clean my room.' WHERE word = 'task' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She decided to devote her time to helping others.' WHERE word = 'devote' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The teacher will evaluate our work at the end.' WHERE word = 'evaluate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need to transfer the files to a new computer.' WHERE word = 'transfer' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The student learned to cite the source of the information.' WHERE word = 'cite' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Frequent practice is the key to getting better.' WHERE word = 'frequent' AND level = 'elem_6';
UPDATE words SET example_sentence = 'If you work hard, you will succeed in the end.' WHERE word = 'succeed' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need a new approach to solve this old problem.' WHERE word = 'approach' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please give me a specific example of what you mean.' WHERE word = 'specific' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The army had to withdraw from the area.' WHERE word = 'withdraw' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Each snowflake has its own distinct shape.' WHERE word = 'distinct' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This is the latest version of the game.' WHERE word = 'version' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I need to revise my essay before I hand it in.' WHERE word = 'revise' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We should not commit the same mistake again.' WHERE word = 'commit' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The photographer tried to capture the beautiful sunset.' WHERE word = 'capture' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need to determine the cause of the problem.' WHERE word = 'determine' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Only the strong animals survive the cold winter.' WHERE word = 'survive' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She composed a beautiful song for the school show.' WHERE word = 'compose' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This box can contain up to fifty books.' WHERE word = 'contain' AND level = 'elem_6';
UPDATE words SET example_sentence = 'They worked hard to restore the old building.' WHERE word = 'restore' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I intend to finish this project by next week.' WHERE word = 'intend' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Can you define the meaning of this word?' WHERE word = 'define' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I assure you that everything will be fine.' WHERE word = 'assure' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Do not blame others for your own mistakes.' WHERE word = 'blame' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please turn down the volume of the music.' WHERE word = 'volume' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Animals evolve over thousands of years.' WHERE word = 'evolve' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I read about this topic in the previous lesson.' WHERE word = 'previous' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This project will involve students from all grades.' WHERE word = 'involve' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We study history to learn from the past.' WHERE word = 'history' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need to resolve this problem before it gets worse.' WHERE word = 'resolve' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She tried to convince her friend to join the club.' WHERE word = 'convince' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Exercise has many benefits for our body and mind.' WHERE word = 'benefit' AND level = 'elem_6';
UPDATE words SET example_sentence = 'You have the option to choose red or blue.' WHERE word = 'option' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Ships use navigation tools to find their way at sea.' WHERE word = 'navigation' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The government will regulate the use of plastic bags.' WHERE word = 'regulate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Bright colors attract the attention of young children.' WHERE word = 'attract' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The country faced a serious crisis after the flood.' WHERE word = 'crisis' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is hard to interpret what the old writing means.' WHERE word = 'interpret' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The two teams will compete in the final game.' WHERE word = 'compete' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The scientist will demonstrate how the experiment works.' WHERE word = 'demonstrate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Pollution has a bad impact on our health.' WHERE word = 'impact' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need a good strategy to win this game.' WHERE word = 'strategy' AND level = 'elem_6';
UPDATE words SET example_sentence = 'What is the status of your homework right now?' WHERE word = 'status' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Every individual person has their own special talent.' WHERE word = 'individual' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The factory will supply food to all the stores.' WHERE word = 'supply' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Patients may undergo several tests at the hospital.' WHERE word = 'undergo' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Hard work always brings a great reward.' WHERE word = 'reward' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please attach the photo to your email.' WHERE word = 'attach' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I really admire my teacher for her kindness.' WHERE word = 'admire' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The museum will display old paintings from the past.' WHERE word = 'display' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The coach will instruct the players on the new rules.' WHERE word = 'instruct' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The school will announce the test results tomorrow.' WHERE word = 'announce' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I do not understand the notion of time travel.' WHERE word = 'notion' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She plays an important role in our team.' WHERE word = 'role' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We cannot afford to buy a new computer right now.' WHERE word = 'afford' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The number of students started to decline this year.' WHERE word = 'decline' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The funny movie will amuse the whole family.' WHERE word = 'amuse' AND level = 'elem_6';
UPDATE words SET example_sentence = 'There was a gradual change in the weather this week.' WHERE word = 'gradual' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This is a no-parking zone near the school.' WHERE word = 'zone' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We use phones to communicate with people far away.' WHERE word = 'communicate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Is this seat available or is someone sitting here?' WHERE word = 'available' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please confirm your name and phone number.' WHERE word = 'confirm' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Scientists estimate that millions of stars exist.' WHERE word = 'estimate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The road is broad enough for three cars.' WHERE word = 'broad' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Is it possible to finish this work by five?' WHERE word = 'possible' AND level = 'elem_6';
UPDATE words SET example_sentence = 'How did you react when you heard the good news?' WHERE word = 'react' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We must seek the truth and never give up.' WHERE word = 'seek' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Loud sounds can trigger fear in some animals.' WHERE word = 'trigger' AND level = 'elem_6';
UPDATE words SET example_sentence = 'My main concern is the safety of the children.' WHERE word = 'concern' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The school has a limited budget for the trip.' WHERE word = 'budget' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Students should engage in activities after school.' WHERE word = 'engage' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Practice can enhance your skills in any subject.' WHERE word = 'enhance' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The teacher wants to stress the importance of reading.' WHERE word = 'stress' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I was lucky to witness the beautiful rainbow.' WHERE word = 'witness' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is important to retain what you learn in class.' WHERE word = 'retain' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We should utilize our time wisely every day.' WHERE word = 'utilize' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She worked hard to prove that she was right.' WHERE word = 'prove' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Water is crucial for all living things on Earth.' WHERE word = 'crucial' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The wind can shift direction at any time.' WHERE word = 'shift' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We had to alter the plan because of the rain.' WHERE word = 'alter' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Good books can inspire people to do great things.' WHERE word = 'inspire' AND level = 'elem_6';
UPDATE words SET example_sentence = 'You need good reasons to justify your decision.' WHERE word = 'justify' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The writer wants to publish her new book soon.' WHERE word = 'publish' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Children are full of curiosity about the world.' WHERE word = 'curiosity' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The teacher has the authority to set the rules.' WHERE word = 'authority' AND level = 'elem_6';
UPDATE words SET example_sentence = 'He tried to deny that he broke the window.' WHERE word = 'deny' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please remove your shoes before entering the house.' WHERE word = 'remove' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The students learned to cooperate and work as a team.' WHERE word = 'cooperate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Let me give you a brief summary of the story.' WHERE word = 'brief' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She worked hard to accomplish her dream of being a doctor.' WHERE word = 'accomplish' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The government works to improve the welfare of the people.' WHERE word = 'welfare' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Do not assume things without checking the facts first.' WHERE word = 'assume' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This job will require a lot of patience and hard work.' WHERE word = 'require' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We should think about every aspect of the problem.' WHERE word = 'aspect' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The travel agency helped us plan the whole trip.' WHERE word = 'agency' AND level = 'elem_6';
UPDATE words SET example_sentence = 'All students must attend the morning meeting.' WHERE word = 'attend' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is apparent that she studied hard for the test.' WHERE word = 'apparent' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The overall score of our team was very high.' WHERE word = 'overall' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Let me introduce my new classmate to everyone.' WHERE word = 'introduce' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Animals must adapt to changes in the weather.' WHERE word = 'adapt' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Are you aware of the new school rules?' WHERE word = 'aware' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Books are sorted into different categories in the library.' WHERE word = 'category' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We plan to extend the deadline by one more week.' WHERE word = 'extend' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The first phase of the project is now complete.' WHERE word = 'phase' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is wise to invest time in learning new skills.' WHERE word = 'invest' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The old building might collapse if not repaired.' WHERE word = 'collapse' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Some people oppose the plan to build a new road.' WHERE word = 'oppose' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We may encounter many challenges along the way.' WHERE word = 'encounter' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Books and bags occupy most of the space on my desk.' WHERE word = 'occupy' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The older students assist the younger ones with reading.' WHERE word = 'assist' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Wearing a helmet is appropriate when riding a bike.' WHERE word = 'appropriate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Teachers monitor the progress of each student.' WHERE word = 'monitor' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Scientists analyze data to find answers to questions.' WHERE word = 'analyze' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We can derive useful lessons from our mistakes.' WHERE word = 'derive' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The noise from the street was constant all day.' WHERE word = 'constant' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Good grades require strong academic effort.' WHERE word = 'academic' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The reporter will expose the truth to the public.' WHERE word = 'expose' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This farm can yield enough food for the whole town.' WHERE word = 'yield' AND level = 'elem_6';
UPDATE words SET example_sentence = 'A good coach can motivate the players to try harder.' WHERE word = 'motivate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'A sponge can absorb a lot of water.' WHERE word = 'absorb' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Korean culture is known for its warm hospitality.' WHERE word = 'hospitality' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I want to apply for the art club at school.' WHERE word = 'apply' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The weather can vary a lot from day to day.' WHERE word = 'vary' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need to modify the plan to make it better.' WHERE word = 'modify' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Every child has the potential to do great things.' WHERE word = 'potential' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The outcome of the game surprised everyone.' WHERE word = 'outcome' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The goal is to unify the two groups into one team.' WHERE word = 'unify' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The team built a prototype of the new robot.' WHERE word = 'prototype' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Can you identify all the countries on this map?' WHERE word = 'identify' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Friends and family support each other in hard times.' WHERE word = 'support' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Making bread is a long process that takes time.' WHERE word = 'process' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The company had to reject the weak plan.' WHERE word = 'reject' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The doctor will examine you carefully.' WHERE word = 'examine' AND level = 'elem_6';
UPDATE words SET example_sentence = 'There is a clear contrast between the two pictures.' WHERE word = 'contrast' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The rain did not cease until late at night.' WHERE word = 'cease' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The company wants to expand its business to other countries.' WHERE word = 'expand' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The school will implement new rules next month.' WHERE word = 'implement' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Scientists can predict the weather a few days ahead.' WHERE word = 'predict' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The mountain is visible from our classroom window.' WHERE word = 'visible' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I am grateful for the help my friends gave me.' WHERE word = 'grateful' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Her kind words really impress everyone around her.' WHERE word = 'impress' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Stay alert when you cross a busy street.' WHERE word = 'alert' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We have adequate food and water for the trip.' WHERE word = 'adequate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Volunteers will distribute food to people in need.' WHERE word = 'distribute' AND level = 'elem_6';
UPDATE words SET example_sentence = 'All students should participate in the school event.' WHERE word = 'participate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'People consume too much sugar in their daily food.' WHERE word = 'consume' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The teacher wants to emphasize the importance of reading.' WHERE word = 'emphasize' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Let us proceed to the next step of the plan.' WHERE word = 'proceed' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Does anyone have a comment about the new rule?' WHERE word = 'comment' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Do not ignore the feelings of your friends.' WHERE word = 'ignore' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please contact me if you have any questions.' WHERE word = 'contact' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Hard work can transform a dream into reality.' WHERE word = 'transform' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Tell me about your family background.' WHERE word = 'background' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She felt anxiety before the big test at school.' WHERE word = 'anxiety' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The school will provide lunch for all students.' WHERE word = 'provide' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We started a recycling program at our school.' WHERE word = 'program' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is natural for leaves to fall in autumn.' WHERE word = 'natural' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Your ticket is valid for one month from today.' WHERE word = 'valid' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please give me the precise time of the meeting.' WHERE word = 'precise' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The underground train runs below the city streets.' WHERE word = 'underground' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We have sufficient time to finish the project.' WHERE word = 'sufficient' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please respond to my email when you have time.' WHERE word = 'respond' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Big trucks transport goods from the farm to the city.' WHERE word = 'transport' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We combine flour, eggs, and milk to make a cake.' WHERE word = 'combine' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Learning a new technique takes time and practice.' WHERE word = 'technique' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The primary goal of the school is to help students learn.' WHERE word = 'primary' AND level = 'elem_6';
UPDATE words SET example_sentence = 'It is cold outside; therefore, wear a warm coat.' WHERE word = 'therefore' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Wind turbines generate clean energy from the wind.' WHERE word = 'generate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Give me one instance of when this rule was used.' WHERE word = 'instance' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Our target is to read thirty books this year.' WHERE word = 'target' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Pollution is a major problem in many big cities.' WHERE word = 'major' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The table is stable and will not fall over.' WHERE word = 'stable' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The new leader plans to reform the school system.' WHERE word = 'reform' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The police will investigate what happened last night.' WHERE word = 'investigate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I want to propose a new idea for the school festival.' WHERE word = 'propose' AND level = 'elem_6';
UPDATE words SET example_sentence = 'This discovery is significant for science and medicine.' WHERE word = 'significant' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The average score of the class was eighty-five points.' WHERE word = 'average' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Please refer to page ten for more information.' WHERE word = 'refer' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The enormous whale swam slowly across the ocean.' WHERE word = 'enormous' AND level = 'elem_6';
UPDATE words SET example_sentence = 'A wide range of books is available in the library.' WHERE word = 'range' AND level = 'elem_6';
UPDATE words SET example_sentence = 'I need to concentrate when I study for a test.' WHERE word = 'concentrate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The dark clouds indicate that rain is coming soon.' WHERE word = 'indicate' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The initial plan was to go camping, but we changed it.' WHERE word = 'initial' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She worked hard to achieve her dream of being a singer.' WHERE word = 'achieve' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The purpose of this meeting is to plan the school trip.' WHERE word = 'purpose' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Everyone has the ability to learn new things.' WHERE word = 'ability' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The police found strong evidence at the scene.' WHERE word = 'evidence' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The fire alarm rang loudly in the building.' WHERE word = 'alarm' AND level = 'elem_6';
UPDATE words SET example_sentence = 'She decided to pursue her dream of becoming a writer.' WHERE word = 'pursue' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The school needs more funds to build a new gym.' WHERE word = 'fund' AND level = 'elem_6';
UPDATE words SET example_sentence = 'Good teachers have a strong influence on their students.' WHERE word = 'influence' AND level = 'elem_6';
UPDATE words SET example_sentence = 'We need to improve our reading skills this year.' WHERE word = 'improve' AND level = 'elem_6';
UPDATE words SET example_sentence = 'The map must be accurate to help us find the way.' WHERE word = 'accurate' AND level = 'elem_6';
