-- ============================================================
-- high_2 단어 데이터 (500개, 25세트 x 20단어)
-- 기존 high_2 데이터를 삭제하고 새로 삽입합니다
-- ============================================================

DELETE FROM public.words WHERE level = 'high_2';

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
  ('word', 'high_2', 1, 'abate', '줄어들다', '완화되다', NULL, 'The storm began to abate after several hours of heavy rain and strong winds.'),
  ('word', 'high_2', 1, 'abolish', '폐지하다', NULL, NULL, 'Many people hope to abolish the outdated law in the next legislative session.'),
  ('word', 'high_2', 1, 'abstain', '삼가다', '자제하다', NULL, 'He decided to abstain from voting on the controversial issue.'),
  ('word', 'high_2', 1, 'abstruse', '난해한', '심오한', NULL, 'The philosopher''s theories were so abstruse that only a few scholars could fully grasp their meaning.'),
  ('word', 'high_2', 1, 'accentuate', '강조하다', '두드러지게 하다', NULL, 'The bright scarf accentuated her elegant outfit.'),
  ('word', 'high_2', 1, 'acquiesce', '마지못해 따르다', '묵인하다', NULL, 'After much debate, she decided to acquiesce to her parents'' wishes regarding her career.'),
  ('word', 'high_2', 1, 'adamant', '단호한', '확고한', NULL, 'He was adamant that the project should be completed before the end of the month.'),
  ('word', 'high_2', 1, 'adept', '숙련된', '능숙한', NULL, 'She is adept at solving complex mathematical problems under time pressure.'),
  ('word', 'high_2', 1, 'adhere', '고수하다', '들러붙다', NULL, 'You must adhere to the rules of the competition.'),
  ('word', 'high_2', 1, 'adjunct', '부속물', '보조적인', '비정규의', 'Physical exercise serves as a valuable adjunct to traditional therapy for patients recovering from depression.'),
  ('word', 'high_2', 1, 'adversary', '적', '상대', NULL, 'The two chess players respected each other, even though they were fierce adversaries.'),
  ('word', 'high_2', 1, 'affinity', '친밀감', '친화력', NULL, 'She felt a natural affinity for languages, easily picking up new ones wherever she traveled.'),
  ('word', 'high_2', 1, 'aftermath', '여파', '후유증', '결과', 'In the aftermath of the earthquake, thousands of volunteers arrived to help with rescue efforts.'),
  ('word', 'high_2', 1, 'alleviate', '완화하다', '경감하다', NULL, 'Aspirin can help to alleviate the pain of a headache.'),
  ('word', 'high_2', 1, 'allude', '암시하다', '넌지시 언급하다', NULL, 'The professor alluded to a famous experiment during his lecture.'),
  ('word', 'high_2', 1, 'aloof', '냉담한', '쌀쌀한', NULL, 'He remained aloof during the party, preferring to observe rather than participate.'),
  ('word', 'high_2', 1, 'altruistic', '이타적인', NULL, NULL, 'Her altruistic desire to help others led her to dedicate her life to humanitarian work.'),
  ('word', 'high_2', 1, 'ambience', '분위기', '환경', NULL, 'The soft lighting and gentle music created a warm ambience in the restaurant.'),
  ('word', 'high_2', 1, 'ameliorate', '개선하다', '좋게 만들다', NULL, 'The new government policies aim to ameliorate the economic conditions for low-income families.'),
  ('word', 'high_2', 1, 'ample', '충분한', '풍부한', NULL, 'There is ample evidence to support this theory.'),
  ('word', 'high_2', 2, 'analogous', '유사한', '비슷한', NULL, 'The human brain is often considered analogous to a computer.'),
  ('word', 'high_2', 2, 'anarchy', '무정부 상태', '혼란', NULL, 'The sudden collapse of the government plunged the country into a state of anarchy and disorder.'),
  ('word', 'high_2', 2, 'animosity', '적대감', '원한', NULL, 'Despite years of animosity between the two families, the younger generation sought peace.'),
  ('word', 'high_2', 2, 'apathy', '무관심', '냉담', NULL, 'Voter apathy is a serious problem in many democracies.'),
  ('word', 'high_2', 2, 'apex', '꼭대기', '정점', NULL, 'The mountaineer finally reached the apex of the peak after days of climbing.'),
  ('word', 'high_2', 2, 'appease', '달래다', '진정시키다', NULL, 'The manager tried to appease the angry customer with a refund.'),
  ('word', 'high_2', 2, 'apprehend', '체포하다', '이해하다', '염려하다', 'The police were able to apprehend the suspect near the crime scene.'),
  ('word', 'high_2', 2, 'apprehensive', '불안한', '염려하는', NULL, 'She felt apprehensive about starting a new job in a completely unfamiliar city.'),
  ('word', 'high_2', 2, 'aptitude', '소질', '적성', '재능', 'Her natural aptitude for languages made learning Spanish much easier for her.'),
  ('word', 'high_2', 2, 'arable', '경작할 수 있는', NULL, NULL, 'Only a small percentage of the land is arable.'),
  ('word', 'high_2', 2, 'arbitrary', '임의적인', '독단적인', NULL, 'The decision to cancel the project seemed arbitrary to many employees.'),
  ('word', 'high_2', 2, 'arbitration', '중재', '조정', NULL, 'The two parties agreed to resolve their dispute through arbitration rather than going to court.'),
  ('word', 'high_2', 2, 'archaic', '구식의', '고대의', NULL, 'The archaic laws were finally updated by the new government.'),
  ('word', 'high_2', 2, 'arduous', '힘든', '고된', NULL, 'Climbing Mount Everest is an arduous task that requires intense preparation.'),
  ('word', 'high_2', 2, 'ascertain', '확인하다', '알아내다', NULL, 'The detective tried to ascertain the cause of the fire.'),
  ('word', 'high_2', 2, 'aspire', '열망하다', '갈망하다', NULL, 'Many young athletes aspire to compete in the Olympics.'),
  ('word', 'high_2', 2, 'assert', '주장하다', '단언하다', NULL, 'It''s important to assert your rights politely but firmly when dealing with difficult situations.'),
  ('word', 'high_2', 2, 'astute', '기민한', '빈틈없는', NULL, 'The astute businessman quickly noticed the flaw in the contract.'),
  ('word', 'high_2', 2, 'atrocity', '잔학 행위', '만행', NULL, 'The documentary exposed the atrocities committed during the war.'),
  ('word', 'high_2', 2, 'attrition', '소모', '마모', NULL, 'The company suffered from high employee attrition due to poor working conditions.'),
  ('word', 'high_2', 3, 'augment', '증가시키다', '보강하다', NULL, 'She took a part-time job to augment her income.'),
  ('word', 'high_2', 3, 'auspicious', '길조의', '상서로운', NULL, 'The clear sky on the morning of the wedding was seen as an auspicious sign.'),
  ('word', 'high_2', 3, 'austere', '엄격한', '검소한', '금욕적인', 'The monks led an austere lifestyle, free from material luxuries and distractions.'),
  ('word', 'high_2', 3, 'auxiliary', '보조적인', '부수적인', '예비의', 'The hospital activated its auxiliary power system when the main generator failed during the storm.'),
  ('word', 'high_2', 3, 'avarice', '탐욕', '욕심', NULL, 'His avarice drove him to exploit others for personal financial gain.'),
  ('word', 'high_2', 3, 'avert', '피하다', '방지하다', NULL, 'Quick action by the pilot averted a disaster.'),
  ('word', 'high_2', 3, 'avow', '공언하다', '단언하다', NULL, 'The politician avowed his commitment to fighting corruption during his campaign speech.'),
  ('word', 'high_2', 3, 'baffle', '당혹하게 하다', '어리둥절하게 하다', NULL, 'The magician''s trick completely baffled the audience.'),
  ('word', 'high_2', 3, 'bane', '골칫거리', '재앙', NULL, 'Procrastination is the bane of many students who struggle to meet deadlines.'),
  ('word', 'high_2', 3, 'bastion', '요새', '보루', NULL, 'The university has long been a bastion of free speech and academic freedom.'),
  ('word', 'high_2', 3, 'beguile', '매혹하다', '속이다', NULL, 'The magician managed to beguile the audience with his incredible sleight of hand.'),
  ('word', 'high_2', 3, 'belie', '거짓으로 나타내다', '모순되다', NULL, 'Her calm expression belied the nervousness she was actually feeling inside.'),
  ('word', 'high_2', 3, 'belligerent', '호전적인', '적대적인', NULL, 'The belligerent tone of his speech alarmed the diplomats.'),
  ('word', 'high_2', 3, 'benevolence', '자선', '선의', NULL, 'The organization is known for its benevolence toward disadvantaged children in the region.'),
  ('word', 'high_2', 3, 'benign', '양성의', '온화한', NULL, 'Fortunately, the tumor turned out to be benign.'),
  ('word', 'high_2', 3, 'bias', '편견', '선입견', '경향', 'We must try to overcome our own unconscious bias to make fair and objective judgments.'),
  ('word', 'high_2', 3, 'bilateral', '양자간의', '쌍방의', NULL, 'The two countries signed a bilateral trade agreement to strengthen their economic relationship.'),
  ('word', 'high_2', 3, 'blatant', '노골적인', '뻔뻔스러운', NULL, 'His blatant disregard for the rules shocked everyone.'),
  ('word', 'high_2', 3, 'bleak', '황량한', '암울한', NULL, 'The economic outlook remained bleak, with no signs of recovery in the near future.'),
  ('word', 'high_2', 3, 'blithe', '태평한', '쾌활한', NULL, 'She showed a blithe disregard for the rules, acting as if they did not apply to her.'),
  ('word', 'high_2', 4, 'bolster', '강화하다', '북돋우다', NULL, 'The new data bolstered her argument significantly.'),
  ('word', 'high_2', 4, 'brandish', '휘두르다', '자랑스럽게 보이다', NULL, 'The protester brandished a sign demanding justice for the victims of the disaster.'),
  ('word', 'high_2', 4, 'brazen', '뻔뻔한', '대담한', NULL, 'The thief made a brazen attempt to steal the painting in broad daylight.'),
  ('word', 'high_2', 4, 'brevity', '간결함', '짧음', NULL, 'The brevity of his speech surprised the audience.'),
  ('word', 'high_2', 4, 'broach', '꺼내다', '말을 꺼내다', NULL, 'She was unsure how to broach the subject of salary during the interview.'),
  ('word', 'high_2', 4, 'bucolic', '전원의', '시골풍의', NULL, 'The artist painted a bucolic scene of green fields and grazing sheep.'),
  ('word', 'high_2', 4, 'burgeon', '급성장하다', '싹트다', NULL, 'The technology industry continued to burgeon throughout the decade.'),
  ('word', 'high_2', 4, 'cacophony', '불협화음, 시끄러운 소리', NULL, NULL, 'The school orchestra produced a cacophony of sounds before the conductor began the rehearsal.'),
  ('word', 'high_2', 4, 'cajole', '구슬리다', '감언이설로 설득하다', NULL, 'She tried to cajole her younger brother into helping her with the household chores.'),
  ('word', 'high_2', 4, 'candid', '솔직한', '숨김없는', NULL, 'Her candid feedback, though sometimes blunt, was always helpful for improving our work.'),
  ('word', 'high_2', 4, 'candor', '솔직함', '정직', NULL, 'I appreciate your candor in telling me the truth.'),
  ('word', 'high_2', 4, 'capacity', '용량', '능력', NULL, 'The small stadium has a seating capacity of only five thousand people.'),
  ('word', 'high_2', 4, 'capitulate', '항복하다', '굴복하다', NULL, 'After weeks of siege, the enemy forces finally capitulated and surrendered their weapons.'),
  ('word', 'high_2', 4, 'capricious', '변덕스러운', '예측 불가능한', NULL, 'Her capricious moods made it difficult to predict her reactions.'),
  ('word', 'high_2', 4, 'captivate', '매료시키다', '사로잡다', NULL, 'The singer''s powerful voice captivated the entire audience.'),
  ('word', 'high_2', 4, 'cater', '충족시키다', '음식을 제공하다', NULL, 'The new library was designed to cater to the needs of students with diverse learning styles.'),
  ('word', 'high_2', 4, 'caustic', '신랄한', '부식성의', NULL, 'His caustic remarks about her presentation left her feeling embarrassed and hurt.'),
  ('word', 'high_2', 4, 'censure', '비난하다', '문책하다', NULL, 'The committee voted to censure the senator for his unethical behavior in office.'),
  ('word', 'high_2', 4, 'cherish', '소중히 여기다', '간직하다', NULL, 'She will always cherish the memories of her childhood summers at her grandparents'' house.'),
  ('word', 'high_2', 4, 'chronic', '만성적인', '고질적인', NULL, 'Chronic stress can lead to serious health problems such as heart disease and depression.'),
  ('word', 'high_2', 5, 'chronicle', '기록하다', '연대기', NULL, 'The journalist set out to chronicle the daily lives of refugees in the camp.'),
  ('word', 'high_2', 5, 'circumscribe', '제한하다', '한정하다', NULL, 'The new law circumscribed the power of the president.'),
  ('word', 'high_2', 5, 'clamber', '기어오르다', '힘들게 오르다', NULL, 'The children clambered over the rocks to reach the hidden cave near the shore.'),
  ('word', 'high_2', 5, 'clandestine', '비밀의, 은밀한', NULL, NULL, 'They held a clandestine meeting under the cover of darkness to discuss their secret plan.'),
  ('word', 'high_2', 5, 'clemency', '관용', '자비', NULL, 'The prisoner appealed to the governor for clemency, hoping to have his sentence reduced.'),
  ('word', 'high_2', 5, 'coalesce', '합치다', '융합하다', NULL, 'The small groups eventually coalesced into one large organization.'),
  ('word', 'high_2', 5, 'coerce', '강요하다', '강제하다', NULL, 'The criminal tried to coerce the witness into changing her testimony with threats.'),
  ('word', 'high_2', 5, 'coercion', '강제', '강압', NULL, 'The confession was dismissed because it was obtained through coercion rather than voluntary admission.'),
  ('word', 'high_2', 5, 'cognitive', '인지의', '인식의', NULL, 'Regular exercise has been shown to improve cognitive function.'),
  ('word', 'high_2', 5, 'colloquial', '구어체의', '일상 회화의', NULL, 'The textbook included colloquial expressions that are commonly used in everyday conversation.'),
  ('word', 'high_2', 5, 'combustion', '연소', '발화', NULL, 'The internal combustion engine revolutionized transportation in the early twentieth century.'),
  ('word', 'high_2', 5, 'commend', '칭찬하다', '추천하다', NULL, 'The teacher commended the student for her outstanding performance on the final examination.'),
  ('word', 'high_2', 5, 'commodious', '넓은', '널찍한', NULL, 'The commodious apartment had more than enough room for the entire family to live comfortably.'),
  ('word', 'high_2', 5, 'compel', '강요하다', '억지로 시키다', NULL, 'The evidence was so strong that it compelled the jury to reach a guilty verdict.'),
  ('word', 'high_2', 5, 'compile', '편집하다', '수집하다', NULL, 'The historian spent years to compile all the scattered documents into a single comprehensive book.'),
  ('word', 'high_2', 5, 'complacency', '안주', '자기만족', NULL, 'The team''s complacency after winning the first match led to their defeat in the second.'),
  ('word', 'high_2', 5, 'complacent', '자만하는', '안주하는', NULL, 'We must not become complacent about environmental issues.'),
  ('word', 'high_2', 5, 'comply', '따르다', '순응하다', NULL, 'All employees must comply with the new safety regulations starting next month.'),
  ('word', 'high_2', 5, 'concede', '인정하다', '양보하다', '시인하다', 'After a long debate, he had to concede that his opponent had a valid point.'),
  ('word', 'high_2', 5, 'conceive', '생각해내다', '임신하다', '상상하다', 'It is hard to conceive of a world without the internet.'),
  ('word', 'high_2', 6, 'concur', '동의하다', '일치하다', NULL, 'I concur with your assessment that the project needs more resources.'),
  ('word', 'high_2', 6, 'condemn', '비난하다', '선고하다', '유죄 판결을 내리다', 'The international community was quick to condemn the recent acts of aggression.'),
  ('word', 'high_2', 6, 'conducive', '~에 좋은, 도움이 되는', NULL, NULL, 'A quiet environment is often more conducive to focused study and concentration.'),
  ('word', 'high_2', 6, 'confine', '한정하다', '가두다', '국한시키다', 'Please try to confine your remarks to the main topic of the debate.'),
  ('word', 'high_2', 6, 'confluence', '합류', '합류점', NULL, 'The town is located at the confluence of two major rivers in the region.'),
  ('word', 'high_2', 6, 'congenial', '마음이 맞는', '쾌적한', NULL, 'The congenial atmosphere made everyone feel welcome.'),
  ('word', 'high_2', 6, 'conjecture', '추측', '짐작', NULL, 'His theory was based on conjecture rather than solid evidence, so it was hard to prove.'),
  ('word', 'high_2', 6, 'conjure', '떠올리다', '마법을 부리다', NULL, 'The smell of baking bread conjured up memories of her grandmother.'),
  ('word', 'high_2', 6, 'connotation', '함축', '내포된 의미', NULL, 'The word "home" carries a positive connotation of warmth, safety, and belonging.'),
  ('word', 'high_2', 6, 'consensus', '합의, 의견 일치', NULL, NULL, 'After a long discussion, the committee finally reached a consensus on the new policy.'),
  ('word', 'high_2', 6, 'consequence', '결과', '중요성', NULL, 'Failing to study for the exam will have serious consequences for your final grade.'),
  ('word', 'high_2', 6, 'consistent', '일관된', '변함없는', NULL, 'To achieve your fitness goals, it''s important to maintain a consistent workout routine every week.'),
  ('word', 'high_2', 6, 'consolidate', '통합하다', '강화하다', NULL, 'The company consolidated its operations into a single office.'),
  ('word', 'high_2', 6, 'consortium', '컨소시엄', '연합체', '협회', 'A consortium of universities collaborated to establish a shared research facility for advanced science.'),
  ('word', 'high_2', 6, 'conspicuous', '눈에 띄는', '뚜렷한', NULL, 'The red car was conspicuous among the white ones.'),
  ('word', 'high_2', 6, 'constrain', '제약하다', '억제하다', NULL, 'Budget limitations constrained our research options.'),
  ('word', 'high_2', 6, 'contend', '주장하다', '경쟁하다', NULL, 'Some scientists contend that the theory is flawed.'),
  ('word', 'high_2', 6, 'contingent', '~에 달려 있는', '부수적인', '파견단', 'The success of the project is contingent upon securing additional funding from external investors.'),
  ('word', 'high_2', 6, 'contrite', '뉘우치는', '회개하는', NULL, 'He appeared genuinely contrite and apologized sincerely for the harm he had caused.'),
  ('word', 'high_2', 6, 'conundrum', '난제', '수수께끼', NULL, 'Solving the economic conundrum requires innovative thinking and cooperation.'),
  ('word', 'high_2', 7, 'convene', '소집하다', '회합하다', NULL, 'The chairman decided to convene an emergency meeting to discuss the financial crisis.'),
  ('word', 'high_2', 7, 'converge', '수렴하다', '모이다', NULL, 'Thousands of fans converged on the stadium for the final match.'),
  ('word', 'high_2', 7, 'convoluted', '복잡한', '뒤얽힌', NULL, 'The plot of the novel was so convoluted that many readers found it hard to follow.'),
  ('word', 'high_2', 7, 'cordial', '다정한', '진심 어린', NULL, 'Despite their differences, the two leaders maintained a cordial relationship in public.'),
  ('word', 'high_2', 7, 'corollary', '필연적 결과', '추론', NULL, 'A natural corollary of increased urbanization is the growing demand for public transportation services.'),
  ('word', 'high_2', 7, 'corroborate', '확증하다', '뒷받침하다', NULL, 'The witness''s testimony corroborated the victim''s account.'),
  ('word', 'high_2', 7, 'corrode', '부식시키다', '침식하다', NULL, 'Salt water can corrode metal structures over time.'),
  ('word', 'high_2', 7, 'covert', '비밀의', '은밀한', NULL, 'The agency conducted a covert operation to gather intelligence.'),
  ('word', 'high_2', 7, 'credential', '자격증', '자격', '증명서', 'Applicants must provide valid credentials before they are considered for the research position.'),
  ('word', 'high_2', 7, 'credible', '믿을 만한', '신뢰할 수 있는', NULL, 'The witness provided a credible account of the events that took place that evening.'),
  ('word', 'high_2', 7, 'cryptic', '수수께끼 같은', '모호한', NULL, 'She left a cryptic message on his desk that took him hours to decipher.'),
  ('word', 'high_2', 7, 'culminate', '절정에 달하다', '최고조에 이르다', NULL, 'The festival culminated in a spectacular fireworks display.'),
  ('word', 'high_2', 7, 'culpable', '유죄인', '비난받을 만한', NULL, 'The investigation determined that the factory owner was culpable for the safety violations.'),
  ('word', 'high_2', 7, 'cumbersome', '번거로운', '다루기 힘든', NULL, 'The cumbersome application process discouraged many qualified candidates from applying for the position.'),
  ('word', 'high_2', 7, 'cumulative', '누적되는', NULL, NULL, 'The cumulative effect of pollution is damaging the ecosystem.'),
  ('word', 'high_2', 7, 'cursory', '대충의', '피상적인', NULL, 'A cursory glance at the report revealed several obvious errors in the data analysis.'),
  ('word', 'high_2', 7, 'curtail', '축소하다', '삭감하다', NULL, 'The government decided to curtail public spending.'),
  ('word', 'high_2', 7, 'cynical', '냉소적인', '비꼬는', NULL, 'He became cynical about politics after the scandal.'),
  ('word', 'high_2', 7, 'daunting', '벅찬', '겁나는', NULL, 'Climbing the mountain seemed like a daunting task.'),
  ('word', 'high_2', 7, 'dearth', '부족, 결핍', NULL, NULL, 'There was a severe dearth of fresh water in the desert region, causing great hardship.'),
  ('word', 'high_2', 8, 'debacle', '대실패', '참패', NULL, 'The product launch turned into a complete debacle when the software crashed on stage.'),
  ('word', 'high_2', 8, 'debilitate', '약화시키다', '쇠약하게 하다', NULL, 'The illness debilitated him for several months.'),
  ('word', 'high_2', 8, 'deceive', '속이다', '기만하다', NULL, 'Appearances can sometimes deceive us.'),
  ('word', 'high_2', 8, 'decorum', '예의', '품위', NULL, 'Students are expected to maintain proper decorum during the formal graduation ceremony.'),
  ('word', 'high_2', 8, 'decree', '법령', '칙령', '명령하다', 'The king issued a decree banning all public gatherings.'),
  ('word', 'high_2', 8, 'deem', '간주하다', '여기다', NULL, 'The committee deemed the proposal unacceptable.'),
  ('word', 'high_2', 8, 'defer', '미루다', '연기하다', '따르다', 'We decided to defer the decision until next month.'),
  ('word', 'high_2', 8, 'defiant', '반항적인', '도전적인', NULL, 'The defiant teenager refused to apologize, standing firm in her belief that she was right.'),
  ('word', 'high_2', 8, 'deft', '능숙한', '솜씨 좋은', NULL, 'The surgeon''s deft hands performed the delicate operation with remarkable precision.'),
  ('word', 'high_2', 8, 'degrade', '저하시키다', '품위를 떨어뜨리다', NULL, 'Plastic waste can degrade the quality of ocean water.'),
  ('word', 'high_2', 8, 'delegate', '위임하다', '대표', '대리인', 'A good leader knows when to delegate tasks to others.'),
  ('word', 'high_2', 8, 'deleterious', '해로운, 유해한', NULL, NULL, 'Smoking has numerous deleterious effects on human health, including lung cancer.'),
  ('word', 'high_2', 8, 'delineate', '윤곽을 그리다', '상세히 묘사하다', NULL, 'The architect used a pencil to clearly delineate the boundaries of the new building.'),
  ('word', 'high_2', 8, 'demeanor', '태도', '품행', NULL, 'Her calm demeanor during the crisis helped reassure everyone around her.'),
  ('word', 'high_2', 8, 'demise', '죽음', '소멸', NULL, 'The demise of the company was caused by poor management.'),
  ('word', 'high_2', 8, 'denounce', '비난하다', '고발하다', NULL, 'Several leaders publicly denounced the act of violence.'),
  ('word', 'high_2', 8, 'depict', '묘사하다', '그리다', NULL, 'The painting depicts a peaceful rural landscape.'),
  ('word', 'high_2', 8, 'deplete', '고갈시키다', '소모시키다', NULL, 'Overuse of groundwater has depleted the aquifer.'),
  ('word', 'high_2', 8, 'deplorable', '한탄스러운', '비참한', NULL, 'The working conditions in the factory were deplorable.'),
  ('word', 'high_2', 8, 'deprivation', '박탈', '결핍', NULL, 'Sleep deprivation can have serious consequences on both physical and mental health.'),
  ('word', 'high_2', 9, 'derelict', '버려진', '유기된', NULL, 'The derelict building on the corner has been abandoned for over twenty years.'),
  ('word', 'high_2', 9, 'deride', '조롱하다', '비웃다', NULL, 'Critics derided the new policy as impractical and poorly thought out.'),
  ('word', 'high_2', 9, 'desiccate', '건조시키다', '바싹 말리다', NULL, 'The extreme heat desiccated the soil, making it impossible for crops to grow.'),
  ('word', 'high_2', 9, 'desolate', '황량한', '쓸쓸한', NULL, 'The abandoned town looked completely desolate.'),
  ('word', 'high_2', 9, 'despot', '폭군', '독재자', NULL, 'The citizens revolted against the despot who had ruled the country with an iron fist.'),
  ('word', 'high_2', 9, 'detain', '구금하다', '억류하다', NULL, 'The police detained the suspect for questioning.'),
  ('word', 'high_2', 9, 'deter', '단념시키다', '억제하다', NULL, 'Heavy fines are meant to deter illegal parking.'),
  ('word', 'high_2', 9, 'detrimental', '해로운', '유해한', NULL, 'Excessive screen time can be detrimental to children''s eyesight and sleeping patterns.'),
  ('word', 'high_2', 9, 'devise', '고안하다', '발명하다', NULL, 'The engineer devised a new method to purify water.'),
  ('word', 'high_2', 9, 'devout', '독실한', '헌신적인', NULL, 'She is a devout follower of the environmental movement.'),
  ('word', 'high_2', 9, 'dichotomy', '이분법', '양분', NULL, 'There is a clear dichotomy between the rich and the poor in many developing nations.'),
  ('word', 'high_2', 9, 'diffident', '자신 없는', '소심한', NULL, 'The diffident student rarely spoke up in class, even when she knew the correct answer.'),
  ('word', 'high_2', 9, 'diffuse', '확산시키다', '퍼뜨리다', '분산된', 'The internet helped diffuse information across the globe.'),
  ('word', 'high_2', 9, 'digress', '주제에서 벗어나다', '탈선하다', NULL, 'The speaker tended to digress from the main topic.'),
  ('word', 'high_2', 9, 'diligent', '부지런한', '성실한', NULL, 'A diligent student often achieves excellent grades in all subjects.'),
  ('word', 'high_2', 9, 'diminutive', '아주 작은', '소형의', NULL, 'Despite his diminutive stature, the athlete displayed extraordinary strength during the competition.'),
  ('word', 'high_2', 9, 'dire', '심각한', '절박한', NULL, 'The country was in dire need of international aid following the devastating earthquake.'),
  ('word', 'high_2', 9, 'discern', '식별하다', '분별하다', NULL, 'It was difficult to discern the subtle differences between the two identical twins.'),
  ('word', 'high_2', 9, 'discourse', '담론', '논의', NULL, 'Public discourse on climate change has intensified recently.'),
  ('word', 'high_2', 9, 'discreet', '신중한', '조심스러운', NULL, 'Please be discreet about this matter, as the information is strictly confidential.'),
  ('word', 'high_2', 10, 'discrepancy', '불일치', '차이', NULL, 'There was a significant discrepancy between the two financial reports, which required further investigation.'),
  ('word', 'high_2', 10, 'disdainful', '경멸하는', '업신여기는', NULL, 'She gave a disdainful look at the poorly written report before tossing it aside.'),
  ('word', 'high_2', 10, 'dismal', '우울한', '음울한', '형편없는', 'The team''s dismal performance this season disappointed their loyal fans.'),
  ('word', 'high_2', 10, 'dismantle', '해체하다', '분해하다', NULL, 'Workers began to dismantle the old bridge piece by piece.'),
  ('word', 'high_2', 10, 'disparage', '폄하하다, 비난하다', NULL, NULL, 'It''s unprofessional to disparage your colleagues'' work in front of clients.'),
  ('word', 'high_2', 10, 'disparate', '서로 전혀 다른', '이질적인', NULL, 'The team consisted of individuals with disparate skills, but they worked together effectively.'),
  ('word', 'high_2', 10, 'disparity', '격차', '불균형', '차이', 'The growing disparity between the rich and the poor remains a pressing social issue worldwide.'),
  ('word', 'high_2', 10, 'displace', '이동시키다', '대체하다', '추방하다', 'The construction of the dam will displace hundreds of families living in the valley below.'),
  ('word', 'high_2', 10, 'disseminate', '보급하다', '퍼뜨리다', NULL, 'The organization works to disseminate scientific knowledge.'),
  ('word', 'high_2', 10, 'dissent', '반대', '이의', '반대하다', 'There was growing dissent among the members of the party.'),
  ('word', 'high_2', 10, 'dissipate', '흩어지다', '낭비하다', NULL, 'The morning fog began to dissipate as the sun rose higher in the sky.'),
  ('word', 'high_2', 10, 'divert', '전환하다', '돌리다', NULL, 'The government diverted funds to disaster relief efforts.'),
  ('word', 'high_2', 10, 'docile', '온순한', '유순한', NULL, 'The docile puppy sat quietly at its owner''s feet during the entire veterinary visit.'),
  ('word', 'high_2', 10, 'doctrine', '교리', '원칙', NULL, 'The political doctrine shaped the nation''s foreign policy.'),
  ('word', 'high_2', 10, 'dogmatic', '독단적인', '교조적인', NULL, 'His dogmatic approach to teaching left no room for student questions or discussion.'),
  ('word', 'high_2', 10, 'dormancy', '휴면', '잠복', NULL, 'Many plants enter a period of dormancy during the cold winter months to conserve energy.'),
  ('word', 'high_2', 10, 'dormant', '휴면의', '잠자는', NULL, 'The volcano had been dormant for over a century.'),
  ('word', 'high_2', 10, 'draconian', '가혹한', '엄격한', NULL, 'The government introduced draconian measures to control the spread of the virus.'),
  ('word', 'high_2', 10, 'dubious', '의심스러운', '수상한', NULL, 'The claim seemed dubious and lacked solid evidence.'),
  ('word', 'high_2', 10, 'dwindle', '줄어들다', '감소하다', NULL, 'The population of the species continued to dwindle.'),
  ('word', 'high_2', 11, 'ebullient', '열정적인', '넘치는', NULL, 'The ebullient crowd cheered wildly when the home team scored the winning goal.'),
  ('word', 'high_2', 11, 'eccentric', '별난', '기이한', NULL, 'The old artist was known for his eccentric fashion sense and unusual habits, but he was brilliant.'),
  ('word', 'high_2', 11, 'eclectic', '절충적인', '다양한', NULL, 'The museum features an eclectic collection of artworks ranging from ancient sculptures to modern installations.'),
  ('word', 'high_2', 11, 'eclipse', '가리다', '능가하다', '식(일식/월식)', 'Her achievements eclipsed those of her predecessors.'),
  ('word', 'high_2', 11, 'edifice', '건물', '대건축물', NULL, 'The grand edifice of the cathedral took nearly a century to complete.'),
  ('word', 'high_2', 11, 'efficacy', '효능', '유효성', NULL, 'Researchers are studying the efficacy of the new vaccine through extensive clinical trials.'),
  ('word', 'high_2', 11, 'egregious', '지독한', '심각한', NULL, 'The report highlighted several egregious errors in the company''s financial statements.'),
  ('word', 'high_2', 11, 'elation', '기쁨', '의기양양', NULL, 'A feeling of elation swept over her when she received the acceptance letter from the university.'),
  ('word', 'high_2', 11, 'elicit', '이끌어내다', '유도하다', NULL, 'The detective tried to elicit information from the reluctant witness.'),
  ('word', 'high_2', 11, 'eloquence', '웅변', '유창함', NULL, 'The lawyer was known for his eloquence in the courtroom.'),
  ('word', 'high_2', 11, 'eloquent', '웅변의', '유창한', NULL, 'Her eloquent speech captivated the audience, leaving a lasting impression on everyone present.'),
  ('word', 'high_2', 11, 'elucidate', '설명하다', '명확히 하다', NULL, 'Could you please elucidate your point further for better understanding?'),
  ('word', 'high_2', 11, 'embark', '착수하다', '승선하다', NULL, 'The young scientist decided to embark on a research project studying marine ecosystems.'),
  ('word', 'high_2', 11, 'embed', '내장하다', '끼워 넣다', NULL, 'Cultural values are deeply embedded in our daily habits.'),
  ('word', 'high_2', 11, 'eminent', '저명한', '탁월한', NULL, 'The conference featured several eminent scholars from universities around the world.'),
  ('word', 'high_2', 11, 'empathy', '공감', '감정이입', NULL, 'Empathy allows us to understand another person''s feelings.'),
  ('word', 'high_2', 11, 'emulate', '모방하다', '본받다', NULL, 'Young players often try to emulate their sports heroes.'),
  ('word', 'high_2', 11, 'encompass', '포함하다', '아우르다', NULL, 'The course encompasses a wide range of topics.'),
  ('word', 'high_2', 11, 'endeavor', '노력, 시도', '노력하다, 애쓰다', NULL, 'Succeeding in a new field requires a great deal of persistent endeavor.'),
  ('word', 'high_2', 11, 'endemic', '풍토성의', '고유의', NULL, 'Malaria is endemic in many tropical regions, affecting millions of people every year.'),
  ('word', 'high_2', 12, 'endorse', '지지하다', '홍보하다', '배서하다', 'Many celebrities choose to endorse various products in exchange for payment.'),
  ('word', 'high_2', 12, 'endow', '부여하다', '기부하다', NULL, 'Nature endowed the region with rich mineral resources.'),
  ('word', 'high_2', 12, 'engender', '야기하다', '낳다', NULL, 'Poverty can engender a cycle of social problems.'),
  ('word', 'high_2', 12, 'enigma', '수수께끼', '불가사의', NULL, 'The disappearance of the plane remains an enigma.'),
  ('word', 'high_2', 12, 'enmity', '적의', '증오', NULL, 'Decades of enmity between the two nations finally ended with the signing of a peace treaty.'),
  ('word', 'high_2', 12, 'entail', '수반하다', '필요로 하다', NULL, 'The project will entail a significant amount of research.'),
  ('word', 'high_2', 12, 'enumerate', '열거하다', '셀 수 있다', NULL, 'The report enumerates the various risk factors associated with the disease.'),
  ('word', 'high_2', 12, 'envision', '상상하다', '마음속에 그리다', NULL, 'She envisioned a future where everyone had access to clean water.'),
  ('word', 'high_2', 12, 'ephemeral', '수명이 짧은, 덧없는', NULL, NULL, 'The beauty of a sunset is ephemeral, fading quickly as night descends.'),
  ('word', 'high_2', 12, 'epitome', '전형', '완벽한 본보기', NULL, 'She is the epitome of grace and elegance, admired by everyone who meets her.'),
  ('word', 'high_2', 12, 'equivocal', '모호한, 애매한', NULL, NULL, 'His answer to the question was so equivocal that no one was sure what he really meant.'),
  ('word', 'high_2', 12, 'eradicate', '근절하다', '뿌리 뽑다', NULL, 'The global effort aims to eradicate polio from the face of the Earth.'),
  ('word', 'high_2', 12, 'erode', '침식하다', '서서히 파괴하다', NULL, 'Heavy rain gradually eroded the hillside.'),
  ('word', 'high_2', 12, 'erratic', '불규칙한', '변덕스러운', NULL, 'His erratic behavior worried his friends and family.'),
  ('word', 'high_2', 12, 'esoteric', '난해한, 소수만 아는', NULL, NULL, 'The philosopher''s lecture was filled with esoteric concepts that only a few experts understood.'),
  ('word', 'high_2', 12, 'espionage', '간첩 행위', '스파이 활동', NULL, 'He was arrested on charges of espionage.'),
  ('word', 'high_2', 12, 'espouse', '지지하다', '옹호하다', NULL, 'The professor espoused a new theory that challenged many long-held beliefs in the field.'),
  ('word', 'high_2', 12, 'esteem', '존경', '존중', '높이 평가하다', 'She is held in high esteem by her colleagues.'),
  ('word', 'high_2', 12, 'euphemism', '완곡어법', NULL, NULL, '"Economically disadvantaged" is a euphemism often used for "poor."'),
  ('word', 'high_2', 12, 'evident', '분명한', '명백한', NULL, 'It was evident from her tired eyes and frequent yawns that she hadn''t slept well last night.'),
  ('word', 'high_2', 13, 'exacerbate', '악화시키다', '더 심하게 만들다', NULL, 'Lack of sleep can often exacerbate existing health problems.'),
  ('word', 'high_2', 13, 'exalt', '높이다', '칭송하다', NULL, 'The poem exalts the beauty of nature.'),
  ('word', 'high_2', 13, 'excerpt', '발췌', '인용문', NULL, 'The teacher read an excerpt from the novel.'),
  ('word', 'high_2', 13, 'exemplary', '모범적인', '본보기가 되는', NULL, 'The firefighter received an award for his exemplary courage during the rescue operation.'),
  ('word', 'high_2', 13, 'exempt', '면제하다', '면제된', NULL, 'Students under the age of eighteen are exempt from paying the full entrance fee at the museum.'),
  ('word', 'high_2', 13, 'exert', '발휘하다', '행사하다', NULL, 'The government exerted pressure on the company to comply.'),
  ('word', 'high_2', 13, 'exhort', '권고하다', '열심히 권하다', NULL, 'The coach exhorted his players to give their best effort in the championship game.'),
  ('word', 'high_2', 13, 'exile', '추방', '망명', '추방하다', 'The writer lived in exile for over twenty years.'),
  ('word', 'high_2', 13, 'exonerate', '무죄를 입증하다', '면제하다', NULL, 'New DNA evidence helped exonerate the man who had been wrongfully imprisoned for years.'),
  ('word', 'high_2', 13, 'expedite', '촉진하다', '신속히 처리하다', NULL, 'We need to expedite the delivery of these supplies.'),
  ('word', 'high_2', 13, 'exponent', '지수', '대표자', '주창자', 'She is a leading exponent of sustainable architecture and has designed award-winning eco-friendly buildings.'),
  ('word', 'high_2', 13, 'exposition', '설명', '박람회', NULL, 'The teacher gave a clear exposition of the scientific principles behind the experiment.'),
  ('word', 'high_2', 13, 'exquisite', '정교한', '절묘한', NULL, 'The museum displayed an exquisite collection of porcelain.'),
  ('word', 'high_2', 13, 'extol', '극찬하다', '칭송하다', NULL, 'The book review extolled the author''s ability to create vivid and memorable characters.'),
  ('word', 'high_2', 13, 'extraneous', '무관한', '외부의', NULL, 'The editor removed all extraneous details that did not contribute to the main argument.'),
  ('word', 'high_2', 13, 'extravagant', '사치스러운', '과도한', NULL, 'The wedding was so extravagant that it made the news.'),
  ('word', 'high_2', 13, 'fabricate', '조작하다', '날조하다', '제작하다', 'The witness was accused of fabricating the entire story.'),
  ('word', 'high_2', 13, 'facet', '측면', '면', NULL, 'The documentary explored every facet of the environmental crisis facing the planet.'),
  ('word', 'high_2', 13, 'faction', '파벌', '분파', NULL, 'The political party split into two opposing factions.'),
  ('word', 'high_2', 13, 'fallacy', '오류', '잘못된 생각', NULL, 'It is a common fallacy that money always brings happiness.'),
  ('word', 'high_2', 14, 'fastidious', '꼼꼼한', '까다로운', NULL, 'She was a fastidious housekeeper, insisting that every item in the room be perfectly aligned.'),
  ('word', 'high_2', 14, 'fatigue', '피로', '지치게 하다', NULL, 'Mental fatigue can be just as harmful as physical tiredness.'),
  ('word', 'high_2', 14, 'fervent', '열렬한', '열정적인', NULL, 'She is a fervent supporter of human rights.'),
  ('word', 'high_2', 14, 'fiasco', '대실패', '대참사', NULL, 'The charity event turned into a fiasco when the main performer cancelled at the last moment.'),
  ('word', 'high_2', 14, 'fickle', '변덕스러운', '불안정한', NULL, 'The fickle weather made it difficult to plan outdoor activities, as conditions changed rapidly.'),
  ('word', 'high_2', 14, 'fiscal', '재정의', '회계의', NULL, 'The government announced new fiscal policies to boost the economy.'),
  ('word', 'high_2', 14, 'flagrant', '명백한', '극악한', NULL, 'The company was fined for its flagrant violation of environmental protection laws.'),
  ('word', 'high_2', 14, 'flaw', '결점', '결함', NULL, 'A small flaw in the design caused the machine to malfunction.'),
  ('word', 'high_2', 14, 'fledgling', '신출내기의', '미숙한', NULL, 'The fledgling company struggled to compete with established firms in the industry.'),
  ('word', 'high_2', 14, 'forebode', '예고하다', '예감하다', NULL, 'The dark clouds on the horizon seemed to forebode a severe thunderstorm approaching.'),
  ('word', 'high_2', 14, 'forfeit', '몰수당하다', '상실하다', '벌금', 'If you break the contract, you will forfeit your deposit.'),
  ('word', 'high_2', 14, 'formidable', '강력한', '무시무시한', NULL, 'The team faced a formidable opponent in the championship.'),
  ('word', 'high_2', 14, 'forsake', '버리다', '저버리다', NULL, 'He chose to forsake his comfortable city life and move to a remote mountain village.'),
  ('word', 'high_2', 14, 'fortuitous', '우연한, 행운의', '뜻밖의', NULL, 'It was a fortuitous coincidence that they met again years later in a different country.'),
  ('word', 'high_2', 14, 'foster', '육성하다', '조성하다', NULL, 'The school aims to foster a love of reading among its young students.'),
  ('word', 'high_2', 14, 'frivolous', '하찮은', '경박한', NULL, 'The judge dismissed the case, calling it a frivolous lawsuit with no legal merit.'),
  ('word', 'high_2', 14, 'frugal', '검소한, 절약하는', NULL, NULL, 'Despite his wealth, he lived a remarkably frugal life, avoiding unnecessary expenses.'),
  ('word', 'high_2', 14, 'fundamental', '근본적인', '기본적인', NULL, 'Understanding the fundamental principles of mathematics is essential for advanced scientific study.'),
  ('word', 'high_2', 14, 'futile', '헛된', '무익한', NULL, 'All attempts to negotiate with the kidnappers proved futile.'),
  ('word', 'high_2', 14, 'galvanize', '자극하다', '활기를 불어넣다', NULL, 'The inspiring documentary galvanized the community into taking action against pollution.'),
  ('word', 'high_2', 15, 'garner', '모으다', '획득하다', NULL, 'The film garnered critical acclaim and won several awards at international festivals.'),
  ('word', 'high_2', 15, 'garrison', '수비대', '주둔지', NULL, 'A garrison of soldiers was stationed at the border.'),
  ('word', 'high_2', 15, 'garrulous', '수다스러운', '말이 많은', NULL, 'The garrulous taxi driver talked nonstop throughout the entire ride to the airport.'),
  ('word', 'high_2', 15, 'genial', '상냥한', '친절한', NULL, 'The genial host made sure every guest felt welcome and comfortable at the dinner party.'),
  ('word', 'high_2', 15, 'germane', '관련 있는', '적절한', NULL, 'Please keep your comments germane to the topic being discussed in today''s meeting.'),
  ('word', 'high_2', 15, 'gist', '요지', '핵심', NULL, 'I did not read the entire article, but I understood the gist of the argument.'),
  ('word', 'high_2', 15, 'gratify', '만족시키다', '기쁘게 하다', NULL, 'It gratified her to see her students succeed.'),
  ('word', 'high_2', 15, 'gratuitous', '불필요한', '무료의', NULL, 'Critics condemned the film for its gratuitous violence that added nothing to the storyline.'),
  ('word', 'high_2', 15, 'gregarious', '사교적인', '군집성의', NULL, 'She is a very gregarious person who loves attending parties and meeting new people.'),
  ('word', 'high_2', 15, 'grievance', '불만', '고충', NULL, 'The workers filed a formal grievance about working conditions.'),
  ('word', 'high_2', 15, 'guile', '교활함', '간계', NULL, 'The fox is often portrayed in fables as a creature of great guile and cunning.'),
  ('word', 'high_2', 15, 'gullible', '잘 속는', '순진한', NULL, 'He was so gullible that he believed every rumor he heard.'),
  ('word', 'high_2', 15, 'hackneyed', '진부한, 낡아빠진', NULL, NULL, 'The movie''s plot was so hackneyed that it failed to surprise or engage the audience.'),
  ('word', 'high_2', 15, 'hamper', '방해하다', '저해하다', NULL, 'Bad weather hampered the rescue efforts.'),
  ('word', 'high_2', 15, 'haphazard', '무계획적인, 되는 대로의', NULL, NULL, 'The room was arranged in a haphazard manner, with books and clothes scattered everywhere.'),
  ('word', 'high_2', 15, 'harbinger', '전조', '선구자', NULL, 'The first robin of spring is often seen as a harbinger of warmer days ahead.'),
  ('word', 'high_2', 15, 'hasten', '서두르다', '재촉하다', NULL, 'The crisis hastened the need for political reform.'),
  ('word', 'high_2', 15, 'hegemony', '패권', '지배권', NULL, 'The empire maintained its hegemony over the region for centuries.'),
  ('word', 'high_2', 15, 'heresy', '이단', '이설', NULL, 'Galileo''s ideas were once considered heresy by the church.'),
  ('word', 'high_2', 15, 'heuristic', '체험적인', '발견적인', '발견법적인', 'The problem-solving approach was largely heuristic, relying on trial and error rather than strict algorithms.'),
  ('word', 'high_2', 16, 'hinder', '방해하다', '저해하다', NULL, 'Heavy rain can significantly hinder the progress of construction work.'),
  ('word', 'high_2', 16, 'homogeneous', '동질적인', '균일한', NULL, 'The researcher noted that the sample group was too homogeneous to represent the broader population.'),
  ('word', 'high_2', 16, 'humanitarian', '인도주의적인', '인도주의자', NULL, 'The organization provides humanitarian aid to refugees.'),
  ('word', 'high_2', 16, 'humility', '겸손', '겸허', NULL, 'Despite his fame, he always showed great humility.'),
  ('word', 'high_2', 16, 'hypocrisy', '위선', NULL, NULL, 'The politician was accused of hypocrisy for breaking his own promises.'),
  ('word', 'high_2', 16, 'idiosyncrasy', '특이한 버릇', '특성', NULL, 'One of his idiosyncrasies is that he always taps his pen three times before writing.'),
  ('word', 'high_2', 16, 'ignominious', '불명예스러운', '수치스러운', NULL, 'The team suffered an ignominious defeat, losing every single game of the season.'),
  ('word', 'high_2', 16, 'immerse', '담그다', '몰두하다', NULL, 'To truly learn a new language, you should try to immerse yourself in the culture where it is spoken.'),
  ('word', 'high_2', 16, 'imminent', '임박한', '곧 닥칠', NULL, 'Residents were warned that a powerful hurricane was imminent and urged to evacuate immediately.'),
  ('word', 'high_2', 16, 'immutable', '변경할 수 없는', '불변의', NULL, 'The laws of physics are considered immutable, remaining constant throughout the universe.'),
  ('word', 'high_2', 16, 'impair', '손상시키다', '약화시키다', NULL, 'Lack of sleep can impair your ability to concentrate.'),
  ('word', 'high_2', 16, 'impartial', '공정한', '편견 없는', NULL, 'A good judge must remain impartial and base decisions solely on the evidence presented.'),
  ('word', 'high_2', 16, 'impasse', '교착 상태, 난국', '막다른 골목', NULL, 'Negotiations reached an impasse, with neither side willing to compromise on key issues.'),
  ('word', 'high_2', 16, 'impeccable', '흠 잡을 데 없는', '완벽한', NULL, 'Her impeccable manners made a great impression on everyone she met at the formal dinner.'),
  ('word', 'high_2', 16, 'impecunious', '무일푼의, 가난한', NULL, NULL, 'He arrived in the city as an impecunious young artist, with only a few dollars to his name.'),
  ('word', 'high_2', 16, 'impede', '방해하다', '저해하다', NULL, 'Heavy traffic impeded the progress of emergency vehicles trying to reach the accident scene.'),
  ('word', 'high_2', 16, 'impediment', '장애', '방해물', NULL, 'The lack of reliable internet access is a major impediment to education in remote areas.'),
  ('word', 'high_2', 16, 'imperative', '필수적인', '긴급한', '명령', 'It is imperative that we act before the situation worsens.'),
  ('word', 'high_2', 16, 'impervious', '~에 영향받지 않는', '통과시키지 않는', NULL, 'The new waterproof coating made the tent impervious to even the heaviest rain.'),
  ('word', 'high_2', 16, 'implausible', '믿기 어려운', '그럴듯하지 않은', NULL, 'The detective found the suspect''s alibi to be implausible and continued the investigation.'),
  ('word', 'high_2', 17, 'implicit', '암묵적인', '내포된', NULL, 'There was an implicit agreement between the two parties.'),
  ('word', 'high_2', 17, 'impoverish', '가난하게 만들다', '빈곤하게 하다', NULL, 'Years of conflict impoverished the nation, leaving millions without basic necessities.'),
  ('word', 'high_2', 17, 'impromptu', '즉흥적인', '준비 없는', NULL, 'The musician gave an impromptu performance in the park that attracted a large crowd.'),
  ('word', 'high_2', 17, 'improvise', '즉흥적으로 하다', '임기응변하다', NULL, 'When the equipment failed, the team had to improvise.'),
  ('word', 'high_2', 17, 'inadvertent', '고의가 아닌', '부주의한', '우연한', 'His inadvertent comment caused an awkward silence in the room, though he hadn''t meant to offend anyone.'),
  ('word', 'high_2', 17, 'incite', '선동하다', '자극하다', NULL, 'The speech was designed to incite anger among the crowd.'),
  ('word', 'high_2', 17, 'incline', '경향이 있다', '기울이다', '경사', 'I am inclined to agree with your point of view.'),
  ('word', 'high_2', 17, 'incongruous', '어울리지 않는', '부조화의', NULL, 'The modern glass building looked incongruous among the historic stone structures of the old town.'),
  ('word', 'high_2', 17, 'incumbent', '현직의', '의무적인', NULL, 'It is incumbent upon all citizens to vote in the upcoming election for their future''s sake.'),
  ('word', 'high_2', 17, 'indifferent', '무관심한', '냉담한', NULL, 'He seemed completely indifferent to the suffering around him.'),
  ('word', 'high_2', 17, 'indignant', '분개한', '분노한', NULL, 'She was indignant about the unfair treatment she received.'),
  ('word', 'high_2', 17, 'indignation', '분개', '분노', NULL, 'The community expressed great indignation over the government''s decision to close the local hospital.'),
  ('word', 'high_2', 17, 'indolent', '게으른', '나태한', NULL, 'The indolent student spent most of his time watching television instead of studying.'),
  ('word', 'high_2', 17, 'induce', '유도하다', '유발하다', NULL, 'Stress can induce a variety of health problems.'),
  ('word', 'high_2', 17, 'inept', '서투른', '무능한', NULL, 'His inept handling of the crisis only made the situation worse for everyone involved.'),
  ('word', 'high_2', 17, 'infer', '추론하다', '추측하다', NULL, 'From the evidence, we can infer that the suspect was present.'),
  ('word', 'high_2', 17, 'inflict', '가하다', '입히다', NULL, 'The storm inflicted severe damage on coastal communities.'),
  ('word', 'high_2', 17, 'infuse', '불어넣다', '주입하다', NULL, 'The new manager infused fresh energy and enthusiasm into the struggling department.'),
  ('word', 'high_2', 17, 'ingenious', '기발한', '독창적인', NULL, 'The engineer came up with an ingenious solution to the complex technical problem.'),
  ('word', 'high_2', 17, 'inherent', '타고난', '내재하는', NULL, 'There is an inherent risk of injury in extreme sports like rock climbing.'),
  ('word', 'high_2', 18, 'inhibit', '억제하다', '방해하다', NULL, 'Fear can inhibit a person''s ability to take risks.'),
  ('word', 'high_2', 18, 'innate', '타고난, 선천적인', NULL, NULL, 'Some people seem to have an innate talent for music, even without formal training.'),
  ('word', 'high_2', 18, 'inquisitive', '호기심 많은', '탐구적인', NULL, 'The inquisitive child asked dozens of questions about how airplanes stay in the sky.'),
  ('word', 'high_2', 18, 'inscription', '비문', '명문', NULL, 'The ancient inscription on the stone was difficult to read.'),
  ('word', 'high_2', 18, 'insidious', '교활한', '서서히 퍼지는', NULL, 'The disease is particularly insidious because its symptoms do not appear until much later.'),
  ('word', 'high_2', 18, 'instigate', '선동하다', '촉발하다', NULL, 'He was accused of instigating the riot.'),
  ('word', 'high_2', 18, 'integral', '필수적인', '통합된', NULL, 'Teamwork is an integral part of any successful project.'),
  ('word', 'high_2', 18, 'intercept', '가로채다', '차단하다', NULL, 'The police intercepted the shipment of illegal goods.'),
  ('word', 'high_2', 18, 'interim', '중간의', '임시의', '과도기', 'An interim manager was appointed until a permanent one was found.'),
  ('word', 'high_2', 18, 'interject', '끼어들다', '불쑥 말하다', NULL, 'He tried to interject a question during the lecture, but the professor continued speaking.'),
  ('word', 'high_2', 18, 'intermittent', '간헐적인', '단속적인', NULL, 'The region experienced intermittent rainfall throughout the week.'),
  ('word', 'high_2', 18, 'intrepid', '대담한', '용감한', NULL, 'The intrepid explorer ventured deep into the uncharted jungle despite the many dangers.'),
  ('word', 'high_2', 18, 'intricate', '복잡한', '정교한', NULL, 'The artist created an intricate pattern using tiny beads.'),
  ('word', 'high_2', 18, 'intrinsic', '본질적인', '고유한', NULL, 'Curiosity is an intrinsic part of human nature.'),
  ('word', 'high_2', 18, 'invoke', '발동하다', '호소하다', NULL, 'The lawyer invoked the right to remain silent.'),
  ('word', 'high_2', 18, 'irony', '아이러니', '반어', NULL, 'The irony of the situation was that the fire station burned down.'),
  ('word', 'high_2', 18, 'irrevocable', '돌이킬 수 없는', '취소 불가능한', NULL, 'Once the decision is made, the consequences will be irrevocable and cannot be undone.'),
  ('word', 'high_2', 18, 'jeopardize', '위태롭게 하다', '위험에 빠뜨리다', NULL, 'Revealing confidential information could jeopardize the entire undercover operation.'),
  ('word', 'high_2', 18, 'jubilant', '승리감에 넘치는', '기뻐하는', NULL, 'The crowd was jubilant after their team scored the winning goal in the final seconds.'),
  ('word', 'high_2', 18, 'jurisdiction', '관할권', '사법권', NULL, 'The case fell outside the jurisdiction of the local court.'),
  ('word', 'high_2', 19, 'jurisprudence', '법학', '법률학', NULL, 'The study of jurisprudence helps law students understand the philosophical foundations of legal systems.'),
  ('word', 'high_2', 19, 'juxtapose', '나란히 놓다', '병치하다', NULL, 'The art exhibition sought to juxtapose ancient artifacts with modern sculptures to highlight cultural evolution.'),
  ('word', 'high_2', 19, 'kindle', '불을 지피다', '불러일으키다', NULL, 'The teacher''s passionate lectures kindled a love of literature in many of her students.'),
  ('word', 'high_2', 19, 'kinship', '친족 관계', '연대감', NULL, 'Despite their different backgrounds, they felt a strong sense of kinship due to their shared experiences.'),
  ('word', 'high_2', 19, 'kudos', '영광', '칭찬', NULL, 'Kudos to the entire team for their outstanding performance in the national competition.'),
  ('word', 'high_2', 19, 'laborious', '힘든', '고된', NULL, 'Sorting through thousands of documents by hand was a laborious but necessary task.'),
  ('word', 'high_2', 19, 'laconic', '간결한', '말을 많이 하지 않는', NULL, 'His laconic response to the long question surprised everyone with its brevity.'),
  ('word', 'high_2', 19, 'lament', '한탄하다', '애통해하다', NULL, 'She began to lament the loss of her childhood innocence as she grew older.'),
  ('word', 'high_2', 19, 'languish', '시들다', '쇠약해지다', NULL, 'The prisoner languished in a dark cell for years before finally being released.'),
  ('word', 'high_2', 19, 'laudable', '칭찬할 만한', '훌륭한', NULL, 'The charity''s efforts to provide clean water to rural communities are truly laudable.'),
  ('word', 'high_2', 19, 'lethal', '치명적인', '치사의', NULL, 'The venom of this snake is lethal to humans.'),
  ('word', 'high_2', 19, 'lethargic', '무기력한', '나른한', NULL, 'The hot summer weather made everyone feel lethargic and unwilling to do anything.'),
  ('word', 'high_2', 19, 'leverage', '영향력', '활용하다', '지렛대', 'She used her expertise to leverage a better deal.'),
  ('word', 'high_2', 19, 'levity', '경솔함', '가벼움', NULL, 'A little levity during the tense meeting helped everyone relax and think more clearly.'),
  ('word', 'high_2', 19, 'liable', '책임이 있는', '~하기 쉬운', NULL, 'The manufacturer is liable for any defects in the product.'),
  ('word', 'high_2', 19, 'linger', '남아 있다', '오래 머무르다', NULL, 'The smell of coffee lingered in the room all morning.'),
  ('word', 'high_2', 19, 'listless', '무기력한', '활기 없는', NULL, 'After the disappointing news, he sat in a listless state, staring out the window.'),
  ('word', 'high_2', 19, 'litigation', '소송', '재판', NULL, 'The company faced years of costly litigation.'),
  ('word', 'high_2', 19, 'loathe', '몹시 싫어하다', '혐오하다', NULL, 'She loathed having to wake up early on weekends.'),
  ('word', 'high_2', 19, 'lofty', '높은', '고상한', '거만한', 'He had lofty ambitions of becoming a world-famous scientist.'),
  ('word', 'high_2', 20, 'lucid', '명쾌한', '명료한', NULL, 'After waking from the anesthesia, she was surprisingly lucid and could recall everything.'),
  ('word', 'high_2', 20, 'lucrative', '수익성 있는', '돈이 되는', NULL, 'The technology sector remains one of the most lucrative industries for young entrepreneurs today.'),
  ('word', 'high_2', 20, 'luminous', '빛나는', '야광의', NULL, 'The luminous dial of the watch made it easy to read the time even in the darkest room.'),
  ('word', 'high_2', 20, 'magnanimous', '관대한', '도량이 넓은', NULL, 'Despite losing the championship, the captain was magnanimous in defeat, congratulating the opposing team wholeheartedly.'),
  ('word', 'high_2', 20, 'malady', '질병', '병', NULL, 'The doctor struggled to diagnose the rare malady that had afflicted the patient.'),
  ('word', 'high_2', 20, 'malevolent', '악의적인', '사악한', NULL, 'The antagonist''s malevolent plot was ultimately thwarted by the hero.'),
  ('word', 'high_2', 20, 'malicious', '악의적인', '심술궂은', NULL, 'He spread malicious rumors about his rival to damage their reputation.'),
  ('word', 'high_2', 20, 'malleable', '유연한', '영향을 잘 받는', NULL, 'Gold is a highly malleable metal, which can be easily shaped into intricate jewelry.'),
  ('word', 'high_2', 20, 'mandate', '명령', '위임', '명령하다', 'The government issued a mandate requiring all schools to reopen.'),
  ('word', 'high_2', 20, 'manifest', '나타내다', '명백한', '목록', 'Her talent manifested itself at a very young age.'),
  ('word', 'high_2', 20, 'manipulate', '조종하다', '다루다', NULL, 'Skilled debaters often try to manipulate public opinion with persuasive arguments.'),
  ('word', 'high_2', 20, 'meager', '빈약한', '부족한', NULL, 'The workers survived on meager rations during the long and difficult winter months.'),
  ('word', 'high_2', 20, 'mediocre', '평범한', '보통의', NULL, 'The restaurant received mixed reviews, with many diners describing the food as mediocre.'),
  ('word', 'high_2', 20, 'menace', '위협', '위험인물', '위협하다', 'Pollution is a growing menace to public health.'),
  ('word', 'high_2', 20, 'mentor', '멘토', '조언자', NULL, 'A good mentor can guide you through difficult career decisions.'),
  ('word', 'high_2', 20, 'mercurial', '변덕스러운', '불안정한', NULL, 'His mercurial temperament made it difficult for colleagues to predict his reactions.'),
  ('word', 'high_2', 20, 'mere', '단순한', '그저 ~에 불과한', NULL, 'The mere thought of the exam made her anxious.'),
  ('word', 'high_2', 20, 'meticulous', '꼼꼼한, 세심한', NULL, NULL, 'The artist was meticulous in her brushstrokes, ensuring every detail was perfect.'),
  ('word', 'high_2', 20, 'mingle', '어울리다', '섞이다', NULL, 'Guests mingled freely at the reception after the ceremony.'),
  ('word', 'high_2', 20, 'misnomer', '잘못된 명칭', '오칭', NULL, 'Calling the device a phone is a misnomer since it is now used primarily for internet access.'),
  ('word', 'high_2', 21, 'mitigate', '완화시키다, 경감하다', NULL, NULL, 'Wearing a helmet can significantly mitigate the risk of head injuries in an accident.'),
  ('word', 'high_2', 21, 'monopoly', '독점', '전매', NULL, 'The corporation held a monopoly over the telecommunications market.'),
  ('word', 'high_2', 21, 'morale', '사기', '의욕', NULL, 'The victory greatly boosted the morale of the entire team.'),
  ('word', 'high_2', 21, 'mundane', '일상적인', '평범한', NULL, 'She longed for adventure to escape her mundane routine.'),
  ('word', 'high_2', 21, 'nascent', '초기의', '발생기의', NULL, 'The nascent democracy faced many challenges as it tried to establish a stable government.'),
  ('word', 'high_2', 21, 'nefarious', '사악한', '비도덕적인', NULL, 'The detective uncovered a nefarious plot to steal valuable historical documents from the museum.'),
  ('word', 'high_2', 21, 'negate', '무효화하다', '부정하다', NULL, 'One mistake could negate all the progress we have made.'),
  ('word', 'high_2', 21, 'negligent', '태만한', '부주의한', NULL, 'The doctor was found negligent in his treatment of the patient.'),
  ('word', 'high_2', 21, 'neophyte', '초보자', '신참', NULL, 'As a neophyte in the world of coding, she spent countless hours learning the basics and debugging simple programs.'),
  ('word', 'high_2', 21, 'nominal', '명목상의', '아주 적은', NULL, 'He held a nominal position with no real authority.'),
  ('word', 'high_2', 21, 'nonchalant', '무심한', '태연한', NULL, 'He tried to appear nonchalant, but his trembling hands revealed his true nervousness.'),
  ('word', 'high_2', 21, 'nostalgia', '향수', '그리움', NULL, 'The old photographs filled her with nostalgia.'),
  ('word', 'high_2', 21, 'notoriety', '악명', NULL, NULL, 'The criminal gained notoriety for his daring escapes.'),
  ('word', 'high_2', 21, 'novice', '초보자', '신참', NULL, 'As a novice, she still had much to learn about cooking.'),
  ('word', 'high_2', 21, 'nurture', '양육하다', '육성하다', NULL, 'Parents play a crucial role in nurturing their children''s talents.'),
  ('word', 'high_2', 21, 'obfuscate', '애매하게 하다', '혼란스럽게 하다', NULL, 'Some politicians try to obfuscate the truth by using complicated jargon.'),
  ('word', 'high_2', 21, 'oblique', '비스듬한', '간접적인', NULL, 'He made an oblique reference to the scandal without directly mentioning anyone by name.'),
  ('word', 'high_2', 21, 'oblivious', '의식하지 못하는', '염두에 없는', NULL, 'He was so engrossed in his book that he remained oblivious to the noise outside.'),
  ('word', 'high_2', 21, 'obscure', '모호한', '잘 알려지지 않은', '가리다', 'The meaning of the ancient text remains obscure.'),
  ('word', 'high_2', 21, 'obsolete', '구식의', '시대에 뒤떨어진', NULL, 'Rapid technological advancement has made many traditional manufacturing methods obsolete in recent years.'),
  ('word', 'high_2', 22, 'obstinate', '완고한', '고집 센', NULL, 'The obstinate negotiator refused to make any concessions despite pressure from both sides.'),
  ('word', 'high_2', 22, 'ominous', '불길한', '험악한', NULL, 'The ominous silence that followed the announcement made everyone in the room uneasy.'),
  ('word', 'high_2', 22, 'onset', '시작', '발생', NULL, 'The onset of winter brought freezing temperatures to the region.'),
  ('word', 'high_2', 22, 'oppress', '억압하다', '탄압하다', NULL, 'The dictator used the military to oppress the civilian population.'),
  ('word', 'high_2', 22, 'opulent', '호화로운', '풍요로운', NULL, 'The opulent mansion featured marble floors, crystal chandeliers, and gold-plated fixtures.'),
  ('word', 'high_2', 22, 'ordeal', '시련', '고난', NULL, 'Surviving the shipwreck was a terrifying ordeal.'),
  ('word', 'high_2', 22, 'orthodox', '정통의', '전통적인', NULL, 'His orthodox approach to teaching did not appeal to modern students.'),
  ('word', 'high_2', 22, 'ostentatious', '과시하는, 허세 부리는', NULL, NULL, 'The celebrity''s ostentatious mansion, complete with gold fixtures, was frequently featured in magazines.'),
  ('word', 'high_2', 22, 'outweigh', '~보다 크다', '능가하다', NULL, 'The benefits of the plan outweigh the potential risks.'),
  ('word', 'high_2', 22, 'overlook', '간과하다', '못 보고 넘어가다', '내려다보다', 'It is easy to overlook small details when you are in a hurry.'),
  ('word', 'high_2', 22, 'overthrow', '전복하다', '타도하다', NULL, 'The rebels attempted to overthrow the government.'),
  ('word', 'high_2', 22, 'pact', '협정', '조약', NULL, 'The two nations signed a pact to reduce nuclear weapons.'),
  ('word', 'high_2', 22, 'painstaking', '공들인', '근면한', NULL, 'The restoration of the painting required painstaking effort.'),
  ('word', 'high_2', 22, 'panacea', '만병통치약', '만능 해결책', NULL, 'Technology alone is not a panacea for all the problems facing the modern education system.'),
  ('word', 'high_2', 22, 'paradigm', '전형적인 예, 패러다임', '이론적 틀', NULL, 'The invention of the internet marked a paradigm shift in how information is shared globally.'),
  ('word', 'high_2', 22, 'paradox', '역설', '모순', NULL, 'It''s a strange paradox that by trying less, you sometimes achieve more.'),
  ('word', 'high_2', 22, 'parsimonious', '인색한', '검약하는', NULL, 'Despite his wealth, he was known for being parsimonious, rarely spending money on luxuries.'),
  ('word', 'high_2', 22, 'partisan', '당파적인', '편파적인', '당원', 'The debate became increasingly partisan and hostile.'),
  ('word', 'high_2', 22, 'patrimony', '유산', '세습 재산', NULL, 'The ancient ruins are part of the nation''s cultural patrimony.'),
  ('word', 'high_2', 22, 'patronize', '후원하다', '깔보다', NULL, 'Do not patronize me by explaining things I already know.'),
  ('word', 'high_2', 23, 'pedagogy', '교육학', '교수법', NULL, 'Modern pedagogy emphasizes student-centered learning rather than traditional lecture-based instruction.'),
  ('word', 'high_2', 23, 'pending', '미결의', '보류 중인', NULL, 'The decision is still pending approval from the board.'),
  ('word', 'high_2', 23, 'perceive', '인지하다', '감지하다', NULL, 'It''s important to understand how others perceive your actions and words.'),
  ('word', 'high_2', 23, 'perennial', '영원한', '다년생의', '반복되는', 'Water scarcity is a perennial problem that affects millions of people in arid regions worldwide.'),
  ('word', 'high_2', 23, 'perfunctory', '형식적인, 마지못해 하는', NULL, NULL, 'His perfunctory apology did not convince anyone that he was truly sorry for his actions.'),
  ('word', 'high_2', 23, 'perpetual', '영구적인', '끊임없는', NULL, 'The perpetual noise from the construction site made it impossible to concentrate on studying.'),
  ('word', 'high_2', 23, 'perpetuate', '영속시키다', '지속시키다', NULL, 'Stereotypes in the media perpetuate harmful misconceptions.'),
  ('word', 'high_2', 23, 'persevere', '인내하다', '끈기 있게 계속하다', NULL, 'Despite numerous setbacks, the young scientist chose to persevere with her groundbreaking research.'),
  ('word', 'high_2', 23, 'pertinent', '적절한', '관련 있는', NULL, 'The lawyer presented only the most pertinent evidence to strengthen her case before the jury.'),
  ('word', 'high_2', 23, 'pervasive', '만연하는', '스며드는', NULL, 'The pervasive smell of fresh baking bread filled the entire house, inviting everyone to the kitchen.'),
  ('word', 'high_2', 23, 'philanthropy', '자선', '박애주의', NULL, 'Her lifelong commitment to philanthropy resulted in the construction of dozens of schools in rural regions.'),
  ('word', 'high_2', 23, 'pivotal', '중추적인', '중요한', NULL, 'The invention of the printing press was a pivotal moment in human history.'),
  ('word', 'high_2', 23, 'plausible', '그럴듯한', '타당한', NULL, 'The detective found the suspect''s alibi plausible but continued investigating to be certain.'),
  ('word', 'high_2', 23, 'plethora', '과다', '많은 양', NULL, 'The market offers a plethora of options for healthy organic foods.'),
  ('word', 'high_2', 23, 'posthumous', '사후의', '유작의', NULL, 'The author received a posthumous award for the novel that was published after her passing.'),
  ('word', 'high_2', 23, 'pragmatic', '실용적인, 현실적인', NULL, NULL, 'She took a pragmatic approach to solving the complex problem, focusing on practical solutions.'),
  ('word', 'high_2', 23, 'precarious', '불안정한', '위태로운', NULL, 'The rock climber found himself in a precarious position, clinging to a narrow ledge.'),
  ('word', 'high_2', 23, 'precedent', '선례', '전례', NULL, 'The court ruling set a legal precedent that would influence future cases involving digital privacy.'),
  ('word', 'high_2', 23, 'preclude', '방해하다', '미리 막다', NULL, 'A prior engagement will preclude me from attending the meeting tomorrow.'),
  ('word', 'high_2', 23, 'premise', '전제', '가정', NULL, 'The entire argument was based on the premise that economic growth would continue indefinitely.'),
  ('word', 'high_2', 24, 'prevalent', '널리 퍼진', '일반적인', NULL, 'The belief in good luck charms is still prevalent in many cultures.'),
  ('word', 'high_2', 24, 'prioritize', '우선순위를 매기다', NULL, NULL, 'To manage your time effectively, it''s essential to prioritize your tasks each morning.'),
  ('word', 'high_2', 24, 'profound', '엄청난', '깊은', '심오한', 'His book had a profound impact on my understanding of philosophy.'),
  ('word', 'high_2', 24, 'prognosis', '예후', '예측', NULL, 'The doctor said the patient''s prognosis was favorable and a full recovery was expected within weeks.'),
  ('word', 'high_2', 24, 'proliferate', '증식하다, 급증하다', NULL, NULL, 'Misinformation tends to proliferate rapidly on social media platforms without proper fact-checking.'),
  ('word', 'high_2', 24, 'propagate', '전파하다', '번식시키다', '확산시키다', 'Social media platforms can propagate misinformation at an alarming speed across the globe.'),
  ('word', 'high_2', 24, 'proprietary', '독점적인', '소유권의', NULL, 'The company developed proprietary technology that gave it a significant advantage over competitors.'),
  ('word', 'high_2', 24, 'proximity', '근접', '가까움', NULL, 'The proximity of the school to the main road raised safety concerns among parents.'),
  ('word', 'high_2', 24, 'prudent', '신중한', '현명한', NULL, 'It would be prudent to save some money for emergencies rather than spending it all at once.'),
  ('word', 'high_2', 24, 'quandary', '곤경', '난처한 상황', NULL, 'The student found himself in a quandary, unable to decide which university to attend.'),
  ('word', 'high_2', 24, 'quell', '진압하다', '가라앉히다', NULL, 'The police had to use tear gas to quell the escalating riot in the city center.'),
  ('word', 'high_2', 24, 'querulous', '불평하는', '짜증내는', NULL, 'The querulous customer complained about every single dish on the menu, making the dining experience unpleasant.'),
  ('word', 'high_2', 24, 'quixotic', '돈키호테식의', '비현실적인', '공상적인', 'His quixotic quest to save every stray animal in the city, though noble, was ultimately impossible to achieve.'),
  ('word', 'high_2', 24, 'rationale', '근거', '이유', '논리적 근거', 'The manager explained the rationale behind the decision to restructure the entire department.'),
  ('word', 'high_2', 24, 'recalcitrant', '저항하는', '다루기 힘든', NULL, 'The recalcitrant donkey refused to move, despite all efforts to coax it forward.'),
  ('word', 'high_2', 24, 'reconcile', '화해시키다', '조정하다', NULL, 'It was difficult to reconcile his current behavior with his past promises.'),
  ('word', 'high_2', 24, 'referendum', '국민투표', '주민투표', NULL, 'The government announced a referendum to let citizens decide on the proposed constitutional amendment.'),
  ('word', 'high_2', 24, 'remnant', '잔재', '나머지', '자취', 'The ruins are the last remnant of a once-thriving ancient civilization that existed centuries ago.'),
  ('word', 'high_2', 24, 'renaissance', '르네상스', '부흥', '재생', 'The city experienced a cultural renaissance after decades of economic decline and neglect.'),
  ('word', 'high_2', 24, 'repercussion', '영향', '반향', '여파', 'The economic repercussions of the trade war were felt across multiple industries worldwide.'),
  ('word', 'high_2', 25, 'replenish', '보충하다', '다시 채우다', NULL, 'It is essential to replenish your body with water and nutrients after intense physical exercise.'),
  ('word', 'high_2', 25, 'resilience', '회복력', '탄력', NULL, 'Despite the economic downturn, the company demonstrated remarkable resilience and bounced back stronger.'),
  ('word', 'high_2', 25, 'resilient', '회복력 있는', '탄력 있는', NULL, 'Despite facing numerous setbacks, the resilient athlete always managed to bounce back stronger.'),
  ('word', 'high_2', 25, 'retract', '철회하다', '취소하다', NULL, 'The newspaper was forced to retract the article after discovering that the source was unreliable.'),
  ('word', 'high_2', 25, 'reverberate', '반향하다', '울려 퍼지다', NULL, 'The sound of the thunder began to reverberate through the entire valley, shaking the windows.'),
  ('word', 'high_2', 25, 'revoke', '철회하다', '취소하다', '폐지하다', 'The authorities decided to revoke the company''s license after discovering multiple safety violations.'),
  ('word', 'high_2', 25, 'rhetoric', '수사학', '미사여구', NULL, 'The politician''s speech was full of empty rhetoric but lacked any concrete plans for improvement.'),
  ('word', 'high_2', 25, 'rudimentary', '기초적인', '초보적인', NULL, 'Even a rudimentary understanding of statistics can help students interpret research data more effectively.'),
  ('word', 'high_2', 25, 'sagacious', '현명한', '영리한', NULL, 'The sagacious old man offered invaluable advice based on his many years of life experience.'),
  ('word', 'high_2', 25, 'sanctimonious', '독선적인', '위선적인', NULL, 'He delivered a sanctimonious lecture on morality, despite his own questionable past actions.'),
  ('word', 'high_2', 25, 'scrutinize', '세심히 살피다', '면밀히 조사하다', NULL, 'The detective had to scrutinize every detail of the crime scene for clues.'),
  ('word', 'high_2', 25, 'secular', '세속적인', '비종교적인', NULL, 'Many modern democracies maintain a secular government that separates religion from state affairs.'),
  ('word', 'high_2', 25, 'serendipity', '뜻밖의 행운', '우연히 발견하는 능력', NULL, 'Finding an old forgotten treasure map in the attic was a moment of pure serendipity.'),
  ('word', 'high_2', 25, 'serene', '고요한', '평화로운', NULL, 'The serene lake perfectly reflected the clear blue sky, creating a breathtaking view.'),
  ('word', 'high_2', 25, 'skeptical', '회의적인', '의심 많은', NULL, 'Many scientists remain skeptical about the new theory until more evidence is provided.'),
  ('word', 'high_2', 25, 'sovereignty', '주권', '통치권', NULL, 'The small nation fought to maintain its sovereignty against the influence of neighboring superpowers.'),
  ('word', 'high_2', 25, 'speculate', '추측하다', '사색하다', NULL, 'Scientists continue to speculate about the origins of the universe based on new discoveries.'),
  ('word', 'high_2', 25, 'stimulus', '자극', '촉진제', NULL, 'The government introduced a large economic stimulus package to boost recovery after the recession.'),
  ('word', 'high_2', 25, 'stipulate', '규정하다', '조건으로 내세우다', NULL, 'The contract clearly stipulates that all work must be completed within six months of signing.'),
  ('word', 'high_2', 25, 'stratify', '계층화하다', '층으로 나누다', NULL, 'Economic inequality tends to stratify society into distinct classes with limited social mobility.');