-- high_1 예문 UPDATE (고1 수준, 10th grade)
-- 문장 길이: 10-15 단어

-- Batch 1: abandonment ~ citation
UPDATE words SET example_sentence = 'The abandonment of the old factory left the entire neighborhood feeling empty.' WHERE word = 'abandonment' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students often abbreviate long technical terms to save time when taking notes.' WHERE word = 'abbreviate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The abbreviation for the United Nations is commonly written as UN.' WHERE word = 'abbreviation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The abrupt change in weather forced everyone to cancel their outdoor plans.' WHERE word = 'abrupt' AND level = 'high_1';
UPDATE words SET example_sentence = 'The absorption of water by plant roots is essential for their survival.' WHERE word = 'absorption' AND level = 'high_1';
UPDATE words SET example_sentence = 'The acceleration of the car was measured carefully during the physics experiment.' WHERE word = 'acceleration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The new library was designed to be accessible to people with disabilities.' WHERE word = 'accessible' AND level = 'high_1';
UPDATE words SET example_sentence = 'She bought a matching accessory to complete her outfit for the ceremony.' WHERE word = 'accessory' AND level = 'high_1';
UPDATE words SET example_sentence = 'The hotel was able to accommodate all the guests who arrived unexpectedly.' WHERE word = 'accommodate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Winning the science competition was her greatest accomplishment of the entire year.' WHERE word = 'accomplishment' AND level = 'high_1';
UPDATE words SET example_sentence = 'The project was carried out in accordance with the safety regulations.' WHERE word = 'accordance' AND level = 'high_1';
UPDATE words SET example_sentence = 'The test was postponed, and accordingly the students had more time to prepare.' WHERE word = 'accordingly' AND level = 'high_1';
UPDATE words SET example_sentence = 'Every team member should be accountable for the tasks they are assigned.' WHERE word = 'accountable' AND level = 'high_1';
UPDATE words SET example_sentence = 'If you accumulate enough points, you will be able to earn a reward.' WHERE word = 'accumulate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The accumulation of plastic waste in the ocean threatens many marine species.' WHERE word = 'accumulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The acquisition of new skills is important for success in the modern world.' WHERE word = 'acquisition' AND level = 'high_1';
UPDATE words SET example_sentence = 'You need to press the green button to activate the emergency alarm system.' WHERE word = 'activate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The activation of the volcano was detected by scientists using advanced sensors.' WHERE word = 'activation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Phone addiction among teenagers has become a serious concern for many parents today.' WHERE word = 'addiction' AND level = 'high_1';
UPDATE words SET example_sentence = 'A small adjustment to the schedule allowed everyone to attend the meeting.' WHERE word = 'adjustment' AND level = 'high_1';
UPDATE words SET example_sentence = 'Nurses were trained to administer medicine to patients in the correct dosage.' WHERE word = 'administer' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school administrator announced that the festival would be held next Friday.' WHERE word = 'administrator' AND level = 'high_1';
UPDATE words SET example_sentence = 'She expressed her admiration for the artist whose paintings inspired her deeply.' WHERE word = 'admiration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The adoption of renewable energy sources has increased significantly in recent years.' WHERE word = 'adoption' AND level = 'high_1';
UPDATE words SET example_sentence = 'The adverse effects of air pollution on human health are well documented.' WHERE word = 'adverse' AND level = 'high_1';
UPDATE words SET example_sentence = 'She overcame great adversity to become the first in her family to graduate.' WHERE word = 'adversity' AND level = 'high_1';
UPDATE words SET example_sentence = 'The academic advisor helped students choose the right courses for their future careers.' WHERE word = 'advisor' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government issued an advisory warning residents about the approaching tropical storm.' WHERE word = 'advisory' AND level = 'high_1';
UPDATE words SET example_sentence = 'Many scientists advocate for stronger laws to protect endangered wildlife around the world.' WHERE word = 'advocate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The aesthetic design of the building attracted visitors from many different countries.' WHERE word = 'aesthetic' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her affiliation with the research group gave her access to valuable laboratory equipment.' WHERE word = 'affiliation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The committee gave an affirmative response to the proposal for a new park.' WHERE word = 'affirmative' AND level = 'high_1';
UPDATE words SET example_sentence = 'The aggregate score of all three tests will determine your final grade.' WHERE word = 'aggregate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Aggression in animals is often triggered by fear or the need to survive.' WHERE word = 'aggression' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students who study algebra learn how to solve equations using unknown variables.' WHERE word = 'algebra' AND level = 'high_1';
UPDATE words SET example_sentence = 'The allegation against the company was investigated thoroughly by the local authorities.' WHERE word = 'allegation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The alliance between the two countries was formed to promote peace and trade.' WHERE word = 'alliance' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government decided to allocate more funding to public schools this year.' WHERE word = 'allocate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The allocation of resources was discussed during the annual budget planning meeting.' WHERE word = 'allocation' AND level = 'high_1';
UPDATE words SET example_sentence = 'A new shopping center was built alongside the river that runs through town.' WHERE word = 'alongside' AND level = 'high_1';
UPDATE words SET example_sentence = 'The alteration of the original plan was necessary due to unexpected weather conditions.' WHERE word = 'alteration' AND level = 'high_1';
UPDATE words SET example_sentence = 'Aluminum is a lightweight metal that is commonly used in packaging and construction.' WHERE word = 'aluminum' AND level = 'high_1';
UPDATE words SET example_sentence = 'The amateur photographer was surprised when her picture won the national contest.' WHERE word = 'amateur' AND level = 'high_1';
UPDATE words SET example_sentence = 'The ambassador represented her country at the international conference held in Geneva.' WHERE word = 'ambassador' AND level = 'high_1';
UPDATE words SET example_sentence = 'The ambiguity of the instructions confused many students who took the exam.' WHERE word = 'ambiguity' AND level = 'high_1';
UPDATE words SET example_sentence = 'The meaning of the poem was ambiguous, so readers interpreted it differently.' WHERE word = 'ambiguous' AND level = 'high_1';
UPDATE words SET example_sentence = 'An amendment to the law was proposed to better protect consumer rights.' WHERE word = 'amendment' AND level = 'high_1';
UPDATE words SET example_sentence = 'The teacher used an analogy comparing the brain to a powerful computer.' WHERE word = 'analogy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The financial analyst predicted that the economy would recover by next summer.' WHERE word = 'analyst' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her analytical thinking helped her solve the complex math problem very quickly.' WHERE word = 'analytical' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists need to analyze the data carefully before drawing any final conclusions.' WHERE word = 'analyze' AND level = 'high_1';
UPDATE words SET example_sentence = 'The speaker shared a personal anecdote that made the audience laugh out loud.' WHERE word = 'anecdote' AND level = 'high_1';
UPDATE words SET example_sentence = 'Researchers discovered an anomaly in the data that could not be easily explained.' WHERE word = 'anomaly' AND level = 'high_1';
UPDATE words SET example_sentence = 'Anthropology is the study of human cultures and societies throughout history.' WHERE word = 'anthropology' AND level = 'high_1';
UPDATE words SET example_sentence = 'The laboratory apparatus was set up carefully before the chemistry experiment began.' WHERE word = 'apparatus' AND level = 'high_1';
UPDATE words SET example_sentence = 'After hiking for several hours, she had built up a strong appetite.' WHERE word = 'appetite' AND level = 'high_1';
UPDATE words SET example_sentence = 'This discount is only applicable to items that were purchased before December.' WHERE word = 'applicable' AND level = 'high_1';
UPDATE words SET example_sentence = 'He expressed his deep appreciation for the help he received from his neighbors.' WHERE word = 'appreciation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The young apprentice learned traditional woodworking skills from an experienced master craftsman.' WHERE word = 'apprentice' AND level = 'high_1';
UPDATE words SET example_sentence = 'Archaeology allows us to understand how ancient civilizations lived thousands of years ago.' WHERE word = 'archaeology' AND level = 'high_1';
UPDATE words SET example_sentence = 'Basic arithmetic skills like addition and multiplication are used in everyday life.' WHERE word = 'arithmetic' AND level = 'high_1';
UPDATE words SET example_sentence = 'She was able to articulate her ideas clearly during the class presentation.' WHERE word = 'articulate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The clear articulation of goals helped the team work together more effectively.' WHERE word = 'articulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The students were asked to assemble in the gym for the school ceremony.' WHERE word = 'assemble' AND level = 'high_1';
UPDATE words SET example_sentence = 'Teachers assess student performance through a combination of tests and group projects.' WHERE word = 'assess' AND level = 'high_1';
UPDATE words SET example_sentence = 'The assessment revealed that most students had improved their reading skills significantly.' WHERE word = 'assessment' AND level = 'high_1';
UPDATE words SET example_sentence = 'The teacher will assign each student a different topic for the research paper.' WHERE word = 'assign' AND level = 'high_1';
UPDATE words SET example_sentence = 'The assumption that all teenagers are lazy is simply not supported by evidence.' WHERE word = 'assumption' AND level = 'high_1';
UPDATE words SET example_sentence = 'The astronaut described what it felt like to see Earth from outer space.' WHERE word = 'astronaut' AND level = 'high_1';
UPDATE words SET example_sentence = 'Astronomy is the branch of science that studies stars, planets, and galaxies.' WHERE word = 'astronomy' AND level = 'high_1';
UPDATE words SET example_sentence = 'Please send the file as an email attachment so that everyone can review it.' WHERE word = 'attachment' AND level = 'high_1';
UPDATE words SET example_sentence = 'With hard work and determination, she was able to attain her academic goals.' WHERE word = 'attain' AND level = 'high_1';
UPDATE words SET example_sentence = 'Regular attendance in class is strongly connected to better performance on exams.' WHERE word = 'attendance' AND level = 'high_1';
UPDATE words SET example_sentence = 'The attorney presented strong evidence that convinced the jury of her argument.' WHERE word = 'attorney' AND level = 'high_1';
UPDATE words SET example_sentence = 'Auditory learners tend to remember information better when it is spoken aloud.' WHERE word = 'auditory' AND level = 'high_1';
UPDATE words SET example_sentence = 'Automation in factories has replaced many jobs that were once done by hand.' WHERE word = 'automation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The region gained autonomy, which allowed its people to govern themselves independently.' WHERE word = 'autonomy' AND level = 'high_1';
UPDATE words SET example_sentence = 'They explored every avenue of research before reaching their final conclusion on the topic.' WHERE word = 'avenue' AND level = 'high_1';
UPDATE words SET example_sentence = 'A single bacterium can multiply into millions within just a few short hours.' WHERE word = 'bacterium' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company filed for bankruptcy after failing to pay its enormous debts.' WHERE word = 'bankruptcy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The lawyer spoke on behalf of the family who could not attend the hearing.' WHERE word = 'behalf' AND level = 'high_1';
UPDATE words SET example_sentence = 'The beneficiary of the scholarship was a talented student from a rural village.' WHERE word = 'beneficiary' AND level = 'high_1';
UPDATE words SET example_sentence = 'The benevolent donor gave a large sum of money to the local hospital.' WHERE word = 'benevolent' AND level = 'high_1';
UPDATE words SET example_sentence = 'The architect created a detailed blueprint before construction of the building could begin.' WHERE word = 'blueprint' AND level = 'high_1';
UPDATE words SET example_sentence = 'His test score was borderline, so the teacher gave him a chance to retake it.' WHERE word = 'borderline' AND level = 'high_1';
UPDATE words SET example_sentence = 'The travel agency handed out a colorful brochure describing popular tourist destinations abroad.' WHERE word = 'brochure' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school posted a bulletin on the board announcing the upcoming science fair.' WHERE word = 'bulletin' AND level = 'high_1';
UPDATE words SET example_sentence = 'The bureaucracy involved in getting a passport can be slow and very frustrating.' WHERE word = 'bureaucracy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The successful businessman donated part of his profits to help fund local schools.' WHERE word = 'businessman' AND level = 'high_1';
UPDATE words SET example_sentence = 'Pollution is an unfortunate byproduct of rapid industrial growth in many developing countries.' WHERE word = 'byproduct' AND level = 'high_1';
UPDATE words SET example_sentence = 'The capability of modern computers to process data has increased dramatically over time.' WHERE word = 'capability' AND level = 'high_1';
UPDATE words SET example_sentence = 'Capitalism is an economic system in which private individuals own the means of production.' WHERE word = 'capitalism' AND level = 'high_1';
UPDATE words SET example_sentence = 'The discovery of penicillin served as a catalyst for advances in modern medicine.' WHERE word = 'catalyst' AND level = 'high_1';
UPDATE words SET example_sentence = 'The earthquake was a catastrophe that destroyed thousands of homes across the region.' WHERE word = 'catastrophe' AND level = 'high_1';
UPDATE words SET example_sentence = 'The orchestra performed beautifully in the grand chamber of the historic concert hall.' WHERE word = 'chamber' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists characterize this species by its bright colors and unusual feeding behavior.' WHERE word = 'characterize' AND level = 'high_1';
UPDATE words SET example_sentence = 'The charity organization raised enough money to build a school in the village.' WHERE word = 'charity' AND level = 'high_1';
UPDATE words SET example_sentence = 'Chemistry helps us understand how different substances interact and form new compounds.' WHERE word = 'chemistry' AND level = 'high_1';
UPDATE words SET example_sentence = 'Under no circumstance should students leave the building during an emergency drill alone.' WHERE word = 'circumstance' AND level = 'high_1';
UPDATE words SET example_sentence = 'Every research paper must include a proper citation for each source that is used.' WHERE word = 'citation' AND level = 'high_1';

-- Batch 2: civilian ~ dominant
UPDATE words SET example_sentence = 'The civilian population was evacuated before the military operation began nearby.' WHERE word = 'civilian' AND level = 'high_1';
UPDATE words SET example_sentence = 'The professor provided further clarification on the theory during office hours.' WHERE word = 'clarification' AND level = 'high_1';
UPDATE words SET example_sentence = 'The classification of animals into different groups is based on shared traits.' WHERE word = 'classification' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists classify living organisms according to their physical and genetic characteristics.' WHERE word = 'classify' AND level = 'high_1';
UPDATE words SET example_sentence = 'The contract included a clause that protected both parties from unexpected losses.' WHERE word = 'clause' AND level = 'high_1';
UPDATE words SET example_sentence = 'The lawyer met with her client to discuss the details of the case.' WHERE word = 'client' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students from different countries will collaborate on the environmental research project together.' WHERE word = 'collaborate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The collaboration between the two universities produced a groundbreaking scientific discovery.' WHERE word = 'collaboration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The collective effort of the entire team led to their championship victory.' WHERE word = 'collective' AND level = 'high_1';
UPDATE words SET example_sentence = 'The columnist wrote an article criticizing the government policy on education reform.' WHERE word = 'columnist' AND level = 'high_1';
UPDATE words SET example_sentence = 'The ceremony will commence at noon once all the invited guests have arrived.' WHERE word = 'commence' AND level = 'high_1';
UPDATE words SET example_sentence = 'The commencement speech was delivered by a famous scientist who inspired the graduates.' WHERE word = 'commencement' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government appointed a commission to investigate the cause of the disaster.' WHERE word = 'commission' AND level = 'high_1';
UPDATE words SET example_sentence = 'The committee reviewed all the applications and selected the most qualified candidates.' WHERE word = 'committee' AND level = 'high_1';
UPDATE words SET example_sentence = 'Oil is a valuable commodity that affects the global economy in significant ways.' WHERE word = 'commodity' AND level = 'high_1';
UPDATE words SET example_sentence = 'The quality of this product is comparable to that of more expensive brands.' WHERE word = 'comparable' AND level = 'high_1';
UPDATE words SET example_sentence = 'This software is compatible with both Windows and Mac operating systems today.' WHERE word = 'compatible' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company agreed to compensate the workers who were injured during the accident.' WHERE word = 'compensate' AND level = 'high_1';
UPDATE words SET example_sentence = 'She received fair compensation for the extra hours she had worked last month.' WHERE word = 'compensation' AND level = 'high_1';
UPDATE words SET example_sentence = 'His competence in mathematics was recognized when he won the national competition award.' WHERE word = 'competence' AND level = 'high_1';
UPDATE words SET example_sentence = 'The competitive market forces companies to improve their products and lower prices.' WHERE word = 'competitive' AND level = 'high_1';
UPDATE words SET example_sentence = 'Regular exercise can complement a healthy diet and improve your overall well-being significantly.' WHERE word = 'complement' AND level = 'high_1';
UPDATE words SET example_sentence = 'A serious complication arose during surgery, which required the doctors to change plans.' WHERE word = 'complication' AND level = 'high_1';
UPDATE words SET example_sentence = 'Each component of the machine must be tested before the final assembly begins.' WHERE word = 'component' AND level = 'high_1';
UPDATE words SET example_sentence = 'Water is a compound made up of hydrogen and oxygen atoms bonded together.' WHERE word = 'compound' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students who comprehend the basic concepts will find advanced topics much easier to learn.' WHERE word = 'comprehend' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school offers a comprehensive program that covers academics, sports, and the arts.' WHERE word = 'comprehensive' AND level = 'high_1';
UPDATE words SET example_sentence = 'Modern computers can compute millions of calculations in just a single second easily.' WHERE word = 'compute' AND level = 'high_1';
UPDATE words SET example_sentence = 'Deep concentration is required when solving complex mathematical problems under time pressure.' WHERE word = 'concentration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The conception of the project began when researchers identified a gap in knowledge.' WHERE word = 'conception' AND level = 'high_1';
UPDATE words SET example_sentence = 'The architect presented a concrete plan that included detailed drawings and cost estimates.' WHERE word = 'concrete' AND level = 'high_1';
UPDATE words SET example_sentence = 'Experts from around the world gathered at the conference to discuss climate change.' WHERE word = 'conference' AND level = 'high_1';
UPDATE words SET example_sentence = 'The configuration of the network was adjusted to improve speed and overall security.' WHERE word = 'configuration' AND level = 'high_1';
UPDATE words SET example_sentence = 'We are waiting for confirmation of the flight schedule before booking the hotel.' WHERE word = 'confirmation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The confrontation between the two leaders was broadcast live on national television networks.' WHERE word = 'confrontation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Traffic congestion in the city center has become worse due to ongoing construction.' WHERE word = 'congestion' AND level = 'high_1';
UPDATE words SET example_sentence = 'After the accident, he slowly regained consciousness and was able to recognize his family.' WHERE word = 'consciousness' AND level = 'high_1';
UPDATE words SET example_sentence = 'The patient gave written consent before the medical procedure was performed by the doctor.' WHERE word = 'consent' AND level = 'high_1';
UPDATE words SET example_sentence = 'After careful consideration, the board decided to approve the new development project proposal.' WHERE word = 'consideration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The research team will consist of scientists, engineers, and data analysts working together.' WHERE word = 'consist' AND level = 'high_1';
UPDATE words SET example_sentence = 'Women constitute nearly half of the workforce in many developed countries around the world.' WHERE word = 'constitute' AND level = 'high_1';
UPDATE words SET example_sentence = 'The constitution guarantees the basic rights and freedoms of every citizen in the nation.' WHERE word = 'constitution' AND level = 'high_1';
UPDATE words SET example_sentence = 'You should consult a professional before making any major financial decisions on your own.' WHERE word = 'consult' AND level = 'high_1';
UPDATE words SET example_sentence = 'The consumer has the right to return defective products within thirty days of purchase.' WHERE word = 'consumer' AND level = 'high_1';
UPDATE words SET example_sentence = 'Contemporary artists often use technology to create works that challenge traditional artistic boundaries.' WHERE word = 'contemporary' AND level = 'high_1';
UPDATE words SET example_sentence = 'The controversy surrounding the new law has divided public opinion across the entire country.' WHERE word = 'controversy' AND level = 'high_1';
UPDATE words SET example_sentence = 'Online shopping offers the convenience of purchasing items from home at any time.' WHERE word = 'convenience' AND level = 'high_1';
UPDATE words SET example_sentence = 'Conventional methods of farming are being replaced by more sustainable and modern techniques.' WHERE word = 'conventional' AND level = 'high_1';
UPDATE words SET example_sentence = 'She tried to converse with the foreign visitor using the English she had learned.' WHERE word = 'converse' AND level = 'high_1';
UPDATE words SET example_sentence = 'The conversion of the old factory into a museum attracted many tourists to the area.' WHERE word = 'conversion' AND level = 'high_1';
UPDATE words SET example_sentence = 'Art can convey powerful emotions that words alone may not be able to express.' WHERE word = 'convey' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her strong conviction that education changes lives motivated her to become a dedicated teacher.' WHERE word = 'conviction' AND level = 'high_1';
UPDATE words SET example_sentence = 'Effective coordination among team members is essential for completing the project on time.' WHERE word = 'coordination' AND level = 'high_1';
UPDATE words SET example_sentence = 'The corporate headquarters were relocated to a larger building in the downtown district.' WHERE word = 'corporate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Researchers found a strong correlation between regular exercise and improved mental health outcomes.' WHERE word = 'correlation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The results of the experiment did not correspond to what the scientists had predicted.' WHERE word = 'correspond' AND level = 'high_1';
UPDATE words SET example_sentence = 'The city council approved a new budget to improve public transportation and local parks.' WHERE word = 'council' AND level = 'high_1';
UPDATE words SET example_sentence = 'The value of the national currency dropped sharply due to the ongoing economic crisis.' WHERE word = 'currency' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school revised its curriculum to include more courses on technology and digital literacy.' WHERE word = 'curriculum' AND level = 'high_1';
UPDATE words SET example_sentence = 'All student records are stored in a secure database that is updated every semester.' WHERE word = 'database' AND level = 'high_1';
UPDATE words SET example_sentence = 'The decisive moment came when the captain scored the winning goal in extra time.' WHERE word = 'decisive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The decorative patterns on the ancient pottery revealed much about the culture of that era.' WHERE word = 'decorative' AND level = 'high_1';
UPDATE words SET example_sentence = 'She decided to dedicate her career to helping children who lack access to education.' WHERE word = 'dedicate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company will deduct taxes from your salary before depositing it into your account.' WHERE word = 'deduct' AND level = 'high_1';
UPDATE words SET example_sentence = 'Through logical deduction, the detective was able to identify the suspect in the case.' WHERE word = 'deduction' AND level = 'high_1';
UPDATE words SET example_sentence = 'A deficiency in vitamin D can lead to serious bone problems over time.' WHERE word = 'deficiency' AND level = 'high_1';
UPDATE words SET example_sentence = 'There is no definite answer to the question, which makes the debate more interesting.' WHERE word = 'definite' AND level = 'high_1';
UPDATE words SET example_sentence = 'The committee made a deliberate decision after reviewing all the evidence that was presented.' WHERE word = 'deliberate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Democracy allows citizens to participate in the political process by voting in free elections.' WHERE word = 'democracy' AND level = 'high_1';
UPDATE words SET example_sentence = 'Demographic data shows that the population of the city has been growing rapidly since 2010.' WHERE word = 'demographic' AND level = 'high_1';
UPDATE words SET example_sentence = 'The train will depart from platform three at exactly nine in the morning.' WHERE word = 'depart' AND level = 'high_1';
UPDATE words SET example_sentence = 'The success of the project is dependent on the cooperation of all team members.' WHERE word = 'dependent' AND level = 'high_1';
UPDATE words SET example_sentence = 'The military planned to deploy additional troops to the region affected by the conflict.' WHERE word = 'deploy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The deployment of new technology in schools has greatly improved the quality of learning.' WHERE word = 'deployment' AND level = 'high_1';
UPDATE words SET example_sentence = 'The president will designate a special envoy to lead the peace negotiations this week.' WHERE word = 'designate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her designation as team leader was announced at the beginning of the staff meeting.' WHERE word = 'designation' AND level = 'high_1';
UPDATE words SET example_sentence = 'If the building is not maintained properly, its condition will deteriorate over the years.' WHERE word = 'deteriorate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her determination to succeed despite many obstacles inspired everyone around her to work harder.' WHERE word = 'determination' AND level = 'high_1';
UPDATE words SET example_sentence = 'If you deviate from the original plan, the entire project schedule could be affected.' WHERE word = 'deviate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The doctor confirmed the diagnosis after running several tests on the patient last week.' WHERE word = 'diagnosis' AND level = 'high_1';
UPDATE words SET example_sentence = 'She faced a dilemma when choosing between studying abroad and staying close to her family.' WHERE word = 'dilemma' AND level = 'high_1';
UPDATE words SET example_sentence = 'The influence of traditional media has started to diminish as social media continues growing.' WHERE word = 'diminish' AND level = 'high_1';
UPDATE words SET example_sentence = 'Diplomacy is often considered the most effective way to resolve international conflicts peacefully today.' WHERE word = 'diplomacy' AND level = 'high_1';
UPDATE words SET example_sentence = 'People with a disability should be given equal opportunities in education and employment settings.' WHERE word = 'disability' AND level = 'high_1';
UPDATE words SET example_sentence = 'The virus can disable a computer system by corrupting essential files stored on the drive.' WHERE word = 'disable' AND level = 'high_1';
UPDATE words SET example_sentence = 'The journalist refused to disclose the identity of the source who provided the information.' WHERE word = 'disclose' AND level = 'high_1';
UPDATE words SET example_sentence = 'The disclosure of secret government documents caused a major political scandal across the nation.' WHERE word = 'disclosure' AND level = 'high_1';
UPDATE words SET example_sentence = 'Discrimination based on race or gender is prohibited by law in most modern democracies.' WHERE word = 'discrimination' AND level = 'high_1';
UPDATE words SET example_sentence = 'The manager decided to dismiss the employee who had repeatedly violated company regulations.' WHERE word = 'dismiss' AND level = 'high_1';
UPDATE words SET example_sentence = 'The sudden dismissal of the popular coach shocked both the players and the fans.' WHERE word = 'dismissal' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her cheerful disposition made her popular among classmates, who always enjoyed her positive energy.' WHERE word = 'disposition' AND level = 'high_1';
UPDATE words SET example_sentence = 'The dispute between the two countries over the border has lasted for several decades.' WHERE word = 'dispute' AND level = 'high_1';
UPDATE words SET example_sentence = 'The disruption caused by the storm forced many schools to cancel classes for days.' WHERE word = 'disruption' AND level = 'high_1';
UPDATE words SET example_sentence = 'There is a clear distinction between knowing a language and being able to use it.' WHERE word = 'distinction' AND level = 'high_1';
UPDATE words SET example_sentence = 'It is important to distinguish between facts and opinions when reading news articles online.' WHERE word = 'distinguish' AND level = 'high_1';
UPDATE words SET example_sentence = 'The organization will distribute food and clean water to families affected by the flood.' WHERE word = 'distribute' AND level = 'high_1';
UPDATE words SET example_sentence = 'Loud construction noise outside the building continued to disturb the students during their exam.' WHERE word = 'disturb' AND level = 'high_1';
UPDATE words SET example_sentence = 'The dominance of technology in daily life has changed how people communicate with each other.' WHERE word = 'dominance' AND level = 'high_1';
UPDATE words SET example_sentence = 'English has become the dominant language used in international business and academic research worldwide.' WHERE word = 'dominant' AND level = 'high_1';

-- Batch 3: ecology ~ intervention
UPDATE words SET example_sentence = 'The study of ecology helps us understand how organisms interact with their environment.' WHERE word = 'ecology' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students who study economics learn how markets and governments influence each other.' WHERE word = 'economics' AND level = 'high_1';
UPDATE words SET example_sentence = 'The editorial published in the newspaper criticized the new education policy strongly.' WHERE word = 'editorial' AND level = 'high_1';
UPDATE words SET example_sentence = 'The election results were announced after all the votes had been counted.' WHERE word = 'election' AND level = 'high_1';
UPDATE words SET example_sentence = 'The emergence of new technology has transformed the way people communicate globally.' WHERE word = 'emergence' AND level = 'high_1';
UPDATE words SET example_sentence = 'The researchers collected empirical data to support their hypothesis about climate change.' WHERE word = 'empirical' AND level = 'high_1';
UPDATE words SET example_sentence = 'Education can empower young people to make informed decisions about their future.' WHERE word = 'empower' AND level = 'high_1';
UPDATE words SET example_sentence = 'Strict enforcement of traffic laws has reduced the number of accidents significantly.' WHERE word = 'enforcement' AND level = 'high_1';
UPDATE words SET example_sentence = 'The enormousness of the ancient castle amazed every visitor who walked through it.' WHERE word = 'enormousness' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students must enroll in the course before the registration deadline next Friday.' WHERE word = 'enroll' AND level = 'high_1';
UPDATE words SET example_sentence = 'The enterprise was founded by two engineers who shared a vision.' WHERE word = 'enterprise' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her enthusiasm for learning science inspired other students in the classroom.' WHERE word = 'enthusiasm' AND level = 'high_1';
UPDATE words SET example_sentence = 'The principle of equality means that everyone should be treated fairly and justly.' WHERE word = 'equality' AND level = 'high_1';
UPDATE words SET example_sentence = 'The ecosystem maintained its equilibrium until pollution disrupted the balance of nature.' WHERE word = 'equilibrium' AND level = 'high_1';
UPDATE words SET example_sentence = 'One kilometer is equivalent to approximately zero point six two miles.' WHERE word = 'equivalent' AND level = 'high_1';
UPDATE words SET example_sentence = 'Tensions between the two nations continued to escalate despite diplomatic efforts.' WHERE word = 'escalate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists must follow ethical guidelines when conducting experiments on human subjects.' WHERE word = 'ethical' AND level = 'high_1';
UPDATE words SET example_sentence = 'The eventual success of the project was the result of teamwork.' WHERE word = 'eventual' AND level = 'high_1';
UPDATE words SET example_sentence = 'If expenses exceed the budget, the school will need to cut programs.' WHERE word = 'exceed' AND level = 'high_1';
UPDATE words SET example_sentence = 'All students passed the exam with the exception of those who were absent.' WHERE word = 'exception' AND level = 'high_1';
UPDATE words SET example_sentence = 'Excessive use of smartphones can negatively affect concentration and sleep quality among teenagers.' WHERE word = 'excessive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The exclusion of certain groups from the program raised concerns about fairness.' WHERE word = 'exclusion' AND level = 'high_1';
UPDATE words SET example_sentence = 'The hotel offers exclusive access to a private beach for its guests.' WHERE word = 'exclusive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The executive made a bold decision that changed the direction of the company.' WHERE word = 'executive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The art exhibition attracted thousands of visitors from around the world last summer.' WHERE word = 'exhibition' AND level = 'high_1';
UPDATE words SET example_sentence = 'The rapid expansion of the city led to increased demand for public transportation.' WHERE word = 'expansion' AND level = 'high_1';
UPDATE words SET example_sentence = 'The experimental treatment showed promising results in the early stages of testing.' WHERE word = 'experimental' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her expertise in computer science helped the team solve a difficult problem.' WHERE word = 'expertise' AND level = 'high_1';
UPDATE words SET example_sentence = 'The teacher gave explicit instructions so that every student understood the assignment clearly.' WHERE word = 'explicit' AND level = 'high_1';
UPDATE words SET example_sentence = 'Companies should not exploit workers by forcing them to work in unsafe conditions.' WHERE word = 'exploit' AND level = 'high_1';
UPDATE words SET example_sentence = 'The exploitation of natural resources without planning leads to environmental destruction over time.' WHERE word = 'exploitation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Prolonged exposure to sunlight without protection can cause serious damage to the skin.' WHERE word = 'exposure' AND level = 'high_1';
UPDATE words SET example_sentence = 'Technology can facilitate communication between people who speak different languages around the world.' WHERE word = 'facilitate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The university faculty voted to approve the new curriculum for incoming students.' WHERE word = 'faculty' AND level = 'high_1';
UPDATE words SET example_sentence = 'The faithful dog waited at the door every day until its owner returned.' WHERE word = 'faithful' AND level = 'high_1';
UPDATE words SET example_sentence = 'The feasibility of the project was evaluated before any funding was approved.' WHERE word = 'feasibility' AND level = 'high_1';
UPDATE words SET example_sentence = 'Building a bridge across the wide river is feasible with modern engineering technology.' WHERE word = 'feasible' AND level = 'high_1';
UPDATE words SET example_sentence = 'The federation of student councils organized a national conference on education reform.' WHERE word = 'federation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The committee will finalize the schedule after reviewing all the proposals next week.' WHERE word = 'finalize' AND level = 'high_1';
UPDATE words SET example_sentence = 'A flexible schedule allows students to balance their studies with extracurricular activities effectively.' WHERE word = 'flexible' AND level = 'high_1';
UPDATE words SET example_sentence = 'Small businesses can flourish when they receive proper support from the local community.' WHERE word = 'flourish' AND level = 'high_1';
UPDATE words SET example_sentence = 'Oil prices tend to fluctuate depending on global supply and demand conditions.' WHERE word = 'fluctuate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The fluctuation in temperature made it difficult to decide what clothes to wear.' WHERE word = 'fluctuation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists need to formulate a hypothesis before they begin conducting any experiments.' WHERE word = 'formulate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The formulation of a clear plan is essential for achieving long-term goals.' WHERE word = 'formulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Only a small fraction of applicants were accepted into the competitive program this year.' WHERE word = 'fraction' AND level = 'high_1';
UPDATE words SET example_sentence = 'The legal framework provides guidelines that protect the rights of all citizens.' WHERE word = 'framework' AND level = 'high_1';
UPDATE words SET example_sentence = 'Repeated failures can frustrate even the most determined students trying to improve.' WHERE word = 'frustrate' AND level = 'high_1';
UPDATE words SET example_sentence = 'She felt frustrated because the instructions were unclear and nobody could help her.' WHERE word = 'frustrated' AND level = 'high_1';
UPDATE words SET example_sentence = 'The building is old but still functional, serving as a community center today.' WHERE word = 'functional' AND level = 'high_1';
UPDATE words SET example_sentence = 'The researchers decided to further investigate the unexpected results they had discovered.' WHERE word = 'further' AND level = 'high_1';
UPDATE words SET example_sentence = 'The plan was well-organized; furthermore, it addressed all the concerns raised by parents.' WHERE word = 'furthermore' AND level = 'high_1';
UPDATE words SET example_sentence = 'It would be wrong to generalize about an entire culture based on one experience.' WHERE word = 'generalize' AND level = 'high_1';
UPDATE words SET example_sentence = 'The emergency generator provided electricity to the hospital when the power went out.' WHERE word = 'generator' AND level = 'high_1';
UPDATE words SET example_sentence = 'Advances in genetics have made it possible to identify diseases before symptoms appear.' WHERE word = 'genetics' AND level = 'high_1';
UPDATE words SET example_sentence = 'After graduation, many students plan to travel before starting their professional careers.' WHERE word = 'graduation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The graphic display of data made the research findings much easier to understand.' WHERE word = 'graphic' AND level = 'high_1';
UPDATE words SET example_sentence = 'The presentation included detailed graphics that illustrated the effects of climate change clearly.' WHERE word = 'graphics' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students who receive proper guidance from teachers tend to perform better in school.' WHERE word = 'guidance' AND level = 'high_1';
UPDATE words SET example_sentence = 'The natural habitat of polar bears is threatened by rising global temperatures.' WHERE word = 'habitat' AND level = 'high_1';
UPDATE words SET example_sentence = 'Living in harmony with nature requires conscious effort from individuals and communities alike.' WHERE word = 'harmony' AND level = 'high_1';
UPDATE words SET example_sentence = 'The ancient temple is considered a cultural heritage that must be preserved carefully.' WHERE word = 'heritage' AND level = 'high_1';
UPDATE words SET example_sentence = 'Understanding the hierarchy of needs helps explain what motivates human behavior and decisions.' WHERE word = 'hierarchy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The historic agreement between the two countries brought an end to decades of conflict.' WHERE word = 'historic' AND level = 'high_1';
UPDATE words SET example_sentence = 'The hostile environment made it nearly impossible for the explorers to continue forward.' WHERE word = 'hostile' AND level = 'high_1';
UPDATE words SET example_sentence = 'Protecting the environment is a responsibility shared by all of humanity today.' WHERE word = 'humanity' AND level = 'high_1';
UPDATE words SET example_sentence = 'Despite his great achievements, the scientist remained humble and kind to everyone around.' WHERE word = 'humble' AND level = 'high_1';
UPDATE words SET example_sentence = 'The two paintings looked identical, but experts found subtle differences between them.' WHERE word = 'identical' AND level = 'high_1';
UPDATE words SET example_sentence = 'Political ideology can influence how people interpret the same event very differently.' WHERE word = 'ideology' AND level = 'high_1';
UPDATE words SET example_sentence = 'The illustration in the textbook helped students visualize the structure of a cell.' WHERE word = 'illustration' AND level = 'high_1';
UPDATE words SET example_sentence = 'As an immigrant, she faced many challenges while adapting to a new culture.' WHERE word = 'immigrant' AND level = 'high_1';
UPDATE words SET example_sentence = 'Immigration policies have been debated widely because they affect millions of families worldwide.' WHERE word = 'immigration' AND level = 'high_1';
UPDATE words SET example_sentence = 'The immune system protects the body from viruses and harmful bacteria every day.' WHERE word = 'immune' AND level = 'high_1';
UPDATE words SET example_sentence = 'The implementation of the new policy required cooperation from every department in the school.' WHERE word = 'implementation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The implication of the study is that sleep directly affects academic performance.' WHERE word = 'implication' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government decided to impose stricter regulations on factories that pollute the river.' WHERE word = 'impose' AND level = 'high_1';
UPDATE words SET example_sentence = 'The sunset over the ocean left a lasting impression on everyone who saw it.' WHERE word = 'impression' AND level = 'high_1';
UPDATE words SET example_sentence = 'The students delivered an impressive presentation that earned praise from all the judges.' WHERE word = 'impressive' AND level = 'high_1';
UPDATE words SET example_sentence = 'Financial incentive programs were introduced to encourage more students to study engineering.' WHERE word = 'incentive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company plans to incorporate feedback from customers into the next product design.' WHERE word = 'incorporate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The incorporation of new technology into classrooms has improved the learning experience significantly.' WHERE word = 'incorporation' AND level = 'high_1';
UPDATE words SET example_sentence = 'There was no indication that the weather would change so suddenly that afternoon.' WHERE word = 'indication' AND level = 'high_1';
UPDATE words SET example_sentence = 'Social inequality remains a serious issue that many countries are still trying to address.' WHERE word = 'inequality' AND level = 'high_1';
UPDATE words SET example_sentence = 'Change is inevitable, so it is better to prepare for it in advance.' WHERE word = 'inevitable' AND level = 'high_1';
UPDATE words SET example_sentence = 'The informal meeting allowed students to share their opinions in a relaxed setting.' WHERE word = 'informal' AND level = 'high_1';
UPDATE words SET example_sentence = 'Many rare species inhabit the rainforest, which must be protected from deforestation.' WHERE word = 'inhabit' AND level = 'high_1';
UPDATE words SET example_sentence = 'Children often inherit certain physical traits and abilities from their parents naturally.' WHERE word = 'inherit' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school decided to initiate a mentoring program to support struggling students.' WHERE word = 'initiate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Reading diverse books can provide valuable insight into different cultures and perspectives.' WHERE word = 'insight' AND level = 'high_1';
UPDATE words SET example_sentence = 'Officials were sent to inspect the factory to ensure safety standards were being met.' WHERE word = 'inspect' AND level = 'high_1';
UPDATE words SET example_sentence = 'The institution has been providing quality education to students for over fifty years.' WHERE word = 'institution' AND level = 'high_1';
UPDATE words SET example_sentence = 'The coach will instruct the players on new strategies before the tournament begins.' WHERE word = 'instruct' AND level = 'high_1';
UPDATE words SET example_sentence = 'The school aims to integrate technology into every subject to enhance student learning.' WHERE word = 'integrate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The integration of art and science creates opportunities for innovative problem solving.' WHERE word = 'integration' AND level = 'high_1';
UPDATE words SET example_sentence = 'A leader with integrity earns the trust and respect of the people around them.' WHERE word = 'integrity' AND level = 'high_1';
UPDATE words SET example_sentence = 'Dolphins are considered intelligent animals because they can solve problems and communicate effectively.' WHERE word = 'intelligent' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students learn better when they interact with their classmates during group discussions regularly.' WHERE word = 'interact' AND level = 'high_1';
UPDATE words SET example_sentence = 'Different people may have a different interpretation of the same piece of literature.' WHERE word = 'interpretation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The bus arrives at regular interval times, making it convenient for daily commuters.' WHERE word = 'interval' AND level = 'high_1';
UPDATE words SET example_sentence = 'The teacher had to intervene when the argument between the two students became serious.' WHERE word = 'intervene' AND level = 'high_1';
UPDATE words SET example_sentence = 'Early intervention can prevent minor health problems from developing into serious medical conditions.' WHERE word = 'intervention' AND level = 'high_1';

-- Batch 4: invention ~ projection
UPDATE words SET example_sentence = 'The invention of the printing press changed the course of human history forever.' WHERE word = 'invention' AND level = 'high_1';
UPDATE words SET example_sentence = 'The police decided to investigate the cause of the fire at the warehouse.' WHERE word = 'investigate' AND level = 'high_1';
UPDATE words SET example_sentence = 'A thorough investigation was conducted by the team to find the missing evidence.' WHERE word = 'investigation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The project will involve students from several different departments working together.' WHERE word = 'involve' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists had to isolate the virus before they could develop an effective vaccine.' WHERE word = 'isolate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Long periods of isolation can have a serious negative effect on mental health.' WHERE word = 'isolation' AND level = 'high_1';
UPDATE words SET example_sentence = 'She studied journalism in college because she wanted to report important stories.' WHERE word = 'journalism' AND level = 'high_1';
UPDATE words SET example_sentence = 'There was no justification for the decision that was made without any discussion.' WHERE word = 'justification' AND level = 'high_1';
UPDATE words SET example_sentence = 'The juvenile offender was given a second chance through a special rehabilitation program.' WHERE word = 'juvenile' AND level = 'high_1';
UPDATE words SET example_sentence = 'The kernel of the argument was hidden beneath layers of complicated language.' WHERE word = 'kernel' AND level = 'high_1';
UPDATE words SET example_sentence = 'The nearest hospital is approximately fifteen kilometer away from our small village.' WHERE word = 'kilometer' AND level = 'high_1';
UPDATE words SET example_sentence = 'The students performed their chemistry experiments in a well-equipped modern laboratory.' WHERE word = 'laboratory' AND level = 'high_1';
UPDATE words SET example_sentence = 'The success of the campaign was largely due to the effort of volunteers.' WHERE word = 'largely' AND level = 'high_1';
UPDATE words SET example_sentence = 'Countries located at a higher latitude tend to experience colder winter temperatures.' WHERE word = 'latitude' AND level = 'high_1';
UPDATE words SET example_sentence = 'Several countries have begun to legalize renewable energy incentives for homeowners and businesses.' WHERE word = 'legalize' AND level = 'high_1';
UPDATE words SET example_sentence = 'New legislation was passed to protect endangered species living in coastal regions.' WHERE word = 'legislation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The legislature approved a new law that would increase funding for public schools.' WHERE word = 'legislature' AND level = 'high_1';
UPDATE words SET example_sentence = 'The researchers raised a legitimate concern about the safety of the new drug.' WHERE word = 'legitimate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company accepted full liability for the environmental damage caused by the spill.' WHERE word = 'liability' AND level = 'high_1';
UPDATE words SET example_sentence = 'A liberal education encourages students to think critically about a wide range of topics.' WHERE word = 'liberal' AND level = 'high_1';
UPDATE words SET example_sentence = 'The liberation of the prisoners was celebrated by people across the entire nation.' WHERE word = 'liberation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Citizens value their liberty and the freedom to express their own opinions publicly.' WHERE word = 'liberty' AND level = 'high_1';
UPDATE words SET example_sentence = 'You must obtain a valid license before you are allowed to drive a car.' WHERE word = 'license' AND level = 'high_1';
UPDATE words SET example_sentence = 'The likelihood of success increases significantly when the team works together with dedication.' WHERE word = 'likelihood' AND level = 'high_1';
UPDATE words SET example_sentence = 'He enjoys reading novels and likewise finds great pleasure in writing short stories.' WHERE word = 'likewise' AND level = 'high_1';
UPDATE words SET example_sentence = 'The main limitation of the study was the small number of participants involved.' WHERE word = 'limitation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her linguistic abilities allowed her to communicate fluently in four different foreign languages.' WHERE word = 'linguistic' AND level = 'high_1';
UPDATE words SET example_sentence = 'The loyalty shown by the dog to its owner moved everyone who watched.' WHERE word = 'loyalty' AND level = 'high_1';
UPDATE words SET example_sentence = 'Heavy machinery was brought to the construction site to begin building the new bridge.' WHERE word = 'machinery' AND level = 'high_1';
UPDATE words SET example_sentence = 'The magnitude of the earthquake was strong enough to be felt across three states.' WHERE word = 'magnitude' AND level = 'high_1';
UPDATE words SET example_sentence = 'The manipulation of data by the researcher led to serious questions about the results.' WHERE word = 'manipulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Effective marketing strategies can help a small business reach a much wider audience quickly.' WHERE word = 'marketing' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company offers generous maternity leave so that new mothers can rest at home.' WHERE word = 'maternity' AND level = 'high_1';
UPDATE words SET example_sentence = 'Emotional maturity is developed through experience and the ability to handle difficult situations calmly.' WHERE word = 'maturity' AND level = 'high_1';
UPDATE words SET example_sentence = 'A neutral third party was asked to mediate the dispute between the two companies.' WHERE word = 'mediate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Through careful mediation, both sides were able to reach a fair and peaceful agreement.' WHERE word = 'mediation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The medieval castle, which was built in the 12th century, still stands on the hill.' WHERE word = 'medieval' AND level = 'high_1';
UPDATE words SET example_sentence = 'A memorial was built in the park to honor the soldiers who served bravely.' WHERE word = 'memorial' AND level = 'high_1';
UPDATE words SET example_sentence = 'Exercising regularly can help people stay both physically and mentally healthy over time.' WHERE word = 'mentally' AND level = 'high_1';
UPDATE words SET example_sentence = 'Many birds migrate south during the winter to find warmer climates and more food.' WHERE word = 'migrate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The migration of whales across the ocean is one of the most impressive natural events.' WHERE word = 'migration' AND level = 'high_1';
UPDATE words SET example_sentence = 'Iron is a mineral that plays an essential role in keeping our bodies healthy.' WHERE word = 'mineral' AND level = 'high_1';
UPDATE words SET example_sentence = 'The project required only minimal effort because most of the work was already done.' WHERE word = 'minimal' AND level = 'high_1';
UPDATE words SET example_sentence = 'We should minimize the use of plastic bags to help protect the natural environment.' WHERE word = 'minimize' AND level = 'high_1';
UPDATE words SET example_sentence = 'A small minority of students opposed the new rule that was proposed by the council.' WHERE word = 'minority' AND level = 'high_1';
UPDATE words SET example_sentence = 'The doctor recommended moderate exercise three times a week for maintaining good health.' WHERE word = 'moderate' AND level = 'high_1';
UPDATE words SET example_sentence = 'A slight modification to the original design made the product much easier to use.' WHERE word = 'modification' AND level = 'high_1';
UPDATE words SET example_sentence = 'The experiment was difficult to perform; moreover, the results were hard to interpret clearly.' WHERE word = 'moreover' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her strong motivation to succeed pushed her to study harder than anyone else around.' WHERE word = 'motivation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The municipal government announced plans to build a new public library in the downtown area.' WHERE word = 'municipal' AND level = 'high_1';
UPDATE words SET example_sentence = 'The talented musician performed a beautiful piece that moved the entire audience to tears.' WHERE word = 'musician' AND level = 'high_1';
UPDATE words SET example_sentence = 'A mysterious light appeared in the sky, and nobody could explain where it came from.' WHERE word = 'mysterious' AND level = 'high_1';
UPDATE words SET example_sentence = 'The mystery of the missing painting remained unsolved for more than fifty long years.' WHERE word = 'mystery' AND level = 'high_1';
UPDATE words SET example_sentence = 'It is natural for people to feel nervous before giving a speech in public.' WHERE word = 'natural' AND level = 'high_1';
UPDATE words SET example_sentence = 'Clean drinking water is a basic necessity that every person in the world deserves.' WHERE word = 'necessity' AND level = 'high_1';
UPDATE words SET example_sentence = 'If you neglect your health now, you may face serious problems in the future.' WHERE word = 'neglect' AND level = 'high_1';
UPDATE words SET example_sentence = 'The negligence of the factory owners resulted in a dangerous chemical leak into the river.' WHERE word = 'negligence' AND level = 'high_1';
UPDATE words SET example_sentence = 'After weeks of negotiation, the two countries finally signed a historic peace agreement together.' WHERE word = 'negotiation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The weather was terrible; nevertheless, the team continued to work on the outdoor project.' WHERE word = 'nevertheless' AND level = 'high_1';
UPDATE words SET example_sentence = 'She made a notable contribution to the field of science through her groundbreaking research.' WHERE word = 'notable' AND level = 'high_1';
UPDATE words SET example_sentence = 'Nuclear energy is considered by many to be a powerful but controversial power source.' WHERE word = 'nuclear' AND level = 'high_1';
UPDATE words SET example_sentence = 'The numerical data collected from the survey was carefully analyzed by the research team.' WHERE word = 'numerical' AND level = 'high_1';
UPDATE words SET example_sentence = 'It was obvious that the student had prepared well for the final presentation today.' WHERE word = 'obvious' AND level = 'high_1';
UPDATE words SET example_sentence = 'His occupation as a firefighter required both physical strength and incredible mental courage daily.' WHERE word = 'occupation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The gains from the new policy were offset by unexpected costs that arose later.' WHERE word = 'offset' AND level = 'high_1';
UPDATE words SET example_sentence = 'Many citizens chose to oppose the plan because they believed it was deeply unfair.' WHERE word = 'oppose' AND level = 'high_1';
UPDATE words SET example_sentence = 'Despite strong opposition from local residents, the construction of the highway was approved officially.' WHERE word = 'opposition' AND level = 'high_1';
UPDATE words SET example_sentence = 'The extra training session is optional, but students who attend will gain valuable experience.' WHERE word = 'optional' AND level = 'high_1';
UPDATE words SET example_sentence = 'A brief orientation was held so that new students could learn about the school rules.' WHERE word = 'orientation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The economic outlook for next year remains uncertain due to the ongoing global challenges.' WHERE word = 'outlook' AND level = 'high_1';
UPDATE words SET example_sentence = 'The two roads run parallel to each other for about ten kilometers through the valley.' WHERE word = 'parallel' AND level = 'high_1';
UPDATE words SET example_sentence = 'Temperature is an important parameter that must be controlled carefully during the chemical experiment.' WHERE word = 'parameter' AND level = 'high_1';
UPDATE words SET example_sentence = 'This issue is particularly important because it affects the health of millions of people.' WHERE word = 'particularly' AND level = 'high_1';
UPDATE words SET example_sentence = 'In a passive sentence, the subject receives the action rather than performing it directly.' WHERE word = 'passive' AND level = 'high_1';
UPDATE words SET example_sentence = 'Our perception of time changes depending on whether we are bored or having fun.' WHERE word = 'perception' AND level = 'high_1';
UPDATE words SET example_sentence = 'The museum has a permanent collection that visitors can enjoy throughout the entire year.' WHERE word = 'permanent' AND level = 'high_1';
UPDATE words SET example_sentence = 'If you persist in practicing every day, you will eventually master the difficult skill.' WHERE word = 'persist' AND level = 'high_1';
UPDATE words SET example_sentence = 'His philosophy of life was based on treating every person with kindness and respect.' WHERE word = 'philosophy' AND level = 'high_1';
UPDATE words SET example_sentence = 'The physician advised her to get more rest and reduce her daily stress levels.' WHERE word = 'physician' AND level = 'high_1';
UPDATE words SET example_sentence = 'Social media has become a powerful platform for sharing ideas and connecting with others.' WHERE word = 'platform' AND level = 'high_1';
UPDATE words SET example_sentence = 'Political leaders must consider the needs of all citizens when making important national decisions.' WHERE word = 'political' AND level = 'high_1';
UPDATE words SET example_sentence = 'Air pollution caused by factories and cars is a growing threat to public health.' WHERE word = 'pollution' AND level = 'high_1';
UPDATE words SET example_sentence = 'The instructions must be followed precisely so that the experiment produces accurate and reliable results.' WHERE word = 'precisely' AND level = 'high_1';
UPDATE words SET example_sentence = 'The prediction made by the scientist about climate change turned out to be remarkably accurate.' WHERE word = 'prediction' AND level = 'high_1';
UPDATE words SET example_sentence = 'A preliminary review of the data suggested that the new treatment was highly effective.' WHERE word = 'preliminary' AND level = 'high_1';
UPDATE words SET example_sentence = 'The preservation of ancient forests is essential for maintaining biodiversity in the natural world.' WHERE word = 'preservation' AND level = 'high_1';
UPDATE words SET example_sentence = 'We should not presume that everyone agrees with the decision without asking them directly.' WHERE word = 'presume' AND level = 'high_1';
UPDATE words SET example_sentence = 'Despite many challenges, the team managed to prevail and win the national championship title.' WHERE word = 'prevail' AND level = 'high_1';
UPDATE words SET example_sentence = 'Wearing a seatbelt is one of the simplest ways to prevent serious injuries in accidents.' WHERE word = 'prevent' AND level = 'high_1';
UPDATE words SET example_sentence = 'The results were compared with data collected from the previous year to identify any trends.' WHERE word = 'previous' AND level = 'high_1';
UPDATE words SET example_sentence = 'There is a high probability that the project will be completed before the deadline.' WHERE word = 'probability' AND level = 'high_1';
UPDATE words SET example_sentence = 'Once the safety checks are completed, we will proceed to the next important step.' WHERE word = 'proceed' AND level = 'high_1';
UPDATE words SET example_sentence = 'The producer of the film spent three years developing the story before filming finally began.' WHERE word = 'producer' AND level = 'high_1';
UPDATE words SET example_sentence = 'The final product was tested thoroughly to ensure it met all the quality standards.' WHERE word = 'product' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company created a detailed profile of their ideal customer to improve their sales strategy.' WHERE word = 'profile' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company earned a large profit after launching its innovative new product line successfully.' WHERE word = 'profit' AND level = 'high_1';
UPDATE words SET example_sentence = 'Investing in renewable energy has proven to be both environmentally friendly and highly profitable.' WHERE word = 'profitable' AND level = 'high_1';
UPDATE words SET example_sentence = 'The program was designed to help young students develop strong leadership skills over time.' WHERE word = 'program' AND level = 'high_1';
UPDATE words SET example_sentence = 'The law was created to prohibit the dumping of toxic waste into rivers and lakes.' WHERE word = 'prohibit' AND level = 'high_1';
UPDATE words SET example_sentence = 'According to the projection, the population of the city will double within twenty years.' WHERE word = 'projection' AND level = 'high_1';

-- Batch 5: proportion ~ zoology
UPDATE words SET example_sentence = 'The proportion of students who passed the exam was surprisingly high this year.' WHERE word = 'proportion' AND level = 'high_1';
UPDATE words SET example_sentence = 'The prospect of studying abroad excited her more than anything else.' WHERE word = 'prospect' AND level = 'high_1';
UPDATE words SET example_sentence = 'Every researcher must follow the protocol established by the scientific committee carefully.' WHERE word = 'protocol' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government made provision for emergency food supplies during the natural disaster.' WHERE word = 'provision' AND level = 'high_1';
UPDATE words SET example_sentence = 'She decided to study psychology because she wanted to understand human behavior.' WHERE word = 'psychology' AND level = 'high_1';
UPDATE words SET example_sentence = 'His pursuit of knowledge led him to read hundreds of books every year.' WHERE word = 'pursuit' AND level = 'high_1';
UPDATE words SET example_sentence = 'The qualitative analysis revealed important differences that numbers alone could not show.' WHERE word = 'qualitative' AND level = 'high_1';
UPDATE words SET example_sentence = 'Quantitative data collected from the survey helped the team draw clear conclusions.' WHERE word = 'quantitative' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company publishes a quarterly report that summarizes its financial performance every season.' WHERE word = 'quarterly' AND level = 'high_1';
UPDATE words SET example_sentence = 'Exposure to harmful radiation can cause serious health problems over a long period.' WHERE word = 'radiation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The radical change in education policy affected every school in the entire country.' WHERE word = 'radical' AND level = 'high_1';
UPDATE words SET example_sentence = 'Information about the new program was readily available on the official website.' WHERE word = 'readily' AND level = 'high_1';
UPDATE words SET example_sentence = 'The novel was praised for its realism in describing the lives of ordinary people.' WHERE word = 'realism' AND level = 'high_1';
UPDATE words SET example_sentence = 'Setting realistic goals is essential if you want to achieve long-term success.' WHERE word = 'realistic' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her logical reasoning helped the team solve the complex problem within one hour.' WHERE word = 'reasoning' AND level = 'high_1';
UPDATE words SET example_sentence = 'I would recommend this book to anyone who is interested in modern history.' WHERE word = 'recommend' AND level = 'high_1';
UPDATE words SET example_sentence = 'Scientists continue to refine their methods so that the results become more accurate.' WHERE word = 'refine' AND level = 'high_1';
UPDATE words SET example_sentence = 'The refinement of the manufacturing process reduced waste and improved product quality significantly.' WHERE word = 'refinement' AND level = 'high_1';
UPDATE words SET example_sentence = 'Strict regulation of air pollution has improved the quality of life in cities.' WHERE word = 'regulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Positive reinforcement from teachers encourages students to participate more actively in class discussions.' WHERE word = 'reinforcement' AND level = 'high_1';
UPDATE words SET example_sentence = 'The reliability of this machine has been proven through years of continuous testing.' WHERE word = 'reliability' AND level = 'high_1';
UPDATE words SET example_sentence = 'We need a reliable source of information before making any important decision together.' WHERE word = 'reliable' AND level = 'high_1';
UPDATE words SET example_sentence = 'Religion has played a significant role in shaping cultures throughout human history worldwide.' WHERE word = 'religion' AND level = 'high_1';
UPDATE words SET example_sentence = 'The heavy rain could render the roads too dangerous for drivers to travel safely.' WHERE word = 'render' AND level = 'high_1';
UPDATE words SET example_sentence = 'Finding a suitable replacement for the retired professor was not an easy task at all.' WHERE word = 'replacement' AND level = 'high_1';
UPDATE words SET example_sentence = 'The painting is a powerful representation of the struggles faced by working-class families.' WHERE word = 'representation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The resolution passed by the student council addressed the issue of recycling on campus.' WHERE word = 'resolution' AND level = 'high_1';
UPDATE words SET example_sentence = 'The restriction on phone use during class helped students focus on their studies better.' WHERE word = 'restriction' AND level = 'high_1';
UPDATE words SET example_sentence = 'The revelation that the data had been falsified shocked the entire scientific community deeply.' WHERE word = 'revelation' AND level = 'high_1';
UPDATE words SET example_sentence = 'A thorough revision of the essay improved both its structure and overall clarity.' WHERE word = 'revision' AND level = 'high_1';
UPDATE words SET example_sentence = 'The industrial revolution transformed society by introducing machines that replaced manual labor in factories.' WHERE word = 'revolution' AND level = 'high_1';
UPDATE words SET example_sentence = 'The rigorous training program prepared the athletes for the international competition held in July.' WHERE word = 'rigorous' AND level = 'high_1';
UPDATE words SET example_sentence = 'The romantic poetry of that era expressed deep emotions about nature and human love.' WHERE word = 'romantic' AND level = 'high_1';
UPDATE words SET example_sentence = 'Following a daily routine helps students manage their time and reduce unnecessary stress effectively.' WHERE word = 'routine' AND level = 'high_1';
UPDATE words SET example_sentence = 'In the worst-case scenario, the project would be delayed by at least three months.' WHERE word = 'scenario' AND level = 'high_1';
UPDATE words SET example_sentence = 'The university has a selective admission process that considers both grades and extracurricular activities.' WHERE word = 'selective' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students who attended the seminar learned valuable skills for writing academic research papers effectively.' WHERE word = 'seminar' AND level = 'high_1';
UPDATE words SET example_sentence = 'He is very sensitive to criticism, so you should choose your words carefully.' WHERE word = 'sensitive' AND level = 'high_1';
UPDATE words SET example_sentence = 'The similarity between the two languages made it easier for her to learn both.' WHERE word = 'similarity' AND level = 'high_1';
UPDATE words SET example_sentence = 'The computer simulation showed how climate change could affect coastal cities in the future.' WHERE word = 'simulation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The sophisticated technology used in modern phones amazes people who remember the older models.' WHERE word = 'sophisticated' AND level = 'high_1';
UPDATE words SET example_sentence = 'Please provide specific examples to support the main argument presented in your essay.' WHERE word = 'specify' AND level = 'high_1';
UPDATE words SET example_sentence = 'A major corporation agreed to sponsor the science fair held at our school.' WHERE word = 'sponsor' AND level = 'high_1';
UPDATE words SET example_sentence = 'Political stability is essential for the economic growth and development of any nation.' WHERE word = 'stability' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government introduced new policies designed to stabilize the economy after the financial crisis.' WHERE word = 'stabilize' AND level = 'high_1';
UPDATE words SET example_sentence = 'According to a recent statistic, more than half of teenagers use social media daily.' WHERE word = 'statistic' AND level = 'high_1';
UPDATE words SET example_sentence = 'Regular exercise can strengthen your immune system and help you stay healthy all year.' WHERE word = 'strengthen' AND level = 'high_1';
UPDATE words SET example_sentence = 'The subsequent investigation revealed that the accident was caused by a mechanical failure.' WHERE word = 'subsequent' AND level = 'high_1';
UPDATE words SET example_sentence = 'If butter is unavailable, you can substitute olive oil in most cooking recipes easily.' WHERE word = 'substitute' AND level = 'high_1';
UPDATE words SET example_sentence = 'The rapid succession of events left everyone confused about what had actually happened that day.' WHERE word = 'succession' AND level = 'high_1';
UPDATE words SET example_sentence = 'The summary at the end of the chapter highlights all the key points discussed.' WHERE word = 'summary' AND level = 'high_1';
UPDATE words SET example_sentence = 'Doctors often supplement traditional treatment with physical therapy to help patients recover faster.' WHERE word = 'supplement' AND level = 'high_1';
UPDATE words SET example_sentence = 'The government attempted to suppress information about the environmental damage caused by the factory.' WHERE word = 'suppress' AND level = 'high_1';
UPDATE words SET example_sentence = 'Sustainable energy sources like solar and wind power are becoming more popular worldwide today.' WHERE word = 'sustainable' AND level = 'high_1';
UPDATE words SET example_sentence = 'The symbolic meaning of the color red varies greatly depending on the culture observed.' WHERE word = 'symbolic' AND level = 'high_1';
UPDATE words SET example_sentence = 'The technical aspects of the project required help from an experienced software engineer.' WHERE word = 'technical' AND level = 'high_1';
UPDATE words SET example_sentence = 'The company decided to terminate the contract because the terms were not being followed.' WHERE word = 'terminate' AND level = 'high_1';
UPDATE words SET example_sentence = 'Animals often defend their territory against intruders to protect their food and young offspring.' WHERE word = 'territory' AND level = 'high_1';
UPDATE words SET example_sentence = 'Teaching tolerance in schools helps young people respect differences and live together in harmony.' WHERE word = 'tolerance' AND level = 'high_1';
UPDATE words SET example_sentence = 'The transformation of the abandoned building into a community center impressed the entire neighborhood.' WHERE word = 'transformation' AND level = 'high_1';
UPDATE words SET example_sentence = 'The transition from middle school to high school can be challenging for many students.' WHERE word = 'transition' AND level = 'high_1';
UPDATE words SET example_sentence = 'The transmission of diseases can be prevented by washing your hands regularly and thoroughly.' WHERE word = 'transmission' AND level = 'high_1';
UPDATE words SET example_sentence = 'Satellites are used to transmit television signals to millions of homes around the world.' WHERE word = 'transmit' AND level = 'high_1';
UPDATE words SET example_sentence = 'Hard work and patience will ultimately lead to the success you have been seeking.' WHERE word = 'ultimately' AND level = 'high_1';
UPDATE words SET example_sentence = 'The organization decided to undertake a major project aimed at reducing ocean pollution levels.' WHERE word = 'undertake' AND level = 'high_1';
UPDATE words SET example_sentence = 'The utility of this software becomes clear once you learn how to use it properly.' WHERE word = 'utility' AND level = 'high_1';
UPDATE words SET example_sentence = 'Researchers questioned the validity of the study because the sample size was extremely small.' WHERE word = 'validity' AND level = 'high_1';
UPDATE words SET example_sentence = 'The experience she gained during the internship proved to be extremely valuable for her career.' WHERE word = 'valuable' AND level = 'high_1';
UPDATE words SET example_sentence = 'Temperature is an important variable that must be controlled carefully during the science experiment.' WHERE word = 'variable' AND level = 'high_1';
UPDATE words SET example_sentence = 'The teacher asked students to verify their answers by checking the original source material.' WHERE word = 'verify' AND level = 'high_1';
UPDATE words SET example_sentence = 'Those who violate the school rules will face serious consequences determined by the principal.' WHERE word = 'violate' AND level = 'high_1';
UPDATE words SET example_sentence = 'The violation of environmental laws resulted in heavy fines imposed on the manufacturing company.' WHERE word = 'violation' AND level = 'high_1';
UPDATE words SET example_sentence = 'Virtual reality technology allows students to explore historical sites without leaving the classroom at all.' WHERE word = 'virtual' AND level = 'high_1';
UPDATE words SET example_sentence = 'Patience is a virtue that helps people handle difficult situations with calmness and wisdom.' WHERE word = 'virtue' AND level = 'high_1';
UPDATE words SET example_sentence = 'The visual presentation of the data made it much easier for everyone to understand.' WHERE word = 'visual' AND level = 'high_1';
UPDATE words SET example_sentence = 'The widespread use of smartphones has changed the way people access information and communicate.' WHERE word = 'widespread' AND level = 'high_1';
UPDATE words SET example_sentence = 'The withdrawal of funding forced the research team to cancel the planned field study.' WHERE word = 'withdrawal' AND level = 'high_1';
UPDATE words SET example_sentence = 'A positive workplace environment increases employee satisfaction and leads to higher overall productivity.' WHERE word = 'workplace' AND level = 'high_1';
UPDATE words SET example_sentence = 'Her youthful energy and enthusiasm inspired everyone on the volunteer team to work harder.' WHERE word = 'youthful' AND level = 'high_1';
UPDATE words SET example_sentence = 'Students interested in zoology often visit wildlife reserves to observe animals in their natural habitat.' WHERE word = 'zoology' AND level = 'high_1';
