-- ============================================================
-- 숙어(idiom) 시드 데이터
-- 중등: 8세트 (set_no 21~23), 160개
-- 고등: 15세트 (set_no 26~33), 300개
-- 총 460개, 학년별 난이도순/시험 빈출순 배열
-- ============================================================

-- ── 중등 1학년 (mid_1) : 2세트, 40개 ──

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
-- Set 21: 기초 일상 숙어
('idiom','mid_1',21,'look forward to','~을 기대하다',NULL,NULL,'I look forward to seeing you.'),
('idiom','mid_1',21,'be good at','~을 잘하다',NULL,NULL,'She is good at drawing.'),
('idiom','mid_1',21,'be interested in','~에 관심이 있다',NULL,NULL,'He is interested in science.'),
('idiom','mid_1',21,'take care of','~을 돌보다',NULL,NULL,'Please take care of my dog.'),
('idiom','mid_1',21,'look for','~을 찾다',NULL,NULL,'I am looking for my keys.'),
('idiom','mid_1',21,'pick up','줍다, 데리러 가다',NULL,NULL,'Can you pick up the phone?'),
('idiom','mid_1',21,'turn on','(전원을) 켜다',NULL,NULL,'Turn on the light, please.'),
('idiom','mid_1',21,'turn off','(전원을) 끄다',NULL,NULL,'Please turn off the TV.'),
('idiom','mid_1',21,'put on','입다, 착용하다',NULL,NULL,'Put on your jacket.'),
('idiom','mid_1',21,'take off','벗다, 이륙하다',NULL,NULL,'The plane will take off soon.'),
('idiom','mid_1',21,'get up','일어나다',NULL,NULL,'I get up at seven every day.'),
('idiom','mid_1',21,'wake up','잠에서 깨다',NULL,NULL,'Wake up! It is morning.'),
('idiom','mid_1',21,'go on','계속하다',NULL,NULL,'Please go on with your story.'),
('idiom','mid_1',21,'come back','돌아오다',NULL,NULL,'When will you come back?'),
('idiom','mid_1',21,'find out','알아내다',NULL,NULL,'I need to find out the truth.'),
('idiom','mid_1',21,'give up','포기하다',NULL,NULL,'Never give up your dream.'),
('idiom','mid_1',21,'hang out','어울리다, 놀다',NULL,NULL,'Let us hang out this weekend.'),
('idiom','mid_1',21,'run out of','~이 다 떨어지다',NULL,NULL,'We ran out of milk.'),
('idiom','mid_1',21,'get along with','~와 잘 지내다',NULL,NULL,'I get along with my classmates.'),
('idiom','mid_1',21,'be afraid of','~을 두려워하다',NULL,NULL,'She is afraid of spiders.'),

-- Set 22: 기초 학교 숙어
('idiom','mid_1',22,'hand in','제출하다',NULL,NULL,'Please hand in your homework.'),
('idiom','mid_1',22,'figure out','이해하다, 알아내다',NULL,NULL,'Can you figure out this problem?'),
('idiom','mid_1',22,'be made of','~로 만들어지다',NULL,NULL,'This desk is made of wood.'),
('idiom','mid_1',22,'be full of','~로 가득 차다',NULL,NULL,'The box is full of toys.'),
('idiom','mid_1',22,'belong to','~에 속하다',NULL,NULL,'This book belongs to me.'),
('idiom','mid_1',22,'depend on','~에 의존하다, ~에 달려 있다',NULL,NULL,'It depends on the weather.'),
('idiom','mid_1',22,'think of','~을 생각하다',NULL,NULL,'What do you think of this idea?'),
('idiom','mid_1',22,'hear of','~에 대해 듣다',NULL,NULL,'Have you heard of this movie?'),
('idiom','mid_1',22,'instead of','~ 대신에',NULL,NULL,'I had tea instead of coffee.'),
('idiom','mid_1',22,'because of','~ 때문에',NULL,NULL,'We stayed home because of the rain.'),
('idiom','mid_1',22,'in front of','~ 앞에',NULL,NULL,'He stood in front of the class.'),
('idiom','mid_1',22,'next to','~ 옆에',NULL,NULL,'Sit next to me.'),
('idiom','mid_1',22,'a lot of','많은',NULL,NULL,'There are a lot of books here.'),
('idiom','mid_1',22,'a kind of','일종의',NULL,NULL,'It is a kind of fish.'),
('idiom','mid_1',22,'on time','정시에',NULL,NULL,'Please arrive on time.'),
('idiom','mid_1',22,'at first','처음에',NULL,NULL,'At first, I did not understand.'),
('idiom','mid_1',22,'at last','마침내',NULL,NULL,'At last, we arrived home.'),
('idiom','mid_1',22,'by the way','그런데',NULL,NULL,'By the way, where is Tom?'),
('idiom','mid_1',22,'for example','예를 들어',NULL,NULL,'I like fruits, for example, apples.'),
('idiom','mid_1',22,'in fact','사실은',NULL,NULL,'In fact, he is my brother.');

-- ── 중등 2학년 (mid_2) : 3세트, 60개 ──

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
-- Set 21: 중급 생활 숙어
('idiom','mid_2',21,'look after','돌보다',NULL,NULL,'She looks after her little sister.'),
('idiom','mid_2',21,'come up with','(아이디어를) 생각해내다',NULL,NULL,'He came up with a great plan.'),
('idiom','mid_2',21,'be used to','~에 익숙하다',NULL,NULL,'I am used to waking up early.'),
('idiom','mid_2',21,'used to','(과거에) ~하곤 했다',NULL,NULL,'I used to play soccer every day.'),
('idiom','mid_2',21,'make up one''s mind','결심하다',NULL,NULL,'She made up her mind to study abroad.'),
('idiom','mid_2',21,'keep in mind','명심하다',NULL,NULL,'Keep in mind that practice makes perfect.'),
('idiom','mid_2',21,'by accident','우연히',NULL,NULL,'I found the book by accident.'),
('idiom','mid_2',21,'on purpose','일부러',NULL,NULL,'He did it on purpose.'),
('idiom','mid_2',21,'from now on','지금부터',NULL,NULL,'From now on, I will study harder.'),
('idiom','mid_2',21,'once in a while','가끔',NULL,NULL,'I eat out once in a while.'),
('idiom','mid_2',21,'sooner or later','조만간',NULL,NULL,'Sooner or later, you will understand.'),
('idiom','mid_2',21,'little by little','조금씩',NULL,NULL,'Little by little, she improved.'),
('idiom','mid_2',21,'all of a sudden','갑자기',NULL,NULL,'All of a sudden, it started raining.'),
('idiom','mid_2',21,'in a hurry','서둘러서',NULL,NULL,'He left in a hurry.'),
('idiom','mid_2',21,'on one''s own','스스로, 혼자서',NULL,NULL,'She did it on her own.'),
('idiom','mid_2',21,'take place','발생하다, 일어나다',NULL,NULL,'The event took place last week.'),
('idiom','mid_2',21,'break down','고장 나다',NULL,NULL,'My car broke down on the road.'),
('idiom','mid_2',21,'show up','나타나다',NULL,NULL,'He finally showed up at the party.'),
('idiom','mid_2',21,'put off','미루다, 연기하다',NULL,NULL,'Do not put off your homework.'),
('idiom','mid_2',21,'carry out','수행하다, 실행하다',NULL,NULL,'We carried out the experiment.'),

-- Set 22: 중급 의사소통 숙어
('idiom','mid_2',22,'have nothing to do with','~와 관계가 없다',NULL,NULL,'This has nothing to do with me.'),
('idiom','mid_2',22,'make a difference','차이를 만들다, 중요하다',NULL,NULL,'Your help makes a big difference.'),
('idiom','mid_2',22,'make sense','이해가 되다, 말이 되다',NULL,NULL,'Does this sentence make sense?'),
('idiom','mid_2',22,'get rid of','~을 없애다, 제거하다',NULL,NULL,'Get rid of those old shoes.'),
('idiom','mid_2',22,'pay attention to','~에 주의를 기울이다',NULL,NULL,'Pay attention to the teacher.'),
('idiom','mid_2',22,'take part in','~에 참여하다',NULL,NULL,'She took part in the contest.'),
('idiom','mid_2',22,'be supposed to','~하기로 되어 있다',NULL,NULL,'You are supposed to be here at nine.'),
('idiom','mid_2',22,'be about to','막 ~하려고 하다',NULL,NULL,'I was about to leave.'),
('idiom','mid_2',22,'end up','결국 ~하게 되다',NULL,NULL,'We ended up staying home.'),
('idiom','mid_2',22,'point out','지적하다',NULL,NULL,'She pointed out my mistake.'),
('idiom','mid_2',22,'stand for','~을 나타내다, 상징하다',NULL,NULL,'UN stands for United Nations.'),
('idiom','mid_2',22,'deal with','~을 다루다, 처리하다',NULL,NULL,'How do you deal with stress?'),
('idiom','mid_2',22,'at least','적어도',NULL,NULL,'At least ten people came.'),
('idiom','mid_2',22,'at most','기껏해야',NULL,NULL,'It will take at most two hours.'),
('idiom','mid_2',22,'no longer','더 이상 ~아닌',NULL,NULL,'He is no longer a student.'),
('idiom','mid_2',22,'as well as','~뿐만 아니라',NULL,NULL,'She speaks French as well as English.'),
('idiom','mid_2',22,'so far','지금까지',NULL,NULL,'So far, everything is fine.'),
('idiom','mid_2',22,'right away','즉시, 당장',NULL,NULL,'I will do it right away.'),
('idiom','mid_2',22,'above all','무엇보다도',NULL,NULL,'Above all, be honest.'),
('idiom','mid_2',22,'after all','결국',NULL,NULL,'After all, she was right.'),

-- Set 23: 중급 독해 숙어
('idiom','mid_2',23,'be related to','~와 관련이 있다',NULL,NULL,'The two events are closely related to each other.'),
('idiom','mid_2',23,'be based on','~에 기초하다',NULL,NULL,'The movie is based on a true story.'),
('idiom','mid_2',23,'be known for','~로 유명하다',NULL,NULL,'Paris is known for the Eiffel Tower.'),
('idiom','mid_2',23,'be similar to','~와 비슷하다',NULL,NULL,'His idea is similar to mine.'),
('idiom','mid_2',23,'be different from','~와 다르다',NULL,NULL,'My opinion is different from yours.'),
('idiom','mid_2',23,'be responsible for','~에 책임이 있다',NULL,NULL,'Who is responsible for this project?'),
('idiom','mid_2',23,'in addition to','~에 더하여',NULL,NULL,'In addition to English, she speaks Korean.'),
('idiom','mid_2',23,'according to','~에 따르면',NULL,NULL,'According to the news, it will rain tomorrow.'),
('idiom','mid_2',23,'in spite of','~에도 불구하고',NULL,NULL,'In spite of the rain, we went out.'),
('idiom','mid_2',23,'thanks to','~ 덕분에',NULL,NULL,'Thanks to your help, I passed the exam.'),
('idiom','mid_2',23,'as a result','결과적으로',NULL,NULL,'He studied hard. As a result, he passed.'),
('idiom','mid_2',23,'in other words','다시 말해서',NULL,NULL,'He is my sibling. In other words, my brother.'),
('idiom','mid_2',23,'on the other hand','반면에',NULL,NULL,'I like coffee. On the other hand, she likes tea.'),
('idiom','mid_2',23,'for instance','예를 들어',NULL,NULL,'Some animals, for instance dogs, are loyal.'),
('idiom','mid_2',23,'in general','일반적으로',NULL,NULL,'In general, students study hard here.'),
('idiom','mid_2',23,'in particular','특히',NULL,NULL,'I like sports, in particular basketball.'),
('idiom','mid_2',23,'as long as','~하는 한',NULL,NULL,'You can go as long as you finish your work.'),
('idiom','mid_2',23,'even though','~에도 불구하고',NULL,NULL,'Even though it was cold, he went outside.'),
('idiom','mid_2',23,'not only A but also B','A뿐만 아니라 B도',NULL,NULL,'She is not only smart but also kind.'),
('idiom','mid_2',23,'either A or B','A 또는 B 둘 중 하나',NULL,NULL,'You can have either tea or coffee.');

-- ── 중등 3학년 (mid_3) : 3세트, 60개 ──

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
-- Set 21: 내신 필수 숙어 1
('idiom','mid_3',21,'come across','우연히 발견하다',NULL,NULL,'I came across an old photo.'),
('idiom','mid_3',21,'bring about','야기하다, 초래하다',NULL,NULL,'Technology brought about many changes.'),
('idiom','mid_3',21,'call off','취소하다',NULL,NULL,'They called off the meeting.'),
('idiom','mid_3',21,'cut down on','~을 줄이다',NULL,NULL,'You should cut down on sugar.'),
('idiom','mid_3',21,'drop by','잠깐 들르다',NULL,NULL,'Feel free to drop by anytime.'),
('idiom','mid_3',21,'fill in','(서류 등을) 작성하다',NULL,NULL,'Please fill in this form.'),
('idiom','mid_3',21,'go through','겪다, 경험하다',NULL,NULL,'She went through a difficult time.'),
('idiom','mid_3',21,'hand out','나눠주다',NULL,NULL,'The teacher handed out the papers.'),
('idiom','mid_3',21,'keep up with','~에 뒤처지지 않다',NULL,NULL,'It is hard to keep up with technology.'),
('idiom','mid_3',21,'let down','실망시키다',NULL,NULL,'I will not let you down.'),
('idiom','mid_3',21,'make up for','~을 보상하다',NULL,NULL,'He tried to make up for his mistake.'),
('idiom','mid_3',21,'set up','설치하다, 설립하다',NULL,NULL,'They set up a new company.'),
('idiom','mid_3',21,'take after','~을 닮다',NULL,NULL,'She takes after her mother.'),
('idiom','mid_3',21,'turn down','거절하다',NULL,NULL,'He turned down the offer.'),
('idiom','mid_3',21,'turn out','~으로 밝혀지다',NULL,NULL,'It turned out to be true.'),
('idiom','mid_3',21,'work out','운동하다, 해결되다',NULL,NULL,'Everything will work out in the end.'),
('idiom','mid_3',21,'look up to','~을 존경하다',NULL,NULL,'I look up to my teacher.'),
('idiom','mid_3',21,'look down on','~을 무시하다',NULL,NULL,'Do not look down on others.'),
('idiom','mid_3',21,'run into','우연히 만나다',NULL,NULL,'I ran into my old friend yesterday.'),
('idiom','mid_3',21,'stand out','두드러지다, 눈에 띄다',NULL,NULL,'Her talent really stands out.'),

-- Set 22: 내신 필수 숙어 2
('idiom','mid_3',22,'be likely to','~할 가능성이 있다',NULL,NULL,'It is likely to rain today.'),
('idiom','mid_3',22,'be willing to','기꺼이 ~하다',NULL,NULL,'She is willing to help us.'),
('idiom','mid_3',22,'be worth -ing','~할 가치가 있다',NULL,NULL,'This book is worth reading.'),
('idiom','mid_3',22,'cannot help -ing','~하지 않을 수 없다',NULL,NULL,'I cannot help laughing at his joke.'),
('idiom','mid_3',22,'feel like -ing','~하고 싶다',NULL,NULL,'I feel like eating pizza tonight.'),
('idiom','mid_3',22,'have difficulty -ing','~하는 데 어려움이 있다',NULL,NULL,'He had difficulty solving the problem.'),
('idiom','mid_3',22,'it is no use -ing','~해도 소용없다',NULL,NULL,'It is no use crying over spilt milk.'),
('idiom','mid_3',22,'prevent A from -ing','A가 ~하는 것을 막다',NULL,NULL,'The rain prevented us from going out.'),
('idiom','mid_3',22,'would rather','차라리 ~하겠다',NULL,NULL,'I would rather stay home today.'),
('idiom','mid_3',22,'had better','~하는 게 좋겠다',NULL,NULL,'You had better see a doctor.'),
('idiom','mid_3',22,'may as well','~하는 편이 낫다',NULL,NULL,'We may as well start now.'),
('idiom','mid_3',22,'would like to','~하고 싶다',NULL,NULL,'I would like to travel abroad.'),
('idiom','mid_3',22,'be apt to','~하기 쉽다, ~하는 경향이 있다',NULL,NULL,'Children are apt to make mistakes.'),
('idiom','mid_3',22,'not A but B','A가 아니라 B',NULL,NULL,'It is not luck but effort that matters.'),
('idiom','mid_3',22,'neither A nor B','A도 B도 아닌',NULL,NULL,'Neither Tom nor Jane was there.'),
('idiom','mid_3',22,'both A and B','A와 B 둘 다',NULL,NULL,'Both she and I like music.'),
('idiom','mid_3',22,'the more, the more','~할수록 더 ~하다',NULL,NULL,'The more you read, the more you learn.'),
('idiom','mid_3',22,'so ~ that','너무 ~해서 …하다',NULL,NULL,'He was so tired that he fell asleep.'),
('idiom','mid_3',22,'too ~ to','너무 ~해서 …할 수 없다',NULL,NULL,'She was too young to understand.'),
('idiom','mid_3',22,'such ~ that','매우 ~해서 …하다',NULL,NULL,'It was such a good movie that I watched it twice.'),

-- Set 23: 내신 고난도 숙어
('idiom','mid_3',23,'account for','설명하다, 차지하다',NULL,NULL,'This accounts for 30 percent of the total.'),
('idiom','mid_3',23,'do away with','없애다, 폐지하다',NULL,NULL,'They did away with the old rules.'),
('idiom','mid_3',23,'hold back','억제하다, 주저하다',NULL,NULL,'She held back her tears.'),
('idiom','mid_3',23,'live up to','(기대에) 부응하다',NULL,NULL,'He lived up to his parents'' expectations.'),
('idiom','mid_3',23,'make the most of','~을 최대한 활용하다',NULL,NULL,'Make the most of your time.'),
('idiom','mid_3',23,'put up with','~을 참다, 견디다',NULL,NULL,'I cannot put up with the noise.'),
('idiom','mid_3',23,'take A for granted','A를 당연하게 여기다',NULL,NULL,'Do not take your health for granted.'),
('idiom','mid_3',23,'take advantage of','~을 이용하다',NULL,NULL,'Take advantage of this opportunity.'),
('idiom','mid_3',23,'with regard to','~에 관하여',NULL,NULL,'With regard to your question, here is my answer.'),
('idiom','mid_3',23,'in terms of','~의 관점에서',NULL,NULL,'In terms of quality, this is the best.'),
('idiom','mid_3',23,'on behalf of','~을 대신하여',NULL,NULL,'I spoke on behalf of the team.'),
('idiom','mid_3',23,'for the sake of','~을 위하여',NULL,NULL,'He did it for the sake of his family.'),
('idiom','mid_3',23,'in the long run','결국, 장기적으로',NULL,NULL,'In the long run, honesty pays off.'),
('idiom','mid_3',23,'by all means','반드시, 물론',NULL,NULL,'By all means, come and visit us.'),
('idiom','mid_3',23,'by no means','결코 ~아닌',NULL,NULL,'This is by no means easy.'),
('idiom','mid_3',23,'to some extent','어느 정도',NULL,NULL,'I agree with you to some extent.'),
('idiom','mid_3',23,'at the expense of','~을 희생하여',NULL,NULL,'He succeeded at the expense of his health.'),
('idiom','mid_3',23,'in the meantime','그 사이에',NULL,NULL,'In the meantime, let us prepare lunch.'),
('idiom','mid_3',23,'under the circumstances','이러한 상황에서',NULL,NULL,'Under the circumstances, we had no choice.'),
('idiom','mid_3',23,'see to it that','~을 확실히 하다',NULL,NULL,'See to it that the door is locked.');

-- ══════════════════════════════════════════════════════════════
-- ── 고등 1학년 (high_1) : 7세트 (set_no 26~32), 140개 ──
-- ══════════════════════════════════════════════════════════════

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
-- Set 26: 내신 필수 구문 1
('idiom','high_1',26,'be bound to','반드시 ~하다',NULL,NULL,'She is bound to succeed.'),
('idiom','high_1',26,'be inclined to','~하는 경향이 있다',NULL,NULL,'He is inclined to agree with you.'),
('idiom','high_1',26,'be obliged to','~할 의무가 있다',NULL,NULL,'We are obliged to follow the rules.'),
('idiom','high_1',26,'be prone to','~하기 쉽다',NULL,NULL,'She is prone to making errors.'),
('idiom','high_1',26,'come to terms with','~을 받아들이다',NULL,NULL,'He finally came to terms with the loss.'),
('idiom','high_1',26,'fall behind','뒤처지다',NULL,NULL,'Do not fall behind in your studies.'),
('idiom','high_1',26,'get the hang of','~의 요령을 터득하다',NULL,NULL,'You will get the hang of it soon.'),
('idiom','high_1',26,'have a say in','~에 발언권이 있다',NULL,NULL,'Everyone should have a say in this.'),
('idiom','high_1',26,'in the wake of','~의 여파로',NULL,NULL,'In the wake of the storm, many trees fell.'),
('idiom','high_1',26,'make ends meet','생계를 꾸려나가다',NULL,NULL,'It is hard to make ends meet these days.'),
('idiom','high_1',26,'narrow down','좁히다, 줄이다',NULL,NULL,'We narrowed down the list to five.'),
('idiom','high_1',26,'pave the way for','~의 길을 열다',NULL,NULL,'Her research paved the way for new treatments.'),
('idiom','high_1',26,'rule out','배제하다',NULL,NULL,'We cannot rule out that possibility.'),
('idiom','high_1',26,'shed light on','~을 밝히다',NULL,NULL,'The study shed light on the issue.'),
('idiom','high_1',26,'take into account','~을 고려하다',NULL,NULL,'Take the cost into account.'),
('idiom','high_1',26,'turn a blind eye to','~을 못 본 척하다',NULL,NULL,'They turned a blind eye to the problem.'),
('idiom','high_1',26,'a far cry from','~와 거리가 먼',NULL,NULL,'This is a far cry from what I expected.'),
('idiom','high_1',26,'at stake','위태로운',NULL,NULL,'Many jobs are at stake.'),
('idiom','high_1',26,'behind the scenes','무대 뒤에서, 비밀리에',NULL,NULL,'A lot of work goes on behind the scenes.'),
('idiom','high_1',26,'beyond one''s reach','손이 닿지 않는',NULL,NULL,'The goal seemed beyond our reach.'),

-- Set 27: 내신 필수 구문 2
('idiom','high_1',27,'break new ground','새로운 분야를 개척하다',NULL,NULL,'This technology breaks new ground.'),
('idiom','high_1',27,'bridge the gap','격차를 줄이다',NULL,NULL,'Education can bridge the gap between rich and poor.'),
('idiom','high_1',27,'catch on','유행하다, 이해하다',NULL,NULL,'The trend quickly caught on.'),
('idiom','high_1',27,'come in handy','유용하다',NULL,NULL,'This tool will come in handy.'),
('idiom','high_1',27,'cut corners','절차를 생략하다, 비용을 줄이다',NULL,NULL,'Do not cut corners on safety.'),
('idiom','high_1',27,'draw the line','선을 긋다, 한계를 정하다',NULL,NULL,'I draw the line at dishonesty.'),
('idiom','high_1',27,'face up to','~에 맞서다',NULL,NULL,'You must face up to the truth.'),
('idiom','high_1',27,'fall short of','~에 미치지 못하다',NULL,NULL,'Sales fell short of expectations.'),
('idiom','high_1',27,'get to the bottom of','~의 진상을 밝히다',NULL,NULL,'We need to get to the bottom of this.'),
('idiom','high_1',27,'give rise to','~을 야기하다',NULL,NULL,'Pollution gives rise to health problems.'),
('idiom','high_1',27,'go out of one''s way','일부러 애쓰다',NULL,NULL,'She went out of her way to help me.'),
('idiom','high_1',27,'hold true','유효하다, 맞다',NULL,NULL,'This rule still holds true today.'),
('idiom','high_1',27,'iron out','(문제를) 해결하다',NULL,NULL,'We need to iron out a few details.'),
('idiom','high_1',27,'keep track of','~을 추적하다',NULL,NULL,'Keep track of your expenses.'),
('idiom','high_1',27,'lay off','해고하다',NULL,NULL,'The company laid off 200 workers.'),
('idiom','high_1',27,'leave out','빠뜨리다, 제외하다',NULL,NULL,'Do not leave out any important details.'),
('idiom','high_1',27,'lose track of','~을 놓치다',NULL,NULL,'I lost track of time while reading.'),
('idiom','high_1',27,'make a point of','반드시 ~하다',NULL,NULL,'She makes a point of exercising daily.'),
('idiom','high_1',27,'miss the point','요점을 놓치다',NULL,NULL,'You are missing the point entirely.'),
('idiom','high_1',27,'on the verge of','막 ~하려는 참인',NULL,NULL,'The company was on the verge of bankruptcy.'),

-- Set 28: 독해 핵심 숙어 1
('idiom','high_1',28,'out of the question','불가능한',NULL,NULL,'A pay raise is out of the question right now.'),
('idiom','high_1',28,'read between the lines','행간의 의미를 파악하다',NULL,NULL,'You need to read between the lines.'),
('idiom','high_1',28,'see eye to eye','의견이 일치하다',NULL,NULL,'We do not always see eye to eye.'),
('idiom','high_1',28,'take a toll on','~에 타격을 주다',NULL,NULL,'Stress takes a toll on your health.'),
('idiom','high_1',28,'think outside the box','창의적으로 생각하다',NULL,NULL,'Try to think outside the box.'),
('idiom','high_1',28,'tip of the iceberg','빙산의 일각',NULL,NULL,'This problem is just the tip of the iceberg.'),
('idiom','high_1',28,'ups and downs','기복, 우여곡절',NULL,NULL,'Life has its ups and downs.'),
('idiom','high_1',28,'with flying colors','큰 성공으로',NULL,NULL,'She passed the test with flying colors.'),
('idiom','high_1',28,'be a matter of','~의 문제이다',NULL,NULL,'It is a matter of time.'),
('idiom','high_1',28,'by virtue of','~ 덕분에',NULL,NULL,'He got the job by virtue of his experience.'),
('idiom','high_1',28,'for good','영원히',NULL,NULL,'She left the country for good.'),
('idiom','high_1',28,'from scratch','처음부터',NULL,NULL,'We built the website from scratch.'),
('idiom','high_1',28,'in lieu of','~ 대신에',NULL,NULL,'He sent a gift in lieu of attending.'),
('idiom','high_1',28,'in one''s shoes','~의 입장에서',NULL,NULL,'Put yourself in my shoes.'),
('idiom','high_1',28,'on the spot','즉석에서, 현장에서',NULL,NULL,'She was hired on the spot.'),
('idiom','high_1',28,'out of nowhere','갑자기, 느닷없이',NULL,NULL,'The idea came out of nowhere.'),
('idiom','high_1',28,'play a role in','~에 역할을 하다',NULL,NULL,'Diet plays a role in good health.'),
('idiom','high_1',28,'prior to','~에 앞서',NULL,NULL,'Prior to the meeting, review the report.'),
('idiom','high_1',28,'wear and tear','마모, 닳음',NULL,NULL,'The carpet shows signs of wear and tear.'),
('idiom','high_1',28,'no strings attached','조건 없이',NULL,NULL,'The offer comes with no strings attached.'),

-- Set 29: 독해 핵심 숙어 2
('idiom','high_1',29,'come to light','밝혀지다',NULL,NULL,'New evidence came to light.'),
('idiom','high_1',29,'comply with','~을 따르다, 준수하다',NULL,NULL,'You must comply with the regulations.'),
('idiom','high_1',29,'consist of','~으로 구성되다',NULL,NULL,'The team consists of five members.'),
('idiom','high_1',29,'contribute to','~에 기여하다',NULL,NULL,'Exercise contributes to good health.'),
('idiom','high_1',29,'cope with','~에 대처하다',NULL,NULL,'He learned to cope with stress.'),
('idiom','high_1',29,'derive from','~에서 비롯되다',NULL,NULL,'The word derives from Latin.'),
('idiom','high_1',29,'distinguish A from B','A와 B를 구별하다',NULL,NULL,'It is hard to distinguish fact from fiction.'),
('idiom','high_1',29,'be entitled to','~할 자격이 있다',NULL,NULL,'You are entitled to a refund.'),
('idiom','high_1',29,'give way to','~에 양보하다',NULL,NULL,'Old methods gave way to new technology.'),
('idiom','high_1',29,'go hand in hand','밀접하게 관련되다',NULL,NULL,'Poverty and crime go hand in hand.'),
('idiom','high_1',29,'have an impact on','~에 영향을 미치다',NULL,NULL,'Social media has an impact on teenagers.'),
('idiom','high_1',29,'impose A on B','A를 B에 부과하다',NULL,NULL,'The government imposed taxes on imports.'),
('idiom','high_1',29,'in conjunction with','~와 함께',NULL,NULL,'The drug works in conjunction with therapy.'),
('idiom','high_1',29,'interfere with','~을 방해하다',NULL,NULL,'Do not interfere with their plans.'),
('idiom','high_1',29,'lead to','~을 야기하다, ~으로 이끌다',NULL,NULL,'Lack of sleep can lead to health issues.'),
('idiom','high_1',29,'on account of','~ 때문에',NULL,NULL,'The game was canceled on account of rain.'),
('idiom','high_1',29,'on the contrary','반대로',NULL,NULL,'On the contrary, I think it is great.'),
('idiom','high_1',29,'refrain from','~을 삼가다',NULL,NULL,'Please refrain from smoking here.'),
('idiom','high_1',29,'resort to','~에 의지하다',NULL,NULL,'Do not resort to violence.'),
('idiom','high_1',29,'prone to','~하기 쉬운',NULL,NULL,'This area is prone to flooding.'),

-- Set 30: 수능 빈출 구문 1
('idiom','high_1',30,'all the more','더욱더',NULL,NULL,'That makes it all the more important.'),
('idiom','high_1',30,'anything but','결코 ~이 아닌',NULL,NULL,'The test was anything but easy.'),
('idiom','high_1',30,'be second to none','누구에게도 뒤지지 않다',NULL,NULL,'Her skills are second to none.'),
('idiom','high_1',30,'boil down to','결국 ~로 귀결되다',NULL,NULL,'It all boils down to money.'),
('idiom','high_1',30,'by and large','대체로',NULL,NULL,'By and large, the plan worked.'),
('idiom','high_1',30,'call into question','~에 의문을 제기하다',NULL,NULL,'The report called the data into question.'),
('idiom','high_1',30,'count on','~에 의지하다',NULL,NULL,'You can always count on me.'),
('idiom','high_1',30,'do justice to','~을 공정하게 평가하다',NULL,NULL,'Photos do not do justice to the scenery.'),
('idiom','high_1',30,'every now and then','때때로',NULL,NULL,'I visit my grandparents every now and then.'),
('idiom','high_1',30,'for the time being','당분간',NULL,NULL,'For the time being, let us wait.'),
('idiom','high_1',30,'go without saying','말할 필요도 없다',NULL,NULL,'It goes without saying that health is important.'),
('idiom','high_1',30,'in a nutshell','요약하면',NULL,NULL,'In a nutshell, we need more funding.'),
('idiom','high_1',30,'in light of','~을 고려하여',NULL,NULL,'In light of the evidence, he was released.'),
('idiom','high_1',30,'in the first place','애초에',NULL,NULL,'Why did you go there in the first place?'),
('idiom','high_1',30,'keep A at bay','A를 저지하다',NULL,NULL,'Exercise keeps illness at bay.'),
('idiom','high_1',30,'leave much to be desired','부족한 점이 많다',NULL,NULL,'His performance left much to be desired.'),
('idiom','high_1',30,'more often than not','대개, 보통',NULL,NULL,'More often than not, she is right.'),
('idiom','high_1',30,'no wonder','~도 당연하다',NULL,NULL,'No wonder you are tired after all that work.'),
('idiom','high_1',30,'nothing but','오직 ~뿐',NULL,NULL,'He is nothing but trouble.'),
('idiom','high_1',30,'now that','~이므로, ~이니',NULL,NULL,'Now that you are here, let us begin.'),

-- Set 31: 수능 빈출 구문 2
('idiom','high_1',31,'on second thought','다시 생각해 보니',NULL,NULL,'On second thought, I will stay home.'),
('idiom','high_1',31,'other than','~ 외에',NULL,NULL,'I have no choice other than to accept.'),
('idiom','high_1',31,'quite a few','꽤 많은',NULL,NULL,'Quite a few students were absent.'),
('idiom','high_1',31,'regardless of','~에 관계없이',NULL,NULL,'We will go regardless of the weather.'),
('idiom','high_1',31,'stem from','~에서 비롯되다',NULL,NULL,'His anger stems from frustration.'),
('idiom','high_1',31,'to the extent that','~하는 한',NULL,NULL,'I agree to the extent that it is fair.'),
('idiom','high_1',31,'under no circumstances','어떤 상황에서도 ~않는',NULL,NULL,'Under no circumstances should you cheat.'),
('idiom','high_1',31,'by the same token','마찬가지로',NULL,NULL,'By the same token, we should help them too.'),
('idiom','high_1',31,'far from','결코 ~이 아닌',NULL,NULL,'The situation is far from ideal.'),
('idiom','high_1',31,'for one thing','우선',NULL,NULL,'For one thing, it is too expensive.'),
('idiom','high_1',31,'let alone','~은 말할 것도 없고',NULL,NULL,'He can barely walk, let alone run.'),
('idiom','high_1',31,'much less','~은 더더욱 아닌',NULL,NULL,'He cannot read English, much less speak it.'),
('idiom','high_1',31,'needless to say','말할 필요도 없이',NULL,NULL,'Needless to say, safety comes first.'),
('idiom','high_1',31,'not to mention','~은 말할 것도 없이',NULL,NULL,'She speaks Korean, not to mention English.'),
('idiom','high_1',31,'to say the least','과소 표현하자면',NULL,NULL,'The experience was unpleasant, to say the least.'),
('idiom','high_1',31,'pertain to','~에 관련되다',NULL,NULL,'This law pertains to all citizens.'),
('idiom','high_1',31,'the odds are','~할 가능성이 높다',NULL,NULL,'The odds are that it will rain.'),
('idiom','high_1',31,'what if','만약 ~라면 어떡하지',NULL,NULL,'What if we miss the train?'),
('idiom','high_1',31,'as it were','말하자면',NULL,NULL,'He is, as it were, a walking dictionary.'),
('idiom','high_1',31,'if anything','오히려, 어찌 되었든',NULL,NULL,'If anything, the problem is getting worse.'),

-- Set 32: 내신 고급 구문
('idiom','high_1',32,'attribute A to B','A를 B의 탓으로 돌리다',NULL,NULL,'She attributed her success to hard work.'),
('idiom','high_1',32,'bear in mind','명심하다',NULL,NULL,'Bear in mind that the deadline is Friday.'),
('idiom','high_1',32,'bring up','기르다, 화제를 꺼내다',NULL,NULL,'She was brought up in a small town.'),
('idiom','high_1',32,'catch up with','~을 따라잡다',NULL,NULL,'I need to catch up with my classmates.'),
('idiom','high_1',32,'come into play','작용하다, 관여하다',NULL,NULL,'Many factors come into play here.'),
('idiom','high_1',32,'do without','~없이 지내다',NULL,NULL,'We cannot do without water.'),
('idiom','high_1',32,'draw on','~을 이용하다',NULL,NULL,'She drew on her experience.'),
('idiom','high_1',32,'embark on','~에 착수하다',NULL,NULL,'They embarked on a new project.'),
('idiom','high_1',32,'fall prey to','~의 희생양이 되다',NULL,NULL,'Many people fall prey to scams.'),
('idiom','high_1',32,'hold on to','~을 고수하다',NULL,NULL,'Hold on to your dreams.'),
('idiom','high_1',32,'in response to','~에 대한 응답으로',NULL,NULL,'In response to complaints, they changed the policy.'),
('idiom','high_1',32,'keep pace with','~에 보조를 맞추다',NULL,NULL,'It is hard to keep pace with technology.'),
('idiom','high_1',32,'lay the groundwork for','~의 토대를 마련하다',NULL,NULL,'This research lays the groundwork for future studies.'),
('idiom','high_1',32,'make way for','~에 길을 비켜주다',NULL,NULL,'Old buildings made way for new ones.'),
('idiom','high_1',32,'on the grounds that','~라는 이유로',NULL,NULL,'He was fired on the grounds that he was dishonest.'),
('idiom','high_1',32,'phase out','단계적으로 폐지하다',NULL,NULL,'They plan to phase out old models.'),
('idiom','high_1',32,'rule of thumb','경험 법칙',NULL,NULL,'As a rule of thumb, save 20 percent of your income.'),
('idiom','high_1',32,'set the stage for','~의 발판을 마련하다',NULL,NULL,'The reforms set the stage for growth.'),
('idiom','high_1',32,'take precedence over','~에 우선하다',NULL,NULL,'Safety takes precedence over speed.'),
('idiom','high_1',32,'touch on','~을 언급하다',NULL,NULL,'The article touched on several key issues.');

-- ══════════════════════════════════════════════════════════════
-- ── 고등 2학년 (high_2) : 8세트 (set_no 26~33), 160개 ──
-- ══════════════════════════════════════════════════════════════

INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
-- Set 26: 수능 핵심 구문 1
('idiom','high_2',26,'at the mercy of','~에 좌우되는',NULL,NULL,'We were at the mercy of the weather.'),
('idiom','high_2',26,'be at a loss','당황하다, 어쩔 줄 모르다',NULL,NULL,'I was at a loss for words.'),
('idiom','high_2',26,'be tantamount to','~와 다름없다',NULL,NULL,'Silence is tantamount to agreement.'),
('idiom','high_2',26,'bring A to a halt','A를 중단시키다',NULL,NULL,'The accident brought traffic to a halt.'),
('idiom','high_2',26,'come to grips with','~을 제대로 다루다',NULL,NULL,'We must come to grips with this problem.'),
('idiom','high_2',26,'dispense with','~없이 해내다',NULL,NULL,'Let us dispense with formalities.'),
('idiom','high_2',26,'fall into place','자리를 잡다, 이해가 되다',NULL,NULL,'Once you study more, things fall into place.'),
('idiom','high_2',26,'gain ground','세력을 얻다',NULL,NULL,'The movement is gaining ground.'),
('idiom','high_2',26,'hit home','뼈를 찌르다, 실감하다',NULL,NULL,'His words really hit home.'),
('idiom','high_2',26,'in the face of','~에 직면하여',NULL,NULL,'She remained calm in the face of danger.'),
('idiom','high_2',26,'jump to conclusions','성급한 결론을 내리다',NULL,NULL,'Do not jump to conclusions.'),
('idiom','high_2',26,'leave no stone unturned','모든 수단을 동원하다',NULL,NULL,'The police left no stone unturned.'),
('idiom','high_2',26,'miss the boat','기회를 놓치다',NULL,NULL,'If you wait too long, you will miss the boat.'),
('idiom','high_2',26,'on thin ice','위태로운 상황에',NULL,NULL,'He is skating on thin ice with the boss.'),
('idiom','high_2',26,'pull strings','배후에서 조종하다',NULL,NULL,'She pulled some strings to get the job.'),
('idiom','high_2',26,'ring a bell','기억이 나다',NULL,NULL,'Does his name ring a bell?'),
('idiom','high_2',26,'scratch the surface','피상적으로 다루다',NULL,NULL,'We have only scratched the surface of this issue.'),
('idiom','high_2',26,'take the plunge','과감히 시작하다',NULL,NULL,'She took the plunge and started her own business.'),
('idiom','high_2',26,'the bottom line','핵심, 결론',NULL,NULL,'The bottom line is that we need more time.'),
('idiom','high_2',26,'by no stretch of imagination','아무리 해도 ~이 아닌',NULL,NULL,'By no stretch of imagination is this fair.'),

-- Set 27: 수능 핵심 구문 2
('idiom','high_2',27,'add insult to injury','설상가상으로',NULL,NULL,'To add insult to injury, it started to rain.'),
('idiom','high_2',27,'beat around the bush','돌려서 말하다',NULL,NULL,'Stop beating around the bush and tell me.'),
('idiom','high_2',27,'bite off more than one can chew','능력 이상의 일을 벌이다',NULL,NULL,'He bit off more than he could chew.'),
('idiom','high_2',27,'break the ice','어색한 분위기를 깨다',NULL,NULL,'A joke helped break the ice.'),
('idiom','high_2',27,'burn the midnight oil','밤늦게까지 공부하다',NULL,NULL,'She burned the midnight oil before the exam.'),
('idiom','high_2',27,'call it a day','마무리하다',NULL,NULL,'Let us call it a day and go home.'),
('idiom','high_2',27,'cross one''s mind','문득 떠오르다',NULL,NULL,'It never crossed my mind.'),
('idiom','high_2',27,'get cold feet','겁을 먹다',NULL,NULL,'He got cold feet before the speech.'),
('idiom','high_2',27,'give the benefit of the doubt','일단 믿어주다',NULL,NULL,'I will give him the benefit of the doubt.'),
('idiom','high_2',27,'go the extra mile','한층 더 노력하다',NULL,NULL,'She always goes the extra mile.'),
('idiom','high_2',27,'have a change of heart','마음을 바꾸다',NULL,NULL,'He had a change of heart about the plan.'),
('idiom','high_2',27,'hit the nail on the head','정곡을 찌르다',NULL,NULL,'You hit the nail on the head.'),
('idiom','high_2',27,'in the nick of time','아슬아슬하게 제시간에',NULL,NULL,'We arrived in the nick of time.'),
('idiom','high_2',27,'keep one''s fingers crossed','행운을 빌다',NULL,NULL,'Keep your fingers crossed for me.'),
('idiom','high_2',27,'make a mountain out of a molehill','침소봉대하다',NULL,NULL,'You are making a mountain out of a molehill.'),
('idiom','high_2',27,'nip in the bud','싹을 자르다, 미연에 방지하다',NULL,NULL,'We must nip this problem in the bud.'),
('idiom','high_2',27,'once and for all','이번에 확실히',NULL,NULL,'Let us settle this once and for all.'),
('idiom','high_2',27,'pull one''s weight','자기 몫을 다하다',NULL,NULL,'Everyone needs to pull their weight.'),
('idiom','high_2',27,'see the big picture','큰 그림을 보다',NULL,NULL,'Try to see the big picture.'),
('idiom','high_2',27,'lose one''s train of thought','생각의 흐름을 잃다',NULL,NULL,'I lost my train of thought.'),

-- Set 28: 수능 빈출 표현 1
('idiom','high_2',28,'a blessing in disguise','전화위복',NULL,NULL,'Losing that job was a blessing in disguise.'),
('idiom','high_2',28,'be cut out for','~에 적합하다',NULL,NULL,'She is cut out for this job.'),
('idiom','high_2',28,'be in the dark','모르고 있다',NULL,NULL,'We were kept in the dark about the plan.'),
('idiom','high_2',28,'by the skin of one''s teeth','간신히',NULL,NULL,'He passed by the skin of his teeth.'),
('idiom','high_2',28,'catch one''s eye','눈길을 끌다',NULL,NULL,'The red dress caught my eye.'),
('idiom','high_2',28,'down to earth','현실적인',NULL,NULL,'Despite her fame, she is very down to earth.'),
('idiom','high_2',28,'food for thought','생각할 거리',NULL,NULL,'The lecture gave us food for thought.'),
('idiom','high_2',28,'get the ball rolling','시작하다, 착수하다',NULL,NULL,'Let us get the ball rolling on this project.'),
('idiom','high_2',28,'go back to the drawing board','처음부터 다시 시작하다',NULL,NULL,'Our plan failed, so we went back to the drawing board.'),
('idiom','high_2',28,'have a stake in','~에 이해관계가 있다',NULL,NULL,'Everyone has a stake in the environment.'),
('idiom','high_2',28,'in a bind','곤란한 상황에',NULL,NULL,'We are in a bind without enough funds.'),
('idiom','high_2',28,'keep a low profile','눈에 띄지 않게 행동하다',NULL,NULL,'He kept a low profile after the scandal.'),
('idiom','high_2',28,'lose ground','세력을 잃다, 뒤처지다',NULL,NULL,'The company is losing ground to competitors.'),
('idiom','high_2',28,'make headway','진전을 이루다',NULL,NULL,'We are making headway on the project.'),
('idiom','high_2',28,'off the top of one''s head','즉석에서, 생각나는 대로',NULL,NULL,'Off the top of my head, I would say yes.'),
('idiom','high_2',28,'out of one''s depth','감당할 수 없는',NULL,NULL,'I felt out of my depth in that meeting.'),
('idiom','high_2',28,'pass the buck','책임을 전가하다',NULL,NULL,'Do not pass the buck to someone else.'),
('idiom','high_2',28,'play it by ear','임기응변으로 하다',NULL,NULL,'We do not have a plan, so let us play it by ear.'),
('idiom','high_2',28,'put one''s foot down','단호하게 나서다',NULL,NULL,'She put her foot down and refused.'),
('idiom','high_2',28,'take a back seat','뒷전으로 물러나다',NULL,NULL,'His career took a back seat to family.'),

-- Set 29: 수능 빈출 표현 2
('idiom','high_2',29,'at cross purposes','서로 어긋나게',NULL,NULL,'We seem to be talking at cross purposes.'),
('idiom','high_2',29,'be in the same boat','같은 처지에 있다',NULL,NULL,'We are all in the same boat.'),
('idiom','high_2',29,'bend over backwards','온갖 노력을 다하다',NULL,NULL,'She bent over backwards to please them.'),
('idiom','high_2',29,'burn bridges','퇴로를 끊다',NULL,NULL,'Do not burn your bridges.'),
('idiom','high_2',29,'cast doubt on','~에 의심을 던지다',NULL,NULL,'New data cast doubt on the theory.'),
('idiom','high_2',29,'cut to the chase','본론으로 들어가다',NULL,NULL,'Let us cut to the chase.'),
('idiom','high_2',29,'drive home','강조하다, 확실히 이해시키다',NULL,NULL,'The teacher drove home the importance of reading.'),
('idiom','high_2',29,'fall through','무산되다, 실패하다',NULL,NULL,'The deal fell through at the last minute.'),
('idiom','high_2',29,'from the ground up','처음부터 완전히',NULL,NULL,'They rebuilt the company from the ground up.'),
('idiom','high_2',29,'get one''s act together','정신을 차리다',NULL,NULL,'You need to get your act together.'),
('idiom','high_2',29,'in the long haul','장기적으로',NULL,NULL,'Patience pays off in the long haul.'),
('idiom','high_2',29,'keep tabs on','~을 주시하다',NULL,NULL,'The manager keeps tabs on progress.'),
('idiom','high_2',29,'level the playing field','공정한 조건을 만들다',NULL,NULL,'Technology can level the playing field.'),
('idiom','high_2',29,'make or break','성패를 가르는',NULL,NULL,'This project is a make-or-break moment.'),
('idiom','high_2',29,'off the beaten path','남들이 가지 않는 길로',NULL,NULL,'We found a restaurant off the beaten path.'),
('idiom','high_2',29,'paint a picture','묘사하다, 상황을 설명하다',NULL,NULL,'The report paints a grim picture.'),
('idiom','high_2',29,'raise the bar','기준을 높이다',NULL,NULL,'This invention raised the bar for quality.'),
('idiom','high_2',29,'set in stone','확정된, 변경 불가능한',NULL,NULL,'The schedule is not set in stone.'),
('idiom','high_2',29,'think on one''s feet','순발력 있게 대처하다',NULL,NULL,'A good leader can think on their feet.'),
('idiom','high_2',29,'have a bone to pick with','~에게 따질 것이 있다',NULL,NULL,'I have a bone to pick with you.'),

-- Set 30: 고급 논술 구문 1
('idiom','high_2',30,'above and beyond','기대 이상으로',NULL,NULL,'She went above and beyond her duties.'),
('idiom','high_2',30,'a double-edged sword','양날의 검',NULL,NULL,'Social media is a double-edged sword.'),
('idiom','high_2',30,'at the forefront of','~의 최전선에',NULL,NULL,'Korea is at the forefront of technology.'),
('idiom','high_2',30,'back to square one','원점으로 돌아가다',NULL,NULL,'The project failed, and we are back to square one.'),
('idiom','high_2',30,'be up in the air','미정이다, 결정되지 않다',NULL,NULL,'Our travel plans are still up in the air.'),
('idiom','high_2',30,'blow out of proportion','과장하다',NULL,NULL,'The media blew the story out of proportion.'),
('idiom','high_2',30,'bring to the table','(논의에) 기여하다',NULL,NULL,'What do you bring to the table?'),
('idiom','high_2',30,'err on the side of caution','조심하는 쪽을 택하다',NULL,NULL,'Let us err on the side of caution.'),
('idiom','high_2',30,'fall by the wayside','도태되다, 중단되다',NULL,NULL,'Many good ideas fall by the wayside.'),
('idiom','high_2',30,'give and take','양보, 타협',NULL,NULL,'A relationship requires give and take.'),
('idiom','high_2',30,'have the upper hand','우위에 있다',NULL,NULL,'Technology gives humans the upper hand.'),
('idiom','high_2',30,'in a league of one''s own','독보적인',NULL,NULL,'Her talent is in a league of its own.'),
('idiom','high_2',30,'keep at arm''s length','거리를 두다',NULL,NULL,'He keeps everyone at arm''s length.'),
('idiom','high_2',30,'leave a mark on','~에 흔적을 남기다',NULL,NULL,'Great leaders leave a mark on history.'),
('idiom','high_2',30,'move the goalposts','규칙을 바꾸다',NULL,NULL,'They keep moving the goalposts.'),
('idiom','high_2',30,'open a can of worms','골치 아픈 문제를 건드리다',NULL,NULL,'That question opened a can of worms.'),
('idiom','high_2',30,'paradigm shift','패러다임의 전환',NULL,NULL,'AI represents a paradigm shift in education.'),
('idiom','high_2',30,'catch-22','진퇴양난',NULL,NULL,'It is a catch-22 situation.'),
('idiom','high_2',30,'devil''s advocate','반대 입장을 취하는 사람',NULL,NULL,'Let me play devil''s advocate for a moment.'),
('idiom','high_2',30,'status quo','현 상태',NULL,NULL,'They want to maintain the status quo.'),

-- Set 31: 고급 논술 구문 2
('idiom','high_2',31,'push the envelope','한계를 넓히다',NULL,NULL,'Scientists push the envelope of knowledge.'),
('idiom','high_2',31,'show one''s true colors','본색을 드러내다',NULL,NULL,'He showed his true colors under pressure.'),
('idiom','high_2',31,'slip through the cracks','간과되다',NULL,NULL,'Some students slip through the cracks.'),
('idiom','high_2',31,'stand the test of time','시간의 시험을 견디다',NULL,NULL,'Great literature stands the test of time.'),
('idiom','high_2',31,'strike a balance','균형을 맞추다',NULL,NULL,'We must strike a balance between work and life.'),
('idiom','high_2',31,'take with a grain of salt','반신반의하다',NULL,NULL,'Take his advice with a grain of salt.'),
('idiom','high_2',31,'the elephant in the room','모두가 아는 불편한 진실',NULL,NULL,'Climate change is the elephant in the room.'),
('idiom','high_2',31,'turn over a new leaf','새 출발을 하다',NULL,NULL,'He decided to turn over a new leaf.'),
('idiom','high_2',31,'under the radar','눈에 띄지 않게',NULL,NULL,'The issue has flown under the radar.'),
('idiom','high_2',31,'vicious circle','악순환',NULL,NULL,'Poverty creates a vicious circle.'),
('idiom','high_2',31,'walk on eggshells','조심조심하다',NULL,NULL,'Everyone walks on eggshells around him.'),
('idiom','high_2',31,'water under the bridge','지나간 일',NULL,NULL,'That is all water under the bridge now.'),
('idiom','high_2',31,'weather the storm','어려움을 견뎌내다',NULL,NULL,'The company weathered the financial storm.'),
('idiom','high_2',31,'word of mouth','입소문',NULL,NULL,'The restaurant grew popular by word of mouth.'),
('idiom','high_2',31,'wrap one''s head around','~을 이해하다',NULL,NULL,'I cannot wrap my head around this concept.'),
('idiom','high_2',31,'zero in on','~에 집중하다',NULL,NULL,'Let us zero in on the main problem.'),
('idiom','high_2',31,'rub salt in the wound','상처에 소금을 뿌리다',NULL,NULL,'Do not rub salt in the wound.'),
('idiom','high_2',31,'throw in the towel','포기하다',NULL,NULL,'He was tempted to throw in the towel.'),
('idiom','high_2',31,'carte blanche','전권, 백지수표',NULL,NULL,'She was given carte blanche to redesign the office.'),
('idiom','high_2',31,'modus operandi','행동 방식',NULL,NULL,'Deception is his modus operandi.'),

-- Set 32: 수능 고난도 1
('idiom','high_2',32,'a foregone conclusion','이미 정해진 결론',NULL,NULL,'The result was a foregone conclusion.'),
('idiom','high_2',32,'at the drop of a hat','즉시, 주저 없이',NULL,NULL,'She would help at the drop of a hat.'),
('idiom','high_2',32,'bark up the wrong tree','헛다리 짚다',NULL,NULL,'If you blame me, you are barking up the wrong tree.'),
('idiom','high_2',32,'be beside the point','요점을 벗어나다',NULL,NULL,'That argument is beside the point.'),
('idiom','high_2',32,'carry weight','영향력이 있다',NULL,NULL,'Her opinion carries a lot of weight.'),
('idiom','high_2',32,'come full circle','원점으로 돌아오다',NULL,NULL,'Fashion trends always come full circle.'),
('idiom','high_2',32,'cut both ways','양면성이 있다',NULL,NULL,'Freedom of speech cuts both ways.'),
('idiom','high_2',32,'face the music','결과를 감수하다',NULL,NULL,'You must face the music for your actions.'),
('idiom','high_2',32,'get wind of','~의 소식을 듣다',NULL,NULL,'He got wind of the plan to fire him.'),
('idiom','high_2',32,'go against the grain','본성에 어긋나다',NULL,NULL,'Following orders goes against his grain.'),
('idiom','high_2',32,'have one''s hands tied','어찌할 도리가 없다',NULL,NULL,'I would help, but my hands are tied.'),
('idiom','high_2',32,'in hindsight','돌이켜 보면',NULL,NULL,'In hindsight, I should have studied harder.'),
('idiom','high_2',32,'jump on the bandwagon','유행에 편승하다',NULL,NULL,'Many companies jumped on the AI bandwagon.'),
('idiom','high_2',32,'keep one''s options open','선택의 여지를 남기다',NULL,NULL,'I am keeping my options open for now.'),
('idiom','high_2',32,'let the cat out of the bag','비밀을 누설하다',NULL,NULL,'Who let the cat out of the bag?'),
('idiom','high_2',32,'move heaven and earth','온갖 노력을 다하다',NULL,NULL,'She moved heaven and earth to find a cure.'),
('idiom','high_2',32,'on the fence','결정을 못 하는',NULL,NULL,'I am still on the fence about the offer.'),
('idiom','high_2',32,'play devil''s advocate','일부러 반대 의견을 내다',NULL,NULL,'Let me play devil''s advocate here.'),
('idiom','high_2',32,'read the room','분위기를 파악하다',NULL,NULL,'A good speaker knows how to read the room.'),
('idiom','high_2',32,'dog-eat-dog','치열한 경쟁의',NULL,NULL,'It is a dog-eat-dog world in business.'),

-- Set 33: 수능 고난도 2
('idiom','high_2',33,'add fuel to the fire','불에 기름을 붓다',NULL,NULL,'His comment added fuel to the fire.'),
('idiom','high_2',33,'at one''s wit''s end','어쩔 줄 모르는',NULL,NULL,'I am at my wit''s end with this problem.'),
('idiom','high_2',33,'back against the wall','궁지에 몰린',NULL,NULL,'With his back against the wall, he fought harder.'),
('idiom','high_2',33,'bite the bullet','이를 악물고 하다',NULL,NULL,'Sometimes you just have to bite the bullet.'),
('idiom','high_2',33,'break the mold','틀을 깨다',NULL,NULL,'This artist truly broke the mold.'),
('idiom','high_2',33,'do a double take','깜짝 놀라 다시 보다',NULL,NULL,'I did a double take when I saw the price.'),
('idiom','high_2',33,'get one''s feet wet','첫발을 내딛다',NULL,NULL,'Start small and get your feet wet.'),
('idiom','high_2',33,'go down the drain','허사가 되다',NULL,NULL,'All our effort went down the drain.'),
('idiom','high_2',33,'have an axe to grind','숨은 목적이 있다',NULL,NULL,'He has an axe to grind with the company.'),
('idiom','high_2',33,'in one fell swoop','단번에',NULL,NULL,'She solved three problems in one fell swoop.'),
('idiom','high_2',33,'keep up appearances','체면을 유지하다',NULL,NULL,'They kept up appearances despite their troubles.'),
('idiom','high_2',33,'learn the ropes','요령을 배우다',NULL,NULL,'It took time to learn the ropes.'),
('idiom','high_2',33,'meet halfway','서로 양보하다',NULL,NULL,'Let us meet each other halfway.'),
('idiom','high_2',33,'piece of cake','아주 쉬운 일',NULL,NULL,'The exam was a piece of cake.'),
('idiom','high_2',33,'put all one''s eggs in one basket','한 곳에 올인하다',NULL,NULL,'Do not put all your eggs in one basket.'),
('idiom','high_2',33,'the last straw','한계를 넘게 하는 마지막 사건',NULL,NULL,'That mistake was the last straw.'),
('idiom','high_2',33,'turn the tide','형세를 역전시키다',NULL,NULL,'One decision can turn the tide.'),
('idiom','high_2',33,'no-brainer','당연한 결정',NULL,NULL,'Accepting the scholarship was a no-brainer.'),
('idiom','high_2',33,'catch wind of','~의 소식을 접하다',NULL,NULL,'The press caught wind of the scandal.'),
('idiom','high_2',33,'a hard pill to swallow','받아들이기 어려운 사실',NULL,NULL,'The truth was a hard pill to swallow.');
