-- ============================================================
-- 중1 예문 UPDATE SQL
-- Supabase SQL Editor에서 실행하세요 (여러 번 나눠서 실행 가능)
-- ============================================================

-- [mid_1] 중등 1학년 (8~12단어)
UPDATE words SET example_sentence = 'Good preparation helps you feel ready for any test.' WHERE word = 'preparation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Our family has a tradition of eating together on holidays.' WHERE word = 'tradition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She showed great leadership as the class president.' WHERE word = 'leadership' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher waited for a response from the students.' WHERE word = 'response' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The expense of the school trip was not too high.' WHERE word = 'expense' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The development of new technology changes our daily lives.' WHERE word = 'development' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Kindness is an important characteristic of a good friend.' WHERE word = 'characteristic' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The scientist tested the theory with a simple experiment.' WHERE word = 'theory' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The company will launch a new product next month.' WHERE word = 'launch' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She has a large collection of stamps from around the world.' WHERE word = 'collection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The view from the top of the mountain was amazing.' WHERE word = 'amazing' AND level = 'mid_1';
UPDATE words SET example_sentence = 'An adaptable person can handle changes easily.' WHERE word = 'adaptable' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Making a big decision takes time and careful thought.' WHERE word = 'decision' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Our flight to Jeju takes about one hour.' WHERE word = 'flight' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The editor checked the article before it was printed.' WHERE word = 'editor' AND level = 'mid_1';
UPDATE words SET example_sentence = 'It is unusual to see snow in April.' WHERE word = 'unusual' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We use electricity to power our lights and computers.' WHERE word = 'electricity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The students had high expectations for the school trip.' WHERE word = 'expectation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The store offers a wide variety of fruits and snacks.' WHERE word = 'variety' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Your participation in class activities is very important.' WHERE word = 'participation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'In biology class, we learned about plants and animals.' WHERE word = 'biology' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Korea gained its independence on August 15, 1945.' WHERE word = 'independence' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The quality of this bag is much better than the old one.' WHERE word = 'quality' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The first trial of the experiment did not go well.' WHERE word = 'trial' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher used an instructional video for the lesson.' WHERE word = 'instructional' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The government makes laws to keep people safe.' WHERE word = 'government' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I had a long conversation with my friend after school.' WHERE word = 'conversation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The store manager helped the customer find the right item.' WHERE word = 'manager' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She shared her thought about the book with the class.' WHERE word = 'thought' AND level = 'mid_1';
UPDATE words SET example_sentence = 'That is a private affair and not our business.' WHERE word = 'affair' AND level = 'mid_1';
UPDATE words SET example_sentence = 'His quick reaction to the ball saved the game.' WHERE word = 'reaction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Innovation in science has made our lives easier.' WHERE word = 'innovation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A strong foundation is needed to build a tall building.' WHERE word = 'foundation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The payment for the meal was made by credit card.' WHERE word = 'payment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Our school team won the basketball championship!' WHERE word = 'championship' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Both sides reached an agreement after a long talk.' WHERE word = 'agreement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The first item on the agenda is the school festival.' WHERE word = 'agenda' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She could not hide her excitement about the trip.' WHERE word = 'excitement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'My uncle started his own business last year.' WHERE word = 'business' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The aircraft flew high above the clouds.' WHERE word = 'aircraft' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A careful inspection of the car showed no problems.' WHERE word = 'inspection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We bought a new electric fan for the summer.' WHERE word = 'electric' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The astronaut''s mission was to study the moon.' WHERE word = 'mission' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We had a party for my parents'' wedding anniversary.' WHERE word = 'anniversary' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The national flag flies in front of our school.' WHERE word = 'national' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A hammer is a useful tool for building things.' WHERE word = 'tool' AND level = 'mid_1';
UPDATE words SET example_sentence = 'People have known about the existence of stars for ages.' WHERE word = 'existence' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Teaching is a noble profession that helps many people.' WHERE word = 'profession' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The restaurant has a good reputation for tasty food.' WHERE word = 'reputation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The violin is a beautiful musical instrument.' WHERE word = 'instrument' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The school made an announcement about the new rules.' WHERE word = 'announcement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Each candidate gave a speech in front of the school.' WHERE word = 'candidate' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Koreans traditionally eat tteok on New Year''s Day.' WHERE word = 'traditionally' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The dance performance at the festival was wonderful.' WHERE word = 'performance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Taking care of a pet is a big responsibility.' WHERE word = 'responsibility' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I read an interesting article about space travel.' WHERE word = 'article' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her belief in herself helped her succeed.' WHERE word = 'belief' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We finally finished the project after three weeks.' WHERE word = 'finally' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The evolution of phones from big to small is amazing.' WHERE word = 'evolution' AND level = 'mid_1';
UPDATE words SET example_sentence = 'You need a membership card to use the gym.' WHERE word = 'membership' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Welcome to our school! We are happy to have you.' WHERE word = 'welcome' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We did an experiment to see how plants grow.' WHERE word = 'experiment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Please choose one topic for your essay.' WHERE word = 'choose' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The biological clock of our body tells us when to sleep.' WHERE word = 'biological' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The bus passenger sat quietly and read a book.' WHERE word = 'passenger' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The water level of the river rises when it rains.' WHERE word = 'level' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Do not judge people only by their appearance.' WHERE word = 'appearance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The discovery of a new planet was big news.' WHERE word = 'discovery' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Exercise is beneficial for both your body and mind.' WHERE word = 'beneficial' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Hard work is the key to success in life.' WHERE word = 'success' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The school administration decided to change the schedule.' WHERE word = 'administration' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Safety should always be the top priority.' WHERE word = 'priority' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Today''s topic for discussion is climate change.' WHERE word = 'topic' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Sometimes dreams feel real, but they are not reality.' WHERE word = 'reality' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I believe that honesty is the best way to live.' WHERE word = 'believe' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The difficulty of the math test surprised everyone.' WHERE word = 'difficulty' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Graduation day is a special occasion for students.' WHERE word = 'occasion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher asked us to use a reference book.' WHERE word = 'reference' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The story takes place in a beautiful mountain setting.' WHERE word = 'setting' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A careful analysis of the data gave us the answer.' WHERE word = 'analysis' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Car insurance can help when there is an accident.' WHERE word = 'insurance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The doctor took an x-ray of her broken arm.' WHERE word = 'x-ray' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Seoul is an attractive city for tourists.' WHERE word = 'attractive' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He is athletic and plays many sports well.' WHERE word = 'athletic' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Close observation of nature teaches us many things.' WHERE word = 'observation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'There is a speed limit on every road for safety.' WHERE word = 'limit' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We should take good care of our health.' WHERE word = 'care' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Cooperation between team members leads to success.' WHERE word = 'cooperation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The school is about two kilometers from my house.' WHERE word = 'kilometer' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Did you notice the new painting on the wall?' WHERE word = 'notice' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Good teaching can change a student''s life.' WHERE word = 'teaching' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A large percentage of students passed the test.' WHERE word = 'percentage' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Communication is important for working in a team.' WHERE word = 'communication' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Positive interaction with friends makes school fun.' WHERE word = 'interaction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'In conclusion, reading helps us learn new things.' WHERE word = 'conclusion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Adaptability is needed when you move to a new school.' WHERE word = 'adaptability' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We had a class discussion about the environment.' WHERE word = 'discussion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She got a promotion at work because of her hard effort.' WHERE word = 'promotion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Our ancestors lived in a very different world.' WHERE word = 'ancestor' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The main attraction of the park is the big lake.' WHERE word = 'attraction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The advancement of science helps solve many problems.' WHERE word = 'advancement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Regular exercise can prevent many kinds of disease.' WHERE word = 'disease' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The patient made a full recovery after the operation.' WHERE word = 'recovery' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We need to understand the situation before we act.' WHERE word = 'situation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'It is normal to feel nervous before a big test.' WHERE word = 'normal' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A teenager goes through many changes in life.' WHERE word = 'teenager' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Please read the first chapter of the book tonight.' WHERE word = 'chapter' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Classical music can help you focus while studying.' WHERE word = 'classical' AND level = 'mid_1';
UPDATE words SET example_sentence = 'There is great anticipation for the school festival.' WHERE word = 'anticipation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher gave a demonstration of the experiment.' WHERE word = 'demonstration' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We have a weekly meeting every Monday morning.' WHERE word = 'weekly' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her strong presence made everyone listen carefully.' WHERE word = 'presence' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I read the biography of a famous scientist.' WHERE word = 'biography' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She sent an application to the art school.' WHERE word = 'application' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The construction of the new school building took a year.' WHERE word = 'construction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Good writing skills are needed for many jobs.' WHERE word = 'writing' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The owner of the shop is very friendly.' WHERE word = 'owner' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Swimming is a great outdoor activity for summer.' WHERE word = 'activity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The definition of this word is in the dictionary.' WHERE word = 'definition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I check my schedule every morning before school.' WHERE word = 'schedule' AND level = 'mid_1';
UPDATE words SET example_sentence = 'True wealth is not only about money but also health.' WHERE word = 'wealth' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Adaptation to a new place takes time and effort.' WHERE word = 'adaptation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The architecture of the old temple was beautiful.' WHERE word = 'architecture' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Teachers explain the importance of studying every day.' WHERE word = 'importance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Follow the instruction on the box to build the toy.' WHERE word = 'instruction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We need a large quantity of paper for the project.' WHERE word = 'quantity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The customer asked for help finding the right size.' WHERE word = 'customer' AND level = 'mid_1';
UPDATE words SET example_sentence = 'One requirement for the club is to attend every meeting.' WHERE word = 'requirement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The architect designed the new library for the city.' WHERE word = 'architect' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She wants to go to college to study medicine.' WHERE word = 'college' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We study literature to understand stories and poems.' WHERE word = 'literature' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Hot and cold are opposite words.' WHERE word = 'opposite' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The arrival of spring makes the flowers bloom.' WHERE word = 'arrival' AND level = 'mid_1';
UPDATE words SET example_sentence = 'You need permission from your parents to join the trip.' WHERE word = 'permission' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The customer made a complaint about the cold food.' WHERE word = 'complaint' AND level = 'mid_1';
UPDATE words SET example_sentence = 'My grandmother has a lot of wisdom to share.' WHERE word = 'wisdom' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Every vehicle must stop at the red light.' WHERE word = 'vehicle' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Force is needed to push a heavy box.' WHERE word = 'force' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We learn from failure as much as from success.' WHERE word = 'failure' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Knowledge is the greatest treasure a person can have.' WHERE word = 'knowledge' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The delivery of the package will take three days.' WHERE word = 'delivery' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Daily practice is the best way to improve your skills.' WHERE word = 'practice' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The sign gave a warning about the slippery road.' WHERE word = 'warning' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Korea is a beautiful country with four seasons.' WHERE word = 'country' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We buy vegetables at the local market.' WHERE word = 'local' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She opened a bank account to save her money.' WHERE word = 'account' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The wedding ceremony was held in a garden.' WHERE word = 'wedding' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher gave an example to explain the rule.' WHERE word = 'example' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The temperature is thirty degrees outside today.' WHERE word = 'degree' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The whole town joined the celebration of the holiday.' WHERE word = 'celebration' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We can find a lot of information on the internet.' WHERE word = 'information' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The environmental movement is growing around the world.' WHERE word = 'movement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We arrive at school before eight every morning.' WHERE word = 'arrive' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This chair is very comfortable to sit in.' WHERE word = 'comfortable' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Admission to the museum is free for students.' WHERE word = 'admission' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Math is my favorite subject at school.' WHERE word = 'subject' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The combination of red and blue makes purple.' WHERE word = 'combination' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Gold and silver are types of metal.' WHERE word = 'metal' AND level = 'mid_1';
UPDATE words SET example_sentence = 'English is an international language used everywhere.' WHERE word = 'international' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The loss of the game made the team feel sad.' WHERE word = 'loss' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The completion of the project took two months.' WHERE word = 'completion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We should speak in a polite manner to others.' WHERE word = 'manner' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Winning the award was a great achievement for her.' WHERE word = 'achievement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The location of the new park is near the river.' WHERE word = 'location' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A comparison of the two shows which one is better.' WHERE word = 'comparison' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Students have access to the library every day.' WHERE word = 'access' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Raising awareness about the environment is important.' WHERE word = 'awareness' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Thomas Edison helped invent the light bulb.' WHERE word = 'invent' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The long journey across the country took three days.' WHERE word = 'journey' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The protection of wildlife is everyone''s duty.' WHERE word = 'protection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The theme of the story is the power of friendship.' WHERE word = 'theme' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her original painting was different from all the others.' WHERE word = 'original' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The traveler visited many countries in one year.' WHERE word = 'traveler' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Everyone makes a mistake from time to time.' WHERE word = 'mistake' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The team celebrated their victory with a big party.' WHERE word = 'victory' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Hanbok is a traditional Korean dress.' WHERE word = 'traditional' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She joined the volunteers'' association at school.' WHERE word = 'association' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The reason I was late is that I missed the bus.' WHERE word = 'reason' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A cooperative attitude helps the team work better.' WHERE word = 'cooperative' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I have a happy memory of my first day at school.' WHERE word = 'memory' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He received recognition for his hard work at school.' WHERE word = 'recognition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Advertising helps people learn about new products.' WHERE word = 'advertising' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I agree with your idea for the school project.' WHERE word = 'agree' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She took the initiative to start a recycling program.' WHERE word = 'initiative' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Water is necessary for all living things to survive.' WHERE word = 'necessary' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Creativity is important when solving new problems.' WHERE word = 'creativity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She found a good partner for the science project.' WHERE word = 'partner' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A healthy lifestyle includes exercise and good food.' WHERE word = 'lifestyle' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Many students volunteer to help at the hospital.' WHERE word = 'volunteer' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He made an offer to help carry the heavy boxes.' WHERE word = 'offer' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Good management of time helps you finish work early.' WHERE word = 'management' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her dedication to studying helped her get top grades.' WHERE word = 'dedication' AND level = 'mid_1';
UPDATE words SET example_sentence = 'My intention is to finish reading this book by Friday.' WHERE word = 'intention' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A good understanding of the rules makes the game fair.' WHERE word = 'understanding' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Quiet reflection helps us learn from our mistakes.' WHERE word = 'reflection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'It is an honor to receive this award from the school.' WHERE word = 'honor' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The building was built over a century ago.' WHERE word = 'century' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her vision is to create a better world for children.' WHERE word = 'vision' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This robot is a model of the one used in factories.' WHERE word = 'model' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The description of the character was very detailed.' WHERE word = 'description' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The building is the tallest one in the city.' WHERE word = 'building' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She has a strong interest in art and music.' WHERE word = 'interest' AND level = 'mid_1';
UPDATE words SET example_sentence = 'In general, most students enjoy field trips.' WHERE word = 'general' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This game is both fun and educational.' WHERE word = 'educational' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Please leave a message after the sound.' WHERE word = 'message' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher asked us to order the books by number.' WHERE word = 'order' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We flew to Busan on a small airline.' WHERE word = 'airline' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Public transportation like buses helps people get around.' WHERE word = 'transportation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This school sets a high standard for its students.' WHERE word = 'standard' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The comfort of this new chair is really nice.' WHERE word = 'comfort' AND level = 'mid_1';
UPDATE words SET example_sentence = 'You need a good balance between study and play.' WHERE word = 'balance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The customer service at this store is excellent.' WHERE word = 'service' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The surface of the moon has many holes.' WHERE word = 'surface' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Learning a new language is a big challenge.' WHERE word = 'challenge' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A typical school day starts at eight thirty.' WHERE word = 'typical' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The treatment for the cold takes about a week.' WHERE word = 'treatment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Our school organization helps plan events and trips.' WHERE word = 'organization' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I especially like math because it is like a puzzle.' WHERE word = 'especially' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The news station will broadcast the game live tonight.' WHERE word = 'broadcast' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Please fill out this form with your name and address.' WHERE word = 'form' AND level = 'mid_1';
UPDATE words SET example_sentence = 'One advantage of reading is that it builds knowledge.' WHERE word = 'advantage' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Every employee at the company works very hard.' WHERE word = 'employee' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Thank you for your helpful suggestion.' WHERE word = 'suggestion' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This is a great opportunity to learn something new.' WHERE word = 'opportunity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The atmosphere at the party was warm and happy.' WHERE word = 'atmosphere' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her kindness made everyone around her feel welcome.' WHERE word = 'kindness' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The proposal for a new park was accepted by the city.' WHERE word = 'proposal' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A symbol of peace is the white dove.' WHERE word = 'symbol' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The landscape of the countryside is very peaceful.' WHERE word = 'landscape' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Students prepare hard for the final examination.' WHERE word = 'examination' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The author of this book is a famous Korean writer.' WHERE word = 'author' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The economic situation of the country is improving.' WHERE word = 'economic' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Science is a branch of knowledge that uses experiments.' WHERE word = 'branch' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The ending of the movie surprised everyone.' WHERE word = 'ending' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A scientific study showed that sleep helps memory.' WHERE word = 'scientific' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She asked for assistance with her homework.' WHERE word = 'assistance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The temperature drops a lot at night in winter.' WHERE word = 'temperature' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She felt great affection for her pet dog.' WHERE word = 'affection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The country received aid after the earthquake.' WHERE word = 'aid' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A reduction in waste helps protect the environment.' WHERE word = 'reduction' AND level = 'mid_1';
UPDATE words SET example_sentence = 'It is important to eat well and stay healthy.' WHERE word = 'important' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Daily exercise keeps your body and mind strong.' WHERE word = 'exercise' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Safety rules are there to protect everyone.' WHERE word = 'safety' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The employer was happy with the new worker.' WHERE word = 'employer' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The trip to the beach was very enjoyable.' WHERE word = 'enjoyable' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Learning new things brings a deeper meaning to life.' WHERE word = 'learning' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The meaning of this word is hard to explain.' WHERE word = 'meaning' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Training hard every day made him a great runner.' WHERE word = 'training' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A strong connection between friends lasts a lifetime.' WHERE word = 'connection' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Each item on the list needs to be checked carefully.' WHERE word = 'item' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The structure of the bridge is very strong.' WHERE word = 'structure' AND level = 'mid_1';
UPDATE words SET example_sentence = 'An investment in education always pays off.' WHERE word = 'investment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher gave a recommendation for a good book.' WHERE word = 'recommendation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We need to find a solution to this problem.' WHERE word = 'solution' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Environmental problems affect everyone on Earth.' WHERE word = 'environmental' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The plan got final approval from the school.' WHERE word = 'approval' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Engineering is the study of how to build things.' WHERE word = 'engineering' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The president made a statement about the new law.' WHERE word = 'statement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She did well at the audition for the school play.' WHERE word = 'audition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'It is impossible to see air with your eyes.' WHERE word = 'impossible' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Friendship is one of the most valuable things in life.' WHERE word = 'friendship' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The improvement in her grades made her parents proud.' WHERE word = 'improvement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The school started a campaign to save water.' WHERE word = 'campaign' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She found an error in her math homework.' WHERE word = 'error' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Can I borrow your pencil for a moment?' WHERE word = 'borrow' AND level = 'mid_1';
UPDATE words SET example_sentence = 'His explanation of the problem was clear and simple.' WHERE word = 'explanation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I like her style of writing because it is clear.' WHERE word = 'style' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Traveling to other countries is a great experience.' WHERE word = 'experience' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I have a good feeling about today''s test.' WHERE word = 'feeling' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Modern technology makes life easier for many people.' WHERE word = 'modern' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Education opens doors to new chances in life.' WHERE word = 'education' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Technology is changing the way we learn and work.' WHERE word = 'technology' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The accuracy of the answer depends on careful work.' WHERE word = 'accuracy' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher gave helpful feedback on our essays.' WHERE word = 'feedback' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The pressure of the test made some students nervous.' WHERE word = 'pressure' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Colds are very common during the winter season.' WHERE word = 'common' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The production of electric cars is increasing every year.' WHERE word = 'production' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She set a new school record in the running race.' WHERE word = 'record' AND level = 'mid_1';
UPDATE words SET example_sentence = 'However, the weather changed and it started to rain.' WHERE word = 'however' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We found good accommodation near the beach.' WHERE word = 'accommodation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'You need a passport to cross the border.' WHERE word = 'border' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I have a dental appointment at three o''clock.' WHERE word = 'appointment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Everyone has a different preference for music.' WHERE word = 'preference' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Learning a new language takes time and practice.' WHERE word = 'language' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I saw an advertisement for the new movie.' WHERE word = 'advertisement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We should protect wildlife and their homes.' WHERE word = 'wildlife' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The school system has changed a lot over the years.' WHERE word = 'system' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She wrote a book review for the English class.' WHERE word = 'review' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The internet is a great source of information.' WHERE word = 'source' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The departure time of the train is at ten o''clock.' WHERE word = 'departure' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Each generation brings new ideas to the world.' WHERE word = 'generation' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She stopped for a moment to look at the sunset.' WHERE word = 'moment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He changed his position to get a better view.' WHERE word = 'position' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A good relationship is built on trust and respect.' WHERE word = 'relationship' AND level = 'mid_1';
UPDATE words SET example_sentence = 'There is heavy traffic on the road every morning.' WHERE word = 'traffic' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A positive attitude helps you face any challenge.' WHERE word = 'positive' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Please pay attention when the teacher is talking.' WHERE word = 'attention' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Everyone has a special talent that makes them unique.' WHERE word = 'talent' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A smile is a simple expression of happiness.' WHERE word = 'expression' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Call 119 in case of an emergency.' WHERE word = 'emergency' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The lack of sleep makes it hard to focus in class.' WHERE word = 'lack' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This is a personal matter between the two of them.' WHERE word = 'personal' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Honesty is a value that everyone should have.' WHERE word = 'value' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Practice builds confidence for the big performance.' WHERE word = 'confidence' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Swimming in a deep river can be dangerous.' WHERE word = 'dangerous' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The sports event will take place next Saturday.' WHERE word = 'event' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Physical exercise is good for your health.' WHERE word = 'physical' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We watched a series of short films at school.' WHERE word = 'series' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Water is a valuable resource that we should save.' WHERE word = 'resource' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her contribution to the project was very helpful.' WHERE word = 'contribution' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He studies a foreign language to talk to new people.' WHERE word = 'foreign' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Good judgment comes from thinking carefully.' WHERE word = 'judgment' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Reading is a skill that improves with practice.' WHERE word = 'skill' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The growth of the city has been very fast.' WHERE word = 'growth' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Group work is an effective way to solve problems.' WHERE word = 'effective' AND level = 'mid_1';
UPDATE words SET example_sentence = 'He made a sincere apology for arriving late.' WHERE word = 'apology' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her ambition is to become a doctor and help people.' WHERE word = 'ambition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Words of encouragement helped her try again.' WHERE word = 'encouragement' AND level = 'mid_1';
UPDATE words SET example_sentence = 'I read an interesting article in a science magazine.' WHERE word = 'magazine' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She took a photograph of the beautiful sunset.' WHERE word = 'photograph' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The signal turned green and the cars started moving.' WHERE word = 'signal' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The entrance to the park is next to the bus stop.' WHERE word = 'entrance' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Ancient civilizations built great buildings and roads.' WHERE word = 'civilization' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Follow the procedure step by step to get the answer.' WHERE word = 'procedure' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Her friendly personality makes her popular at school.' WHERE word = 'personality' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The population of the city keeps growing each year.' WHERE word = 'population' AND level = 'mid_1';
UPDATE words SET example_sentence = 'This brand of shoes is very popular among students.' WHERE word = 'brand' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Finding your own identity is part of growing up.' WHERE word = 'identity' AND level = 'mid_1';
UPDATE words SET example_sentence = 'We need to find an alternative plan if it rains.' WHERE word = 'alternative' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The teacher''s assistant helped prepare the classroom.' WHERE word = 'assistant' AND level = 'mid_1';
UPDATE words SET example_sentence = 'An independent thinker forms their own ideas.' WHERE word = 'independent' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The tourist took many photos of the old temple.' WHERE word = 'tourist' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Agriculture is important for feeding the world.' WHERE word = 'agriculture' AND level = 'mid_1';
UPDATE words SET example_sentence = 'There is a tendency for it to rain more in summer.' WHERE word = 'tendency' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The ceremony to open the new school was very nice.' WHERE word = 'ceremony' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The artist painted a portrait of the famous leader.' WHERE word = 'portrait' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The merchant sold goods at the busy market.' WHERE word = 'merchant' AND level = 'mid_1';
UPDATE words SET example_sentence = 'She had a brilliant idea to solve the problem.' WHERE word = 'brilliant' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Every creature on Earth plays a role in nature.' WHERE word = 'creature' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Fever and cough are common symptoms of a cold.' WHERE word = 'symptom' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Good nutrition helps children grow strong and healthy.' WHERE word = 'nutrition' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The weather forecast says it will rain tomorrow.' WHERE word = 'forecast' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Trees make oxygen that all living things need.' WHERE word = 'oxygen' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Carbon is found in all living things on Earth.' WHERE word = 'carbon' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Dinosaurs are extinct and can only be seen in museums.' WHERE word = 'extinct' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Asia is the largest continent in the world.' WHERE word = 'continent' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A compass shows you which way is north.' WHERE word = 'compass' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A hurricane is a very powerful storm with strong wind.' WHERE word = 'hurricane' AND level = 'mid_1';
UPDATE words SET example_sentence = 'A tsunami can cause great damage to the coast.' WHERE word = 'tsunami' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Wheat is used to make bread and noodles.' WHERE word = 'wheat' AND level = 'mid_1';
UPDATE words SET example_sentence = 'The parliament makes the laws of the country.' WHERE word = 'parliament' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Many people around the world still live in poverty.' WHERE word = 'poverty' AND level = 'mid_1';
UPDATE words SET example_sentence = 'Freedom is a right that all people should have.' WHERE word = 'freedom' AND level = 'mid_1';
