-- mid_2 예문 UPDATE (중2 수준, 8th grade)
-- 문장 길이: 9-13 단어

-- Batch 1: ability ~ border
UPDATE words SET example_sentence = 'Hard work and practice can help you improve your ability.' WHERE word = 'ability' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She wants to study abroad in Canada after high school.' WHERE word = 'abroad' AND level = 'mid_2';
UPDATE words SET example_sentence = 'His absence from class worried the teacher and his friends.' WHERE word = 'absence' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school decided to accept more students this year.' WHERE word = 'accept' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Students can access the library computers during lunch break.' WHERE word = 'access' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The accident on the road caused traffic to stop completely.' WHERE word = 'accident' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her parents will accompany her to the school event tonight.' WHERE word = 'accompany' AND level = 'mid_2';
UPDATE words SET example_sentence = 'With enough effort, you can accomplish any goal you set.' WHERE word = 'accomplish' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The scientist made accurate measurements during the experiment in class.' WHERE word = 'accurate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is wrong to accuse someone without any real evidence.' WHERE word = 'accuse' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Setting small goals makes big dreams feel more achievable over time.' WHERE word = 'achievable' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She worked hard all year to achieve the top score.' WHERE word = 'achieve' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Being active every day is important for your health and energy.' WHERE word = 'active' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The actual cost of the trip was lower than expected.' WHERE word = 'actual' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Animals must adapt to changes in their environment to survive.' WHERE word = 'adapt' AND level = 'mid_2';
UPDATE words SET example_sentence = 'In addition to math, she also studies science after school.' WHERE word = 'addition' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Make sure you drink an adequate amount of water every day.' WHERE word = 'adequate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You can adjust the volume on your phone if it is too loud.' WHERE word = 'adjust' AND level = 'mid_2';
UPDATE words SET example_sentence = 'I really admire my teacher for her patience and kindness.' WHERE word = 'admire' AND level = 'mid_2';
UPDATE words SET example_sentence = 'He had to admit that the other team played better today.' WHERE word = 'admit' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The family decided to adopt a dog from the shelter.' WHERE word = 'adopt' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Every adult should set a good example for young people.' WHERE word = 'adult' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Technology continues to advance and change our daily lives quickly.' WHERE word = 'advance' AND level = 'mid_2';
UPDATE words SET example_sentence = 'One advantage of reading is that it builds your vocabulary fast.' WHERE word = 'advantage' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Going camping in the mountains was a great adventure for us.' WHERE word = 'adventure' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Companies advertise their products on social media to reach more people.' WHERE word = 'advertise' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school affair was organized by the student council this year.' WHERE word = 'affair' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The weather can affect your mood and energy during the day.' WHERE word = 'affect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'They could not afford to buy a new computer this month.' WHERE word = 'afford' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The travel agency helped our family plan the summer vacation trip.' WHERE word = 'agency' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The main agenda for the meeting was the school festival plan.' WHERE word = 'agenda' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Most students agree that homework helps them understand the lesson better.' WHERE word = 'agree' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Modern agriculture uses technology to grow more food with less water.' WHERE word = 'agriculture' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The group sent aid to families who lost their homes.' WHERE word = 'aid' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her aim is to become a doctor and help sick children.' WHERE word = 'aim' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The fire alarm rang loudly and everyone left the building quickly.' WHERE word = 'alarm' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She keeps all her favorite photos in a special album.' WHERE word = 'album' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The weather alert warned people about the coming storm tonight.' WHERE word = 'alert' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher does not allow students to use phones in class.' WHERE word = 'allow' AND level = 'mid_2';
UPDATE words SET example_sentence = 'He saved his weekly allowance to buy a new video game.' WHERE word = 'allowance' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Walking to school is a healthy alternative to taking the bus.' WHERE word = 'alternative' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The magic show last night was truly amazing and fun to watch.' WHERE word = 'amazing' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her ambition is to travel the world and learn new languages.' WHERE word = 'ambition' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A large amount of rain fell during the storm last week.' WHERE word = 'amount' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The funny movie never fails to amuse the whole family.' WHERE word = 'amuse' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The analysis of the data showed that students improved their scores.' WHERE word = 'analysis' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We learned about ancient Rome and its famous buildings in history.' WHERE word = 'ancient' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Try to see the problem from a different angle before giving up.' WHERE word = 'angle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The principal will announce the winner of the contest after lunch.' WHERE word = 'announce' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She felt anxiety before the big test but did her best.' WHERE word = 'anxiety' AND level = 'mid_2';
UPDATE words SET example_sentence = 'He was anxious about giving a speech in front of everyone.' WHERE word = 'anxious' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You should apologize when you hurt someone, even by accident.' WHERE word = 'apologize' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She wrote an apology letter to her friend after the argument.' WHERE word = 'apology' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It was apparent that the team needed more practice before the game.' WHERE word = 'apparent' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The idea of a school trip to the beach had strong appeal.' WHERE word = 'appeal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Dark clouds appear in the sky when a storm is coming.' WHERE word = 'appear' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She decided to apply for the summer camp program this year.' WHERE word = 'apply' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school will appoint a new leader for the science club.' WHERE word = 'appoint' AND level = 'mid_2';
UPDATE words SET example_sentence = 'I appreciate your help with my homework — it means a lot.' WHERE word = 'appreciate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We need a creative approach to solve this difficult math problem.' WHERE word = 'approach' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Wearing appropriate clothes for the weather keeps you healthy and comfortable.' WHERE word = 'appropriate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The committee voted to approve the plan for the new playground.' WHERE word = 'approve' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The two friends often argue about which movie is the best.' WHERE word = 'argue' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We need to arrange the chairs in a circle for the activity.' WHERE word = 'arrange' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The arrival of spring brings warm weather and beautiful flowers.' WHERE word = 'arrival' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The bus should arrive at the station in about ten minutes.' WHERE word = 'arrive' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She wrote an article about healthy eating for the school newspaper.' WHERE word = 'article' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The artificial flowers looked so real that everyone was surprised.' WHERE word = 'artificial' AND level = 'mid_2';
UPDATE words SET example_sentence = 'One important aspect of teamwork is listening to other people.' WHERE word = 'aspect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The older students assist younger ones with reading every Wednesday.' WHERE word = 'assist' AND level = 'mid_2';
UPDATE words SET example_sentence = 'People often associate rainy days with staying inside and reading books.' WHERE word = 'associate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Do not assume the answer is wrong before checking it carefully.' WHERE word = 'assume' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The young athlete trained every morning to prepare for the competition.' WHERE word = 'athlete' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please attach your photo to the application form before submitting it.' WHERE word = 'attach' AND level = 'mid_2';
UPDATE words SET example_sentence = 'On her first attempt, she solved the puzzle in five minutes.' WHERE word = 'attempt' AND level = 'mid_2';
UPDATE words SET example_sentence = 'All students must attend the safety meeting in the gym today.' WHERE word = 'attend' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A positive attitude can make difficult situations feel much easier.' WHERE word = 'attitude' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Bright colors and fun designs attract young customers to the store.' WHERE word = 'attract' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The audience clapped loudly after the students finished their performance on stage.' WHERE word = 'audience' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The author of this book is a famous Korean writer.' WHERE word = 'author' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The local authority decided to build a new park for families.' WHERE word = 'authority' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The doors of the building are automatic and open by themselves.' WHERE word = 'automatic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The book is available at the school library for all students.' WHERE word = 'available' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The average score on the math test was eighty-five points.' WHERE word = 'average' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Try to avoid eating too much sugar before going to bed.' WHERE word = 'avoid' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She received an award for her outstanding science project at school.' WHERE word = 'award' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We should be aware of the rules before starting the game.' WHERE word = 'aware' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning about her background helped us understand her story much better.' WHERE word = 'background' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is important to keep a good balance between study and play.' WHERE word = 'balance' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You need basic math skills to solve everyday problems at home.' WHERE word = 'basic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The two teams prepared hard for the final battle of the season.' WHERE word = 'battle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Good behavior in class helps everyone learn in a better environment.' WHERE word = 'behavior' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Regular exercise has a great benefit for both your body and mind.' WHERE word = 'benefit' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The stars beyond our solar system are very far from Earth.' WHERE word = 'beyond' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Over a billion people around the world use the internet every day.' WHERE word = 'billion' AND level = 'mid_2';
UPDATE words SET example_sentence = 'In biology class, we studied how plants make food from sunlight.' WHERE word = 'biology' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The birth of the baby brought happiness to the whole family.' WHERE word = 'birth' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Do not blame others when you make a mistake — learn from it.' WHERE word = 'blame' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The river forms a natural border between the two countries.' WHERE word = 'border' AND level = 'mid_2';

-- Batch 2: brain ~ energy
UPDATE words SET example_sentence = 'The human brain controls everything we think, feel, and do.' WHERE word = 'brain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The library has a special branch for children near the park.' WHERE word = 'branch' AND level = 'mid_2';
UPDATE words SET example_sentence = 'That brand of sneakers is very popular among students at school.' WHERE word = 'brand' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher gave a brief explanation before starting the group activity.' WHERE word = 'brief' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school offers a broad range of clubs for all students.' WHERE word = 'broad' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The student council set a budget for the school festival this year.' WHERE word = 'budget' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Too much homework can become a heavy burden for young students.' WHERE word = 'burden' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You need to calculate the total cost before buying all the items.' WHERE word = 'calculate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The students started a campaign to reduce plastic waste at school.' WHERE word = 'campaign' AND level = 'mid_2';
UPDATE words SET example_sentence = 'They had to cancel the outdoor event because of heavy rain.' WHERE word = 'cancel' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The photographer tried to capture the beautiful sunset over the ocean.' WHERE word = 'capture' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She is thinking about a career in medicine to help people.' WHERE word = 'career' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Books in the library are organized by category and author name.' WHERE word = 'category' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Heavy rain was the main cause of the flood in the village.' WHERE word = 'cause' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The whole school gathered to celebrate the end of the semester.' WHERE word = 'celebrate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning a new language is a challenge that takes time and effort.' WHERE word = 'challenge' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The main character in the story is a brave young girl.' WHERE word = 'character' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The museum does not charge students for entry on weekends.' WHERE word = 'charge' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Making the right choice can be difficult when you have many options.' WHERE word = 'choice' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Every citizen has the right to vote in a national election.' WHERE word = 'citizen' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Scientists claim that exercise helps improve memory and focus at school.' WHERE word = 'claim' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Let me clarify the instructions so that everyone understands the task.' WHERE word = 'clarify' AND level = 'mid_2';
UPDATE words SET example_sentence = 'That classic movie is still enjoyed by people of all ages.' WHERE word = 'classic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Climate change is causing temperatures to rise around the whole world.' WHERE word = 'climate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We helped collect old clothes to donate to people in need.' WHERE word = 'collect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You can combine different colors to create a beautiful painting easily.' WHERE word = 'combine' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher asked us to comment on each other and give feedback.' WHERE word = 'comment' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is important to communicate clearly when working in a group.' WHERE word = 'communicate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Our community organized a clean-up event at the local park last Saturday.' WHERE word = 'community' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher asked us to compare the two stories and find differences.' WHERE word = 'compare' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Many students compete in the spelling contest held every spring.' WHERE word = 'compete' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You must complete all the questions before handing in your test.' WHERE word = 'complete' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The math problem was complex, but she solved it step by step.' WHERE word = 'complex' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The concept of gravity was hard to understand at first.' WHERE word = 'concept' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The main concern of parents is the safety of their children.' WHERE word = 'concern' AND level = 'mid_2';
UPDATE words SET example_sentence = 'After reviewing the results, the team could conclude that the plan worked.' WHERE word = 'conclude' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The condition of the road was bad after the heavy snowfall.' WHERE word = 'condition' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please confirm your attendance by sending a reply before Friday.' WHERE word = 'confirm' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The conflict between the two groups was resolved through a calm discussion.' WHERE word = 'conflict' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The internet helps people connect with friends all around the world.' WHERE word = 'connect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You should consider all the options before making your final decision.' WHERE word = 'consider' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The constant noise from the construction site made it hard to study.' WHERE word = 'constant' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Workers will construct a new bridge over the river this summer.' WHERE word = 'construct' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please contact the office if you have any questions about the event.' WHERE word = 'contact' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This box can contain up to twenty books of different sizes.' WHERE word = 'contain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The content of the video was useful for our science project.' WHERE word = 'content' AND level = 'mid_2';
UPDATE words SET example_sentence = 'If you continue to practice every day, your skills will improve.' WHERE word = 'continue' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The contrast between the two paintings was clear to everyone in class.' WHERE word = 'contrast' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Everyone should contribute ideas to make the group project more creative.' WHERE word = 'contribute' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning to control your emotions is an important life skill.' WHERE word = 'control' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She tried to convince her parents to let her join the trip.' WHERE word = 'convince' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The two countries agreed to cooperate on protecting the environment together.' WHERE word = 'cooperate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The core idea of the lesson was about respecting other people.' WHERE word = 'core' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Students worked together to create a poster for the school event.' WHERE word = 'create' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning about different culture helps us understand people around the world.' WHERE word = 'culture' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The storm caused serious damage to many houses near the coast.' WHERE word = 'damage' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The class held a debate about whether school uniforms should be required.' WHERE word = 'debate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The city has changed a lot over the past decade.' WHERE word = 'decade' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is hard to decide which club to join this semester.' WHERE word = 'decide' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Can you define what the word means using a simple example?' WHERE word = 'define' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Bad weather may delay the flight by several hours today.' WHERE word = 'delay' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The company will deliver the package to your home by tomorrow.' WHERE word = 'deliver' AND level = 'mid_2';
UPDATE words SET example_sentence = 'There is a growing demand for clean energy in many countries.' WHERE word = 'demand' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Young children depend on their parents for food and safety.' WHERE word = 'depend' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Can you describe what the main character looks like in the book?' WHERE word = 'describe' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The students worked together to design a new logo for the club.' WHERE word = 'design' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Your effort and attitude determine how well you do in school.' WHERE word = 'determine' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Scientists develop new ways to use solar energy every year.' WHERE word = 'develop' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This small device can measure the temperature of any room quickly.' WHERE word = 'device' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The earthquake was a terrible disaster that affected thousands of people.' WHERE word = 'disaster' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The team was excited to discover a new species of insect.' WHERE word = 'discover' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We will discuss the topic in small groups during class today.' WHERE word = 'discuss' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The museum will display artwork from students across the whole country.' WHERE word = 'display' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The distant mountains looked beautiful under the orange sunset sky.' WHERE word = 'distant' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Each season has distinct weather patterns that make it special.' WHERE word = 'distinct' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school is located in a quiet district near the river.' WHERE word = 'district' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Our class has a diverse mix of students from many different countries.' WHERE word = 'diverse' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Domestic flights are usually cheaper and shorter than international ones.' WHERE word = 'domestic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is our duty to keep the classroom clean and organized.' WHERE word = 'duty' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The dynamic presentation kept the audience interested from start to finish.' WHERE word = 'dynamic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She worked part-time at a cafe to earn money for books.' WHERE word = 'earn' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The economic growth of the country improved life for many families.' WHERE word = 'economic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Schools educate young people and help them prepare for the future.' WHERE word = 'educate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Getting enough sleep has a positive effect on your school performance.' WHERE word = 'effect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Using a timer is an efficient way to manage your study time.' WHERE word = 'efficient' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The elder brother always helps his younger sister with her homework.' WHERE word = 'elder' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The people will elect a new class president next Monday.' WHERE word = 'elect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Water is an important element that all living things need to survive.' WHERE word = 'element' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We should eliminate waste by recycling and reusing items at home.' WHERE word = 'eliminate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'New technology companies continue to emerge in cities around the world.' WHERE word = 'emerge' AND level = 'mid_2';
UPDATE words SET example_sentence = 'In case of an emergency, call for help and stay calm.' WHERE word = 'emergency' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Music can express emotion in ways that words sometimes cannot.' WHERE word = 'emotion' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher wanted to emphasize the importance of reading every day.' WHERE word = 'emphasize' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The factory will employ more workers to meet the growing demand.' WHERE word = 'employ' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Every employee in the company received a bonus at the end of the year.' WHERE word = 'employee' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A good employer cares about the health and happiness of workers.' WHERE word = 'employer' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Good study habits enable students to perform better on their exams.' WHERE word = 'enable' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She did not expect to encounter her old friend at the market.' WHERE word = 'encounter' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Parents should encourage their children to try new things without fear.' WHERE word = 'encourage' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Solar energy is a clean source of power for homes and schools.' WHERE word = 'energy' AND level = 'mid_2';

-- Batch 3: engine ~ majority
UPDATE words SET example_sentence = 'The engine of the car makes a strange noise when it starts.' WHERE word = 'engine' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The engineer designed a new bridge that is both strong and safe.' WHERE word = 'engineer' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please check your work carefully to ensure there are no mistakes.' WHERE word = 'ensure' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The entire class worked together to finish the group project on time.' WHERE word = 'entire' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The entry to the museum is free for all students on Saturdays.' WHERE word = 'entry' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We must protect the environment by reducing waste and saving water.' WHERE word = 'environment' AND level = 'mid_2';
UPDATE words SET example_sentence = 'All students should have equal chances to learn and grow at school.' WHERE word = 'equal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The science lab has new equipment for experiments this semester.' WHERE word = 'equipment' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The rabbit managed to escape from the cage through a small hole.' WHERE word = 'escape' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Drinking water is essential for staying healthy during hot summer days.' WHERE word = 'essential' AND level = 'mid_2';
UPDATE words SET example_sentence = 'They plan to establish a new club for students who love art.' WHERE word = 'establish' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The real estate market has grown a lot in this area recently.' WHERE word = 'estate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Scientists estimate that millions of species live in the ocean.' WHERE word = 'estimate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher asked us to evaluate our own work before submitting it.' WHERE word = 'evaluate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The sports event brought students from many different schools together.' WHERE word = 'event' AND level = 'mid_2';
UPDATE words SET example_sentence = 'There is strong evidence that reading improves your writing skills over time.' WHERE word = 'evidence' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Animals evolve over time to survive better in their environment.' WHERE word = 'evolve' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Can you tell me the exact time the movie starts tonight?' WHERE word = 'exact' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The doctor will examine the patient to find the cause of pain.' WHERE word = 'examine' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Students can exchange ideas with partners from schools in other countries.' WHERE word = 'exchange' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The news about the field trip made everyone feel very excited.' WHERE word = 'excite' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Daily exercise helps you stay fit and feel more focused in class.' WHERE word = 'exercise' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Many different kinds of animals exist in the tropical rainforest.' WHERE word = 'exist' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school plans to expand the library to hold more books.' WHERE word = 'expand' AND level = 'mid_2';
UPDATE words SET example_sentence = 'I expect the test results to come out by next week.' WHERE word = 'expect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The expense of the school trip was shared equally among all students.' WHERE word = 'expense' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Traveling to a new country is always a great learning experience.' WHERE word = 'experience' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The expert explained how to stay safe during an earthquake.' WHERE word = 'expert' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Can you explain how this math formula works in simple words?' WHERE word = 'explain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We went to explore the forest and found a small waterfall.' WHERE word = 'explore' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Art allows people to express their feelings in many different ways.' WHERE word = 'express' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher gave us extra time to finish the difficult test.' WHERE word = 'extra' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Time is an important factor when preparing for a big exam.' WHERE word = 'factor' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Do not be afraid of failure because it helps you learn and grow.' WHERE word = 'failure' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This song sounds familiar because we heard it in class last week.' WHERE word = 'familiar' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The best feature of this phone is its long battery life.' WHERE word = 'feature' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The federal government made a new law to protect the environment.' WHERE word = 'federal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Understanding personal finance helps young people manage their money wisely.' WHERE word = 'finance' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Try to focus on one task at a time to do it well.' WHERE word = 'focus' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The strong wind forced the trees to bend toward the ground.' WHERE word = 'force' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning a foreign language opens doors to new cultures and ideas.' WHERE word = 'foreign' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Students must wear formal clothes for the graduation ceremony next week.' WHERE word = 'formal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The former principal visited the school and spoke to the students.' WHERE word = 'former' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A strong foundation in math is important for learning science later.' WHERE word = 'foundation' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Frequent practice is the key to improving your English speaking skills.' WHERE word = 'frequent' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The main function of the heart is to pump blood through the body.' WHERE word = 'function' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school raised a fund to help students who need school supplies.' WHERE word = 'fund' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You will gain more confidence if you practice speaking in front of others.' WHERE word = 'gain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'In general, students prefer group activities over working alone in class.' WHERE word = 'general' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Wind turbines generate electricity without polluting the air or water.' WHERE word = 'generate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Climate change is a global problem that affects every country on Earth.' WHERE word = 'global' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her goal is to read fifty books before the end of this year.' WHERE word = 'goal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'He studied hard and received a high grade on the final exam.' WHERE word = 'grade' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The government gave a grant to the school for new science equipment.' WHERE word = 'grant' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The rapid growth of the city has created many new jobs.' WHERE word = 'growth' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This travel guide has useful information about places to visit in Seoul.' WHERE word = 'guide' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Reading before bed is a good habit that can improve your vocabulary.' WHERE word = 'habit' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She learned how to handle stress by taking deep breaths and resting.' WHERE word = 'handle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Too much screen time can cause harm to your eyes and sleep.' WHERE word = 'harm' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The headline of the newspaper talked about the new discovery in space.' WHERE word = 'headline' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Eating fresh vegetables every day is very important for your health.' WHERE word = 'health' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The height of the building is over one hundred meters tall.' WHERE word = 'height' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher wanted to highlight the most important points of the lesson.' WHERE word = 'highlight' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The historical museum shows how people lived hundreds of years ago.' WHERE word = 'historical' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is an honor to be chosen as the team captain this year.' WHERE word = 'honor' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The host of the show welcomed all the guests with a warm smile.' WHERE word = 'host' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Every household should have a plan in case of a fire emergency.' WHERE word = 'household' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The human body needs food, water, and sleep to stay healthy.' WHERE word = 'human' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The park is an ideal place for families to spend weekends together.' WHERE word = 'ideal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The police were able to identify the owner of the lost bag.' WHERE word = 'identify' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You should never ignore a friend who is asking for your help.' WHERE word = 'ignore' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher used a simple diagram to illustrate how volcanoes work.' WHERE word = 'illustrate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The image on the screen was so clear that it looked real.' WHERE word = 'image' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Pollution has a big impact on the health of people and animals.' WHERE word = 'impact' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Korea has to import oil because it does not produce its own.' WHERE word = 'import' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The importance of teamwork is something we learn through group projects.' WHERE word = 'importance' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her speech at the contest was able to impress everyone in the audience.' WHERE word = 'impress' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You can improve your writing by reading more books and practicing daily.' WHERE word = 'improve' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Make sure to include your name on the top of every page.' WHERE word = 'include' AND level = 'mid_2';
UPDATE words SET example_sentence = 'His family has a low income, so he studies hard for a scholarship.' WHERE word = 'income' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The number of students learning coding continues to increase every year.' WHERE word = 'increase' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Being independent means making your own decisions and solving problems yourself.' WHERE word = 'independent' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The survey results indicate that most students enjoy science class the most.' WHERE word = 'indicate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Every individual has unique talents that can help the team succeed.' WHERE word = 'individual' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Friends can have a strong influence on the choices you make.' WHERE word = 'influence' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please inform the teacher if you cannot come to school tomorrow.' WHERE word = 'inform' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This new innovation in technology makes learning more fun and easy.' WHERE word = 'innovation' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Water pollution is a serious issue that we need to solve together.' WHERE word = 'issue' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Everyone deserves to be treated with fairness and justice in society.' WHERE word = 'justice' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Farm labor is very hard work, especially during the hot summer months.' WHERE word = 'labor' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The landscape of the countryside was beautiful with green hills and rivers.' WHERE word = 'landscape' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Have you seen the latest news about the space mission today?' WHERE word = 'latest' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The legal age to drive a car in Korea is eighteen years old.' WHERE word = 'legal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'There is a speed limit on this road to keep everyone safe.' WHERE word = 'limit' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The local market sells fresh fruit and vegetables from nearby farms.' WHERE word = 'local' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We used a map to locate the nearest hospital from our school.' WHERE word = 'locate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You need to maintain a healthy diet and exercise regularly to stay fit.' WHERE word = 'maintain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'One major reason students study hard is to get into a good university.' WHERE word = 'major' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The majority of students voted to have the festival outdoors this year.' WHERE word = 'majority' AND level = 'mid_2';

-- Batch 4: manage ~ vision
UPDATE words SET example_sentence = 'Learning to manage your time well is important for school and life.' WHERE word = 'manage' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She spoke in a polite manner that made everyone feel welcome.' WHERE word = 'manner' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We used recycled material to build the model house for our project.' WHERE word = 'material' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We need to measure the length of the table for the experiment.' WHERE word = 'measure' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The medical team at the hospital worked hard to help patients recover.' WHERE word = 'medical' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She has a good memory and can remember names very easily.' WHERE word = 'memory' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Good mental health is just as important as physical health for students.' WHERE word = 'mental' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The best method to learn new words is to use them in sentences.' WHERE word = 'method' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The park is located in the middle of the city near the station.' WHERE word = 'middle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The military protects the country and helps people during natural disasters.' WHERE word = 'military' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Modern technology has changed the way students learn in the classroom.' WHERE word = 'modern' AND level = 'mid_2';
UPDATE words SET example_sentence = 'That special moment with my family is a memory I will never forget.' WHERE word = 'moment' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher uses a screen to monitor student progress during class.' WHERE word = 'monitor' AND level = 'mid_2';
UPDATE words SET example_sentence = 'People across the nation celebrated the holiday with food and fireworks.' WHERE word = 'nation' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She is a native speaker of Korean and also speaks English fluently.' WHERE word = 'native' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We should respect nature and protect forests and rivers from pollution.' WHERE word = 'nature' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Sleep is necessary for the brain to rest and work well each day.' WHERE word = 'necessary' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Building a strong network of friends can help you in many ways.' WHERE word = 'network' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Did you notice the new poster on the wall in the hallway?' WHERE word = 'notice' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The main object of the game is to score the most points.' WHERE word = 'object' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We went outside to observe the stars during the science field trip.' WHERE word = 'observe' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Students can obtain a library card by filling out a simple form.' WHERE word = 'obtain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Birthdays and holidays are a special occasion for gathering with family.' WHERE word = 'occasion' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Books and boxes occupy most of the space in her small room.' WHERE word = 'occupy' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The store made a special offer on school supplies this week.' WHERE word = 'offer' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The official announcement about the school trip will come out on Friday.' WHERE word = 'official' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Only trained staff are allowed to operate the machines in the lab.' WHERE word = 'operate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The rescue operation saved many people from the flooded area safely.' WHERE word = 'operation' AND level = 'mid_2';
UPDATE words SET example_sentence = 'In my opinion, working in groups is more fun than working alone.' WHERE word = 'opinion' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She shook hands with her opponent before the tennis match began.' WHERE word = 'opponent' AND level = 'mid_2';
UPDATE words SET example_sentence = 'This program gives students the opportunity to learn about different careers.' WHERE word = 'opportunity' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You have the option to choose between two different project topics.' WHERE word = 'option' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The teacher asked us to put the books in alphabetical order.' WHERE word = 'order' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It was just an ordinary day until the surprise party started.' WHERE word = 'ordinary' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We need to organize our notes before the final exam next week.' WHERE word = 'organize' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The origin of this traditional food goes back hundreds of years.' WHERE word = 'origin' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The output of the factory increased after they added new machines.' WHERE word = 'output' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The overall quality of student projects has improved compared to last year.' WHERE word = 'overall' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The delivery package arrived at the front door early this morning.' WHERE word = 'package' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A panel of judges will choose the best artwork at the contest.' WHERE word = 'panel' AND level = 'mid_2';
UPDATE words SET example_sentence = 'All students should participate in the discussion to share their ideas.' WHERE word = 'participate' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The artist used a flower pattern to decorate the wall of the cafeteria.' WHERE word = 'pattern' AND level = 'mid_2';
UPDATE words SET example_sentence = 'People around the world hope for peace and an end to war.' WHERE word = 'peace' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The students will perform a play for their parents at the festival.' WHERE word = 'perform' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The exam period is always a stressful time for many students.' WHERE word = 'period' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The nurse does a periodic health check for students every six months.' WHERE word = 'periodic' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You need a permit to park your car in the school parking area.' WHERE word = 'permit' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Keep your personal belongings in your locker during gym class.' WHERE word = 'personal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'He tried to persuade his friends to join the volunteer group.' WHERE word = 'persuade' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The first phase of the project is to gather information from books.' WHERE word = 'phase' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Regular physical activity keeps your body strong and your mind clear.' WHERE word = 'physical' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school has a policy that does not allow phones during class.' WHERE word = 'policy' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Each student received a small portion of the cake at the party.' WHERE word = 'portion' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A positive mindset helps you overcome challenges and keep trying harder.' WHERE word = 'positive' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She has the potential to become a great scientist in the future.' WHERE word = 'potential' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Cooking is a practical skill that everyone should learn before college.' WHERE word = 'practical' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The directions must be precise so that no one makes a mistake.' WHERE word = 'precise' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Scientists predict that the weather will get warmer in the coming years.' WHERE word = 'predict' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Most students prefer group work because it is more fun and creative.' WHERE word = 'prefer' AND level = 'mid_2';
UPDATE words SET example_sentence = 'You should prepare all your materials the night before the big test.' WHERE word = 'prepare' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The principal gave a speech about the importance of kindness at school.' WHERE word = 'principal' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The principle of fairness means treating everyone with equal respect.' WHERE word = 'principle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Safety should always be the top priority during science experiments at school.' WHERE word = 'priority' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The conversation between them was private and not meant for others.' WHERE word = 'private' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Learning a new language is a long process that requires daily practice.' WHERE word = 'process' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Local farms produce fresh fruits and vegetables for the whole community.' WHERE word = 'produce' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The team made great progress on the project during the past month.' WHERE word = 'progress' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Our group project is about how to save energy at school.' WHERE word = 'project' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We should all work together to protect endangered animals and their homes.' WHERE word = 'protect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school will provide free lunch to all students during the camp.' WHERE word = 'provide' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The purpose of this experiment is to learn how plants grow faster.' WHERE word = 'purpose' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We can reduce pollution by using public transportation instead of driving cars.' WHERE word = 'reduce' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Take some time to reflect on what you learned in class today.' WHERE word = 'reflect' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Each region of the country has its own special food and culture.' WHERE word = 'region' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A few problems remain that we need to fix before the deadline.' WHERE word = 'remain' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The students did research on ocean pollution for their science project.' WHERE word = 'research' AND level = 'mid_2';
UPDATE words SET example_sentence = 'How you respond to mistakes shows what kind of person you are.' WHERE word = 'respond' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Hard work and practice led to a good result on the final exam.' WHERE word = 'result' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Each member of the team has an important role to play.' WHERE word = 'role' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Please select one topic from the list for your presentation next week.' WHERE word = 'select' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is good to share what you know with friends and classmates.' WHERE word = 'share' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Regular reading makes a significant difference in your vocabulary and writing.' WHERE word = 'significant' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The two books are similar in style but different in their message.' WHERE word = 'similar' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Working together was the best solution to the problem we faced.' WHERE word = 'solution' AND level = 'mid_2';
UPDATE words SET example_sentence = 'We need to solve this math problem before moving to the next one.' WHERE word = 'solve' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The internet is a great source of information for school projects.' WHERE word = 'source' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A good strategy for studying is to review your notes every night.' WHERE word = 'strategy' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The structure of the essay should include an introduction, body, and conclusion.' WHERE word = 'structure' AND level = 'mid_2';
UPDATE words SET example_sentence = 'I suggest we meet at the library to work on our project.' WHERE word = 'suggest' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Friends and family support each other during difficult and happy times.' WHERE word = 'support' AND level = 'mid_2';
UPDATE words SET example_sentence = 'A good transportation system helps people travel safely and quickly every day.' WHERE word = 'system' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The target of the campaign is to plant one thousand trees this year.' WHERE word = 'target' AND level = 'mid_2';
UPDATE words SET example_sentence = 'New technology makes it easier for students to learn at their own pace.' WHERE word = 'technology' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The school set up a temporary classroom while the building was repaired.' WHERE word = 'temporary' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The theory explains why objects fall to the ground when dropped.' WHERE word = 'theory' AND level = 'mid_2';
UPDATE words SET example_sentence = 'It is a family tradition to eat together on New Year morning.' WHERE word = 'tradition' AND level = 'mid_2';
UPDATE words SET example_sentence = 'She wants to transfer to a school that is closer to her home.' WHERE word = 'transfer' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Buses and trains transport millions of people to work and school daily.' WHERE word = 'transport' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Honesty is a value that people respect in every culture around the world.' WHERE word = 'value' AND level = 'mid_2';
UPDATE words SET example_sentence = 'The library has various types of books for students of all ages.' WHERE word = 'various' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Electric vehicle use is growing as people try to reduce air pollution.' WHERE word = 'vehicle' AND level = 'mid_2';
UPDATE words SET example_sentence = 'Her vision for the future includes clean energy and better schools for all.' WHERE word = 'vision' AND level = 'mid_2';
