-- mid_3 예문 UPDATE (중3 수준, 9th grade)
-- 문장 길이: 10-14 단어

-- Batch 1: abandon ~ deviation
UPDATE words SET example_sentence = 'You should never abandon your dreams, even when things get really difficult.' WHERE word = 'abandon' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Plants absorb water through their roots and sunlight through their leaves.' WHERE word = 'absorb' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The concept of justice is abstract and can be understood in many ways.' WHERE word = 'abstract' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The car began to accelerate as it entered the highway ramp.' WHERE word = 'accelerate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The young filmmaker received great acclaim for her first short movie.' WHERE word = 'acclaim' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is important to acknowledge your mistakes and learn from them quickly.' WHERE word = 'acknowledge' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The squirrel buried an acorn in the ground to save it for winter.' WHERE word = 'acorn' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Reading widely is a great way to acquire new knowledge and vocabulary.' WHERE word = 'acquire' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Some people become addict to their phones and cannot stop using them.' WHERE word = 'addict' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher gave us additional homework to prepare for the final exam.' WHERE word = 'additional' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Use adhesive tape to attach the poster firmly to the classroom wall.' WHERE word = 'adhesive' AND level = 'mid_3';
UPDATE words SET example_sentence = 'During the adolescent years, young people experience many physical and emotional changes.' WHERE word = 'adolescent' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The doctor will advise you on how to stay healthy during winter.' WHERE word = 'advise' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Aerobic exercise like running helps strengthen your heart and improve your stamina.' WHERE word = 'aerobic' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The coach wanted to affirm that every player on the team matters.' WHERE word = 'affirm' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The store offers affordable prices so that all students can buy school supplies.' WHERE word = 'affordable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We had lunch first and went to the museum afterward to see the exhibit.' WHERE word = 'afterward' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The dog became aggressive when a stranger tried to enter the house.' WHERE word = 'aggressive' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She walked down the aisle of the supermarket looking for cereal and milk.' WHERE word = 'aisle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She is an ambitious student who aims to attend the best university.' WHERE word = 'ambitious' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We anticipate that more students will join the science club next semester.' WHERE word = 'anticipate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The approximate distance from our school to the station is two kilometers.' WHERE word = 'approximate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Many people attribute their success to hard work and support from family.' WHERE word = 'attribute' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Only the principal can authorize the use of the school gym after hours.' WHERE word = 'authorize' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Washing your hands regularly helps prevent the spread of harmful bacteria.' WHERE word = 'bacteria' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Each volunteer received a badge to wear during the community clean-up event.' WHERE word = 'badge' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They stood on the balcony and watched the sunset over the ocean together.' WHERE word = 'balcony' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The bamboo forest was so tall and thick that it blocked all sunlight.' WHERE word = 'bamboo' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He went to the barber to get his hair cut before the school photo.' WHERE word = 'barber' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She could barely hear the announcement because the hallway was so noisy.' WHERE word = 'barely' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They found a great bargain on shoes during the holiday sale at the mall.' WHERE word = 'bargain' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The battery of my phone died in the middle of an important call.' WHERE word = 'battery' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The old man had a long white beard that reached down to his chest.' WHERE word = 'beard' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We discovered a beehive hidden inside the wall of the old garden shed.' WHERE word = 'beehive' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Students are expected to behave respectfully toward teachers and classmates at all times.' WHERE word = 'behave' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The treasure was hidden beneath the old tree in the school garden.' WHERE word = 'beneath' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A true friend would never betray your trust or share your secrets.' WHERE word = 'betray' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Water is the healthiest beverage you can drink throughout the entire day.' WHERE word = 'beverage' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Being bilingual gives you the advantage of communicating with people from different countries.' WHERE word = 'bilingual' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She packed a biscuit and some fruit for her afternoon snack at school.' WHERE word = 'biscuit' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He wrapped the blanket around his shoulders to keep warm on the cold night.' WHERE word = 'blanket' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The chef decided to blend several spices together to create a unique flavor.' WHERE word = 'blend' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The family stayed in a small cabin by the lake during summer vacation.' WHERE word = 'cabin' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A cactus can survive in the desert because it stores water inside its stem.' WHERE word = 'cactus' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school cafeteria serves healthy meals that include vegetables and fresh fruit daily.' WHERE word = 'cafeteria' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She used a calculator to check her answers on the math worksheet.' WHERE word = 'calculator' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The students sat around the campfire and shared stories under the bright stars.' WHERE word = 'campfire' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We paddled the canoe across the calm lake on a warm summer morning.' WHERE word = 'canoe' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She is capable of solving complex math problems without any help from others.' WHERE word = 'capable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The carpenter built a beautiful wooden bookshelf for the new school library.' WHERE word = 'carpenter' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The soft carpet in the living room feels warm and comfortable under your feet.' WHERE word = 'carpet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'In the old days, people used a horse-drawn carriage to travel between towns.' WHERE word = 'carriage' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The mail carrier delivers letters and packages to our neighborhood every morning.' WHERE word = 'carrier' AND level = 'mid_3';
UPDATE words SET example_sentence = 'My younger brother loves watching his favorite cartoon show every Saturday morning.' WHERE word = 'cartoon' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The cashier at the grocery store was friendly and helped us find everything.' WHERE word = 'cashier' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The library has an online catalog where you can search for any book.' WHERE word = 'catalog' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The caterpillar will eventually transform into a beautiful butterfly in a few weeks.' WHERE word = 'caterpillar' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Be cautious when crossing the street, especially during rush hour in the morning.' WHERE word = 'cautious' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The fighting between the two countries finally ceased after a peace agreement was signed.' WHERE word = 'cease' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She looked up at the ceiling and noticed a small crack in the paint.' WHERE word = 'ceiling' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Almost every student carries a cellphone, but they must turn it off in class.' WHERE word = 'cellphone' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Blood needs to circulate through the entire body to deliver oxygen to every cell.' WHERE word = 'circulate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Her essay was well-organized and presented a coherent argument from beginning to end.' WHERE word = 'coherent' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It was strange how our birthdays coincide on the exact same day in June.' WHERE word = 'coincide' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The old bridge could collapse if heavy trucks continue to drive across it.' WHERE word = 'collapse' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Joining the volunteer club requires a strong commitment to helping the local community.' WHERE word = 'commitment' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Adding too many rules can complicate a simple game and confuse the players.' WHERE word = 'complicate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She decided to compose a short poem about nature for the school contest.' WHERE word = 'compose' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Both sides had to compromise to reach a fair solution to the problem.' WHERE word = 'compromise' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is hard to concentrate on studying when there is loud music playing.' WHERE word = 'concentrate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We should be conscious of how our actions affect the people around us.' WHERE word = 'conscious' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Conservation of water resources is essential for protecting the environment and wildlife.' WHERE word = 'conservation' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A considerable amount of time was spent planning the school festival this year.' WHERE word = 'considerable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The main constraint of the project was the limited budget we had available.' WHERE word = 'constraint' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The student had a consultation with the teacher about choosing the right courses.' WHERE word = 'consultation' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Reducing energy consumption at home can help protect the environment and save money.' WHERE word = 'consumption' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She sat by the window to contemplate what career she wanted to pursue.' WHERE word = 'contemplate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The science convention brought together students from schools all across the country.' WHERE word = 'convention' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The team leader helped coordinate the tasks so that everyone worked efficiently together.' WHERE word = 'coordinate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They kept up their correspondence by writing letters to each other every month.' WHERE word = 'correspondence' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The main criterion for the award is the creativity shown in the project.' WHERE word = 'criterion' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Farmers cultivate the land carefully to grow healthy crops throughout the growing season.' WHERE word = 'cultivate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She makes it a daily habit to read for at least thirty minutes.' WHERE word = 'daily' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Dairy products like milk and cheese provide calcium that strengthens your bones.' WHERE word = 'dairy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The bright yellow dandelion grew between the cracks in the concrete sidewalk.' WHERE word = 'dandelion' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We must finish the project before the deadline, which is next Friday.' WHERE word = 'deadline' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He is a decent person who always treats others with kindness and respect.' WHERE word = 'decent' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The students helped decorate the classroom with colorful paper flowers for the party.' WHERE word = 'decorate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She cares deeply about the environment and volunteers for clean-up events every weekend.' WHERE word = 'deeply' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The lawyer worked hard to defend her client and prove his innocence.' WHERE word = 'defend' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The country faces a budget deficit because it spends more than it earns.' WHERE word = 'deficit' AND level = 'mid_3';
UPDATE words SET example_sentence = 'You should definitely visit the science museum — it has amazing exhibits for students.' WHERE word = 'definitely' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The density of the population in this city has increased over the past decade.' WHERE word = 'density' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The dentist advised her to brush her teeth at least twice every day.' WHERE word = 'dentist' AND level = 'mid_3';
UPDATE words SET example_sentence = 'You need to make a deposit at the bank before the end of the month.' WHERE word = 'deposit' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Many English words derive from Latin and Greek roots that are centuries old.' WHERE word = 'derive' AND level = 'mid_3';
UPDATE words SET example_sentence = 'After dinner, they shared a chocolate dessert that was rich and delicious.' WHERE word = 'dessert' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The security camera was able to detect movement near the building at night.' WHERE word = 'detect' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The detective carefully examined the clues to find out who committed the crime.' WHERE word = 'detective' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Any deviation from the original plan must be reported to the team leader.' WHERE word = 'deviation' AND level = 'mid_3';

-- Batch 2: devote ~ interrupt
UPDATE words SET example_sentence = 'She decided to devote her free time to volunteering at the animal shelter.' WHERE word = 'devote' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The doctor was able to diagnose the illness after running several medical tests.' WHERE word = 'diagnose' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher drew a diagram on the board to explain the water cycle.' WHERE word = 'diagram' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is important to differentiate between facts and opinions when reading the news.' WHERE word = 'differentiate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The dimension of the room was too small to fit all the new furniture.' WHERE word = 'dimension' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We should never discriminate against people because of their background or appearance.' WHERE word = 'discriminate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Proper disposal of waste helps keep the environment clean and safe for everyone.' WHERE word = 'disposal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Cultural diversity makes our school a more interesting and exciting place to learn.' WHERE word = 'diversity' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She lost one of her earring somewhere between the classroom and the gym.' WHERE word = 'earring' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The earthquake shook the buildings and caused people to run outside in panic.' WHERE word = 'earthquake' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She downloaded an ebook about space exploration to read on her tablet.' WHERE word = 'ebook' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Buying items in bulk is more economical than purchasing them one at a time.' WHERE word = 'economical' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The artist created an elaborate painting with incredible detail and vibrant colors.' WHERE word = 'elaborate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We should always help elderly people carry heavy bags when they need assistance.' WHERE word = 'elderly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The elevator in the building was out of service, so we took the stairs.' WHERE word = 'elevator' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Forgetting the words during a presentation can really embarrass you in front of everyone.' WHERE word = 'embarrass' AND level = 'mid_3';
UPDATE words SET example_sentence = 'People often use emoji to express their feelings in text messages and online chats.' WHERE word = 'emoji' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher placed emphasis on the importance of understanding, not just memorizing facts.' WHERE word = 'emphasis' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Pollution and habitat loss continue to endanger many animal species around the world.' WHERE word = 'endanger' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The endless field of sunflowers stretched all the way to the distant horizon.' WHERE word = 'endless' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The government decided to enforce stricter rules to reduce air pollution in cities.' WHERE word = 'enforce' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The enhancement of the school library made it a better place for studying.' WHERE word = 'enhancement' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A school is not just a building — it is an entity with its own culture.' WHERE word = 'entity' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She put the letter inside the envelope and mailed it to her grandmother.' WHERE word = 'envelope' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He used an eraser to fix the mistake he made on his drawing.' WHERE word = 'eraser' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She spent the whole weekend writing an essay about climate change for class.' WHERE word = 'essay' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Brushing your teeth is an everyday activity that keeps your mouth healthy.' WHERE word = 'everyday' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The instructions must be followed exactly to get the right result in the experiment.' WHERE word = 'exactly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The club rules exclude anyone who does not attend the meetings regularly.' WHERE word = 'exclude' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The museum will exhibit paintings by young artists from schools across the region.' WHERE word = 'exhibit' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The fable about the tortoise and the hare teaches us the value of patience.' WHERE word = 'fable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Fairness in the classroom means giving every student an equal chance to succeed.' WHERE word = 'fairness' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She wore a fancy dress to the school dance and everyone noticed her.' WHERE word = 'fancy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The documentary about ocean life was so good that it will fascinate viewers.' WHERE word = 'fascinate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Fashion trends change every season, but personal style stays with you forever.' WHERE word = 'fashion' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It was not your fault that the experiment failed — the instructions were unclear.' WHERE word = 'fault' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The bird dropped a colorful feather on the ground near the park bench.' WHERE word = 'feather' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She stayed home from school because she had a high fever and sore throat.' WHERE word = 'fever' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The water filter removes harmful chemicals and makes the drinking water safe and clean.' WHERE word = 'filter' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Good financial planning helps families save money for future needs and emergencies.' WHERE word = 'financial' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Every person has a unique fingerprint that can be used for identification.' WHERE word = 'fingerprint' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The firework display on New Year lit up the entire night sky beautifully.' WHERE word = 'firework' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She firmly believes that education is the key to changing the world.' WHERE word = 'firmly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The fisherman caught several large fish in the river early that morning.' WHERE word = 'fisherman' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The flame of the candle flickered gently in the wind on the table.' WHERE word = 'flame' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She used a flashlight to find her way through the dark trail at camp.' WHERE word = 'flashlight' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The machine can flatten the metal sheet into a thin, smooth surface easily.' WHERE word = 'flatten' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The ice cream shop offers many different flavor choices including chocolate and mango.' WHERE word = 'flavor' AND level = 'mid_3';
UPDATE words SET example_sentence = 'This new gadget makes cooking faster and easier for people who are busy.' WHERE word = 'gadget' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Scientists estimate that there are billions of stars in our galaxy alone.' WHERE word = 'galaxy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The art gallery downtown is hosting an exhibit of photographs taken by local students.' WHERE word = 'gallery' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We parked the car in the garage because it was raining heavily outside.' WHERE word = 'garage' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Reducing the amount of garbage we produce is important for protecting the environment.' WHERE word = 'garbage' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Adding garlic to the soup gives it a rich and savory flavor.' WHERE word = 'garlic' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The price of gasoline has gone up significantly compared to last year.' WHERE word = 'gasoline' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Education is often seen as a gateway to a better future and career.' WHERE word = 'gateway' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She is a generous person who always shares what she has with others.' WHERE word = 'generous' AND level = 'mid_3';
UPDATE words SET example_sentence = 'His genuine kindness made everyone around him feel welcome and appreciated.' WHERE word = 'genuine' AND level = 'mid_3';
UPDATE words SET example_sentence = 'In geography class, we studied the mountains, rivers, and climate of East Asia.' WHERE word = 'geography' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A simple gesture like holding the door open can brighten someone entire day.' WHERE word = 'gesture' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She added fresh ginger to the tea to give it a spicy warm taste.' WHERE word = 'ginger' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He took a quick glance at his notes before starting the presentation.' WHERE word = 'glance' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A wild goose flew over the lake and landed on the water gracefully.' WHERE word = 'goose' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Spreading gossip about classmates can hurt their feelings and damage important friendships.' WHERE word = 'gossip' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The gradual change in temperature signals the transition from autumn to cold winter.' WHERE word = 'gradual' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Understanding basic grammar rules is essential for writing clear and correct English sentences.' WHERE word = 'grammar' AND level = 'mid_3';
UPDATE words SET example_sentence = 'My grandparent always tell us stories about what life was like long ago.' WHERE word = 'grandparent' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It took her a while to fully grasp the meaning of the complex theory.' WHERE word = 'grasp' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The hacker tried to break into the school computer system but was stopped.' WHERE word = 'hacker' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They ordered a large hamburger with fresh vegetables and cheese for lunch today.' WHERE word = 'hamburger' AND level = 'mid_3';
UPDATE words SET example_sentence = 'This handy tool makes it easy to fix small things around the house.' WHERE word = 'handy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She could hardly believe that she won first place in the speech contest.' WHERE word = 'hardly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The computer hardware was upgraded so that the lab could run faster programs.' WHERE word = 'hardware' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Certain chemicals in cleaning products can be harmful to both people and animals.' WHERE word = 'harmful' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The choir worked hard to harmonize their voices for the school concert performance.' WHERE word = 'harmonize' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Farmers usually harvest their crops in the fall when they are fully ripe.' WHERE word = 'harvest' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The helicopter flew over the mountain to rescue the hikers who were stranded.' WHERE word = 'helicopter' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Always wear a helmet when riding a bicycle to protect your head from injury.' WHERE word = 'helmet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The heroine of the story saved her village from danger through her bravery.' WHERE word = 'heroine' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She did not hesitate to help her friend who was struggling with the homework.' WHERE word = 'hesitate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Having a hobby like painting or playing music helps reduce stress after school.' WHERE word = 'hobby' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school hockey team practiced every day to prepare for the championship game.' WHERE word = 'hockey' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The sun slowly set below the horizon, painting the sky in shades of orange.' WHERE word = 'horizon' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The tip of the iceberg was visible above the water, but most of it was below.' WHERE word = 'iceberg' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is illegal to park in front of the fire station at any time.' WHERE word = 'illegal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Proper rest and good nutrition can help prevent serious illness during the winter.' WHERE word = 'illness' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The firefighters took immediate action to put out the fire before it spread.' WHERE word = 'immediate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The main ingredient in this recipe is fresh tomato from the local farm.' WHERE word = 'ingredient' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He had to sit out the game because he managed to injure his ankle.' WHERE word = 'injure' AND level = 'mid_3';
UPDATE words SET example_sentence = 'If you want more information about the program, feel free to inquire at the office.' WHERE word = 'inquire' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The students studied different types of insect life during the biology field trip.' WHERE word = 'insect' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She continued to insist that her idea was the best solution to the problem.' WHERE word = 'insist' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Great teachers have the ability to inspire their students to dream bigger goals.' WHERE word = 'inspire' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The technician came to install the new software on all the school computers.' WHERE word = 'install' AND level = 'mid_3';
UPDATE words SET example_sentence = 'In this instance, the teacher allowed students to work together on the assignment.' WHERE word = 'instance' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Instead of watching TV, she decided to read a novel before going to bed.' WHERE word = 'instead' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The intense heat of the summer made it difficult to exercise outside safely.' WHERE word = 'intense' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The internet has changed the way people learn, communicate, and share information.' WHERE word = 'internet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She was asked to interpret the poem and explain its deeper meaning to class.' WHERE word = 'interpret' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Please do not interrupt the speaker — wait until she finishes her point.' WHERE word = 'interrupt' AND level = 'mid_3';

-- Batch 3: interview ~ rainbow
UPDATE words SET example_sentence = 'The journalist conducted an interview with the mayor about the new education policy.' WHERE word = 'interview' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She received an invitation to the science competition held at the national university.' WHERE word = 'invitation' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A large jellyfish was spotted floating near the shore at the beach yesterday.' WHERE word = 'jellyfish' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The journalist wrote an article about how schools are using technology for learning.' WHERE word = 'journalist' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The judge carefully listened to both sides before making a fair decision.' WHERE word = 'judge' AND level = 'mid_3';
UPDATE words SET example_sentence = 'As a junior member of the team, she still has a lot to learn.' WHERE word = 'junior' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He tried to justify his late arrival by saying the bus had broken down.' WHERE word = 'justify' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She put the kettle on the stove to boil water for hot tea.' WHERE word = 'kettle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He types so fast on the keyboard that he can finish reports quickly.' WHERE word = 'keyboard' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The ancient kingdom was known for its beautiful castles and rich cultural traditions.' WHERE word = 'kingdom' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The store sells kitchenware such as pots, pans, and other cooking tools.' WHERE word = 'kitchenware' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Always read the label on food products to check the nutrition information carefully.' WHERE word = 'label' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The airplane made a smooth landing at the airport despite the strong crosswind.' WHERE word = 'landing' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They hung a beautiful lantern outside the front door to celebrate the festival.' WHERE word = 'lantern' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She brought her laptop to class so she could take notes during the lecture.' WHERE word = 'laptop' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He does his own laundry every weekend to help out with chores at home.' WHERE word = 'laundry' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The lawyer presented strong evidence in court to prove that her client was innocent.' WHERE word = 'lawyer' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school handed out a leaflet about the upcoming science fair to every student.' WHERE word = 'leaflet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Having enough leisure time is important for reducing stress and staying mentally healthy.' WHERE word = 'leisure' AND level = 'mid_3';
UPDATE words SET example_sentence = 'On hot summer days, a cold glass of lemonade is the perfect refreshing drink.' WHERE word = 'lemonade' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The length of the bridge is about three hundred meters from one end to the other.' WHERE word = 'length' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The most important lesson I learned this year is to never give up easily.' WHERE word = 'lesson' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The librarian helped us find reliable sources for our history research project.' WHERE word = 'librarian' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The lifeguard watched the swimmers carefully to make sure everyone stayed safe in the pool.' WHERE word = 'lifeguard' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Reading is a lifelong habit that continues to bring joy and knowledge at any age.' WHERE word = 'lifelong' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The lighthouse on the cliff guided ships safely through the fog at night.' WHERE word = 'lighthouse' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A bright flash of lightning lit up the entire sky during the thunderstorm.' WHERE word = 'lightning' AND level = 'mid_3';
UPDATE words SET example_sentence = 'With hard work and creativity, the possibilities for your future are truly limitless.' WHERE word = 'limitless' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She accidentally left her lipstick in the school bathroom after the morning assembly.' WHERE word = 'lipstick' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The machine in the factory can produce hundreds of bottles in just one hour.' WHERE word = 'machine' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher used a magnet to demonstrate how opposite poles attract each other.' WHERE word = 'magnet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She checked the mailbox every afternoon hoping for a letter from her pen pal.' WHERE word = 'mailbox' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She learned how to apply natural-looking makeup by watching online tutorial videos.' WHERE word = 'makeup' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The company plans to manufacture eco-friendly products using recycled materials from the ocean.' WHERE word = 'manufacture' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Running a marathon requires months of training and strong mental determination.' WHERE word = 'marathon' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The floor of the old palace was made of smooth, shiny marble stone.' WHERE word = 'marble' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The local marketplace is always crowded on weekends with families buying fresh food.' WHERE word = 'marketplace' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A relaxing neck massage can help relieve tension after a long day of studying.' WHERE word = 'massage' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The massive earthquake destroyed many buildings and left thousands of people without homes.' WHERE word = 'massive' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She has always loved mathematics and dreams of becoming an engineer one day.' WHERE word = 'mathematics' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A comfortable mattress is important for getting a good night of sleep every night.' WHERE word = 'mattress' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She became more mature after spending a year living away from her family.' WHERE word = 'mature' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Volunteering at the shelter was one of the most meaningful experiences of her life.' WHERE word = 'meaningful' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She finished her homework and meanwhile her brother was preparing dinner in the kitchen.' WHERE word = 'meanwhile' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Accurate measurements are essential for getting the right results in a science experiment.' WHERE word = 'measurements' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She won a gold medal at the national swimming competition held last summer.' WHERE word = 'medal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Modern medicine has helped cure many diseases that were once considered untreatable.' WHERE word = 'medicine' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher made a brief mention of the upcoming field trip during morning class.' WHERE word = 'mention' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The narrative of the novel follows a young girl who travels through time.' WHERE word = 'narrative' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The narrow path through the forest was just wide enough for one person.' WHERE word = 'narrow' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The nationwide campaign encouraged people to recycle more and reduce plastic waste.' WHERE word = 'nationwide' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She wore a beautiful silver necklace that her grandmother had given her last year.' WHERE word = 'necklace' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The doctor used a small needle to give the patient a flu vaccine.' WHERE word = 'needle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Try not to have a negative attitude when facing challenges — stay positive instead.' WHERE word = 'negative' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The two countries agreed to negotiate a peaceful solution to their border dispute.' WHERE word = 'negotiate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Her nickname at school was Sunny because she always had a bright smile.' WHERE word = 'nickname' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He had a terrible nightmare about being lost in a dark forest alone.' WHERE word = 'nightmare' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She always carries a small notebook to write down ideas whenever they come.' WHERE word = 'notebook' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The novelty of the new phone wore off after just a few weeks.' WHERE word = 'novelty' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Accidents can occur at any time, so it is important to always be careful.' WHERE word = 'occur' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The octopus used its eight arms to open a jar that was tightly sealed.' WHERE word = 'octopus' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Be careful not to offend people by making jokes about things that are sensitive.' WHERE word = 'offend' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The police officer directed traffic at the intersection while the signal was broken.' WHERE word = 'officer' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Many students prefer to take online classes because they can study from home.' WHERE word = 'online' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They went to the opera house to watch a famous musical performance together.' WHERE word = 'opera' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The satellite travels in a fixed orbit around the Earth every ninety minutes.' WHERE word = 'orbit' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The apple orchard was full of ripe fruit ready to be picked in autumn.' WHERE word = 'orchard' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The heart is a vital organ that pumps blood throughout the entire body.' WHERE word = 'organ' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school organized an orient program to help new students adjust to campus life.' WHERE word = 'orient' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Before writing the essay, she made an outline of the main ideas and arguments.' WHERE word = 'outline' AND level = 'mid_3';
UPDATE words SET example_sentence = 'With enough effort and determination, you can overcome any obstacle in your path.' WHERE word = 'overcome' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She traveled overseas for the first time and visited museums in several European countries.' WHERE word = 'overseas' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He grabbed a packet of crackers from his bag for a quick afternoon snack.' WHERE word = 'packet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They used a paddle to steer the small boat through the calm river.' WHERE word = 'paddle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The volunteers handed out a pamphlet with information about recycling to every household.' WHERE word = 'pamphlet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'When the fire alarm went off, some students started to panic and run.' WHERE word = 'panic' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She spent the whole morning doing paperwork for the student council election.' WHERE word = 'paperwork' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The colorful parade marched through the streets of the city during the festival.' WHERE word = 'parade' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Each paragraph of the essay should focus on one main idea with supporting details.' WHERE word = 'paragraph' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Parental support plays a key role in helping children succeed at school.' WHERE word = 'parental' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The colorful parrot repeated every word that the visitor said in a funny voice.' WHERE word = 'parrot' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She was particular about keeping her desk neat and organized at all times.' WHERE word = 'particular' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He is passionate about music and practices the guitar for two hours every day.' WHERE word = 'passionate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'You must carry a valid passport when traveling to another country by airplane.' WHERE word = 'passport' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Choose a strong password that includes numbers, letters, and special characters for safety.' WHERE word = 'password' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The nurse placed a small patch on his arm after giving him the injection.' WHERE word = 'patch' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The stone pathway through the garden was lined with beautiful flowers on both sides.' WHERE word = 'pathway' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Learning a musical instrument requires patience because progress comes slowly over many months.' WHERE word = 'patience' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The patient waited calmly in the hospital room for the doctor to arrive.' WHERE word = 'patient' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She packed a peanut butter sandwich for lunch because it was her favorite food.' WHERE word = 'peanut' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The diver found a beautiful pearl inside a large shell at the bottom of the sea.' WHERE word = 'pearl' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The whole building shook during the quake, and everyone rushed outside to safety.' WHERE word = 'quake' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She finished about a quarter of the book on the first day of reading.' WHERE word = 'quarter' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The students filled out a questionnaire about their study habits and learning preferences.' WHERE word = 'questionnaire' AND level = 'mid_3';
UPDATE words SET example_sentence = 'There was a long queue at the cafeteria because a new menu was introduced.' WHERE word = 'queue' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She quickly finished her homework so she could play outside with her friends.' WHERE word = 'quickly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He quietly left the room so he would not wake anyone who was sleeping.' WHERE word = 'quietly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher shared an inspiring quote about perseverance at the beginning of class.' WHERE word = 'quote' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She bought a new racquet for the badminton tournament at school next week.' WHERE word = 'racquet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The railway connects the two cities and makes it easy to travel between them.' WHERE word = 'railway' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A beautiful rainbow appeared in the sky right after the afternoon rain stopped.' WHERE word = 'rainbow' AND level = 'mid_3';

-- Batch 4: raise ~ yield
UPDATE words SET example_sentence = 'The students helped raise money for charity by organizing a bake sale at school.' WHERE word = 'raise' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher selected students in random order to present their projects to the class.' WHERE word = 'random' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The rapid growth of the city has changed the landscape of the entire area.' WHERE word = 'rapid' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She rarely misses a class because she values her education and attendance record.' WHERE word = 'rarely' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It took her a moment to realize that she had left her phone at home.' WHERE word = 'realize' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The price of the meal was reasonable, so we decided to eat there again.' WHERE word = 'reasonable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Always keep the receipt in case you need to return the product later.' WHERE word = 'receipt' AND level = 'mid_3';
UPDATE words SET example_sentence = 'I did not recognize her at first because she had changed her hairstyle completely.' WHERE word = 'recognize' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We should recycle paper, plastic, and glass to reduce waste and protect the environment.' WHERE word = 'recycle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'You can refill your water bottle at the fountain near the school entrance.' WHERE word = 'refill' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She put the leftover food in the refrigerator so it would stay fresh.' WHERE word = 'refrigerator' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The store offered a full refund because the product was damaged when it arrived.' WHERE word = 'refund' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She decided to refuse the invitation because she had too much homework to finish.' WHERE word = 'refuse' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Students who exercise regularly tend to perform better on tests and stay healthier.' WHERE word = 'regularly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The committee had to reject the proposal because it did not meet the requirements.' WHERE word = 'reject' AND level = 'mid_3';
UPDATE words SET example_sentence = 'After a long week of exams, she finally had time to relax at home.' WHERE word = 'relax' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The athletes worked as a team to relay the baton quickly around the track.' WHERE word = 'relay' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He had to sacrifice his free time to prepare for the national competition.' WHERE word = 'sacrifice' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She ordered a fresh salad with tomatoes, cucumbers, and lettuce for lunch today.' WHERE word = 'salad' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Teachers deserve a higher salary because of the important role they play in society.' WHERE word = 'salary' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She wore a comfortable pair of sandal to walk along the sandy beach.' WHERE word = 'sandal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The satellite sends data back to Earth that helps scientists predict the weather.' WHERE word = 'satellite' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The results of the experiment were enough to satisfy the requirements of the assignment.' WHERE word = 'satisfy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The pasta tasted even better with the homemade tomato sauce her mother prepared.' WHERE word = 'sauce' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The office scanner quickly turned the paper document into a digital file.' WHERE word = 'scanner' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Science helps us understand the natural world and solve problems that affect society.' WHERE word = 'science' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The scientist discovered a new way to turn plastic waste into useful energy.' WHERE word = 'scientist' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The restaurant near the coast is famous for its fresh and delicious seafood.' WHERE word = 'seafood' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Wearing seasonal clothing helps your body adjust to changes in temperature and weather.' WHERE word = 'seasonal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The secretary organized all the meeting documents and sent them to every team member.' WHERE word = 'secretary' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Make sure your online accounts are secure by using strong and unique passwords.' WHERE word = 'secure' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school increased security by installing cameras at every entrance to the building.' WHERE word = 'security' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She plans to improve her grades during the second semester by studying more.' WHERE word = 'semester' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It would be sensible to bring an umbrella because rain is expected later today.' WHERE word = 'sensible' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The teacher asked each student to write one sentence using the new vocabulary word.' WHERE word = 'sentence' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is important to separate recyclable items from regular trash before throwing them away.' WHERE word = 'separate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She uses her tablet to read books, watch videos, and take notes for class.' WHERE word = 'tablet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The team worked together to tackle the difficult problem and find a creative solution.' WHERE word = 'tackle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The airplane had a smooth takeoff despite the strong winds at the airport today.' WHERE word = 'takeoff' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The talented young pianist won first place at the national music competition this year.' WHERE word = 'talented' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She peeled a fresh tangerine and shared the sweet pieces with her friends.' WHERE word = 'tangerine' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Her teammate encouraged her to keep trying even when the game was going badly.' WHERE word = 'teammate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'There was growing tension between the two groups before the debate competition started.' WHERE word = 'tension' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The terrible storm knocked down trees and caused power outages across the whole city.' WHERE word = 'terrible' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The horror movie was so scary that it could terrify even the bravest viewer.' WHERE word = 'terrify' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Each student must bring their own textbook to class starting from next Monday.' WHERE word = 'textbook' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The factory produces textile materials that are used to make clothes and furniture covers.' WHERE word = 'textile' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The nurse used a thermometer to check whether the student had a high fever.' WHERE word = 'thermometer' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Climate change poses a serious threat to wildlife and natural ecosystems around the world.' WHERE word = 'threat' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The loud thunder scared the dog, and it hid under the bed immediately.' WHERE word = 'thunder' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Please tighten the screws on the shelf so that it does not fall down.' WHERE word = 'tighten' AND level = 'mid_3';
UPDATE words SET example_sentence = 'We must learn to tolerate different opinions if we want to live in peace.' WHERE word = 'tolerate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The ultimate goal of the project is to make clean water available to everyone.' WHERE word = 'ultimate' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She was unable to attend the meeting because she had a doctor appointment.' WHERE word = 'unable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Make sure to pack enough underwear and socks for the five-day school camping trip.' WHERE word = 'underwear' AND level = 'mid_3';
UPDATE words SET example_sentence = 'It is unfair to judge people based on their appearance rather than their character.' WHERE word = 'unfair' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Eating too much fast food is unhealthy and can lead to serious health problems.' WHERE word = 'unhealthy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Every person is unique and has special talents that make them different from others.' WHERE word = 'unique' AND level = 'mid_3';
UPDATE words SET example_sentence = 'People from different backgrounds can unite to solve problems that affect the whole community.' WHERE word = 'unite' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Access to clean water should be a universal right for every person on Earth.' WHERE word = 'universal' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Scientists continue to explore the universe in search of planets that could support life.' WHERE word = 'universe' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The cause of the power failure remained unknown until the repair team arrived.' WHERE word = 'unknown' AND level = 'mid_3';
UPDATE words SET example_sentence = 'You should update your phone software regularly to keep it running smoothly and safely.' WHERE word = 'update' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She had to upload her completed assignment to the school website before midnight.' WHERE word = 'upload' AND level = 'mid_3';
UPDATE words SET example_sentence = 'More people are moving to urban areas in search of better jobs and education.' WHERE word = 'urban' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She used the vacuum to clean the carpet before the guests arrived at home.' WHERE word = 'vacuum' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Your student ID card must be valid to enter the library after school hours.' WHERE word = 'valid' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The beautiful valley between the mountains was covered with wildflowers in the spring.' WHERE word = 'valley' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Eating a variety of vegetable every day is essential for staying healthy and strong.' WHERE word = 'vegetable' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Starting a new business venture requires careful planning, hard work, and some courage.' WHERE word = 'venture' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She watched a short video about the history of ancient civilizations for her project.' WHERE word = 'video' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Listening to different viewpoint helps you understand problems from many angles before deciding.' WHERE word = 'viewpoint' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The young violinist performed beautifully at the school concert and received a standing ovation.' WHERE word = 'violinist' AND level = 'mid_3';
UPDATE words SET example_sentence = 'A computer virus can damage your files, so always keep your antivirus software updated.' WHERE word = 'virus' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The stars were clearly visible in the night sky because there were no clouds.' WHERE word = 'visible' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Reading books is one of the best ways to build a strong vocabulary over time.' WHERE word = 'vocabulary' AND level = 'mid_3';
UPDATE words SET example_sentence = 'They ordered a crispy waffle with fresh strawberries and cream for breakfast at the cafe.' WHERE word = 'waffle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'He put his wallet in his front pocket to keep it safe from pickpockets.' WHERE word = 'wallet' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She loved to wander through the old streets of the town and explore new shops.' WHERE word = 'wander' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Using too many paper cups is wasteful when you can bring your own bottle.' WHERE word = 'wasteful' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The waterfall in the mountains was so tall that we could hear it from far away.' WHERE word = 'waterfall' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She wore a waterproof jacket to stay dry during the hike in the rain.' WHERE word = 'waterproof' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The wealthy businessman donated a large sum of money to build a new school.' WHERE word = 'wealthy' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She turned on the webcam so that her grandparents could see her during the video call.' WHERE word = 'webcam' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school website has all the information you need about events and important dates.' WHERE word = 'website' AND level = 'mid_3';
UPDATE words SET example_sentence = 'On a weekday morning, the subway is always crowded with students and office workers.' WHERE word = 'weekday' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The doctor asked her to weigh herself to check her health progress this month.' WHERE word = 'weigh' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school installed a ramp so that students in a wheelchair could access every floor.' WHERE word = 'wheelchair' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She had to whisper the answer because the teacher was standing right nearby.' WHERE word = 'whisper' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The referee blew the whistle to signal the end of the soccer match.' WHERE word = 'whistle' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The city plans to widen the road to reduce traffic congestion during rush hour.' WHERE word = 'widen' AND level = 'mid_3';
UPDATE words SET example_sentence = 'She is willing to help anyone who asks for her assistance after class.' WHERE word = 'willing' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The winner of the science fair received a trophy and a certificate of achievement.' WHERE word = 'winner' AND level = 'mid_3';
UPDATE words SET example_sentence = 'During wintertime, the lake freezes over and people enjoy ice skating on its surface.' WHERE word = 'wintertime' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Xenon is a chemical element that is used in special lighting and medical equipment.' WHERE word = 'xenon' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Some people use xylitol as a sugar substitute because it is better for teeth.' WHERE word = 'xylitol' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The music teacher showed the children how to play simple notes on the xylophone.' WHERE word = 'xylophone' AND level = 'mid_3';
UPDATE words SET example_sentence = 'The school holds a yearly festival where students showcase their talents and creative work.' WHERE word = 'yearly' AND level = 'mid_3';
UPDATE words SET example_sentence = 'Hard work and dedication will eventually yield great results in both school and life.' WHERE word = 'yield' AND level = 'mid_3';
