-- ============================================================
-- 영단어 학습 앱 - 통합 초기화 스크립트 (동기화 완료)
-- ============================================================

-- 1. 기존 테이블 삭제
DROP TABLE IF EXISTS public.battle_rooms CASCADE;
DROP TABLE IF EXISTS public.study_logs  CASCADE;
DROP TABLE IF EXISTS public.profiles    CASCADE;
DROP TABLE IF EXISTS public.words       CASCADE;

-- 2. words 테이블 생성
CREATE TABLE public.words (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type       text NOT NULL DEFAULT 'word',
  level      text NOT NULL,
  set_no     int  NOT NULL,
  word       text NOT NULL,
  mean_1     text NOT NULL,
  mean_2     text,                   
  mean_3     text,                   
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_words_level_set ON public.words (level, set_no);
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "words_read_all" ON public.words FOR SELECT USING (true);

-- 3. battle_rooms 테이블 생성
CREATE TABLE public.battle_rooms (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  room_code varchar(6) NOT NULL UNIQUE,
  host_id uuid NOT NULL,
  guest_id uuid,
  status varchar(20) NOT NULL DEFAULT 'waiting',
  level varchar(50) NOT NULL,
  set_no integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.battle_rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view rooms" ON public.battle_rooms FOR SELECT USING (true);
CREATE POLICY "Auth users can create" ON public.battle_rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Participants can update" ON public.battle_rooms FOR UPDATE USING (true);

-- 4. profiles 테이블 생성
CREATE TABLE public.profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_self" ON public.profiles FOR ALL USING (auth.uid() = id);

-- 5. 단어 데이터 입력 (DB와 동기화됨: 1000개)
INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3) VALUES
  ('word', 'elem_low', 1, 'apple', '사과', NULL, NULL),
  ('word', 'elem_low', 1, 'book', '책', NULL, NULL),
  ('word', 'elem_low', 1, 'cat', '고양이', NULL, NULL),
  ('word', 'elem_low', 1, 'dog', '개', NULL, NULL),
  ('word', 'elem_low', 1, 'egg', '달걀', '계란', NULL),
  ('word', 'elem_low', 1, 'fish', '물고기', '생선', NULL),
  ('word', 'elem_low', 1, 'girl', '소녀', '여자아이', NULL),
  ('word', 'elem_low', 1, 'hand', '손', NULL, NULL),
  ('word', 'elem_low', 1, 'ice', '얼음', NULL, NULL),
  ('word', 'elem_low', 1, 'jump', '점프하다', '뛰다', NULL),
  ('word', 'elem_low', 1, 'king', '왕', '임금', NULL),
  ('word', 'elem_low', 1, 'lion', '사자', NULL, NULL),
  ('word', 'elem_low', 1, 'mom', '엄마', NULL, NULL),
  ('word', 'elem_low', 1, 'nose', '코', NULL, NULL),
  ('word', 'elem_low', 1, 'orange', '오렌지', '주황색', NULL),
  ('word', 'elem_low', 1, 'pig', '돼지', NULL, NULL),
  ('word', 'elem_low', 1, 'queen', '여왕', NULL, NULL),
  ('word', 'elem_low', 1, 'rain', '비', '비가 오다', NULL),
  ('word', 'elem_low', 1, 'sun', '태양', '해', NULL),
  ('word', 'elem_low', 1, 'tree', '나무', NULL, NULL),
  ('word', 'elem_low', 2, 'water', '물', NULL, NULL),
  ('word', 'elem_low', 2, 'milk', '우유', NULL, NULL),
  ('word', 'elem_low', 2, 'bread', '빵', NULL, NULL),
  ('word', 'elem_low', 2, 'school', '학교', NULL, NULL),
  ('word', 'elem_low', 2, 'teacher', '선생님', NULL, NULL),
  ('word', 'elem_low', 2, 'friend', '친구', NULL, NULL),
  ('word', 'elem_low', 2, 'house', '집', NULL, NULL),
  ('word', 'elem_low', 2, 'door', '문', NULL, NULL),
  ('word', 'elem_low', 2, 'window', '창문', NULL, NULL),
  ('word', 'elem_low', 2, 'chair', '의자', NULL, NULL),
  ('word', 'elem_low', 2, 'desk', '책상', NULL, NULL),
  ('word', 'elem_low', 2, 'pencil', '연필', NULL, NULL),
  ('word', 'elem_low', 2, 'bag', '가방', NULL, NULL),
  ('word', 'elem_low', 2, 'ball', '공', NULL, NULL),
  ('word', 'elem_low', 2, 'bird', '새', NULL, NULL),
  ('word', 'elem_low', 2, 'cow', '소', NULL, NULL),
  ('word', 'elem_low', 2, 'duck', '오리', NULL, NULL),
  ('word', 'elem_low', 2, 'fire', '불', NULL, NULL),
  ('word', 'elem_low', 2, 'star', '별', NULL, NULL),
  ('word', 'elem_low', 2, 'moon', '달', NULL, NULL),
  ('word', 'elem_low', 3, 'red', '빨간색', NULL, NULL),
  ('word', 'elem_low', 3, 'blue', '파란색', NULL, NULL),
  ('word', 'elem_low', 3, 'green', '초록색', NULL, NULL),
  ('word', 'elem_low', 3, 'yellow', '노란색', NULL, NULL),
  ('word', 'elem_low', 3, 'white', '흰색', NULL, NULL),
  ('word', 'elem_low', 3, 'black', '검은색', NULL, NULL),
  ('word', 'elem_low', 3, 'big', '큰', NULL, NULL),
  ('word', 'elem_low', 3, 'small', '작은', NULL, NULL),
  ('word', 'elem_low', 3, 'long', '긴', NULL, NULL),
  ('word', 'elem_low', 3, 'short', '짧은', NULL, NULL),
  ('word', 'elem_low', 3, 'fast', '빠른', NULL, NULL),
  ('word', 'elem_low', 3, 'slow', '느린', NULL, NULL),
  ('word', 'elem_low', 3, 'happy', '행복한', NULL, NULL),
  ('word', 'elem_low', 3, 'sad', '슬픈', NULL, NULL),
  ('word', 'elem_low', 3, 'hot', '뜨거운', '더운', NULL),
  ('word', 'elem_low', 3, 'cold', '차가운', '추운', NULL),
  ('word', 'elem_low', 3, 'good', '좋은', NULL, NULL),
  ('word', 'elem_low', 3, 'bad', '나쁜', NULL, NULL),
  ('word', 'elem_low', 3, 'old', '오래된', '나이든', NULL),
  ('word', 'elem_low', 3, 'new', '새로운', NULL, NULL),
  ('word', 'elem_low', 4, 'bread', '빵', NULL, NULL),
  ('word', 'elem_low', 4, 'butter', '버터', NULL, NULL),
  ('word', 'elem_low', 4, 'cheese', '치즈', NULL, NULL),
  ('word', 'elem_low', 4, 'rice', '밥', '쌀', NULL),
  ('word', 'elem_low', 4, 'soup', '수프', NULL, NULL),
  ('word', 'elem_low', 4, 'cake', '케이크', NULL, NULL),
  ('word', 'elem_low', 4, 'cookie', '과자', '쿠키', NULL),
  ('word', 'elem_low', 4, 'juice', '주스', NULL, NULL),
  ('word', 'elem_low', 4, 'tea', '차', '마시는 차', NULL),
  ('word', 'elem_low', 4, 'cup', '컵', NULL, NULL),
  ('word', 'elem_low', 4, 'plate', '접시', NULL, NULL),
  ('word', 'elem_low', 4, 'fork', '포크', NULL, NULL),
  ('word', 'elem_low', 4, 'knife', '칼', NULL, NULL),
  ('word', 'elem_low', 4, 'spoon', '숟가락', NULL, NULL),
  ('word', 'elem_low', 4, 'breakfast', '아침식사', NULL, NULL),
  ('word', 'elem_low', 4, 'lunch', '점심식사', NULL, NULL),
  ('word', 'elem_low', 4, 'dinner', '저녁식사', NULL, NULL),
  ('word', 'elem_low', 4, 'cook', '요리하다', '요리사', NULL),
  ('word', 'elem_low', 4, 'eat', '먹다', NULL, NULL),
  ('word', 'elem_low', 4, 'drink', '마시다', NULL, NULL),
  ('word', 'elem_low', 5, 'school', '학교', NULL, NULL),
  ('word', 'elem_low', 5, 'class', '수업', '반', NULL),
  ('word', 'elem_low', 5, 'teacher', '선생님', NULL, NULL),
  ('word', 'elem_low', 5, 'student', '학생', NULL, NULL),
  ('word', 'elem_low', 5, 'friend', '친구', NULL, NULL),
  ('word', 'elem_low', 5, 'desk', '책상', NULL, NULL),
  ('word', 'elem_low', 5, 'chair', '의자', NULL, NULL),
  ('word', 'elem_low', 5, 'book', '책', NULL, NULL),
  ('word', 'elem_low', 5, 'notebook', '공책', NULL, NULL),
  ('word', 'elem_low', 5, 'pencil', '연필', NULL, NULL),
  ('word', 'elem_low', 5, 'eraser', '지우개', NULL, NULL),
  ('word', 'elem_low', 5, 'ruler', '자', NULL, NULL),
  ('word', 'elem_low', 5, 'bag', '가방', NULL, NULL),
  ('word', 'elem_low', 5, 'room', '방', NULL, NULL),
  ('word', 'elem_low', 5, 'floor', '바닥', '층', NULL),
  ('word', 'elem_low', 5, 'wall', '벽', NULL, NULL),
  ('word', 'elem_low', 5, 'window', '창문', NULL, NULL),
  ('word', 'elem_low', 5, 'door', '문', NULL, NULL),
  ('word', 'elem_low', 5, 'open', '열다', NULL, NULL),
  ('word', 'elem_low', 5, 'close', '닫다', NULL, NULL),
  ('word', 'elem_low', 6, 'one', '하나', NULL, NULL),
  ('word', 'elem_low', 6, 'two', '둘', NULL, NULL),
  ('word', 'elem_low', 6, 'three', '셋', NULL, NULL),
  ('word', 'elem_low', 6, 'four', '넷', NULL, NULL),
  ('word', 'elem_low', 6, 'five', '다섯', NULL, NULL),
  ('word', 'elem_low', 6, 'six', '여섯', NULL, NULL),
  ('word', 'elem_low', 6, 'seven', '일곱', NULL, NULL),
  ('word', 'elem_low', 6, 'eight', '여덟', NULL, NULL),
  ('word', 'elem_low', 6, 'nine', '아홉', NULL, NULL),
  ('word', 'elem_low', 6, 'ten', '열', NULL, NULL),
  ('word', 'elem_low', 6, 'first', '첫 번째의', NULL, NULL),
  ('word', 'elem_low', 6, 'second', '두 번째의', NULL, NULL),
  ('word', 'elem_low', 6, 'third', '세 번째의', NULL, NULL),
  ('word', 'elem_low', 6, 'sunday', '일요일', NULL, NULL),
  ('word', 'elem_low', 6, 'monday', '월요일', NULL, NULL),
  ('word', 'elem_low', 6, 'tuesday', '화요일', NULL, NULL),
  ('word', 'elem_low', 6, 'wednesday', '수요일', NULL, NULL),
  ('word', 'elem_low', 6, 'thursday', '목요일', NULL, NULL),
  ('word', 'elem_low', 6, 'friday', '금요일', NULL, NULL),
  ('word', 'elem_low', 6, 'saturday', '토요일', NULL, NULL),
  ('word', 'elem_low', 7, 'body', '몸', NULL, NULL),
  ('word', 'elem_low', 7, 'head', '머리', NULL, NULL),
  ('word', 'elem_low', 7, 'hair', '머리카락', NULL, NULL),
  ('word', 'elem_low', 7, 'face', '얼굴', NULL, NULL),
  ('word', 'elem_low', 7, 'eye', '눈', NULL, NULL),
  ('word', 'elem_low', 7, 'ear', '귀', NULL, NULL),
  ('word', 'elem_low', 7, 'nose', '코', NULL, NULL),
  ('word', 'elem_low', 7, 'mouth', '입', NULL, NULL),
  ('word', 'elem_low', 7, 'tooth', '치아', '이', NULL),
  ('word', 'elem_low', 7, 'neck', '목', NULL, NULL),
  ('word', 'elem_low', 7, 'shoulder', '어깨', NULL, NULL),
  ('word', 'elem_low', 7, 'arm', '팔', NULL, NULL),
  ('word', 'elem_low', 7, 'hand', '손', NULL, NULL),
  ('word', 'elem_low', 7, 'finger', '손가락', NULL, NULL),
  ('word', 'elem_low', 7, 'leg', '다리', NULL, NULL),
  ('word', 'elem_low', 7, 'knee', '무릎', NULL, NULL),
  ('word', 'elem_low', 7, 'foot', '발', NULL, NULL),
  ('word', 'elem_low', 7, 'toe', '발가락', NULL, NULL),
  ('word', 'elem_low', 7, 'tall', '키가 큰', NULL, NULL),
  ('word', 'elem_low', 7, 'short', '키가 작은', '짧은', NULL),
  ('word', 'elem_low', 8, 'park', '공원', NULL, NULL),
  ('word', 'elem_low', 8, 'tree', '나무', NULL, NULL),
  ('word', 'elem_low', 8, 'flower', '꽃', NULL, NULL),
  ('word', 'elem_low', 8, 'grass', '풀', '잔디', NULL),
  ('word', 'elem_low', 8, 'sky', '하늘', NULL, NULL),
  ('word', 'elem_low', 8, 'sun', '태양', '해', NULL),
  ('word', 'elem_low', 8, 'moon', '달', NULL, NULL),
  ('word', 'elem_low', 8, 'star', '별', NULL, NULL),
  ('word', 'elem_low', 8, 'cloud', '구름', NULL, NULL),
  ('word', 'elem_low', 8, 'bird', '새', NULL, NULL),
  ('word', 'elem_low', 8, 'animal', '동물', NULL, NULL),
  ('word', 'elem_low', 8, 'zoo', '동물원', NULL, NULL),
  ('word', 'elem_low', 8, 'mountain', '산', NULL, NULL),
  ('word', 'elem_low', 8, 'river', '강', NULL, NULL),
  ('word', 'elem_low', 8, 'sea', '바다', NULL, NULL),
  ('word', 'elem_low', 8, 'stone', '돌', NULL, NULL),
  ('word', 'elem_low', 8, 'wind', '바람', NULL, NULL),
  ('word', 'elem_low', 8, 'snow', '눈', NULL, NULL),
  ('word', 'elem_low', 8, 'weather', '날씨', NULL, NULL),
  ('word', 'elem_low', 8, 'nature', '자연', NULL, NULL),
  ('word', 'elem_low', 9, 'car', '자동차', NULL, NULL),
  ('word', 'elem_low', 9, 'bus', '버스', NULL, NULL),
  ('word', 'elem_low', 9, 'train', '기차', NULL, NULL),
  ('word', 'elem_low', 9, 'bike', '자전거', NULL, NULL),
  ('word', 'elem_low', 9, 'plane', '비행기', NULL, NULL),
  ('word', 'elem_low', 9, 'ship', '배', '선박', NULL),
  ('word', 'elem_low', 9, 'boat', '보트', NULL, NULL),
  ('word', 'elem_low', 9, 'street', '거리', '길', NULL),
  ('word', 'elem_low', 9, 'road', '도로', NULL, NULL),
  ('word', 'elem_low', 9, 'bridge', '다리', '교량', NULL),
  ('word', 'elem_low', 9, 'station', '역', NULL, NULL),
  ('word', 'elem_low', 9, 'stop', '멈추다', '정거장', NULL),
  ('word', 'elem_low', 9, 'go', '가다', NULL, NULL),
  ('word', 'elem_low', 9, 'run', '달리다', NULL, NULL),
  ('word', 'elem_low', 9, 'walk', '걷다', NULL, NULL),
  ('word', 'elem_low', 9, 'drive', '운전하다', NULL, NULL),
  ('word', 'elem_low', 9, 'fast', '빠른', NULL, NULL),
  ('word', 'elem_low', 9, 'slow', '느린', NULL, NULL),
  ('word', 'elem_low', 9, 'left', '왼쪽', NULL, NULL),
  ('word', 'elem_low', 9, 'right', '오른쪽', NULL, NULL),
  ('word', 'elem_low', 10, 'happy', '행복한', NULL, NULL),
  ('word', 'elem_low', 10, 'sad', '슬픈', NULL, NULL),
  ('word', 'elem_low', 10, 'angry', '화난', NULL, NULL),
  ('word', 'elem_low', 10, 'scared', '무서워하는', NULL, NULL),
  ('word', 'elem_low', 10, 'tired', '피곤한', NULL, NULL),
  ('word', 'elem_low', 10, 'hungry', '배고픈', NULL, NULL),
  ('word', 'elem_low', 10, 'thirsty', '목마른', NULL, NULL),
  ('word', 'elem_low', 10, 'hot', '더운', '뜨거운', NULL),
  ('word', 'elem_low', 10, 'cold', '추운', '차가운', NULL),
  ('word', 'elem_low', 10, 'good', '좋은', NULL, NULL),
  ('word', 'elem_low', 10, 'bad', '나쁜', NULL, NULL),
  ('word', 'elem_low', 10, 'pretty', '예쁜', NULL, NULL),
  ('word', 'elem_low', 10, 'cute', '귀여운', NULL, NULL),
  ('word', 'elem_low', 10, 'strong', '강한', NULL, NULL),
  ('word', 'elem_low', 10, 'weak', '약한', NULL, NULL),
  ('word', 'elem_low', 10, 'smart', '똑똑한', NULL, NULL),
  ('word', 'elem_low', 10, 'kind', '친절한', NULL, NULL),
  ('word', 'elem_low', 10, 'brave', '용감한', NULL, NULL),
  ('word', 'elem_low', 10, 'funny', '웃긴', '재미있는', NULL),
  ('word', 'elem_low', 10, 'quiet', '조용한', NULL, NULL),
  ('word', 'elem_low', 11, 'home', '집', NULL, NULL),
  ('word', 'elem_low', 11, 'kitchen', '주방', '부엌', NULL),
  ('word', 'elem_low', 11, 'bathroom', '화장실', '욕실', NULL),
  ('word', 'elem_low', 11, 'bed', '침대', NULL, NULL),
  ('word', 'elem_low', 11, 'table', '식탁', '테이블', NULL),
  ('word', 'elem_low', 11, 'clock', '시계', NULL, NULL),
  ('word', 'elem_low', 11, 'phone', '전화기', NULL, NULL),
  ('word', 'elem_low', 11, 'radio', '라디오', NULL, NULL),
  ('word', 'elem_low', 11, 'tv', '텔레비전', NULL, NULL),
  ('word', 'elem_low', 11, 'computer', '컴퓨터', NULL, NULL),
  ('word', 'elem_low', 11, 'lamp', '램프', '등', NULL),
  ('word', 'elem_low', 11, 'soap', '비누', NULL, NULL),
  ('word', 'elem_low', 11, 'towel', '수건', NULL, NULL),
  ('word', 'elem_low', 11, 'brush', '빗', '솔', NULL),
  ('word', 'elem_low', 11, 'toy', '장난감', NULL, NULL),
  ('word', 'elem_low', 11, 'doll', '인형', NULL, NULL),
  ('word', 'elem_low', 11, 'box', '상자', NULL, NULL),
  ('word', 'elem_low', 11, 'paper', '종이', NULL, NULL),
  ('word', 'elem_low', 11, 'money', '돈', NULL, NULL),
  ('word', 'elem_low', 11, 'gift', '선물', NULL, NULL),
  ('word', 'elem_low', 12, 'clothes', '옷', NULL, NULL),
  ('word', 'elem_low', 12, 'shirt', '셔츠', NULL, NULL),
  ('word', 'elem_low', 12, 'pants', '바지', NULL, NULL),
  ('word', 'elem_low', 12, 'dress', '드레스', NULL, NULL),
  ('word', 'elem_low', 12, 'skirt', '치마', NULL, NULL),
  ('word', 'elem_low', 12, 'coat', '코트', NULL, NULL),
  ('word', 'elem_low', 12, 'hat', '모자', NULL, NULL),
  ('word', 'elem_low', 12, 'cap', '모자', '야구모자', NULL),
  ('word', 'elem_low', 12, 'shoes', '신발', NULL, NULL),
  ('word', 'elem_low', 12, 'socks', '양말', NULL, NULL),
  ('word', 'elem_low', 12, 'glove', '장갑', NULL, NULL),
  ('word', 'elem_low', 12, 'watch', '손목시계', '보다', NULL),
  ('word', 'elem_low', 12, 'glasses', '안경', NULL, NULL),
  ('word', 'elem_low', 12, 'umbrella', '우산', NULL, NULL),
  ('word', 'elem_low', 12, 'wear', '입다', '쓰다', NULL),
  ('word', 'elem_low', 12, 'take off', '벗다', NULL, NULL),
  ('word', 'elem_low', 12, 'wash', '씻다', NULL, NULL),
  ('word', 'elem_low', 12, 'clean', '깨끗한', '청소하다', NULL),
  ('word', 'elem_low', 12, 'dirty', '더러운', NULL, NULL),
  ('word', 'elem_low', 12, 'color', '색깔', NULL, NULL),
  ('word', 'elem_low', 13, 'morning', '아침', NULL, NULL),
  ('word', 'elem_low', 13, 'afternoon', '오후', NULL, NULL),
  ('word', 'elem_low', 13, 'evening', '저녁', NULL, NULL),
  ('word', 'elem_low', 13, 'night', '밤', NULL, NULL),
  ('word', 'elem_low', 13, 'today', '오늘', NULL, NULL),
  ('word', 'elem_low', 13, 'yesterday', '어제', NULL, NULL),
  ('word', 'elem_low', 13, 'tomorrow', '내일', NULL, NULL),
  ('word', 'elem_low', 13, 'week', '주', '일주일', NULL),
  ('word', 'elem_low', 13, 'month', '달', '월', NULL),
  ('word', 'elem_low', 13, 'year', '해', '년', NULL),
  ('word', 'elem_low', 13, 'time', '시간', NULL, NULL),
  ('word', 'elem_low', 13, 'clock', '시계', NULL, NULL),
  ('word', 'elem_low', 13, 'hour', '시간', NULL, NULL),
  ('word', 'elem_low', 13, 'minute', '분', NULL, NULL),
  ('word', 'elem_low', 13, 'second', '초', NULL, NULL),
  ('word', 'elem_low', 13, 'early', '이른', '빨리', NULL),
  ('word', 'elem_low', 13, 'late', '늦은', '늦게', NULL),
  ('word', 'elem_low', 13, 'now', '지금', NULL, NULL),
  ('word', 'elem_low', 13, 'always', '항상', NULL, NULL),
  ('word', 'elem_low', 13, 'never', '결코 ~않다', NULL, NULL),
  ('word', 'elem_low', 14, 'spring', '봄', NULL, NULL),
  ('word', 'elem_low', 14, 'summer', '여름', NULL, NULL),
  ('word', 'elem_low', 14, 'fall', '가을', '떨어지다', NULL),
  ('word', 'elem_low', 14, 'winter', '겨울', NULL, NULL),
  ('word', 'elem_low', 14, 'warm', '따뜻한', NULL, NULL),
  ('word', 'elem_low', 14, 'cool', '시원한', '멋진', NULL),
  ('word', 'elem_low', 14, 'sunny', '화창한', NULL, NULL),
  ('word', 'elem_low', 14, 'cloudy', '흐린', NULL, NULL),
  ('word', 'elem_low', 14, 'rainy', '비오는', NULL, NULL),
  ('word', 'elem_low', 14, 'snowy', '눈오는', NULL, NULL),
  ('word', 'elem_low', 14, 'windy', '바람 부는', NULL, NULL),
  ('word', 'elem_low', 14, 'earth', '지구', '땅', NULL),
  ('word', 'elem_low', 14, 'world', '세계', NULL, NULL),
  ('word', 'elem_low', 14, 'country', '나라', '국가', NULL),
  ('word', 'elem_low', 14, 'city', '도시', NULL, NULL),
  ('word', 'elem_low', 14, 'village', '마을', NULL, NULL),
  ('word', 'elem_low', 14, 'sea', '바다', NULL, NULL),
  ('word', 'elem_low', 14, 'island', '섬', NULL, NULL),
  ('word', 'elem_low', 14, 'forest', '숲', NULL, NULL),
  ('word', 'elem_low', 14, 'field', '들판', '분야', NULL),
  ('word', 'elem_low', 15, 'play', '놀다', '연주하다', '경기하다'),
  ('word', 'elem_low', 15, 'sing', '노래하다', NULL, NULL),
  ('word', 'elem_low', 15, 'dance', '춤추다', NULL, NULL),
  ('word', 'elem_low', 15, 'draw', '그리다', NULL, NULL),
  ('word', 'elem_low', 15, 'paint', '칠하다', '그리다', NULL),
  ('word', 'elem_low', 15, 'write', '쓰다', NULL, NULL),
  ('word', 'elem_low', 15, 'read', '읽다', NULL, NULL),
  ('word', 'elem_low', 15, 'study', '공부하다', NULL, NULL),
  ('word', 'elem_low', 15, 'learn', '배우다', NULL, NULL),
  ('word', 'elem_low', 15, 'listen', '듣다', NULL, NULL),
  ('word', 'elem_low', 15, 'speak', '말하다', NULL, NULL),
  ('word', 'elem_low', 15, 'sleep', '자다', NULL, NULL),
  ('word', 'elem_low', 15, 'wake up', '깨다', '일어나다', NULL),
  ('word', 'elem_low', 15, 'sit', '앉다', NULL, NULL),
  ('word', 'elem_low', 15, 'stand', '서다', NULL, NULL),
  ('word', 'elem_low', 15, 'swim', '수영하다', NULL, NULL),
  ('word', 'elem_low', 15, 'fly', '날다', NULL, NULL),
  ('word', 'elem_low', 15, 'help', '돕다', NULL, NULL),
  ('word', 'elem_low', 15, 'love', '사랑하다', NULL, NULL),
  ('word', 'elem_low', 15, 'like', '좋아하다', '~처럼', NULL),
  ('word', 'elem_low', 16, 'big', '큰', NULL, NULL),
  ('word', 'elem_low', 16, 'small', '작은', NULL, NULL),
  ('word', 'elem_low', 16, 'long', '긴', NULL, NULL),
  ('word', 'elem_low', 16, 'short', '짧은', '키가 작은', NULL),
  ('word', 'elem_low', 16, 'heavy', '무거운', NULL, NULL),
  ('word', 'elem_low', 16, 'light', '가벼운', '빛', NULL),
  ('word', 'elem_low', 16, 'full', '가득 찬', '배부른', NULL),
  ('word', 'elem_low', 16, 'empty', '비어 있는', NULL, NULL),
  ('word', 'elem_low', 16, 'new', '새로운', NULL, NULL),
  ('word', 'elem_low', 16, 'old', '오래된', '나이 든', NULL),
  ('word', 'elem_low', 16, 'clean', '깨끗한', NULL, NULL),
  ('word', 'elem_low', 16, 'dirty', '더러운', NULL, NULL),
  ('word', 'elem_low', 16, 'hard', '딱딱한', '어려운', '열심히'),
  ('word', 'elem_low', 16, 'soft', '부드러운', NULL, NULL),
  ('word', 'elem_low', 16, 'fast', '빠른', NULL, NULL),
  ('word', 'elem_low', 16, 'slow', '느린', NULL, NULL),
  ('word', 'elem_low', 16, 'high', '높은', NULL, NULL),
  ('word', 'elem_low', 16, 'low', '낮은', NULL, NULL),
  ('word', 'elem_low', 16, 'easy', '쉬운', NULL, NULL),
  ('word', 'elem_low', 16, 'difficult', '어려운', NULL, NULL),
  ('word', 'elem_low', 17, 'up', '위로', NULL, NULL),
  ('word', 'elem_low', 17, 'down', '아래로', NULL, NULL),
  ('word', 'elem_low', 17, 'in', '안에', NULL, NULL),
  ('word', 'elem_low', 17, 'out', '밖에', NULL, NULL),
  ('word', 'elem_low', 17, 'on', '위에', NULL, NULL),
  ('word', 'elem_low', 17, 'under', '아래에', NULL, NULL),
  ('word', 'elem_low', 17, 'near', '가까이', NULL, NULL),
  ('word', 'elem_low', 17, 'far', '멀리', NULL, NULL),
  ('word', 'elem_low', 17, 'front', '앞', NULL, NULL),
  ('word', 'elem_low', 17, 'back', '뒤', NULL, NULL),
  ('word', 'elem_low', 17, 'top', '꼭대기', NULL, NULL),
  ('word', 'elem_low', 17, 'bottom', '바닥', NULL, NULL),
  ('word', 'elem_low', 17, 'left', '왼쪽', NULL, NULL),
  ('word', 'elem_low', 17, 'right', '오른쪽', NULL, NULL),
  ('word', 'elem_low', 17, 'here', '여기', NULL, NULL),
  ('word', 'elem_low', 17, 'there', '저기', NULL, NULL),
  ('word', 'elem_low', 17, 'inside', '내부', NULL, NULL),
  ('word', 'elem_low', 17, 'outside', '외부', NULL, NULL),
  ('word', 'elem_low', 17, 'between', '사이에', NULL, NULL),
  ('word', 'elem_low', 17, 'beside', '옆에', NULL, NULL),
  ('word', 'elem_low', 18, 'always', '항상', NULL, NULL),
  ('word', 'elem_low', 18, 'usually', '보통', NULL, NULL),
  ('word', 'elem_low', 18, 'often', '자주', NULL, NULL),
  ('word', 'elem_low', 18, 'sometimes', '때때로', NULL, NULL),
  ('word', 'elem_low', 18, 'never', '결코 ~않다', NULL, NULL),
  ('word', 'elem_low', 18, 'early', '일찍', NULL, NULL),
  ('word', 'elem_low', 18, 'late', '늦게', NULL, NULL),
  ('word', 'elem_low', 18, 'soon', '곧', NULL, NULL),
  ('word', 'elem_low', 18, 'already', '이미', NULL, NULL),
  ('word', 'elem_low', 18, 'yet', '아직', NULL, NULL),
  ('word', 'elem_low', 18, 'still', '여전히', NULL, NULL),
  ('word', 'elem_low', 18, 'again', '다시', NULL, NULL),
  ('word', 'elem_low', 18, 'together', '함께', NULL, NULL),
  ('word', 'elem_low', 18, 'alone', '혼자', NULL, NULL),
  ('word', 'elem_low', 18, 'very', '매우', NULL, NULL),
  ('word', 'elem_low', 18, 'really', '정말로', NULL, NULL),
  ('word', 'elem_low', 18, 'well', '잘', NULL, NULL),
  ('word', 'elem_low', 18, 'fast', '빨리', NULL, NULL),
  ('word', 'elem_low', 18, 'slowly', '느리게', NULL, NULL),
  ('word', 'elem_low', 18, 'quietly', '조용히', NULL, NULL),
  ('word', 'elem_low', 19, 'i', '나', NULL, NULL),
  ('word', 'elem_low', 19, 'you', '너', NULL, NULL),
  ('word', 'elem_low', 19, 'he', '그', NULL, NULL),
  ('word', 'elem_low', 19, 'she', '그녀', NULL, NULL),
  ('word', 'elem_low', 19, 'it', '그것', NULL, NULL),
  ('word', 'elem_low', 19, 'we', '우리', NULL, NULL),
  ('word', 'elem_low', 19, 'they', '그들', NULL, NULL),
  ('word', 'elem_low', 19, 'my', '나의', NULL, NULL),
  ('word', 'elem_low', 19, 'your', '너의', NULL, NULL),
  ('word', 'elem_low', 19, 'his', '그의', NULL, NULL),
  ('word', 'elem_low', 19, 'her', '그녀의', NULL, NULL),
  ('word', 'elem_low', 19, 'its', '그것의', NULL, NULL),
  ('word', 'elem_low', 19, 'our', '우리의', NULL, NULL),
  ('word', 'elem_low', 19, 'their', '그들의', NULL, NULL),
  ('word', 'elem_low', 19, 'me', '나를', NULL, NULL),
  ('word', 'elem_low', 19, 'him', '그를', NULL, NULL),
  ('word', 'elem_low', 19, 'them', '그들을', NULL, NULL),
  ('word', 'elem_low', 19, 'this', '이것', NULL, NULL),
  ('word', 'elem_low', 19, 'that', '저것', NULL, NULL),
  ('word', 'elem_low', 19, 'who', '누구', NULL, NULL),
  ('word', 'elem_low', 20, 'what', '무엇', NULL, NULL),
  ('word', 'elem_low', 20, 'when', '언제', NULL, NULL),
  ('word', 'elem_low', 20, 'where', '어디', NULL, NULL),
  ('word', 'elem_low', 20, 'why', '왜', NULL, NULL),
  ('word', 'elem_low', 20, 'how', '어떻게', NULL, NULL),
  ('word', 'elem_low', 20, 'which', '어느 것', NULL, NULL),
  ('word', 'elem_low', 20, 'yes', '예', NULL, NULL),
  ('word', 'elem_low', 20, 'no', '아니오', NULL, NULL),
  ('word', 'elem_low', 20, 'and', '그리고', NULL, NULL),
  ('word', 'elem_low', 20, 'but', '그러나', NULL, NULL),
  ('word', 'elem_low', 20, 'or', '또는', NULL, NULL),
  ('word', 'elem_low', 20, 'so', '그래서', NULL, NULL),
  ('word', 'elem_low', 20, 'because', '때문에', NULL, NULL),
  ('word', 'elem_low', 20, 'with', '함께', NULL, NULL),
  ('word', 'elem_low', 20, 'for', '위하여', NULL, NULL),
  ('word', 'elem_low', 20, 'from', '로부터', NULL, NULL),
  ('word', 'elem_low', 20, 'to', '에게', '로', NULL),
  ('word', 'elem_low', 20, 'about', '대하여', NULL, NULL),
  ('word', 'elem_low', 20, 'if', '만약', NULL, NULL),
  ('word', 'elem_low', 20, 'like', '~처럼', '좋아하다', NULL),
  ('word', 'elem_low', 21, 'sky', '하늘', NULL, NULL),
  ('word', 'elem_low', 21, 'cloud', '구름', NULL, NULL),
  ('word', 'elem_low', 21, 'sun', '해', NULL, NULL),
  ('word', 'elem_low', 21, 'moon', '달', NULL, NULL),
  ('word', 'elem_low', 21, 'star', '별', NULL, NULL),
  ('word', 'elem_low', 21, 'rain', '비', NULL, NULL),
  ('word', 'elem_low', 21, 'snow', '눈', NULL, NULL),
  ('word', 'elem_low', 21, 'wind', '바람', NULL, NULL),
  ('word', 'elem_low', 21, 'weather', '날씨', NULL, NULL),
  ('word', 'elem_low', 21, 'mountain', '산', NULL, NULL),
  ('word', 'elem_low', 21, 'sea', '바다', NULL, NULL),
  ('word', 'elem_low', 21, 'river', '강', NULL, NULL),
  ('word', 'elem_low', 21, 'tree', '나무', NULL, NULL),
  ('word', 'elem_low', 21, 'flower', '꽃', NULL, NULL),
  ('word', 'elem_low', 21, 'grass', '풀', NULL, NULL),
  ('word', 'elem_low', 21, 'leaf', '잎', NULL, NULL),
  ('word', 'elem_low', 21, 'animal', '동물', NULL, NULL),
  ('word', 'elem_low', 21, 'bird', '새', NULL, NULL),
  ('word', 'elem_low', 21, 'fish', '물고기', NULL, NULL),
  ('word', 'elem_low', 21, 'bug', '벌레', NULL, NULL),
  ('word', 'elem_low', 22, 'doctor', '의사', NULL, NULL),
  ('word', 'elem_low', 22, 'nurse', '간호사', NULL, NULL),
  ('word', 'elem_low', 22, 'police', '경찰', NULL, NULL),
  ('word', 'elem_low', 22, 'singer', '가수', NULL, NULL),
  ('word', 'elem_low', 22, 'dancer', '무용수', NULL, NULL),
  ('word', 'elem_low', 22, 'pilot', '조종사', NULL, NULL),
  ('word', 'elem_low', 22, 'cook', '요리사', NULL, NULL),
  ('word', 'elem_low', 22, 'baker', '제빵사', NULL, NULL),
  ('word', 'elem_low', 22, 'farmer', '농부', NULL, NULL),
  ('word', 'elem_low', 22, 'driver', '운전사', NULL, NULL),
  ('word', 'elem_low', 22, 'worker', '노동자', NULL, NULL),
  ('word', 'elem_low', 22, 'job', '직업', NULL, NULL),
  ('word', 'elem_low', 22, 'work', '일하다', NULL, NULL),
  ('word', 'elem_low', 22, 'help', '돕다', NULL, NULL),
  ('word', 'elem_low', 22, 'make', '만들다', NULL, NULL),
  ('word', 'elem_low', 22, 'build', '짓다', NULL, NULL),
  ('word', 'elem_low', 22, 'sell', '팔다', NULL, NULL),
  ('word', 'elem_low', 22, 'buy', '사다', NULL, NULL),
  ('word', 'elem_low', 22, 'use', '사용하다', NULL, NULL),
  ('word', 'elem_low', 22, 'fix', '고치다', NULL, NULL),
  ('word', 'elem_low', 23, 'red', '빨간색', NULL, NULL),
  ('word', 'elem_low', 23, 'blue', '파란색', NULL, NULL),
  ('word', 'elem_low', 23, 'yellow', '노란색', NULL, NULL),
  ('word', 'elem_low', 23, 'green', '초록색', NULL, NULL),
  ('word', 'elem_low', 23, 'orange', '주황색', NULL, NULL),
  ('word', 'elem_low', 23, 'purple', '보라색', NULL, NULL),
  ('word', 'elem_low', 23, 'pink', '분홍색', NULL, NULL),
  ('word', 'elem_low', 23, 'white', '흰색', NULL, NULL),
  ('word', 'elem_low', 23, 'black', '검정색', NULL, NULL),
  ('word', 'elem_low', 23, 'gray', '회색', NULL, NULL),
  ('word', 'elem_low', 23, 'brown', '갈색', NULL, NULL),
  ('word', 'elem_low', 23, 'circle', '원', NULL, NULL),
  ('word', 'elem_low', 23, 'square', '사각형', NULL, NULL),
  ('word', 'elem_low', 23, 'triangle', '삼각형', NULL, NULL),
  ('word', 'elem_low', 23, 'star', '별 모양', NULL, NULL),
  ('word', 'elem_low', 23, 'heart', '하트 모양', NULL, NULL),
  ('word', 'elem_low', 23, 'line', '선', NULL, NULL),
  ('word', 'elem_low', 23, 'point', '점', NULL, NULL),
  ('word', 'elem_low', 23, 'long', '긴', NULL, NULL),
  ('word', 'elem_low', 23, 'round', '둥근', NULL, NULL),
  ('word', 'elem_low', 24, 'one', '1', NULL, NULL),
  ('word', 'elem_low', 24, 'two', '2', NULL, NULL),
  ('word', 'elem_low', 24, 'three', '3', NULL, NULL),
  ('word', 'elem_low', 24, 'four', '4', NULL, NULL),
  ('word', 'elem_low', 24, 'five', '5', NULL, NULL),
  ('word', 'elem_low', 24, 'six', '6', NULL, NULL),
  ('word', 'elem_low', 24, 'seven', '7', NULL, NULL),
  ('word', 'elem_low', 24, 'eight', '8', NULL, NULL),
  ('word', 'elem_low', 24, 'nine', '9', NULL, NULL),
  ('word', 'elem_low', 24, 'ten', '10', NULL, NULL),
  ('word', 'elem_low', 24, 'eleven', '11', NULL, NULL),
  ('word', 'elem_low', 24, 'twelve', '12', NULL, NULL),
  ('word', 'elem_low', 24, 'thirteen', '13', NULL, NULL),
  ('word', 'elem_low', 24, 'fourteen', '14', NULL, NULL),
  ('word', 'elem_low', 24, 'fifteen', '15', NULL, NULL),
  ('word', 'elem_low', 24, 'twenty', '20', NULL, NULL),
  ('word', 'elem_low', 24, 'thirty', '30', NULL, NULL),
  ('word', 'elem_low', 24, 'hundred', '100', NULL, NULL),
  ('word', 'elem_low', 24, 'first', '첫 번째', NULL, NULL),
  ('word', 'elem_low', 24, 'second', '두 번째', NULL, NULL),
  ('word', 'elem_low', 25, 'spring', '봄', NULL, NULL),
  ('word', 'elem_low', 25, 'summer', '여름', NULL, NULL),
  ('word', 'elem_low', 25, 'fall', '가을', NULL, NULL),
  ('word', 'elem_low', 25, 'winter', '겨울', NULL, NULL),
  ('word', 'elem_low', 25, 'january', '1월', NULL, NULL),
  ('word', 'elem_low', 25, 'february', '2월', NULL, NULL),
  ('word', 'elem_low', 25, 'march', '3월', NULL, NULL),
  ('word', 'elem_low', 25, 'april', '4월', NULL, NULL),
  ('word', 'elem_low', 25, 'may', '5월', NULL, NULL),
  ('word', 'elem_low', 25, 'june', '6월', NULL, NULL),
  ('word', 'elem_low', 25, 'july', '7월', NULL, NULL),
  ('word', 'elem_low', 25, 'august', '8월', NULL, NULL),
  ('word', 'elem_low', 25, 'september', '9월', NULL, NULL),
  ('word', 'elem_low', 25, 'october', '10월', NULL, NULL),
  ('word', 'elem_low', 25, 'november', '11월', NULL, NULL),
  ('word', 'elem_low', 25, 'december', '12월', NULL, NULL),
  ('word', 'elem_low', 25, 'holiday', '휴일', NULL, NULL),
  ('word', 'elem_low', 25, 'birthday', '생일', NULL, NULL),
  ('word', 'elem_low', 25, 'party', '파티', NULL, NULL),
  ('word', 'elem_low', 25, 'festival', '축제', NULL, NULL),
  ('word', 'middle_1', 1, 'accept', '받아들이다', '수락하다', NULL),
  ('word', 'middle_1', 1, 'advice', '조언', '충고', NULL),
  ('word', 'middle_1', 1, 'affect', '영향을 미치다', NULL, NULL),
  ('word', 'middle_1', 1, 'agree', '동의하다', '찬성하다', NULL),
  ('word', 'middle_1', 1, 'allow', '허락하다', '허가하다', NULL),
  ('word', 'middle_1', 1, 'amazing', '놀라운', '멋진', NULL),
  ('word', 'middle_1', 1, 'amount', '양', '액수', NULL),
  ('word', 'middle_1', 1, 'ancient', '고대의', '옛날의', NULL),
  ('word', 'middle_1', 1, 'appear', '나타나다', '~인 것 같다', NULL),
  ('word', 'middle_1', 1, 'area', '지역', '구역', NULL),
  ('word', 'middle_1', 1, 'arrange', '정리하다', '배열하다', NULL),
  ('word', 'middle_1', 1, 'arrive', '도착하다', NULL, NULL),
  ('word', 'middle_1', 1, 'article', '기사', '물품', NULL),
  ('word', 'middle_1', 1, 'artist', '예술가', '화가', NULL),
  ('word', 'middle_1', 1, 'asleep', '잠든', NULL, NULL),
  ('word', 'middle_1', 1, 'attend', '참석하다', '다니다', NULL),
  ('word', 'middle_1', 1, 'attitude', '태도', '자세', NULL),
  ('word', 'middle_1', 1, 'attract', '끌어들이다', '매혹하다', NULL),
  ('word', 'middle_1', 1, 'audience', '관객', '청중', NULL),
  ('word', 'middle_1', 1, 'average', '평균', '보통의', NULL),
  ('word', 'middle_1', 2, 'balance', '균형', '잔고', NULL),
  ('word', 'middle_1', 2, 'balloon', '풍선', NULL, NULL),
  ('word', 'middle_1', 2, 'band', '밴드', '끈', NULL),
  ('word', 'middle_1', 2, 'bank', '은행', '강둑', NULL),
  ('word', 'middle_1', 2, 'base', '기초', '토대', NULL),
  ('word', 'middle_1', 2, 'basket', '바구니', NULL, NULL),
  ('word', 'middle_1', 2, 'beach', '해변', '바닷가', NULL),
  ('word', 'middle_1', 2, 'beat', '이기다', '두드리다', NULL),
  ('word', 'middle_1', 2, 'beautiful', '아름다운', NULL, NULL),
  ('word', 'middle_1', 2, 'become', '~이 되다', NULL, NULL),
  ('word', 'middle_1', 2, 'before', '~전에', NULL, NULL),
  ('word', 'middle_1', 2, 'begin', '시작하다', NULL, NULL),
  ('word', 'middle_1', 2, 'behind', '~뒤에', NULL, NULL),
  ('word', 'middle_1', 2, 'believe', '믿다', NULL, NULL),
  ('word', 'middle_1', 2, 'below', '~아래에', NULL, NULL),
  ('word', 'middle_1', 2, 'beside', '~옆에', NULL, NULL),
  ('word', 'middle_1', 2, 'best', '최고의', NULL, NULL),
  ('word', 'middle_1', 2, 'better', '더 좋은', NULL, NULL),
  ('word', 'middle_1', 2, 'between', '~사이에', NULL, NULL),
  ('word', 'middle_1', 2, 'beyond', '~저머에', '넘어서', NULL),
  ('word', 'middle_1', 3, 'bicycle', '자전거', NULL, NULL),
  ('word', 'middle_1', 3, 'bill', '고지서', '지폐', NULL),
  ('word', 'middle_1', 3, 'birth', '탄생', '출생', NULL),
  ('word', 'middle_1', 3, 'blank', '빈칸', '공백의', NULL),
  ('word', 'middle_1', 3, 'blood', '피', '혈액', NULL),
  ('word', 'middle_1', 3, 'blow', '불다', NULL, NULL),
  ('word', 'middle_1', 3, 'board', '판자', '게시판', '탑승하다'),
  ('word', 'middle_1', 3, 'borrow', '빌리다', NULL, NULL),
  ('word', 'middle_1', 3, 'bottle', '병', NULL, NULL),
  ('word', 'middle_1', 3, 'bottom', '바닥', '맨 아래', NULL),
  ('word', 'middle_1', 3, 'bowl', '그릇', NULL, NULL),
  ('word', 'middle_1', 3, 'brain', '뇌', '두뇌', NULL),
  ('word', 'middle_1', 3, 'branch', '나뭇가지', '지점', NULL),
  ('word', 'middle_1', 3, 'brave', '용감한', NULL, NULL),
  ('word', 'middle_1', 3, 'bridge', '다리', '교량', NULL),
  ('word', 'middle_1', 3, 'bright', '밝은', '똑똑한', NULL),
  ('word', 'middle_1', 3, 'bring', '가져오다', NULL, NULL),
  ('word', 'middle_1', 3, 'brush', '붓', '솔', '질하다'),
  ('word', 'middle_1', 3, 'build', '짓다', '세우다', NULL),
  ('word', 'middle_1', 3, 'burn', '타다', '태우다', NULL),
  ('word', 'middle_1', 4, 'button', '단추', '버튼', NULL),
  ('word', 'middle_1', 4, 'calm', '침착한', '진정시키다', NULL),
  ('word', 'middle_1', 4, 'camera', '카메라', NULL, NULL),
  ('word', 'middle_1', 4, 'camp', '캠프', '야영하다', NULL),
  ('word', 'middle_1', 4, 'candle', '양초', NULL, NULL),
  ('word', 'middle_1', 4, 'capital', '수도', '대문자', '자본'),
  ('word', 'middle_1', 4, 'captain', '장교', '선장', '주장'),
  ('word', 'middle_1', 4, 'care', '돌봄', '관심', '걱정하다'),
  ('word', 'middle_1', 4, 'careful', '조심스러운', NULL, NULL),
  ('word', 'middle_1', 4, 'carry', '나르다', '휴대하다', NULL),
  ('word', 'middle_1', 4, 'case', '경우', '사건', '상자'),
  ('word', 'middle_1', 4, 'castle', '성', NULL, NULL),
  ('word', 'middle_1', 4, 'catch', '잡다', NULL, NULL),
  ('word', 'middle_1', 4, 'cause', '원인', '일으키다', NULL),
  ('word', 'middle_1', 4, 'ceiling', '천장', NULL, NULL),
  ('word', 'middle_1', 4, 'celebrate', '축하하다', NULL, NULL),
  ('word', 'middle_1', 4, 'center', '중심', '중앙', NULL),
  ('word', 'middle_1', 4, 'century', '세기', '100년', NULL),
  ('word', 'middle_1', 4, 'certain', '확실한', '어떤', NULL),
  ('word', 'middle_1', 4, 'chance', '기회', '가능성', NULL),
  ('word', 'middle_1', 5, 'change', '바꾸다', '변화', '잔돈'),
  ('word', 'middle_1', 5, 'charge', '요금', '책임', '충전하다'),
  ('word', 'middle_1', 5, 'cheap', '싼', '저렴한', NULL),
  ('word', 'middle_1', 5, 'cheat', '속이다', '부정행위를 하다', NULL),
  ('word', 'middle_1', 5, 'check', '확인하다', '수표', NULL),
  ('word', 'middle_1', 5, 'cheer', '응원하다', '환호', NULL),
  ('word', 'middle_1', 5, 'chest', '가슴', '상자', NULL),
  ('word', 'middle_1', 5, 'choice', '선택', NULL, NULL),
  ('word', 'middle_1', 5, 'choose', '고르다', '선택하다', NULL),
  ('word', 'middle_1', 5, 'circle', '원', '동그라미', NULL),
  ('word', 'middle_1', 5, 'city', '도시', NULL, NULL),
  ('word', 'middle_1', 5, 'class', '수업', '학급', '종류'),
  ('word', 'middle_1', 5, 'clever', '영리한', '똑똑한', NULL),
  ('word', 'middle_1', 5, 'climb', '오르다', '등반하다', NULL),
  ('word', 'middle_1', 5, 'clock', '시계', NULL, NULL),
  ('word', 'middle_1', 5, 'close', '닫다', '가까운', NULL),
  ('word', 'middle_1', 5, 'cloth', '천', '헝겊', NULL),
  ('word', 'middle_1', 5, 'cloud', '구름', NULL, NULL),
  ('word', 'middle_1', 5, 'coach', '코치', '지도하다', NULL),
  ('word', 'middle_1', 5, 'coast', '해안', NULL, NULL),
  ('word', 'middle_1', 6, 'collect', '모으다', '수집하다', NULL),
  ('word', 'middle_1', 6, 'college', '대학', NULL, NULL),
  ('word', 'middle_1', 6, 'comfort', '편안함', '위로하다', NULL),
  ('word', 'middle_1', 6, 'common', '공통의', '흔한', NULL),
  ('word', 'middle_1', 6, 'compare', '비교하다', NULL, NULL),
  ('word', 'middle_1', 6, 'complain', '불평하다', NULL, NULL),
  ('word', 'middle_1', 6, 'complete', '완성하다', '완전한', NULL),
  ('word', 'middle_1', 6, 'condition', '상태', '조건', NULL),
  ('word', 'middle_1', 6, 'connect', '연결하다', NULL, NULL),
  ('word', 'middle_1', 6, 'consider', '고려하다', '~라고 여기다', NULL),
  ('word', 'middle_1', 6, 'contain', '포함하다', '들어있다', NULL),
  ('word', 'middle_1', 6, 'continue', '계속하다', NULL, NULL),
  ('word', 'middle_1', 6, 'control', '조절하다', '지배하다', NULL),
  ('word', 'middle_1', 6, 'corner', '모퉁이', NULL, NULL),
  ('word', 'middle_1', 6, 'correct', '맞는', '수정하다', NULL),
  ('word', 'middle_1', 6, 'cost', '비용', '비용이 들다', NULL),
  ('word', 'middle_1', 6, 'count', '세다', '계산하다', NULL),
  ('word', 'middle_1', 6, 'couple', '쌍', '부부', NULL),
  ('word', 'middle_1', 6, 'course', '과정', '강좌', NULL),
  ('word', 'middle_1', 6, 'court', '법원', '경기장', NULL),
  ('word', 'middle_1', 7, 'cover', '덮다', '표지', NULL),
  ('word', 'middle_1', 7, 'create', '창조하다', '만들다', NULL),
  ('word', 'middle_1', 7, 'cross', '건너다', '십자가', NULL),
  ('word', 'middle_1', 7, 'crowd', '군중', '무표', NULL),
  ('word', 'middle_1', 7, 'cruel', '잔인한', NULL, NULL),
  ('word', 'middle_1', 7, 'culture', '문화', NULL, NULL),
  ('word', 'middle_1', 7, 'curious', '궁금한', NULL, NULL),
  ('word', 'middle_1', 7, 'curtain', '커튼', NULL, NULL),
  ('word', 'middle_1', 7, 'custom', '관습', '습관', NULL),
  ('word', 'middle_1', 7, 'cycle', '순환', '자전거를 타다', NULL),
  ('word', 'middle_1', 7, 'daily', '매일의', NULL, NULL),
  ('word', 'middle_1', 7, 'damage', '손상', '피해를 입히다', NULL),
  ('word', 'middle_1', 7, 'danger', '위험', NULL, NULL),
  ('word', 'middle_1', 7, 'dark', '어두운', NULL, NULL),
  ('word', 'middle_1', 7, 'date', '날짜', '데이트', NULL),
  ('word', 'middle_1', 7, 'dead', '죽은', NULL, NULL),
  ('word', 'middle_1', 7, 'deal', '다루다', '거래', NULL),
  ('word', 'middle_1', 7, 'death', '죽음', NULL, NULL),
  ('word', 'middle_1', 7, 'decide', '결정하다', NULL, NULL),
  ('word', 'middle_1', 7, 'deep', '깊은', NULL, NULL),
  ('word', 'middle_1', 8, 'degree', '도', '학위', NULL),
  ('word', 'middle_1', 8, 'delay', '미루다', '연기하다', NULL),
  ('word', 'middle_1', 8, 'deliver', '배달하다', NULL, NULL),
  ('word', 'middle_1', 8, 'depend', '의존하다', NULL, NULL),
  ('word', 'middle_1', 8, 'describe', '묘사하다', '설명하다', NULL),
  ('word', 'middle_1', 8, 'desert', '사막', '버리다', NULL),
  ('word', 'middle_1', 8, 'design', '디자인', '설계하다', NULL),
  ('word', 'middle_1', 8, 'desire', '욕구', '바라다', NULL),
  ('word', 'middle_1', 8, 'detail', '세부사항', NULL, NULL),
  ('word', 'middle_1', 8, 'develop', '발달시키다', '개발하다', NULL),
  ('word', 'middle_1', 8, 'dictionary', '사전', NULL, NULL),
  ('word', 'middle_1', 8, 'difference', '차이', NULL, NULL),
  ('word', 'middle_1', 8, 'direction', '방향', '지시', NULL),
  ('word', 'middle_1', 8, 'dirty', '더러운', NULL, NULL),
  ('word', 'middle_1', 8, 'discover', '발견하다', NULL, NULL),
  ('word', 'middle_1', 8, 'discuss', '토론하다', NULL, NULL),
  ('word', 'middle_1', 8, 'distance', '거리', NULL, NULL),
  ('word', 'middle_1', 8, 'divide', '나누다', NULL, NULL),
  ('word', 'middle_1', 8, 'double', '두 배의', NULL, NULL),
  ('word', 'middle_1', 8, 'doubt', '의심하다', NULL, NULL),
  ('word', 'middle_1', 9, 'dream', '꿈', '꿈꾸다', NULL),
  ('word', 'middle_1', 9, 'dress', '옷', '드레스', '입다'),
  ('word', 'middle_1', 9, 'drop', '떨어뜨리다', '방울', NULL),
  ('word', 'middle_1', 9, 'dry', '마른', '말리다', NULL),
  ('word', 'middle_1', 9, 'during', '~동안에', NULL, NULL),
  ('word', 'middle_1', 9, 'dust', '먼지', NULL, NULL),
  ('word', 'middle_1', 9, 'duty', '의무', '세금', NULL),
  ('word', 'middle_1', 9, 'each', '각각의', NULL, NULL),
  ('word', 'middle_1', 9, 'early', '이른', '일찍', NULL),
  ('word', 'middle_1', 9, 'earn', '벌다', NULL, NULL),
  ('word', 'middle_1', 9, 'earth', '지구', '땅', NULL),
  ('word', 'middle_1', 9, 'edge', '가장자리', NULL, NULL),
  ('word', 'middle_1', 9, 'effect', '효과', '결과', NULL),
  ('word', 'middle_1', 9, 'effort', '노력', NULL, NULL),
  ('word', 'middle_1', 9, 'either', '둘 중 하나', NULL, NULL),
  ('word', 'middle_1', 9, 'elect', '선출하다', NULL, NULL),
  ('word', 'middle_1', 9, 'else', '그 밖의', NULL, NULL),
  ('word', 'middle_1', 9, 'empty', '비어 있는', NULL, NULL),
  ('word', 'middle_1', 9, 'end', '끝', '끝나다', NULL),
  ('word', 'middle_1', 9, 'enemy', '적', NULL, NULL),
  ('word', 'middle_1', 10, 'energy', '에너지', NULL, NULL),
  ('word', 'middle_1', 10, 'enjoy', '즐기다', NULL, NULL),
  ('word', 'middle_1', 10, 'enough', '충분한', NULL, NULL),
  ('word', 'middle_1', 10, 'enter', '들어가다', NULL, NULL),
  ('word', 'middle_1', 10, 'environment', '환경', NULL, NULL),
  ('word', 'middle_1', 10, 'equal', '같은', '평등한', NULL),
  ('word', 'middle_1', 10, 'escape', '탈출하다', NULL, NULL),
  ('word', 'middle_1', 10, 'even', '심지어', '평평한', NULL),
  ('word', 'middle_1', 10, 'event', '사건', '행사', NULL),
  ('word', 'middle_1', 10, 'ever', '언젠가', '여태껏', NULL),
  ('word', 'middle_1', 10, 'every', '모든', NULL, NULL),
  ('word', 'middle_1', 10, 'exact', '정확한', NULL, NULL),
  ('word', 'middle_1', 10, 'examine', '조사하다', '진찰하다', NULL),
  ('word', 'middle_1', 10, 'excellent', '훌륭한', NULL, NULL),
  ('word', 'middle_1', 10, 'except', '~을 제외하고', NULL, NULL),
  ('word', 'middle_1', 10, 'excite', '흥분시키다', NULL, NULL),
  ('word', 'middle_1', 10, 'excuse', '변명', '용서하다', NULL),
  ('word', 'middle_1', 10, 'exercise', '운동', '연습하다', NULL),
  ('word', 'middle_1', 10, 'expect', '기대하다', '예상하다', NULL),
  ('word', 'middle_1', 10, 'expensive', '비싼', NULL, NULL),
  ('word', 'middle_1', 11, 'experience', '경험', '경험하다', NULL),
  ('word', 'middle_1', 11, 'explain', '설명하다', NULL, NULL),
  ('word', 'middle_1', 11, 'express', '표현하다', '급행의', NULL),
  ('word', 'middle_1', 11, 'face', '얼굴', '직면하다', NULL),
  ('word', 'middle_1', 11, 'fact', '사실', NULL, NULL),
  ('word', 'middle_1', 11, 'factory', '공장', NULL, NULL),
  ('word', 'middle_1', 11, 'fail', '실패하다', NULL, NULL),
  ('word', 'middle_1', 11, 'fair', '공평한', '박람회', NULL),
  ('word', 'middle_1', 11, 'fall', '떨어지다', '가을', NULL),
  ('word', 'middle_1', 11, 'false', '가짜의', '틀린', NULL),
  ('word', 'middle_1', 11, 'familiar', '친숙한', NULL, NULL),
  ('word', 'middle_1', 11, 'famous', '유명한', NULL, NULL),
  ('word', 'middle_1', 11, 'far', '먼', '멀리', NULL),
  ('word', 'middle_1', 11, 'farm', '농장', NULL, NULL),
  ('word', 'middle_1', 11, 'fashion', '패션', '유행', NULL),
  ('word', 'middle_1', 11, 'fast', '빠른', '빨리', NULL),
  ('word', 'middle_1', 11, 'fault', '잘못', '결점', NULL),
  ('word', 'middle_1', 11, 'favor', '호의', '부탁', NULL),
  ('word', 'middle_1', 11, 'favorite', '가장 좋아하는', NULL, NULL),
  ('word', 'middle_1', 11, 'fear', '두려움', '두려워하다', NULL),
  ('word', 'middle_1', 12, 'feed', '먹이를 주다', NULL, NULL),
  ('word', 'middle_1', 12, 'feel', '느끼다', NULL, NULL),
  ('word', 'middle_1', 12, 'female', '여성', '암컷', NULL),
  ('word', 'middle_1', 12, 'festival', '축제', NULL, NULL),
  ('word', 'middle_1', 12, 'field', '들판', '분야', NULL),
  ('word', 'middle_1', 12, 'fight', '싸우다', '싸움', NULL),
  ('word', 'middle_1', 12, 'figure', '숫자', '모양', '생각하다'),
  ('word', 'middle_1', 12, 'fill', '채우다', NULL, NULL),
  ('word', 'middle_1', 12, 'final', '최후의', '결승전', NULL),
  ('word', 'middle_1', 12, 'finally', '마침내', NULL, NULL),
  ('word', 'middle_1', 12, 'find', '찾다', '발견하다', NULL),
  ('word', 'middle_1', 12, 'fine', '좋은', '벌금', NULL),
  ('word', 'middle_1', 12, 'finish', '끝내다', NULL, NULL),
  ('word', 'middle_1', 12, 'fire', '불', '해고하다', NULL),
  ('word', 'middle_1', 12, 'firm', '회사', '단단한', NULL),
  ('word', 'middle_1', 12, 'fix', '고치다', '고정시키다', NULL),
  ('word', 'middle_1', 12, 'flag', '깃발', NULL, NULL),
  ('word', 'middle_1', 12, 'flat', '평평한', NULL, NULL),
  ('word', 'middle_1', 12, 'floor', '바닥', '층', NULL),
  ('word', 'middle_1', 12, 'flow', '흐르다', '흐름', NULL),
  ('word', 'middle_1', 12, 'flower', '꽃', NULL, NULL),
  ('word', 'middle_1', 13, 'fly', '날다', '파리', NULL),
  ('word', 'middle_1', 13, 'focus', '초점', '집중하다', NULL),
  ('word', 'middle_1', 13, 'follow', '따라가다', NULL, NULL),
  ('word', 'middle_1', 13, 'food', '음식', NULL, NULL),
  ('word', 'middle_1', 13, 'fool', '바보', '속이다', NULL),
  ('word', 'middle_1', 13, 'foot', '발', NULL, NULL),
  ('word', 'middle_1', 13, 'force', '힘', '강요하다', NULL),
  ('word', 'middle_1', 13, 'foreign', '외국의', NULL, NULL),
  ('word', 'middle_1', 13, 'forest', '숲', NULL, NULL),
  ('word', 'middle_1', 13, 'forget', '잊다', NULL, NULL),
  ('word', 'middle_1', 13, 'forgive', '용서하다', NULL, NULL),
  ('word', 'middle_1', 13, 'form', '형태', '형성하다', NULL),
  ('word', 'middle_1', 13, 'forward', '앞으로', NULL, NULL),
  ('word', 'middle_1', 13, 'free', '자유로운', '공짜의', NULL),
  ('word', 'middle_1', 13, 'freeze', '얼다', NULL, NULL),
  ('word', 'middle_1', 13, 'fresh', '신선한', NULL, NULL),
  ('word', 'middle_1', 13, 'friend', '친구', NULL, NULL),
  ('word', 'middle_1', 13, 'front', '앞', NULL, NULL),
  ('word', 'middle_1', 13, 'fruit', '과일', NULL, NULL),
  ('word', 'middle_1', 13, 'full', '가득 찬', NULL, NULL),
  ('word', 'middle_1', 14, 'fun', '재미', NULL, NULL),
  ('word', 'middle_1', 14, 'funny', '웃기는', NULL, NULL),
  ('word', 'middle_1', 14, 'future', '미래', NULL, NULL),
  ('word', 'middle_1', 14, 'gain', '얻다', '이익', NULL),
  ('word', 'middle_1', 14, 'game', '게임', '경기', NULL),
  ('word', 'middle_1', 14, 'garden', '정원', NULL, NULL),
  ('word', 'middle_1', 14, 'gate', '문', NULL, NULL),
  ('word', 'middle_1', 14, 'gather', '모으다', NULL, NULL),
  ('word', 'middle_1', 14, 'general', '일반적인', '장군', NULL),
  ('word', 'middle_1', 14, 'gentle', '부드러운', '온화한', NULL),
  ('word', 'middle_1', 14, 'gift', '선물', '재능', NULL),
  ('word', 'middle_1', 14, 'girl', '소녀', NULL, NULL),
  ('word', 'middle_1', 14, 'give', '주다', NULL, NULL),
  ('word', 'middle_1', 14, 'glad', '기쁜', NULL, NULL),
  ('word', 'middle_1', 14, 'glass', '유리', '컵', '안경'),
  ('word', 'middle_1', 14, 'glove', '장갑', NULL, NULL),
  ('word', 'middle_1', 14, 'goal', '목표', '골', NULL),
  ('word', 'middle_1', 14, 'god', '신', NULL, NULL),
  ('word', 'middle_1', 14, 'gold', '금', NULL, NULL),
  ('word', 'middle_1', 14, 'good', '좋은', NULL, NULL),
  ('word', 'middle_1', 15, 'government', '정부', NULL, NULL),
  ('word', 'middle_1', 15, 'grade', '학년', '성적', NULL),
  ('word', 'middle_1', 15, 'graduate', '졸업하다', NULL, NULL),
  ('word', 'middle_1', 15, 'grain', '곡물', NULL, NULL),
  ('word', 'middle_1', 15, 'grand', '웅장한', NULL, NULL),
  ('word', 'middle_1', 15, 'grass', '풀', '잔디', NULL),
  ('word', 'middle_1', 15, 'gray', '회색', NULL, NULL),
  ('word', 'middle_1', 15, 'great', '위대한', '큰', NULL),
  ('word', 'middle_1', 15, 'green', '초록색', NULL, NULL),
  ('word', 'middle_1', 15, 'ground', '땅', '운동장', NULL),
  ('word', 'middle_1', 15, 'group', '집단', '그룹', NULL),
  ('word', 'middle_1', 15, 'grow', '성장하다', '재배하다', NULL),
  ('word', 'middle_1', 15, 'guard', '경비원', '지키다', NULL),
  ('word', 'middle_1', 15, 'guess', '추측하다', NULL, NULL),
  ('word', 'middle_1', 15, 'guest', '손님', NULL, NULL),
  ('word', 'middle_1', 15, 'guide', '안내하다', '가이드', NULL),
  ('word', 'middle_1', 15, 'guilty', '유죄의', NULL, NULL),
  ('word', 'middle_1', 15, 'gun', '총', NULL, NULL),
  ('word', 'middle_1', 15, 'habit', '습관', NULL, NULL),
  ('word', 'middle_1', 15, 'hair', '머리카락', NULL, NULL),
  ('word', 'middle_1', 16, 'half', '절반', NULL, NULL),
  ('word', 'middle_1', 16, 'hall', '홀', '복도', NULL),
  ('word', 'middle_1', 16, 'hammer', '망치', NULL, NULL),
  ('word', 'middle_1', 16, 'hand', '손', '건네주다', NULL),
  ('word', 'middle_1', 16, 'handle', '다루다', '손잡이', NULL),
  ('word', 'middle_1', 16, 'hang', '걸다', '매달다', NULL),
  ('word', 'middle_1', 16, 'happen', '일어나다', '발생하다', NULL),
  ('word', 'middle_1', 16, 'happy', '행복한', NULL, NULL),
  ('word', 'middle_1', 16, 'hard', '열심히', '딱딱한', '어려운'),
  ('word', 'middle_1', 16, 'harvest', '수확', '수확하다', NULL),
  ('word', 'middle_1', 16, 'hate', '싫어하다', NULL, NULL),
  ('word', 'middle_1', 16, 'have', '가지다', NULL, NULL),
  ('word', 'middle_1', 16, 'head', '머리', '이끌다', NULL),
  ('word', 'middle_1', 16, 'health', '건강', NULL, NULL),
  ('word', 'middle_1', 16, 'hear', '듣다', NULL, NULL),
  ('word', 'middle_1', 16, 'heart', '심장', '마음', NULL),
  ('word', 'middle_1', 16, 'heat', '열', '가열하다', NULL),
  ('word', 'middle_1', 16, 'heavy', '무거운', NULL, NULL),
  ('word', 'middle_1', 16, 'height', '높이', '키', NULL),
  ('word', 'middle_1', 16, 'hell', '지옥', NULL, NULL),
  ('word', 'middle_1', 17, 'hello', '안녕', NULL, NULL),
  ('word', 'middle_1', 17, 'help', '돕다', NULL, NULL),
  ('word', 'middle_1', 17, 'here', '여기', NULL, NULL),
  ('word', 'middle_1', 17, 'hero', '영웅', NULL, NULL),
  ('word', 'middle_1', 17, 'hide', '숨다', '숨기다', NULL),
  ('word', 'middle_1', 17, 'high', '높은', NULL, NULL),
  ('word', 'middle_1', 17, 'hill', '언덕', NULL, NULL),
  ('word', 'middle_1', 17, 'history', '역사', NULL, NULL),
  ('word', 'middle_1', 17, 'hit', '치다', NULL, NULL),
  ('word', 'middle_1', 17, 'hobby', '취미', NULL, NULL),
  ('word', 'middle_1', 17, 'hold', '잡다', '개최하다', NULL),
  ('word', 'middle_1', 17, 'hole', '구멍', NULL, NULL),
  ('word', 'middle_1', 17, 'holiday', '휴일', '명절', NULL),
  ('word', 'middle_1', 17, 'holy', '신성한', NULL, NULL),
  ('word', 'middle_1', 17, 'home', '집', NULL, NULL),
  ('word', 'middle_1', 17, 'honest', '정직한', NULL, NULL),
  ('word', 'middle_1', 17, 'honor', '명예', '존경하다', NULL),
  ('word', 'middle_1', 17, 'hope', '희망', '바라다', NULL),
  ('word', 'middle_1', 17, 'hospital', '병원', NULL, NULL),
  ('word', 'middle_1', 17, 'hot', '뜨거운', NULL, NULL),
  ('word', 'middle_1', 18, 'hotel', '호텔', NULL, NULL),
  ('word', 'middle_1', 18, 'hour', '시간', NULL, NULL),
  ('word', 'middle_1', 18, 'house', '집', NULL, NULL),
  ('word', 'middle_1', 18, 'however', '하지만', '그러나', NULL),
  ('word', 'middle_1', 18, 'huge', '거대한', NULL, NULL),
  ('word', 'middle_1', 18, 'human', '인간', NULL, NULL),
  ('word', 'middle_1', 18, 'hundred', '백', NULL, NULL),
  ('word', 'middle_1', 18, 'hungry', '배고픈', NULL, NULL),
  ('word', 'middle_1', 18, 'hunt', '사냥하다', NULL, NULL),
  ('word', 'middle_1', 18, 'hurry', '서두르다', NULL, NULL),
  ('word', 'middle_1', 18, 'hurt', '다치게 하다', NULL, NULL),
  ('word', 'middle_1', 18, 'husband', '남편', NULL, NULL),
  ('word', 'middle_1', 18, 'ice', '얼음', NULL, NULL),
  ('word', 'middle_1', 18, 'idea', '생각', NULL, NULL),
  ('word', 'middle_1', 18, 'island', '섬', NULL, NULL),
  ('word', 'middle_1', 18, 'issue', '주제', '발행하다', NULL),
  ('word', 'middle_1', 18, 'item', '항목', '물품', NULL),
  ('word', 'middle_1', 18, 'jacket', '재킷', NULL, NULL),
  ('word', 'middle_1', 18, 'jail', '감옥', NULL, NULL),
  ('word', 'middle_1', 18, 'jam', '잼', '막다', NULL),
  ('word', 'middle_1', 19, 'job', '직업', NULL, NULL),
  ('word', 'middle_1', 19, 'join', '참가하다', '연결하다', NULL),
  ('word', 'middle_1', 19, 'joke', '농담', NULL, NULL),
  ('word', 'middle_1', 19, 'journey', '여행', NULL, NULL),
  ('word', 'middle_1', 19, 'joy', '기쁨', NULL, NULL),
  ('word', 'middle_1', 19, 'judge', '판사', '판단하다', NULL),
  ('word', 'middle_1', 19, 'juice', '주스', NULL, NULL),
  ('word', 'middle_1', 19, 'jump', '점프하다', NULL, NULL),
  ('word', 'middle_1', 19, 'junior', '후배', '하급의', NULL),
  ('word', 'middle_1', 19, 'just', '방금', '단지', '공정한'),
  ('word', 'middle_1', 19, 'keep', '유지하다', '보관하다', NULL),
  ('word', 'middle_1', 19, 'key', '열쇠', '핵심적인', NULL),
  ('word', 'middle_1', 19, 'kick', '차다', NULL, NULL),
  ('word', 'middle_1', 19, 'kid', '아이', '농담하다', NULL),
  ('word', 'middle_1', 19, 'kill', '죽이다', NULL, NULL),
  ('word', 'middle_1', 19, 'kind', '종류', '친절한', NULL),
  ('word', 'middle_1', 19, 'king', '왕', NULL, NULL),
  ('word', 'middle_1', 19, 'kiss', '키스', '키스하다', NULL),
  ('word', 'middle_1', 19, 'kitchen', '주방', NULL, NULL),
  ('word', 'middle_1', 19, 'knee', '무릎', NULL, NULL),
  ('word', 'middle_1', 20, 'knife', '칼', NULL, NULL),
  ('word', 'middle_1', 20, 'knock', '노크하다', NULL, NULL),
  ('word', 'middle_1', 20, 'know', '알다', NULL, NULL),
  ('word', 'middle_1', 20, 'knowledge', '지식', NULL, NULL),
  ('word', 'middle_1', 20, 'labor', '노동', NULL, NULL),
  ('word', 'middle_1', 20, 'lack', '부족', '부족하다', NULL),
  ('word', 'middle_1', 20, 'lady', '숙녀', NULL, NULL),
  ('word', 'middle_1', 20, 'lake', '호수', NULL, NULL),
  ('word', 'middle_1', 20, 'lamp', '램프', NULL, NULL),
  ('word', 'middle_1', 20, 'land', '땅', '착륙하다', NULL),
  ('word', 'middle_1', 20, 'language', '언어', NULL, NULL),
  ('word', 'middle_1', 20, 'large', '큰', NULL, NULL),
  ('word', 'middle_1', 20, 'last', '마지막의', '지속되다', NULL),
  ('word', 'middle_1', 20, 'late', '늦은', '늦게', NULL),
  ('word', 'middle_1', 20, 'laugh', '웃다', NULL, NULL),
  ('word', 'middle_1', 20, 'law', '법', NULL, NULL),
  ('word', 'middle_1', 20, 'lead', '이끌다', NULL, NULL),
  ('word', 'middle_1', 20, 'leader', '지도자', NULL, NULL),
  ('word', 'middle_1', 20, 'leaf', '잎', NULL, NULL),
  ('word', 'middle_1', 20, 'learn', '배우다', NULL, NULL),
  ('word', 'middle_2', 21, 'least', '최소의', '적어도', NULL),
  ('word', 'middle_2', 21, 'leave', '떠나다', '남겨두다', NULL),
  ('word', 'middle_2', 21, 'lecture', '강의', '강연', NULL),
  ('word', 'middle_2', 21, 'lend', '빌려주다', NULL, NULL),
  ('word', 'middle_2', 21, 'less', '더 적은', '덜하게', NULL),
  ('word', 'middle_2', 21, 'lesson', '수업', '교훈', NULL),
  ('word', 'middle_2', 21, 'level', '수준', '평평한', NULL),
  ('word', 'middle_2', 21, 'library', '도서관', NULL, NULL),
  ('word', 'middle_2', 21, 'license', '면허', '자격증', NULL),
  ('word', 'middle_2', 21, 'lie', '거짓말하다', '눕다', NULL),
  ('word', 'middle_2', 21, 'life', '인생', '생명', NULL),
  ('word', 'middle_2', 21, 'lift', '들어올리다', '승강기', NULL),
  ('word', 'middle_2', 21, 'light', '빛', '가벼운', '전등'),
  ('word', 'middle_2', 21, 'likely', '~할 것 같은', '아마', NULL),
  ('word', 'middle_2', 21, 'limit', '제한', '한계', NULL),
  ('word', 'middle_2', 21, 'line', '선', '줄', NULL),
  ('word', 'middle_2', 21, 'list', '목록', '명단', NULL),
  ('word', 'middle_2', 21, 'listen', '듣다', '경청하다', NULL),
  ('word', 'middle_2', 21, 'little', '작은', '거의 없는', NULL),
  ('word', 'middle_2', 21, 'live', '살다', '생방송의', NULL),
  ('word', 'middle_2', 22, 'load', '짐', '싣다', NULL),
  ('word', 'middle_2', 22, 'local', '지역의', '현지의', NULL),
  ('word', 'middle_2', 22, 'lock', '잠그다', '자물쇠', NULL),
  ('word', 'middle_2', 22, 'long', '긴', '오랫동안', NULL),
  ('word', 'middle_2', 22, 'look', '보다', '~처럼 보이다', NULL),
  ('word', 'middle_2', 22, 'loose', '느슨한', '헐거운', NULL),
  ('word', 'middle_2', 22, 'lose', '잃다', '지다', NULL),
  ('word', 'middle_2', 22, 'loss', '손실', '상실', NULL),
  ('word', 'middle_2', 22, 'loud', '소리가 큰', '시끄러운', NULL),
  ('word', 'middle_2', 22, 'love', '사랑', '사랑하다', NULL),
  ('word', 'middle_2', 22, 'low', '낮은', NULL, NULL),
  ('word', 'middle_2', 22, 'luck', '운', '행운', NULL),
  ('word', 'middle_2', 22, 'lucky', '운이 좋은', NULL, NULL),
  ('word', 'middle_2', 22, 'machine', '기계', NULL, NULL),
  ('word', 'middle_2', 22, 'mad', '화난', '미친', NULL),
  ('word', 'middle_2', 22, 'magazine', '잡지', NULL, NULL),
  ('word', 'middle_2', 22, 'main', '주요한', '주된', NULL),
  ('word', 'middle_2', 22, 'major', '주요한', '전공', NULL),
  ('word', 'middle_2', 22, 'make', '만들다', NULL, NULL),
  ('word', 'middle_2', 22, 'male', '남성', '수컷', NULL),
  ('word', 'middle_2', 23, 'manage', '관리하다', '해내다', NULL),
  ('word', 'middle_2', 23, 'manager', '경영자', '지배인', NULL),
  ('word', 'middle_2', 23, 'manner', '방법', '예의범절', NULL),
  ('word', 'middle_2', 23, 'many', '많은', NULL, NULL),
  ('word', 'middle_2', 23, 'map', '지도', NULL, NULL),
  ('word', 'middle_2', 23, 'market', '시장', NULL, NULL),
  ('word', 'middle_2', 23, 'marry', '결혼하다', NULL, NULL),
  ('word', 'middle_2', 23, 'mass', '덩어리', '대중', NULL),
  ('word', 'middle_2', 23, 'master', '주인', '숙달하다', NULL),
  ('word', 'middle_2', 23, 'match', '경기', '어울리다', '성냥'),
  ('word', 'middle_2', 23, 'material', '재료', '물질', NULL),
  ('word', 'middle_2', 23, 'matter', '문제', '중요하다', '물질'),
  ('word', 'middle_2', 23, 'maximum', '최대의', NULL, NULL),
  ('word', 'middle_2', 23, 'maybe', '아마도', NULL, NULL),
  ('word', 'middle_2', 23, 'meal', '식사', NULL, NULL),
  ('word', 'middle_2', 23, 'mean', '의미하다', '비열한', NULL),
  ('word', 'middle_2', 23, 'meaning', '의미', '뜻', NULL),
  ('word', 'middle_2', 23, 'measure', '측정하다', '조치', NULL),
  ('word', 'middle_2', 23, 'meat', '고기', NULL, NULL),
  ('word', 'middle_2', 23, 'media', '매체', '미디어', NULL),
  ('word', 'middle_2', 24, 'medicine', '약', '의학', NULL),
  ('word', 'middle_2', 24, 'meet', '만나다', NULL, NULL),
  ('word', 'middle_2', 24, 'meeting', '회의', '모임', NULL),
  ('word', 'middle_2', 24, 'member', '구성원', '회원', NULL),
  ('word', 'middle_2', 24, 'memory', '기억', '추억', NULL),
  ('word', 'middle_2', 24, 'mention', '언급하다', NULL, NULL),
  ('word', 'middle_2', 24, 'menu', '메뉴', '식단', NULL),
  ('word', 'middle_2', 24, 'message', '메시지', NULL, NULL),
  ('word', 'middle_2', 24, 'metal', '금속', NULL, NULL),
  ('word', 'middle_2', 24, 'method', '방법', NULL, NULL),
  ('word', 'middle_2', 24, 'middle', '중간의', NULL, NULL),
  ('word', 'middle_2', 24, 'might', '아마 ~일지도 모른다', '힘', NULL),
  ('word', 'middle_2', 24, 'mild', '온화한', '부드러운', NULL),
  ('word', 'middle_2', 24, 'mile', '마일', NULL, NULL),
  ('word', 'middle_2', 24, 'mind', '마음', '꺼려하다', NULL),
  ('word', 'middle_2', 24, 'mine', '나의 것', '광산', NULL),
  ('word', 'middle_2', 24, 'mirror', '거울', NULL, NULL),
  ('word', 'middle_2', 24, 'miss', '놓치다', '그리워하다', NULL),
  ('word', 'middle_2', 24, 'mistake', '실수', NULL, NULL),
  ('word', 'middle_2', 24, 'mix', '섞다', NULL, NULL),
  ('word', 'middle_2', 25, 'model', '모델', '모형', NULL),
  ('word', 'middle_2', 25, 'modern', '현대적인', NULL, NULL),
  ('word', 'middle_2', 25, 'moment', '순간', '잠시', NULL),
  ('word', 'middle_2', 25, 'money', '돈', NULL, NULL),
  ('word', 'middle_2', 25, 'month', '달', '월', NULL),
  ('word', 'middle_2', 25, 'mood', '기분', '분위기', NULL),
  ('word', 'middle_2', 25, 'moon', '달', NULL, NULL),
  ('word', 'middle_2', 25, 'moral', '도덕적인', NULL, NULL),
  ('word', 'middle_2', 25, 'more', '더 많은', '더 많이', NULL),
  ('word', 'middle_2', 25, 'morning', '아침', NULL, NULL),
  ('word', 'middle_2', 25, 'most', '가장 많은', '대부분의', NULL),
  ('word', 'middle_2', 25, 'mountain', '산', NULL, NULL),
  ('word', 'middle_2', 25, 'mouth', '입', NULL, NULL),
  ('word', 'middle_2', 25, 'move', '움직이다', '이사하다', NULL),
  ('word', 'middle_2', 25, 'movie', '영화', NULL, NULL),
  ('word', 'middle_2', 25, 'much', '많은', '매우', NULL),
  ('word', 'middle_2', 25, 'music', '음악', NULL, NULL),
  ('word', 'middle_2', 25, 'must', '~해야 한다', '~임에 틀림없다', NULL),
  ('word', 'middle_2', 25, 'name', '이름', NULL, NULL);

-- 6. 트리거 설정
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, external_id)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'external_id', NEW.id::text))
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();