-- ============================================================
-- 영단어 학습 앱 - 수준별 데이터 재설계 반영 초급~고급 DB 구조
-- ============================================================

-- 1. 기존 테이블 삭제
DROP TABLE IF EXISTS public.user_progress CASCADE;
DROP TABLE IF EXISTS public.battle_rooms CASCADE;
DROP TABLE IF EXISTS public.study_logs  CASCADE;
DROP TABLE IF EXISTS public.profiles    CASCADE;
DROP TABLE IF EXISTS public.words       CASCADE;

-- 2. words 테이블 생성
CREATE TABLE public.words (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type       text NOT NULL DEFAULT 'word',
  level      text NOT NULL,
  set_no     int  NOT NULL,
  word       text NOT NULL,
  mean_1     text NOT NULL,
  mean_2     text,                   
  mean_3     text,                   
  example_sentence text,             -- 마스터 챌린지용 예문
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_words_level_set ON public.words (level, set_no);
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "words_read_all" ON public.words FOR SELECT USING (true);

-- 3. battle_rooms 테이블 생성
CREATE TABLE public.battle_rooms (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  room_code varchar(6) NOT NULL UNIQUE,
  host_id uuid NOT NULL,
  guest_id uuid,
  status varchar(20) NOT NULL DEFAULT 'waiting',
  level varchar(50) NOT NULL,
  set_no integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.battle_rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view rooms" ON public.battle_rooms FOR SELECT USING (true);
CREATE POLICY "Auth users can create" ON public.battle_rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Participants can update" ON public.battle_rooms FOR UPDATE USING (true);

-- 4. profiles 테이블 생성
CREATE TABLE public.profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_self" ON public.profiles FOR ALL USING (auth.uid() = id);

-- 5. user_progress 테이블 생성 (세트 클리어 시스템)
CREATE TABLE public.user_progress (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id       uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  level         text   NOT NULL,
  set_no        int    NOT NULL,
  success_count int    NOT NULL DEFAULT 0 CHECK (success_count >= 0 AND success_count <= 3),
  is_cleared    boolean NOT NULL DEFAULT false,
  has_medal     boolean NOT NULL DEFAULT false, -- 마스터 챌린지 훈장 획득 여부
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, level, set_no)           -- UPSERT를 위한 복합 유니크
);

CREATE INDEX idx_progress_user ON public.user_progress (user_id, level);
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
-- 본인 데이터만 읽기/쓰기
CREATE POLICY "progress_self_select" ON public.user_progress
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "progress_self_insert" ON public.user_progress
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "progress_self_update" ON public.user_progress
  FOR UPDATE USING (auth.uid() = user_id);

-- 6. 단어 데이블
INSERT INTO public.words (type, level, set_no, word, mean_1, mean_2, mean_3, example_sentence) VALUES
('word', '초3', 1, 'I', '나', '', '', ''),
('word', '초3', 1, 'you', '너', '', '', ''),
('word', '초3', 1, 'he', '그', '', '', ''),
('word', '초3', 1, 'she', '그녀', '', '', ''),
('word', '초3', 1, 'we', '우리', '', '', ''),
('word', '초3', 1, 'they', '그들', '', '', ''),
('word', '초3', 1, 'my', '나의', '', '', ''),
('word', '초3', 1, 'your', '너의', '', '', ''),
('word', '초3', 1, 'his', '그의', '', '', ''),
('word', '초3', 1, 'her', '그녀의', '', '', ''),
('word', '초3', 1, 'this', '이것', '', '', ''),
('word', '초3', 1, 'that', '저것', '', '', ''),
('word', '초3', 1, 'yes', '예', '', '', ''),
('word', '초3', 1, 'no', '아니오', '', '', ''),
('word', '초3', 1, 'hello', '안녕', '', '', ''),
('word', '초3', 1, 'bye', '잘가', '', '', ''),
('word', '초3', 1, 'please', '제발', '', '', ''),
('word', '초3', 1, 'sorry', '미안해', '', '', ''),
('word', '초3', 1, 'thanks', '고마워', '', '', ''),
('word', '초3', 1, 'name', '이름', '', '', ''),
('word', '초3', 3, 'age', '나이', '', '', ''),
('word', '초3', 2, 'friend', '친구', '', '', ''),
('word', '초3', 2, 'family', '가족', '', '', ''),
('word', '초3', 2, 'mother', '엄마', '', '', ''),
('word', '초3', 2, 'father', '아빠', '', '', ''),
('word', '초3', 2, 'sister', '자매', '', '', ''),
('word', '초3', 2, 'brother', '형제', '', '', ''),
('word', '초3', 2, 'teacher', '선생님', '', '', ''),
('word', '초3', 2, 'student', '학생', '', '', ''),
('word', '초3', 2, 'school', '학교', '', '', ''),
('word', '초3', 2, 'class', '수업', '', '', ''),
('word', '초3', 2, 'book', '책', '', '', ''),
('word', '초3', 2, 'pen', '펜', '', '', ''),
('word', '초3', 2, 'pencil', '연필', '', '', ''),
('word', '초3', 2, 'bag', '가방', '', '', ''),
('word', '초3', 2, 'desk', '책상', '', '', ''),
('word', '초3', 2, 'chair', '의자', '', '', ''),
('word', '초3', 2, 'home', '집', '', '', ''),
('word', '초3', 2, 'room', '방', '', '', ''),
('word', '초3', 2, 'door', '문', '', '', ''),
('word', '초3', 4, 'window', '창문', '', '', ''),
('word', '초3', 3, 'bed', '침대', '', '', ''),
('word', '초3', 3, 'table', '탁자', '', '', ''),
('word', '초3', 3, 'food', '음식', '', '', ''),
('word', '초3', 3, 'water', '물', '', '', ''),
('word', '초3', 3, 'milk', '우유', '', '', ''),
('word', '초3', 3, 'rice', '밥', '', '', ''),
('word', '초3', 3, 'bread', '빵', '', '', ''),
('word', '초3', 3, 'apple', '사과', '', '', ''),
('word', '초3', 3, 'banana', '바나나', '', '', ''),
('word', '초3', 3, 'dog', '개', '', '', ''),
('word', '초3', 3, 'cat', '고양이', '', '', ''),
('word', '초3', 3, 'bird', '새', '', '', ''),
('word', '초3', 3, 'fish', '물고기', '', '', ''),
('word', '초3', 3, 'sun', '태양', '', '', ''),
('word', '초3', 3, 'moon', '달', '', '', ''),
('word', '초3', 3, 'sky', '하늘', '', '', ''),
('word', '초3', 3, 'rain', '비', '', '', ''),
('word', '초3', 3, 'snow', '눈', '', '', ''),
('word', '초3', 3, 'wind', '바람', '', '', ''),
('word', '초3', 5, 'red', '빨강', '', '', ''),
('word', '초3', 4, 'blue', '파랑', '', '', ''),
('word', '초3', 4, 'yellow', '노랑', '', '', ''),
('word', '초3', 4, 'green', '초록', '', '', ''),
('word', '초3', 4, 'black', '검정', '', '', ''),
('word', '초3', 4, 'white', '하양', '', '', ''),
('word', '초3', 4, 'one', '하나', '', '', ''),
('word', '초3', 4, 'two', '둘', '', '', ''),
('word', '초3', 4, 'three', '셋', '', '', ''),
('word', '초3', 4, 'four', '넷', '', '', ''),
('word', '초3', 4, 'five', '다섯', '', '', ''),
('word', '초3', 4, 'six', '여섯', '', '', ''),
('word', '초3', 4, 'seven', '일곱', '', '', ''),
('word', '초3', 4, 'eight', '여덟', '', '', ''),
('word', '초3', 4, 'nine', '아홉', '', '', ''),
('word', '초3', 4, 'ten', '열', '', '', ''),
('word', '초3', 4, 'morning', '아침', '', '', ''),
('word', '초3', 4, 'afternoon', '오후', '', '', ''),
('word', '초3', 4, 'evening', '저녁', '', '', ''),
('word', '초3', 4, 'night', '밤', '', '', ''),
('word', '초3', 6, 'today', '오늘', '', '', ''),
('word', '초3', 5, 'tomorrow', '내일', '', '', ''),
('word', '초3', 5, 'happy', '행복한', '', '', ''),
('word', '초3', 5, 'sad', '슬픈', '', '', ''),
('word', '초3', 5, 'big', '큰', '', '', ''),
('word', '초3', 5, 'small', '작은', '', '', ''),
('word', '초3', 5, 'hot', '더운', '', '', ''),
('word', '초3', 5, 'cold', '추운', '', '', ''),
('word', '초3', 5, 'good', '좋은', '', '', ''),
('word', '초3', 5, 'bad', '나쁜', '', '', ''),
('word', '초3', 5, 'fast', '빠른', '', '', ''),
('word', '초3', 5, 'slow', '느린', '', '', ''),
('word', '초3', 5, 'run', '달리다', '', '', ''),
('word', '초3', 5, 'walk', '걷다', '', '', ''),
('word', '초3', 5, 'jump', '뛰다', '', '', ''),
('word', '초3', 5, 'sit', '앉다', '', '', ''),
('word', '초3', 5, 'stand', '서다', '', '', ''),
('word', '초3', 5, 'eat', '먹다', '', '', ''),
('word', '초3', 5, 'drink', '마시다', '', '', ''),
('word', '초3', 5, 'sleep', '자다', '', '', ''),
('word', '초3', 7, 'go', '가다', '', '', ''),
('word', '초3', 6, 'come', '오다', '', '', ''),
('word', '초3', 6, 'see', '보다', '', '', ''),
('word', '초3', 6, 'look', '보다', '', '', ''),
('word', '초3', 6, 'listen', '듣다', '', '', ''),
('word', '초3', 6, 'speak', '말하다', '', '', ''),
('word', '초3', 6, 'read', '읽다', '', '', ''),
('word', '초3', 6, 'write', '쓰다', '', '', ''),
('word', '초3', 6, 'play', '놀다', '', '', ''),
('word', '초3', 6, 'like', '좋아하다', '', '', ''),
('word', '초3', 6, 'love', '사랑하다', '', '', ''),
('word', '초3', 6, 'have', '가지다', '', '', ''),
('word', '초3', 6, 'make', '만들다', '', '', ''),
('word', '초3', 6, 'help', '돕다', '', '', ''),
('word', '초3', 6, 'give', '주다', '', '', ''),
('word', '초3', 6, 'take', '가져가다', '', '', ''),
('word', '초3', 6, 'open', '열다', '', '', ''),
('word', '초3', 6, 'close', '닫다', '', '', ''),
('word', '초3', 6, 'clean', '청소하다', '', '', ''),
('word', '초3', 6, 'wash', '씻다', '', '', ''),
('word', '초3', 8, 'day', '날', '', '', ''),
('word', '초3', 7, 'week', '주', '', '', ''),
('word', '초3', 7, 'month', '달', '', '', ''),
('word', '초3', 7, 'year', '해', '', '', ''),
('word', '초3', 7, 'Monday', '월요일', '', '', ''),
('word', '초3', 7, 'Tuesday', '화요일', '', '', ''),
('word', '초3', 7, 'Wednesday', '수요일', '', '', ''),
('word', '초3', 7, 'Thursday', '목요일', '', '', ''),
('word', '초3', 7, 'Friday', '금요일', '', '', ''),
('word', '초3', 7, 'Saturday', '토요일', '', '', ''),
('word', '초3', 7, 'Sunday', '일요일', '', '', ''),
('word', '초3', 7, 'spring', '봄', '', '', ''),
('word', '초3', 7, 'summer', '여름', '', '', ''),
('word', '초3', 7, 'fall', '가을', '', '', ''),
('word', '초3', 7, 'winter', '겨울', '', '', ''),
('word', '초3', 7, 'park', '공원', '', '', ''),
('word', '초3', 7, 'store', '가게', '', '', ''),
('word', '초3', 7, 'bus', '버스', '', '', ''),
('word', '초3', 7, 'car', '자동차', '', '', ''),
('word', '초3', 7, 'bike', '자전거', '', '', ''),
('word', '초3', 9, 'tree', '나무', '', '', ''),
('word', '초3', 8, 'flower', '꽃', '', '', ''),
('word', '초3', 8, 'grass', '풀', '', '', ''),
('word', '초3', 8, 'river', '강', '', '', ''),
('word', '초3', 8, 'sea', '바다', '', '', ''),
('word', '초3', 8, 'mountain', '산', '', '', ''),
('word', '초3', 8, 'head', '머리', '', '', ''),
('word', '초3', 8, 'eye', '눈', '', '', ''),
('word', '초3', 8, 'ear', '귀', '', '', ''),
('word', '초3', 8, 'nose', '코', '', '', ''),
('word', '초3', 8, 'mouth', '입', '', '', ''),
('word', '초3', 8, 'hand', '손', '', '', ''),
('word', '초3', 8, 'foot', '발', '', '', ''),
('word', '초3', 8, 'arm', '팔', '', '', ''),
('word', '초3', 8, 'leg', '다리', '', '', ''),
('word', '초3', 8, 'shirt', '셔츠', '', '', ''),
('word', '초3', 8, 'pants', '바지', '', '', ''),
('word', '초3', 8, 'shoes', '신발', '', '', ''),
('word', '초3', 8, 'hat', '모자', '', '', ''),
('word', '초3', 8, 'coat', '코트', '', '', ''),
('word', '초3', 10, 'ball', '공', '', '', ''),
('word', '초3', 9, 'game', '게임', '', '', ''),
('word', '초3', 9, 'music', '음악', '', '', ''),
('word', '초3', 9, 'song', '노래', '', '', ''),
('word', '초3', 9, 'picture', '그림', '', '', ''),
('word', '초3', 9, 'farm', '농장', '', '', ''),
('word', '초3', 9, 'zoo', '동물원', '', '', ''),
('word', '초3', 9, 'doctor', '의사', '', '', ''),
('word', '초3', 9, 'nurse', '간호사', '', '', ''),
('word', '초3', 9, 'hospital', '병원', '', '', ''),
('word', '초3', 9, 'star', '별', '', '', ''),
('word', '초3', 9, 'cloud', '구름', '', '', ''),
('word', '초3', 9, 'clock', '시계', '', '', ''),
('word', '초3', 9, 'birthday', '생일', '', '', ''),
('word', '초3', 9, 'gift', '선물', '', '', ''),
('word', '초3', 9, 'smile', '미소', '', '', ''),
('word', '초3', 9, 'cup', '컵', '', '', ''),
('word', '초3', 9, 'plate', '접시', '', '', ''),
('word', '초3', 9, 'toy', '장난감', '', '', ''),
('word', '초3', 9, 'baby', '아기', '', '', ''),
('word', '초4', 1, 'actor', '배우', '', '', ''),
('word', '초4', 1, 'airport', '공항', '', '', ''),
('word', '초4', 1, 'album', '앨범', '', '', ''),
('word', '초4', 1, 'almost', '거의', '', '', ''),
('word', '초4', 1, 'alone', '혼자', '', '', ''),
('word', '초4', 1, 'along', '~을 따라', '', '', ''),
('word', '초4', 1, 'angry', '화난', '', '', ''),
('word', '초4', 1, 'animal', '동물', '', '', ''),
('word', '초4', 1, 'anyone', '누구나', '', '', ''),
('word', '초4', 1, 'around', '주위에', '', '', ''),
('word', '초4', 1, 'artist', '예술가', '', '', ''),
('word', '초4', 1, 'autumn', '가을철', '', '', ''),
('word', '초4', 1, 'bakery', '빵집', '', '', ''),
('word', '초4', 1, 'balloon', '풍선', '', '', ''),
('word', '초4', 1, 'basement', '지하실', '', '', ''),
('word', '초4', 1, 'beach', '해변', '', '', ''),
('word', '초4', 1, 'bear', '곰', '', '', ''),
('word', '초4', 1, 'become', '~이 되다', '', '', ''),
('word', '초4', 1, 'before', '이전에', '', '', ''),
('word', '초4', 1, 'bench', '벤치', '', '', ''),
('word', '초4', 2, 'best', '최고의', '', '', ''),
('word', '초4', 2, 'better', '더 좋은', '', '', ''),
('word', '초4', 2, 'boat', '배', '', '', ''),
('word', '초4', 2, 'bottle', '병', '', '', ''),
('word', '초4', 2, 'breakfast', '아침식사', '', '', ''),
('word', '초4', 2, 'bridge', '다리', '', '', ''),
('word', '초4', 2, 'bright', '밝은', '', '', ''),
('word', '초4', 2, 'bring', '가져오다', '', '', ''),
('word', '초4', 2, 'build', '짓다', '', '', ''),
('word', '초4', 2, 'butterfly', '나비', '', '', ''),
('word', '초4', 2, 'calendar', '달력', '', '', ''),
('word', '초4', 2, 'camera', '카메라', '', '', ''),
('word', '초4', 2, 'camp', '야영', '', '', ''),
('word', '초4', 2, 'candle', '양초', '', '', ''),
('word', '초4', 2, 'careful', '조심스러운', '', '', ''),
('word', '초4', 2, 'carry', '나르다', '', '', ''),
('word', '초4', 2, 'castle', '성', '', '', ''),
('word', '초4', 2, 'center', '중심', '', '', ''),
('word', '초4', 2, 'change', '변화', '', '', ''),
('word', '초4', 2, 'cheap', '값싼', '', '', ''),
('word', '초4', 3, 'cheer', '응원하다', '', '', ''),
('word', '초4', 3, 'chef', '요리사', '', '', ''),
('word', '초4', 3, 'chocolate', '초콜릿', '', '', ''),
('word', '초4', 3, 'church', '교회', '', '', ''),
('word', '초4', 3, 'circle', '원', '', '', ''),
('word', '초4', 3, 'city', '도시', '', '', ''),
('word', '초4', 3, 'clap', '박수치다', '', '', ''),
('word', '초4', 3, 'climb', '오르다', '', '', ''),
('word', '초4', 3, 'cloudy', '흐린', '', '', ''),
('word', '초4', 3, 'collect', '모으다', '', '', ''),
('word', '초4', 3, 'colorful', '다채로운', '', '', ''),
('word', '초4', 3, 'comic', '만화책', '', '', ''),
('word', '초4', 3, 'corner', '모퉁이', '', '', ''),
('word', '초4', 3, 'cost', '비용', '', '', ''),
('word', '초4', 3, 'count', '세다', '', '', ''),
('word', '초4', 3, 'cousin', '사촌', '', '', ''),
('word', '초4', 3, 'crowd', '군중', '', '', ''),
('word', '초4', 3, 'dance', '춤', '', '', ''),
('word', '초4', 3, 'danger', '위험', '', '', ''),
('word', '초4', 3, 'daughter', '딸', '', '', ''),
('word', '초4', 4, 'decide', '결정하다', '', '', ''),
('word', '초4', 4, 'deep', '깊은', '', '', ''),
('word', '초4', 4, 'delicious', '맛있는', '', '', ''),
('word', '초4', 4, 'different', '다른', '', '', ''),
('word', '초4', 4, 'dinner', '저녁식사', '', '', ''),
('word', '초4', 4, 'dirty', '더러운', '', '', ''),
('word', '초4', 4, 'dolphin', '돌고래', '', '', ''),
('word', '초4', 4, 'dream', '꿈', '', '', ''),
('word', '초4', 4, 'driver', '운전자', '', '', ''),
('word', '초4', 4, 'early', '일찍', '', '', ''),
('word', '초4', 4, 'earth', '지구', '', '', ''),
('word', '초4', 4, 'easy', '쉬운', '', '', ''),
('word', '초4', 4, 'elephant', '코끼리', '', '', ''),
('word', '초4', 4, 'empty', '비어있는', '', '', ''),
('word', '초4', 4, 'enjoy', '즐기다', '', '', ''),
('word', '초4', 4, 'enough', '충분한', '', '', ''),
('word', '초4', 4, 'excited', '신난', '', '', ''),
('word', '초4', 4, 'expensive', '비싼', '', '', ''),
('word', '초4', 4, 'factory', '공장', '', '', ''),
('word', '초4', 4, 'famous', '유명한', '', '', ''),
('word', '초4', 5, 'farmer', '농부', '', '', ''),
('word', '초4', 5, 'festival', '축제', '', '', ''),
('word', '초4', 5, 'field', '들판', '', '', ''),
('word', '초4', 5, 'finish', '끝내다', '', '', ''),
('word', '초4', 5, 'firefighter', '소방관', '', '', ''),
('word', '초4', 5, 'first', '첫번째', '', '', ''),
('word', '초4', 5, 'forest', '숲', '', '', ''),
('word', '초4', 5, 'fork', '포크', '', '', ''),
('word', '초4', 5, 'friendly', '친절한', '', '', ''),
('word', '초4', 5, 'future', '미래', '', '', ''),
('word', '초4', 5, 'garden', '정원', '', '', ''),
('word', '초4', 5, 'gentle', '온화한', '', '', ''),
('word', '초4', 5, 'giraffe', '기린', '', '', ''),
('word', '초4', 5, 'glove', '장갑', '', '', ''),
('word', '초4', 5, 'goal', '목표', '', '', ''),
('word', '초4', 5, 'gold', '금', '', '', ''),
('word', '초4', 5, 'guest', '손님', '', '', ''),
('word', '초4', 5, 'guide', '안내하다', '', '', ''),
('word', '초4', 5, 'habit', '습관', '', '', ''),
('word', '초4', 5, 'half', '절반', '', '', ''),
('word', '초4', 6, 'hall', '홀', '', '', ''),
('word', '초4', 6, 'healthy', '건강한', '', '', ''),
('word', '초4', 6, 'hear', '듣다', '', '', ''),
('word', '초4', 6, 'heart', '심장', '', '', ''),
('word', '초4', 6, 'heavy', '무거운', '', '', ''),
('word', '초4', 6, 'helpful', '도움이 되는', '', '', ''),
('word', '초4', 6, 'high', '높은', '', '', ''),
('word', '초4', 6, 'hill', '언덕', '', '', ''),
('word', '초4', 6, 'holiday', '휴일', '', '', ''),
('word', '초4', 6, 'hope', '희망', '', '', ''),
('word', '초4', 6, 'horse', '말', '', '', ''),
('word', '초4', 6, 'hotel', '호텔', '', '', ''),
('word', '초4', 6, 'hour', '시간', '', '', ''),
('word', '초4', 6, 'hungry', '배고픈', '', '', ''),
('word', '초4', 6, 'idea', '생각', '', '', ''),
('word', '초4', 6, 'inside', '안에', '', '', ''),
('word', '초4', 6, 'island', '섬', '', '', ''),
('word', '초4', 6, 'jacket', '재킷', '', '', ''),
('word', '초4', 6, 'jeans', '청바지', '', '', ''),
('word', '초4', 6, 'jelly', '젤리', '', '', ''),
('word', '초4', 7, 'jungle', '정글', '', '', ''),
('word', '초4', 7, 'kangaroo', '캥거루', '', '', ''),
('word', '초4', 7, 'key', '열쇠', '', '', ''),
('word', '초4', 7, 'kind', '친절한', '', '', ''),
('word', '초4', 7, 'kitchen', '부엌', '', '', ''),
('word', '초4', 7, 'ladder', '사다리', '', '', ''),
('word', '초4', 7, 'lake', '호수', '', '', ''),
('word', '초4', 7, 'lamp', '램프', '', '', ''),
('word', '초4', 7, 'laugh', '웃다', '', '', ''),
('word', '초4', 7, 'leader', '지도자', '', '', ''),
('word', '초4', 7, 'learn', '배우다', '', '', ''),
('word', '초4', 7, 'leave', '떠나다', '', '', ''),
('word', '초4', 7, 'library', '도서관', '', '', ''),
('word', '초4', 7, 'lion', '사자', '', '', ''),
('word', '초4', 7, 'list', '목록', '', '', ''),
('word', '초4', 7, 'little', '작은', '', '', ''),
('word', '초4', 7, 'market', '시장', '', '', ''),
('word', '초4', 7, 'match', '경기', '', '', ''),
('word', '초4', 7, 'member', '회원', '', '', ''),
('word', '초4', 7, 'middle', '가운데', '', '', ''),
('word', '초4', 8, 'mirror', '거울', '', '', ''),
('word', '초4', 8, 'museum', '박물관', '', '', ''),
('word', '초4', 8, 'nature', '자연', '', '', ''),
('word', '초4', 8, 'neighbor', '이웃', '', '', ''),
('word', '초4', 8, 'nervous', '긴장한', '', '', ''),
('word', '초4', 8, 'north', '북쪽', '', '', ''),
('word', '초4', 8, 'ocean', '대양', '', '', ''),
('word', '초4', 8, 'office', '사무실', '', '', ''),
('word', '초4', 8, 'often', '자주', '', '', ''),
('word', '초4', 8, 'orange', '오렌지', '', '', ''),
('word', '초4', 8, 'outside', '바깥', '', '', ''),
('word', '초4', 8, 'painter', '화가', '', '', ''),
('word', '초4', 8, 'paper', '종이', '', '', ''),
('word', '초4', 8, 'parent', '부모', '', '', ''),
('word', '초4', 8, 'party', '파티', '', '', ''),
('word', '초4', 8, 'piano', '피아노', '', '', ''),
('word', '초4', 8, 'pilot', '조종사', '', '', ''),
('word', '초4', 8, 'planet', '행성', '', '', ''),
('word', '초4', 8, 'player', '선수', '', '', ''),
('word', '초4', 8, 'police', '경찰', '', '', ''),
('word', '초4', 9, 'popular', '인기있는', '', '', ''),
('word', '초4', 9, 'postcard', '엽서', '', '', ''),
('word', '초4', 9, 'present', '선물', '', '', ''),
('word', '초4', 9, 'queen', '여왕', '', '', ''),
('word', '초4', 9, 'quick', '빠른', '', '', ''),
('word', '초4', 9, 'quiet', '조용한', '', '', ''),
('word', '초4', 9, 'rabbit', '토끼', '', '', ''),
('word', '초4', 9, 'raincoat', '우비', '', '', ''),
('word', '초4', 9, 'ready', '준비된', '', '', ''),
('word', '초4', 9, 'restaurant', '식당', '', '', ''),
('word', '초4', 9, 'robot', '로봇', '', '', ''),
('word', '초4', 9, 'roof', '지붕', '', '', ''),
('word', '초4', 9, 'sailor', '선원', '', '', ''),
('word', '초4', 9, 'season', '계절', '', '', ''),
('word', '초4', 9, 'secret', '비밀', '', '', ''),
('word', '초4', 9, 'sheep', '양', '', '', ''),
('word', '초4', 9, 'shopping', '쇼핑', '', '', ''),
('word', '초4', 9, 'singer', '가수', '', '', ''),
('word', '초4', 9, 'silver', '은', '', '', ''),
('word', '초4', 9, 'snowman', '눈사람', '', '', ''),
('word', '초4', 10, 'south', '남쪽', '', '', ''),
('word', '초4', 10, 'special', '특별한', '', '', ''),
('word', '초4', 10, 'springtime', '봄철', '', '', ''),
('word', '초4', 10, 'stadium', '경기장', '', '', ''),
('word', '초4', 10, 'station', '역', '', '', ''),
('word', '초4', 10, 'story', '이야기', '', '', ''),
('word', '초4', 10, 'supermarket', '슈퍼마켓', '', '', ''),
('word', '초4', 10, 'ticket', '표', '', '', ''),
('word', '초4', 10, 'tiger', '호랑이', '', '', ''),
('word', '초4', 10, 'travel', '여행', '', '', ''),
('word', '초4', 10, 'umbrella', '우산', '', '', ''),
('word', '초4', 10, 'uncle', '삼촌', '', '', ''),
('word', '초4', 10, 'uniform', '교복', '', '', ''),
('word', '초4', 10, 'useful', '유용한', '', '', ''),
('word', '초4', 10, 'vacation', '방학', '', '', ''),
('word', '초4', 10, 'village', '마을', '', '', ''),
('word', '초4', 10, 'visitor', '방문객', '', '', ''),
('word', '초4', 10, 'voice', '목소리', '', '', ''),
('word', '초4', 10, 'waiter', '웨이터', '', '', ''),
('word', '초4', 10, 'weather', '날씨', '', '', ''),
('word', '중1', 1, 'ability', '능력', '어떤 일을 해낼 수 있는 힘', '', ''),
('word', '중1', 1, 'academic', '학문의', '학업의', '', ''),
('word', '중1', 1, 'access', '접근', '이용 기회', '', ''),
('word', '중1', 1, 'accommodation', '숙박', '편의 시설', '', ''),
('word', '중1', 1, 'account', '계정', '설명', '', ''),
('word', '중1', 1, 'accuracy', '정확성', '정밀함', '', ''),
('word', '중1', 1, 'achievement', '성취', '업적', '', ''),
('word', '중1', 1, 'activity', '활동', '활발한 행동', '', ''),
('word', '중1', 1, 'adaptability', '적응력', '융통성', '', ''),
('word', '중1', 1, 'adaptable', '적응력 있는', '융통성 있는', '', ''),
('word', '중1', 1, 'adaptation', '적응', '각색', '', ''),
('word', '중1', 1, 'administration', '행정', '관리', '', ''),
('word', '중1', 1, 'administrative', '행정의', '관리의', '', ''),
('word', '중1', 1, 'admission', '입장', '입학 허가', '', ''),
('word', '중1', 1, 'advancement', '발전', '진보', '', ''),
('word', '중1', 1, 'advantage', '이점', '유리함', '', ''),
('word', '중1', 1, 'advertisement', '광고', '선전', '', ''),
('word', '중1', 1, 'advertising', '광고 활동', '광고업', '', ''),
('word', '중1', 1, 'affair', '일', '사건', '', ''),
('word', '중1', 1, 'affection', '애정', '사랑', '', ''),
('word', '중1', 2, 'agency', '기관', '대행사', '', ''),
('word', '중1', 2, 'agenda', '의제', '회의 안건', '', ''),
('word', '중1', 2, 'agree', '동의하다', '찬성하다', '', ''),
('word', '중1', 2, 'agreement', '합의', '동의', '', ''),
('word', '중1', 2, 'agricultural', '농업의', '농사의', '', ''),
('word', '중1', 2, 'agriculture', '농업', '농사', '', ''),
('word', '중1', 2, 'aid', '도움', '지원', '', ''),
('word', '중1', 2, 'aircraft', '항공기', '비행기', '', ''),
('word', '중1', 2, 'airline', '항공사', '항공 노선', '', ''),
('word', '중1', 2, 'alarm', '경보', '불안하게 하다', '', ''),
('word', '중1', 2, 'alternative', '대안', '대체', '', ''),
('word', '중1', 2, 'amazing', '놀라운', '굉장한', '', ''),
('word', '중1', 2, 'ambition', '야망', '포부', '', ''),
('word', '중1', 2, 'amusement', '오락', '즐거움', '', ''),
('word', '중1', 2, 'analysis', '분석', '검토', '', ''),
('word', '중1', 2, 'ancestor', '조상', '선조', '', ''),
('word', '중1', 2, 'anniversary', '기념일', '주년', '', ''),
('word', '중1', 2, 'announcement', '발표', '공지', '', ''),
('word', '중1', 2, 'anticipation', '기대', '예상', '', ''),
('word', '중1', 2, 'anxiety', '불안', '걱정', '', ''),
('word', '중1', 3, 'apartment', '아파트', '공동주택', '', ''),
('word', '중1', 3, 'apology', '사과', '변명', '', ''),
('word', '중1', 3, 'appearance', '외모', '등장', '', ''),
('word', '중1', 3, 'appliance', '기기', '가전제품', '', ''),
('word', '중1', 3, 'application', '신청', '적용', '', ''),
('word', '중1', 3, 'appointment', '약속', '임명', '', ''),
('word', '중1', 3, 'approach', '접근하다', '다가가다', '', ''),
('word', '중1', 3, 'approval', '승인', '찬성', '', ''),
('word', '중1', 3, 'architect', '건축가', '설계자', '', ''),
('word', '중1', 3, 'architecture', '건축', '건축 양식', '', ''),
('word', '중1', 3, 'arrival', '도착', '도래', '', ''),
('word', '중1', 3, 'arrive', '도착하다', '이르다', '', ''),
('word', '중1', 3, 'article', '기사', '물품', '', ''),
('word', '중1', 3, 'assistance', '도움', '지원', '', ''),
('word', '중1', 3, 'assistant', '조수', '보조자', '', ''),
('word', '중1', 3, 'assistantship', '조교직', '보조 역할', '', ''),
('word', '중1', 3, 'association', '협회', '연관', '', ''),
('word', '중1', 3, 'athletic', '운동의', '체육의', '', ''),
('word', '중1', 3, 'atmosphere', '대기', '분위기', '', ''),
('word', '중1', 3, 'attend', '참석하다', '출석하다', '', ''),
('word', '중1', 4, 'attention', '주의', '집중', '', ''),
('word', '중1', 4, 'attraction', '매력', '명소', '', ''),
('word', '중1', 4, 'attractive', '매력적인', '눈길을 끄는', '', ''),
('word', '중1', 4, 'audition', '오디션', '시험 공연', '', ''),
('word', '중1', 4, 'author', '저자', '작가', '', ''),
('word', '중1', 4, 'awareness', '인식', '자각', '', ''),
('word', '중1', 4, 'baggage', '짐', '수하물', '', ''),
('word', '중1', 4, 'balance', '균형', '균형을 잡다', '', ''),
('word', '중1', 4, 'beautiful', '아름다운', '멋진', '', ''),
('word', '중1', 4, 'belief', '믿음', '신념', '', ''),
('word', '중1', 4, 'believe', '믿다', '생각하다', '', ''),
('word', '중1', 4, 'beneficial', '유익한', '이로운', '', ''),
('word', '중1', 4, 'biography', '전기', '생애', '', ''),
('word', '중1', 4, 'biological', '생물학의', '생물의', '', ''),
('word', '중1', 4, 'biology', '생물학', '생명 과학', '', ''),
('word', '중1', 4, 'border', '경계', '국경', '', ''),
('word', '중1', 4, 'borrow', '빌리다', '차용하다', '', ''),
('word', '중1', 4, 'branch', '가지', '지점', '', ''),
('word', '중1', 4, 'brand', '상표', '브랜드', '', ''),
('word', '중1', 4, 'broadcast', '방송', '방송하다', '', ''),
('word', '중1', 5, 'building', '건물', '건축', '', ''),
('word', '중1', 5, 'business', '사업', '업무', '', ''),
('word', '중1', 5, 'campaign', '운동', '캠페인', '', ''),
('word', '중1', 5, 'candidate', '후보', '지원자', '', ''),
('word', '중1', 5, 'care', '돌보다', '걱정하다', '', ''),
('word', '중1', 5, 'celebration', '축하', '기념 행사', '', ''),
('word', '중1', 5, 'century', '세기', '100년', '', ''),
('word', '중1', 5, 'championship', '선수권', '우승', '', ''),
('word', '중1', 5, 'characteristic', '특징', '특성', '', ''),
('word', '중1', 5, 'choose', '선택하다', '고르다', '', ''),
('word', '중1', 5, 'citizens', '시민들', '국민들', '', ''),
('word', '중1', 5, 'citizenship', '시민권', '시민 의식', '', ''),
('word', '중1', 5, 'civilization', '문명', '문명 사회', '', ''),
('word', '중1', 5, 'classical', '고전의', '전통적인', '', ''),
('word', '중1', 5, 'collection', '수집', '모음', '', ''),
('word', '중1', 5, 'college', '대학', '단과대학', '', ''),
('word', '중1', 5, 'combination', '결합', '조합', '', ''),
('word', '중1', 5, 'comfort', '편안함', '위로', '', ''),
('word', '중1', 5, 'comfortable', '편안한', '쾌적한', '', ''),
('word', '중1', 5, 'commentary', '논평', '해설', '', ''),
('word', '중1', 6, 'commerce', '상업', '무역', '', ''),
('word', '중1', 6, 'common', '흔한', '공통의', '', ''),
('word', '중1', 6, 'communicate', '의사소통하다', '전달하다', '', ''),
('word', '중1', 6, 'communication', '의사소통', '전달', '', ''),
('word', '중1', 6, 'comparison', '비교', '대조', '', ''),
('word', '중1', 6, 'complaint', '불평', '항의', '', ''),
('word', '중1', 6, 'completion', '완성', '마무리', '', ''),
('word', '중1', 6, 'composition', '구성', '작문', '', ''),
('word', '중1', 6, 'conclusion', '결론', '마무리', '', ''),
('word', '중1', 6, 'confidence', '자신감', '신뢰', '', ''),
('word', '중1', 6, 'connection', '연결', '관계', '', ''),
('word', '중1', 6, 'construction', '건설', '구조', '', ''),
('word', '중1', 6, 'contribution', '기여', '공헌', '', ''),
('word', '중1', 6, 'conversation', '대화', '회화', '', ''),
('word', '중1', 6, 'cooperation', '협력', '협동', '', ''),
('word', '중1', 6, 'cooperative', '협력적인', '협동의', '', ''),
('word', '중1', 6, 'country', '나라', '시골', '', ''),
('word', '중1', 6, 'creativity', '창의력', '창의성', '', ''),
('word', '중1', 6, 'curiosity', '호기심', '궁금해하는 마음', '', ''),
('word', '중1', 6, 'curiosity', '호기심', '궁금해하는 마음', '', ''),
('word', '중1', 7, 'customer', '손님', '고객', '', ''),
('word', '중1', 7, 'dangerous', '위험한', '위험성이 있는', '', ''),
('word', '중1', 7, 'decision', '결정', '판단', '', ''),
('word', '중1', 7, 'dedication', '헌신', '전념', '', ''),
('word', '중1', 7, 'definition', '정의', '의미', '', ''),
('word', '중1', 7, 'degree', '정도', '학위', '', ''),
('word', '중1', 7, 'delivery', '배달', '전달', '', ''),
('word', '중1', 7, 'demonstration', '시연', '증명', '', ''),
('word', '중1', 7, 'departure', '출발', '떠남', '', ''),
('word', '중1', 7, 'description', '설명', '묘사', '', ''),
('word', '중1', 7, 'development', '발전', '개발', '', ''),
('word', '중1', 7, 'developmental', '발달의', '발전의', '', ''),
('word', '중1', 7, 'difficult', '어려운', '힘든', '', ''),
('word', '중1', 7, 'difficulty', '어려움', '곤란', '', ''),
('word', '중1', 7, 'directional', '방향의', '지시의', '', ''),
('word', '중1', 7, 'discovery', '발견', '발견물', '', ''),
('word', '중1', 7, 'discussion', '토론', '논의', '', ''),
('word', '중1', 7, 'disease', '질병', '병', '', ''),
('word', '중1', 7, 'distribution', '분배', '유통', '', ''),
('word', '중1', 7, 'economic', '경제의', '경제적인', '', ''),
('word', '중1', 8, 'editor', '편집자', '편집인', '', ''),
('word', '중1', 8, 'education', '교육', '학습', '', ''),
('word', '중1', 8, 'educational', '교육의', '교육적인', '', ''),
('word', '중1', 8, 'effective', '효과적인', '유효한', '', ''),
('word', '중1', 8, 'efficiency', '효율', '능률', '', ''),
('word', '중1', 8, 'electric', '전기의', '전기와 관련된', '', ''),
('word', '중1', 8, 'electricity', '전기', '전력', '', ''),
('word', '중1', 8, 'emergency', '비상 상황', '응급 상황', '', ''),
('word', '중1', 8, 'employee', '직원', '종업원', '', ''),
('word', '중1', 8, 'employer', '고용주', '사용자', '', ''),
('word', '중1', 8, 'encouragement', '격려', '용기', '', ''),
('word', '중1', 8, 'ending', '끝', '결말', '', ''),
('word', '중1', 8, 'engineering', '공학', '기술 분야', '', ''),
('word', '중1', 8, 'enjoyable', '즐거운', '재미있는', '', ''),
('word', '중1', 8, 'entrance', '입구', '입장', '', ''),
('word', '중1', 8, 'environmental', '환경의', '환경적인', '', ''),
('word', '중1', 8, 'error', '오류', '실수', '', ''),
('word', '중1', 8, 'especially', '특히', '유난히', '', ''),
('word', '중1', 8, 'establishment', '설립', '기관', '', ''),
('word', '중1', 8, 'evaluation', '평가', '판단', '', ''),
('word', '중1', 9, 'event', '사건', '행사', '', ''),
('word', '중1', 9, 'evolution', '진화', '발전', '', ''),
('word', '중1', 9, 'examination', '시험', '검사', '', ''),
('word', '중1', 9, 'example', '예', '본보기', '', ''),
('word', '중1', 9, 'excitement', '흥분', '신남', '', ''),
('word', '중1', 9, 'exercise', '운동', '연습', '', ''),
('word', '중1', 9, 'existence', '존재', '실재', '', ''),
('word', '중1', 9, 'expectation', '기대', '예상', '', ''),
('word', '중1', 9, 'expense', '비용', '지출', '', ''),
('word', '중1', 9, 'experience', '경험', '체험', '', ''),
('word', '중1', 9, 'experiment', '실험', '시험', '', ''),
('word', '중1', 9, 'explanation', '설명', '해명', '', ''),
('word', '중1', 9, 'expression', '표현', '표정', '', ''),
('word', '중1', 9, 'failure', '실패', '고장', '', ''),
('word', '중1', 9, 'feedback', '피드백', '반응', '', ''),
('word', '중1', 9, 'feeling', '감정', '기분', '', ''),
('word', '중1', 9, 'finally', '마침내', '결국', '', ''),
('word', '중1', 9, 'flight', '비행', '항공편', '', ''),
('word', '중1', 9, 'force', '힘', '강요하다', '', ''),
('word', '중1', 9, 'foreign', '외국의', '외래의', '', ''),
('word', '중1', 10, 'form', '형태', '양식', '', ''),
('word', '중1', 10, 'foundation', '기초', '재단', '', ''),
('word', '중1', 10, 'foundational', '기초의', '기본적인', '', ''),
('word', '중1', 10, 'friendship', '우정', '친밀함', '', ''),
('word', '중1', 10, 'general', '일반적인', '보통의', '', ''),
('word', '중1', 10, 'generation', '세대', '발전기', '', ''),
('word', '중1', 10, 'government', '정부', '통치', '', ''),
('word', '중1', 10, 'governmental', '정부의', '행정의', '', ''),
('word', '중1', 10, 'growth', '성장', '증가', '', ''),
('word', '중1', 10, 'happen', '일어나다', '발생하다', '', ''),
('word', '중1', 10, 'history', '역사', '이력', '', ''),
('word', '중1', 10, 'honor', '명예', '존경', '', ''),
('word', '중1', 10, 'however', '그러나', '하지만', '', ''),
('word', '중1', 10, 'identity', '정체성', '신원', '', ''),
('word', '중1', 10, 'importance', '중요성', '중대함', '', ''),
('word', '중1', 10, 'important', '중요한', '중대한', '', ''),
('word', '중1', 10, 'impossible', '불가능한', '어려운', '', ''),
('word', '중1', 10, 'improvement', '개선', '향상', '', ''),
('word', '중1', 10, 'independence', '독립', '자립', '', ''),
('word', '중1', 10, 'independent', '독립적인', '자립적인', '', ''),
('word', '중1', 11, 'information', '정보', '지식', '', ''),
('word', '중1', 11, 'informational', '정보의', '정보 제공의', '', ''),
('word', '중1', 11, 'initiative', '주도권', '진취성', '', ''),
('word', '중1', 11, 'innovation', '혁신', '새로운 변화', '', ''),
('word', '중1', 11, 'inspection', '검사', '점검', '', ''),
('word', '중1', 11, 'instruction', '지시', '설명', '', ''),
('word', '중1', 11, 'instructional', '교육의', '지도용의', '', ''),
('word', '중1', 11, 'instrument', '기구', '악기', '', ''),
('word', '중1', 11, 'insurance', '보험', '보장', '', ''),
('word', '중1', 11, 'intention', '의도', '목적', '', ''),
('word', '중1', 11, 'interaction', '상호작용', '교류', '', ''),
('word', '중1', 11, 'interest', '관심', '흥미', '', ''),
('word', '중1', 11, 'international', '국제적인', '국가 간의', '', ''),
('word', '중1', 11, 'introduce', '소개하다', '도입하다', '', ''),
('word', '중1', 11, 'invent', '발명하다', '고안하다', '', ''),
('word', '중1', 11, 'investment', '투자', '투입', '', ''),
('word', '중1', 11, 'item', '항목', '물품', '', ''),
('word', '중1', 11, 'journey', '여행', '여정', '', ''),
('word', '중1', 11, 'judgment', '판단', '판결', '', ''),
('word', '중1', 11, 'kindness', '친절', '상냥함', '', ''),
('word', '중1', 12, 'knowledge', '지식', '이해', '', ''),
('word', '중1', 12, 'lack', '부족', '부족하다', '', ''),
('word', '중1', 12, 'landscape', '풍경', '경치', '', ''),
('word', '중1', 12, 'language', '언어', '말', '', ''),
('word', '중1', 12, 'launch', '출시하다', '발사하다', '', ''),
('word', '중1', 12, 'leadership', '지도력', '리더십', '', ''),
('word', '중1', 12, 'learned', '배운', '학식 있는', '', ''),
('word', '중1', 12, 'learning', '학습', '배움', '', ''),
('word', '중1', 12, 'level', '수준', '단계', '', ''),
('word', '중1', 12, 'lifestyle', '생활 방식', '삶의 방식', '', ''),
('word', '중1', 12, 'limit', '한계', '제한', '', ''),
('word', '중1', 12, 'literature', '문학', '문헌', '', ''),
('word', '중1', 12, 'local', '지역의', '현지의', '', ''),
('word', '중1', 12, 'location', '위치', '장소', '', ''),
('word', '중1', 12, 'loss', '손실', '상실', '', ''),
('word', '중1', 12, 'magazine', '잡지', '정기 간행물', '', ''),
('word', '중1', 12, 'maintenance', '유지', '정비', '', ''),
('word', '중1', 12, 'management', '관리', '경영', '', ''),
('word', '중1', 12, 'manager', '관리자', '경영자', '', ''),
('word', '중1', 12, 'manner', '방식', '태도', '', ''),
('word', '중1', 13, 'meaning', '의미', '뜻', '', ''),
('word', '중1', 13, 'membership', '회원 자격', '회원권', '', ''),
('word', '중1', 13, 'memory', '기억', '추억', '', ''),
('word', '중1', 13, 'message', '메시지', '전언', '', ''),
('word', '중1', 13, 'metal', '금속', '쇠', '', ''),
('word', '중1', 13, 'mission', '임무', '사명', '', ''),
('word', '중1', 13, 'mistake', '실수', '잘못', '', ''),
('word', '중1', 13, 'mixture', '혼합', '혼합물', '', ''),
('word', '중1', 13, 'model', '모형', '본보기', '', ''),
('word', '중1', 13, 'modern', '현대의', '최신의', '', ''),
('word', '중1', 13, 'moment', '순간', '잠깐', '', ''),
('word', '중1', 13, 'movement', '운동', '움직임', '', ''),
('word', '중1', 13, 'national', '국가의', '국민의', '', ''),
('word', '중1', 13, 'necessary', '필요한', '필수적인', '', ''),
('word', '중1', 13, 'normal', '보통의', '정상적인', '', ''),
('word', '중1', 13, 'notice', '알아차리다', '공지', '', ''),
('word', '중1', 13, 'noticeable', '눈에 띄는', '알아차릴 수 있는', '', ''),
('word', '중1', 13, 'observation', '관찰', '관측', '', ''),
('word', '중1', 13, 'occasion', '경우', '행사', '', ''),
('word', '중1', 13, 'offer', '제안하다', '제공하다', '', ''),
('word', '중1', 14, 'operation', '작동', '운영', '', ''),
('word', '중1', 14, 'opportunity', '기회', '찬스', '', ''),
('word', '중1', 14, 'opposite', '반대의', '맞은편의', '', ''),
('word', '중1', 14, 'order', '순서', '주문', '', ''),
('word', '중1', 14, 'organization', '조직', '단체', '', ''),
('word', '중1', 14, 'organizational', '조직의', '단체의', '', ''),
('word', '중1', 14, 'original', '원래의', '독창적인', '', ''),
('word', '중1', 14, 'output', '산출물', '생산량', '', ''),
('word', '중1', 14, 'owner', '주인', '소유자', '', ''),
('word', '중1', 14, 'participation', '참여', '참가', '', ''),
('word', '중1', 14, 'partner', '파트너', '동료', '', ''),
('word', '중1', 14, 'passenger', '승객', '탑승객', '', ''),
('word', '중1', 14, 'payment', '지불', '납부', '', ''),
('word', '중1', 14, 'percentage', '백분율', '비율', '', ''),
('word', '중1', 14, 'performance', '공연', '성과', '', ''),
('word', '중1', 14, 'permission', '허가', '허락', '', ''),
('word', '중1', 14, 'personal', '개인의', '사적인', '', ''),
('word', '중1', 14, 'personality', '성격', '개성', '', ''),
('word', '중1', 14, 'perspective', '관점', '시각', '', ''),
('word', '중1', 14, 'photograph', '사진', '촬영하다', '', ''),
('word', '중1', 15, 'physical', '신체의', '물리적인', '', ''),
('word', '중1', 15, 'population', '인구', '주민', '', ''),
('word', '중1', 15, 'position', '위치', '직책', '', ''),
('word', '중1', 15, 'positive', '긍정적인', '확실한', '', ''),
('word', '중1', 15, 'possible', '가능한', '있을 수 있는', '', ''),
('word', '중1', 15, 'practice', '연습', '실행', '', ''),
('word', '중1', 15, 'preference', '선호', '선택', '', ''),
('word', '중1', 15, 'preparation', '준비', '예비', '', ''),
('word', '중1', 15, 'presence', '존재', '참석', '', ''),
('word', '중1', 15, 'pressure', '압력', '압박', '', ''),
('word', '중1', 15, 'priority', '우선', '우선순위', '', ''),
('word', '중1', 15, 'procedure', '절차', '과정', '', ''),
('word', '중1', 15, 'production', '생산', '제작', '', ''),
('word', '중1', 15, 'profession', '직업', '전문직', '', ''),
('word', '중1', 15, 'promotion', '촉진', '승진', '', ''),
('word', '중1', 15, 'proposal', '제안', '계획안', '', ''),
('word', '중1', 15, 'protection', '보호', '방어', '', ''),
('word', '중1', 15, 'quality', '질', '품질', '', ''),
('word', '중1', 15, 'quantity', '양', '수량', '', ''),
('word', '중1', 15, 'reaction', '반응', '반작용', '', ''),
('word', '중1', 16, 'reality', '현실', '실제', '', ''),
('word', '중1', 16, 'reason', '이유', '이성', '', ''),
('word', '중1', 16, 'recognition', '인식', '인정', '', ''),
('word', '중1', 16, 'recommendation', '추천', '권고', '', ''),
('word', '중1', 16, 'record', '기록', '기록하다', '', ''),
('word', '중1', 16, 'recovery', '회복', '복구', '', ''),
('word', '중1', 16, 'reduction', '감소', '축소', '', ''),
('word', '중1', 16, 'reference', '참고', '언급', '', ''),
('word', '중1', 16, 'reflection', '반영', '반성', '', ''),
('word', '중1', 16, 'relationship', '관계', '연관', '', ''),
('word', '중1', 16, 'reputation', '평판', '명성', '', ''),
('word', '중1', 16, 'requirement', '요구', '조건', '', ''),
('word', '중1', 16, 'resource', '자원', '자료', '', ''),
('word', '중1', 16, 'response', '응답', '반응', '', ''),
('word', '중1', 16, 'responsibility', '책임', '의무', '', ''),
('word', '중1', 16, 'revenue', '수익', '수입', '', ''),
('word', '중1', 16, 'review', '검토', '평가', '', ''),
('word', '중1', 16, 'safety', '안전', '안전성', '', ''),
('word', '중1', 16, 'sample', '표본', '샘플', '', ''),
('word', '중1', 16, 'schedule', '일정', '시간표', '', ''),
('word', '중1', 17, 'scientific', '과학의', '과학적인', '', ''),
('word', '중1', 17, 'selection', '선택', '선발', '', ''),
('word', '중1', 17, 'series', '연속', '시리즈', '', ''),
('word', '중1', 17, 'service', '서비스', '봉사', '', ''),
('word', '중1', 17, 'setting', '환경', '배경', '', ''),
('word', '중1', 17, 'signal', '신호', '신호를 보내다', '', ''),
('word', '중1', 17, 'significance', '중요성', '의미', '', ''),
('word', '중1', 17, 'significant', '중요한', '의미 있는', '', ''),
('word', '중1', 17, 'situation', '상황', '상태', '', ''),
('word', '중1', 17, 'skill', '기술', '능력', '', ''),
('word', '중1', 17, 'solution', '해결', '해답', '', ''),
('word', '중1', 17, 'source', '출처', '원천', '', ''),
('word', '중1', 17, 'standard', '기준', '표준', '', ''),
('word', '중1', 17, 'statement', '진술', '성명', '', ''),
('word', '중1', 17, 'strategy', '전략', '계획', '', ''),
('word', '중1', 17, 'structure', '구조', '구성', '', ''),
('word', '중1', 17, 'style', '스타일', '양식', '', ''),
('word', '중1', 17, 'subject', '주제', '과목', '', ''),
('word', '중1', 17, 'success', '성공', '성과', '', ''),
('word', '중1', 17, 'suggestion', '제안', '조언', '', ''),
('word', '중1', 18, 'supply', '공급', '제공하다', '', ''),
('word', '중1', 18, 'support', '지원', '지지', '', ''),
('word', '중1', 18, 'surface', '표면', '겉면', '', ''),
('word', '중1', 18, 'system', '체계', '시스템', '', ''),
('word', '중1', 18, 'talent', '재능', '소질', '', ''),
('word', '중1', 18, 'target', '목표', '표적', '', ''),
('word', '중1', 18, 'task', '과제', '임무', '', ''),
('word', '중1', 18, 'teaching', '가르침', '교육', '', ''),
('word', '중1', 18, 'technique', '기술', '기법', '', ''),
('word', '중1', 18, 'technology', '기술', '과학 기술', '', ''),
('word', '중1', 18, 'teenager', '십대', '청소년', '', ''),
('word', '중1', 18, 'temperature', '온도', '기온', '', ''),
('word', '중1', 18, 'tendency', '경향', '성향', '', ''),
('word', '중1', 18, 'theme', '주제', '테마', '', ''),
('word', '중1', 18, 'theory', '이론', '학설', '', ''),
('word', '중1', 18, 'thought', '생각', '사고', '', ''),
('word', '중1', 18, 'tool', '도구', '수단', '', ''),
('word', '중1', 18, 'topic', '주제', '이야깃거리', '', ''),
('word', '중1', 18, 'tourist', '관광객', '여행자', '', ''),
('word', '중1', 18, 'tradition', '전통', '관습', '', ''),
('word', '중1', 19, 'traditional', '전통적인', '관습적인', '', ''),
('word', '중1', 19, 'traditionally', '전통적으로', '관례적으로', '', ''),
('word', '중1', 19, 'traffic', '교통', '차량 흐름', '', ''),
('word', '중1', 19, 'training', '훈련', '교육 과정', '', ''),
('word', '중1', 19, 'transfer', '이동', '이전', '', ''),
('word', '중1', 19, 'transport', '수송', '운송하다', '', ''),
('word', '중1', 19, 'transportation', '교통', '운송', '', ''),
('word', '중1', 19, 'traveler', '여행자', '관광객', '', ''),
('word', '중1', 19, 'treatment', '치료', '대우', '', ''),
('word', '중1', 19, 'trend', '경향', '유행', '', ''),
('word', '중1', 19, 'trial', '시험', '재판', '', ''),
('word', '중1', 19, 'typical', '전형적인', '대표적인', '', ''),
('word', '중1', 19, 'understanding', '이해', '이해심', '', ''),
('word', '중1', 19, 'unusual', '이상한', '드문', '', ''),
('word', '중1', 19, 'usefully', '유용하게', '쓸모 있게', '', ''),
('word', '중1', 19, 'value', '가치', '중요성', '', ''),
('word', '중1', 19, 'variation', '변화', '변형', '', ''),
('word', '중1', 19, 'variety', '다양성', '종류', '', ''),
('word', '중1', 19, 'vehicle', '차량', '운송 수단', '', ''),
('word', '중1', 19, 'version', '버전', '판', '', ''),
('word', '중1', 20, 'victory', '승리', '성공', '', ''),
('word', '중1', 20, 'vision', '시야', '비전', '', ''),
('word', '중1', 20, 'volume', '양', '부피', '', ''),
('word', '중1', 20, 'volunteer', '자원봉사자', '자원하다', '', ''),
('word', '중1', 20, 'warning', '경고', '주의', '', ''),
('word', '중1', 20, 'wealth', '부', '재산', '', ''),
('word', '중1', 20, 'weathering', '풍화', '바람·비로 닳는 현상', '', ''),
('word', '중1', 20, 'wedding', '결혼식', '혼례', '', ''),
('word', '중1', 20, 'weekly', '매주의', '주간의', '', ''),
('word', '중1', 20, 'welcome', '환영하다', '환영', '', ''),
('word', '중1', 20, 'welfare', '복지', '행복', '', ''),
('word', '중1', 20, 'western', '서쪽의', '서양의', '', ''),
('word', '중1', 20, 'wildlife', '야생 동물', '야생 생물', '', ''),
('word', '중1', 20, 'willingness', '의지', '자발성', '', ''),
('word', '중1', 20, 'wisdom', '지혜', '현명함', '', ''),
('word', '중1', 20, 'worker', '노동자', '일하는 사람', '', ''),
('word', '중1', 20, 'writing', '글쓰기', '저술', '', ''),
('word', '중1', 20, 'x-ray', '엑스선', '엑스선 사진', '', ''),
('word', '중1', 20, 'youth', '젊은이', '청년', '', ''),
('word', '중1', 20, 'zone', '지역', '구역', '', ''),
('word', '중2', 1, 'ability', '능력', '재능', '', ''),
('word', '중2', 1, 'abroad', '해외로', '외국에서', '', ''),
('word', '중2', 1, 'absence', '결석', '부재', '', ''),
('word', '중2', 1, 'accept', '받아들이다', '수락하다', '', ''),
('word', '중2', 1, 'access', '접근', '이용 권한', '', ''),
('word', '중2', 1, 'accident', '사고', '우연한 사건', '', ''),
('word', '중2', 1, 'accompany', '동행하다', '수반하다', '', ''),
('word', '중2', 1, 'accomplish', '성취하다', '완수하다', '', ''),
('word', '중2', 1, 'accurate', '정확한', '정밀한', '', ''),
('word', '중2', 1, 'accuse', '비난하다', '고발하다', '', ''),
('word', '중2', 1, 'achievable', '달성 가능한', '이룰 수 있는', '', ''),
('word', '중2', 1, 'achieve', '달성하다', '이루다', '', ''),
('word', '중2', 1, 'active', '활동적인', '능동적인', '', ''),
('word', '중2', 1, 'actual', '실제의', '사실상의', '', ''),
('word', '중2', 1, 'adapt', '적응하다', '맞추다', '', ''),
('word', '중2', 1, 'addition', '추가', '덧붙임', '', ''),
('word', '중2', 1, 'adequate', '충분한', '적절한', '', ''),
('word', '중2', 1, 'adjust', '조정하다', '맞추다', '', ''),
('word', '중2', 1, 'admire', '존경하다', '감탄하다', '', ''),
('word', '중2', 1, 'admit', '인정하다', '허가하다', '', ''),
('word', '중2', 2, 'adopt', '채택하다', '입양하다', '', ''),
('word', '중2', 2, 'adult', '성인', '어른', '', ''),
('word', '중2', 2, 'advance', '전진하다', '진보', '', ''),
('word', '중2', 2, 'advantage', '이점', '유리한 점', '', ''),
('word', '중2', 2, 'adventure', '모험', '모험 경험', '', ''),
('word', '중2', 2, 'advertise', '광고하다', '홍보하다', '', ''),
('word', '중2', 2, 'affair', '일', '사건', '', ''),
('word', '중2', 2, 'affect', '영향을 주다', '감정을 건드리다', '', ''),
('word', '중2', 2, 'afford', '여유가 있다', '~할 형편이 되다', '', ''),
('word', '중2', 2, 'agency', '기관', '대행사', '', ''),
('word', '중2', 2, 'agenda', '의제', '일정표', '', ''),
('word', '중2', 2, 'agree', '동의하다', '의견이 일치하다', '', ''),
('word', '중2', 2, 'agriculture', '농업', '농사', '', ''),
('word', '중2', 2, 'aid', '도움', '지원하다', '', ''),
('word', '중2', 2, 'aim', '목표', '겨누다', '', ''),
('word', '중2', 2, 'alarm', '경보', '놀라게 하다', '', ''),
('word', '중2', 2, 'album', '앨범', '사진첩', '', ''),
('word', '중2', 2, 'alert', '경계하는', '알리다', '', ''),
('word', '중2', 2, 'allow', '허락하다', '가능하게 하다', '', ''),
('word', '중2', 2, 'allowance', '용돈', '허용량', '', ''),
('word', '중2', 3, 'alternative', '대안', '대체 선택', '', ''),
('word', '중2', 3, 'amazing', '놀라운', '굉장한', '', ''),
('word', '중2', 3, 'ambition', '야망', '목표', '', ''),
('word', '중2', 3, 'amount', '양', '총액', '', ''),
('word', '중2', 3, 'amuse', '즐겁게 하다', '재미있게 하다', '', ''),
('word', '중2', 3, 'analysis', '분석', '세부 검토', '', ''),
('word', '중2', 3, 'ancient', '고대의', '아주 오래된', '', ''),
('word', '중2', 3, 'angle', '각도', '관점', '', ''),
('word', '중2', 3, 'announce', '발표하다', '알리다', '', ''),
('word', '중2', 3, 'anxiety', '불안', '걱정', '', ''),
('word', '중2', 3, 'anxious', '불안한', '걱정하는', '', ''),
('word', '중2', 3, 'apologize', '사과하다', '미안해하다', '', ''),
('word', '중2', 3, 'apology', '사과', '미안함 표현', '', ''),
('word', '중2', 3, 'apparent', '분명한', '겉으로 보이는', '', ''),
('word', '중2', 3, 'appeal', '호소하다', '매력', '', ''),
('word', '중2', 3, 'appear', '나타나다', '~처럼 보이다', '', ''),
('word', '중2', 3, 'apply', '지원하다', '적용하다', '', ''),
('word', '중2', 3, 'appoint', '임명하다', '지정하다', '', ''),
('word', '중2', 3, 'appreciate', '감사하다', '가치를 인정하다', '', ''),
('word', '중2', 3, 'approach', '접근하다', '방법', '', ''),
('word', '중2', 4, 'appropriate', '적절한', '알맞은', '', ''),
('word', '중2', 4, 'approve', '승인하다', '찬성하다', '', ''),
('word', '중2', 4, 'argue', '논쟁하다', '주장하다', '', ''),
('word', '중2', 4, 'arrange', '정리하다', '준비하다', '', ''),
('word', '중2', 4, 'arrival', '도착', '도착함', '', ''),
('word', '중2', 4, 'arrive', '도착하다', '이르다', '', ''),
('word', '중2', 4, 'article', '기사', '물품', '', ''),
('word', '중2', 4, 'artificial', '인공의', '인위적인', '', ''),
('word', '중2', 4, 'aspect', '측면', '관점', '', ''),
('word', '중2', 4, 'assist', '돕다', '보조하다', '', ''),
('word', '중2', 4, 'associate', '연관시키다', '동료', '', ''),
('word', '중2', 4, 'assume', '추정하다', '가정하다', '', ''),
('word', '중2', 4, 'athlete', '운동선수', '체육인', '', ''),
('word', '중2', 4, 'attach', '붙이다', '첨부하다', '', ''),
('word', '중2', 4, 'attempt', '시도', '시도하다', '', ''),
('word', '중2', 4, 'attend', '참석하다', '출석하다', '', ''),
('word', '중2', 4, 'attitude', '태도', '마음가짐', '', ''),
('word', '중2', 4, 'attract', '끌다', '매료시키다', '', ''),
('word', '중2', 4, 'audience', '청중', '관객', '', ''),
('word', '중2', 4, 'author', '저자', '작가', '', ''),
('word', '중2', 5, 'authority', '권위', '당국', '', ''),
('word', '중2', 5, 'automatic', '자동의', '무의식적인', '', ''),
('word', '중2', 5, 'available', '이용 가능한', '시간이 있는', '', ''),
('word', '중2', 5, 'average', '평균', '평균의', '', ''),
('word', '중2', 5, 'avoid', '피하다', '방지하다', '', ''),
('word', '중2', 5, 'award', '상', '수여하다', '', ''),
('word', '중2', 5, 'aware', '알고 있는', '인식하는', '', ''),
('word', '중2', 5, 'background', '배경', '배경 지식', '', ''),
('word', '중2', 5, 'balance', '균형', '균형을 잡다', '', ''),
('word', '중2', 5, 'basic', '기본적인', '기초의', '', ''),
('word', '중2', 5, 'battle', '전투', '싸우다', '', ''),
('word', '중2', 5, 'behavior', '행동', '행동 양식', '', ''),
('word', '중2', 5, 'benefit', '이익', '혜택', '', ''),
('word', '중2', 5, 'beyond', '~을 넘어서', '그 이상으로', '', ''),
('word', '중2', 5, 'billion', '10억', '십억', '', ''),
('word', '중2', 5, 'biology', '생물학', '생명 과학', '', ''),
('word', '중2', 5, 'birth', '탄생', '출생', '', ''),
('word', '중2', 5, 'blame', '비난하다', '책임을 돌리다', '', ''),
('word', '중2', 5, 'border', '경계', '국경', '', ''),
('word', '중2', 5, 'brain', '뇌', '지능', '', ''),
('word', '중2', 6, 'branch', '가지', '지점', '', ''),
('word', '중2', 6, 'brand', '상표', '브랜드', '', ''),
('word', '중2', 6, 'brief', '짧은', '간단한', '', ''),
('word', '중2', 6, 'broad', '넓은', '폭넓은', '', ''),
('word', '중2', 6, 'budget', '예산', '예산을 세우다', '', ''),
('word', '중2', 6, 'burden', '부담', '짐', '', ''),
('word', '중2', 6, 'calculate', '계산하다', '추정하다', '', ''),
('word', '중2', 6, 'campaign', '운동', '캠페인', '', ''),
('word', '중2', 6, 'cancel', '취소하다', '무효로 하다', '', ''),
('word', '중2', 6, 'capture', '포착하다', '붙잡다', '', ''),
('word', '중2', 6, 'career', '직업', '경력', '', ''),
('word', '중2', 6, 'category', '범주', '부류', '', ''),
('word', '중2', 6, 'cause', '원인', '야기하다', '', ''),
('word', '중2', 6, 'celebrate', '축하하다', '기념하다', '', ''),
('word', '중2', 6, 'challenge', '도전', '도전하다', '', ''),
('word', '중2', 6, 'character', '성격', '인물', '', ''),
('word', '중2', 6, 'charge', '요금', '청구하다', '', ''),
('word', '중2', 6, 'choice', '선택', '선택권', '', ''),
('word', '중2', 6, 'citizen', '시민', '국민', '', ''),
('word', '중2', 6, 'claim', '주장하다', '요구하다', '', ''),
('word', '중2', 7, 'clarify', '명확히 하다', '분명하게 설명하다', '', ''),
('word', '중2', 7, 'classic', '고전적인', '대표적인', '', ''),
('word', '중2', 7, 'climate', '기후', '날씨 상태', '', ''),
('word', '중2', 7, 'collect', '수집하다', '모으다', '', ''),
('word', '중2', 7, 'combine', '결합하다', '합치다', '', ''),
('word', '중2', 7, 'comment', '논평', '의견', '', ''),
('word', '중2', 7, 'communicate', '의사소통하다', '전달하다', '', ''),
('word', '중2', 7, 'community', '공동체', '지역사회', '', ''),
('word', '중2', 7, 'compare', '비교하다', '대조하다', '', ''),
('word', '중2', 7, 'compete', '경쟁하다', '겨루다', '', ''),
('word', '중2', 7, 'complete', '완성하다', '완전한', '', ''),
('word', '중2', 7, 'complex', '복잡한', '복합적인', '', ''),
('word', '중2', 7, 'concept', '개념', '생각', '', ''),
('word', '중2', 7, 'concern', '걱정', '관련되다', '', ''),
('word', '중2', 7, 'conclude', '결론 내리다', '마무리하다', '', ''),
('word', '중2', 7, 'condition', '상태', '조건', '', ''),
('word', '중2', 7, 'confirm', '확인하다', '확정하다', '', ''),
('word', '중2', 7, 'conflict', '갈등', '충돌', '', ''),
('word', '중2', 7, 'connect', '연결하다', '관련시키다', '', ''),
('word', '중2', 7, 'consider', '고려하다', '생각하다', '', ''),
('word', '중2', 8, 'constant', '지속적인', '변하지 않는', '', ''),
('word', '중2', 8, 'construct', '건설하다', '구성하다', '', ''),
('word', '중2', 8, 'contact', '접촉', '연락', '', ''),
('word', '중2', 8, 'contain', '포함하다', '담고 있다', '', ''),
('word', '중2', 8, 'content', '내용', '만족하는', '', ''),
('word', '중2', 8, 'continue', '계속하다', '이어지다', '', ''),
('word', '중2', 8, 'contrast', '대조', '대조하다', '', ''),
('word', '중2', 8, 'contribute', '기여하다', '공헌하다', '', ''),
('word', '중2', 8, 'control', '통제하다', '조절하다', '', ''),
('word', '중2', 8, 'convince', '설득하다', '확신시키다', '', ''),
('word', '중2', 8, 'cooperate', '협력하다', '협동하다', '', ''),
('word', '중2', 8, 'core', '핵심', '중심', '', ''),
('word', '중2', 8, 'create', '창조하다', '만들다', '', ''),
('word', '중2', 8, 'culture', '문화', '생활 방식', '', ''),
('word', '중2', 8, 'damage', '손상', '해를 끼치다', '', ''),
('word', '중2', 8, 'debate', '토론', '논쟁', '', ''),
('word', '중2', 8, 'decade', '10년', '십 년의 기간', '', ''),
('word', '중2', 8, 'decide', '결정하다', '판단하다', '', ''),
('word', '중2', 8, 'define', '정의하다', '의미를 규정하다', '', ''),
('word', '중2', 8, 'delay', '지연', '미루다', '', ''),
('word', '중2', 9, 'deliver', '배달하다', '전달하다', '', ''),
('word', '중2', 9, 'demand', '요구', '요구하다', '', ''),
('word', '중2', 9, 'depend', '의존하다', '~에 달려 있다', '', ''),
('word', '중2', 9, 'describe', '묘사하다', '설명하다', '', ''),
('word', '중2', 9, 'design', '설계하다', '디자인', '', ''),
('word', '중2', 9, 'determine', '결정하다', '판단하다', '', ''),
('word', '중2', 9, 'develop', '발전시키다', '개발하다', '', ''),
('word', '중2', 9, 'device', '장치', '기기', '', ''),
('word', '중2', 9, 'disaster', '재난', '큰 사고', '', ''),
('word', '중2', 9, 'discover', '발견하다', '알아내다', '', ''),
('word', '중2', 9, 'discuss', '논의하다', '토론하다', '', ''),
('word', '중2', 9, 'display', '보여주다', '전시하다', '', ''),
('word', '중2', 9, 'distant', '먼', '멀리 떨어진', '', ''),
('word', '중2', 9, 'distinct', '뚜렷한', '구별되는', '', ''),
('word', '중2', 9, 'district', '지역', '구역', '', ''),
('word', '중2', 9, 'diverse', '다양한', '서로 다른', '', ''),
('word', '중2', 9, 'domestic', '국내의', '가정의', '', ''),
('word', '중2', 9, 'duty', '의무', '임무', '', ''),
('word', '중2', 9, 'dynamic', '역동적인', '활발한', '', ''),
('word', '중2', 9, 'earn', '벌다', '획득하다', '', ''),
('word', '중2', 10, 'economic', '경제의', '경제적인', '', ''),
('word', '중2', 10, 'educate', '교육하다', '가르치다', '', ''),
('word', '중2', 10, 'effect', '영향', '효과', '', ''),
('word', '중2', 10, 'efficient', '효율적인', '능률적인', '', ''),
('word', '중2', 10, 'elder', '연장자', '손윗사람', '', ''),
('word', '중2', 10, 'elect', '선출하다', '선택하다', '', ''),
('word', '중2', 10, 'element', '요소', '성분', '', ''),
('word', '중2', 10, 'eliminate', '제거하다', '없애다', '', ''),
('word', '중2', 10, 'emerge', '나타나다', '드러나다', '', ''),
('word', '중2', 10, 'emergency', '비상사태', '긴급 상황', '', ''),
('word', '중2', 10, 'emotion', '감정', '정서', '', ''),
('word', '중2', 10, 'emphasize', '강조하다', '두드러지게 하다', '', ''),
('word', '중2', 10, 'employ', '고용하다', '사용하다', '', ''),
('word', '중2', 10, 'employee', '직원', '근로자', '', ''),
('word', '중2', 10, 'employer', '고용주', '사용자', '', ''),
('word', '중2', 10, 'enable', '가능하게 하다', '허락하다', '', ''),
('word', '중2', 10, 'encounter', '우연히 만나다', '마주치다', '', ''),
('word', '중2', 10, 'encourage', '격려하다', '용기를 주다', '', ''),
('word', '중2', 10, 'energy', '에너지', '활력', '', ''),
('word', '중2', 10, 'engine', '엔진', '기관', '', ''),
('word', '중2', 11, 'engineer', '엔지니어', '기술자', '', ''),
('word', '중2', 11, 'ensure', '확실하게 하다', '보장하다', '', ''),
('word', '중2', 11, 'entire', '전체의', '전부의', '', ''),
('word', '중2', 11, 'entry', '입장', '기록', '', ''),
('word', '중2', 11, 'environment', '환경', '주변 환경', '', ''),
('word', '중2', 11, 'equal', '동등한', '같은', '', ''),
('word', '중2', 11, 'equipment', '장비', '설비', '', ''),
('word', '중2', 11, 'escape', '탈출하다', '벗어나다', '', ''),
('word', '중2', 11, 'essential', '필수적인', '매우 중요한', '', ''),
('word', '중2', 11, 'establish', '설립하다', '확립하다', '', ''),
('word', '중2', 11, 'estate', '재산', '부동산', '', ''),
('word', '중2', 11, 'estimate', '추정하다', '평가하다', '', ''),
('word', '중2', 11, 'evaluate', '평가하다', '판단하다', '', ''),
('word', '중2', 11, 'event', '사건', '행사', '', ''),
('word', '중2', 11, 'evidence', '증거', '근거', '', ''),
('word', '중2', 11, 'evolve', '진화하다', '발전하다', '', ''),
('word', '중2', 11, 'exact', '정확한', '정확히', '', ''),
('word', '중2', 11, 'examine', '조사하다', '검사하다', '', ''),
('word', '중2', 11, 'exchange', '교환하다', '교환', '', ''),
('word', '중2', 11, 'excite', '흥분시키다', '자극하다', '', ''),
('word', '중2', 12, 'exercise', '운동', '연습', '', ''),
('word', '중2', 12, 'exist', '존재하다', '실재하다', '', ''),
('word', '중2', 12, 'expand', '확장하다', '넓히다', '', ''),
('word', '중2', 12, 'expect', '기대하다', '예상하다', '', ''),
('word', '중2', 12, 'expense', '비용', '지출', '', ''),
('word', '중2', 12, 'experience', '경험', '체험', '', ''),
('word', '중2', 12, 'expert', '전문가', '숙련된', '', ''),
('word', '중2', 12, 'explain', '설명하다', '이해시키다', '', ''),
('word', '중2', 12, 'explore', '탐구하다', '조사하다', '', ''),
('word', '중2', 12, 'express', '표현하다', '나타내다', '', ''),
('word', '중2', 12, 'extra', '추가의', '여분의', '', ''),
('word', '중2', 12, 'factor', '요인', '요소', '', ''),
('word', '중2', 12, 'failure', '실패', '실패한 일', '', ''),
('word', '중2', 12, 'familiar', '익숙한', '친숙한', '', ''),
('word', '중2', 12, 'feature', '특징', '특성', '', ''),
('word', '중2', 12, 'federal', '연방의', '연방 정부의', '', ''),
('word', '중2', 12, 'finance', '재정', '자금을 조달하다', '', ''),
('word', '중2', 12, 'focus', '집중하다', '초점', '', ''),
('word', '중2', 12, 'force', '힘', '강요하다', '', ''),
('word', '중2', 12, 'foreign', '외국의', '해외의', '', ''),
('word', '중2', 13, 'formal', '공식적인', '격식을 차린', '', ''),
('word', '중2', 13, 'former', '이전의', '전자의', '', ''),
('word', '중2', 13, 'foundation', '기초', '재단', '', ''),
('word', '중2', 13, 'frequent', '빈번한', '자주 일어나는', '', ''),
('word', '중2', 13, 'function', '기능', '작용', '', ''),
('word', '중2', 13, 'fund', '기금', '자금을 대다', '', ''),
('word', '중2', 13, 'gain', '얻다', '증가', '', ''),
('word', '중2', 13, 'general', '일반적인', '전반적인', '', ''),
('word', '중2', 13, 'generate', '생성하다', '발생시키다', '', ''),
('word', '중2', 13, 'global', '세계적인', '전 세계의', '', ''),
('word', '중2', 13, 'goal', '목표', '목적', '', ''),
('word', '중2', 13, 'grade', '등급', '학년', '', ''),
('word', '중2', 13, 'grant', '허가하다', '보조금', '', ''),
('word', '중2', 13, 'growth', '성장', '증가', '', ''),
('word', '중2', 13, 'guide', '안내하다', '가이드', '', ''),
('word', '중2', 13, 'habit', '습관', '버릇', '', ''),
('word', '중2', 13, 'handle', '다루다', '처리하다', '', ''),
('word', '중2', 13, 'harm', '해', '해치다', '', ''),
('word', '중2', 13, 'headline', '표제', '헤드라인', '', ''),
('word', '중2', 13, 'health', '건강', '보건', '', ''),
('word', '중2', 14, 'height', '높이', '키', '', ''),
('word', '중2', 14, 'highlight', '강조하다', '주요 부분', '', ''),
('word', '중2', 14, 'historical', '역사적인', '역사상의', '', ''),
('word', '중2', 14, 'honor', '명예', '존경하다', '', ''),
('word', '중2', 14, 'host', '주최하다', '주인', '', ''),
('word', '중2', 14, 'household', '가정의', '가구', '', ''),
('word', '중2', 14, 'human', '인간', '사람의', '', ''),
('word', '중2', 14, 'ideal', '이상적인', '이상', '', ''),
('word', '중2', 14, 'identify', '확인하다', '식별하다', '', ''),
('word', '중2', 14, 'ignore', '무시하다', '외면하다', '', ''),
('word', '중2', 14, 'illustrate', '설명하다', '예시하다', '', ''),
('word', '중2', 14, 'image', '이미지', '상', '', ''),
('word', '중2', 14, 'impact', '영향', '충격', '', ''),
('word', '중2', 14, 'import', '수입하다', '들여오다', '', ''),
('word', '중2', 14, 'importance', '중요성', '중요함', '', ''),
('word', '중2', 14, 'impress', '감명을 주다', '인상을 남기다', '', ''),
('word', '중2', 14, 'improve', '개선하다', '향상시키다', '', ''),
('word', '중2', 14, 'include', '포함하다', '넣다', '', ''),
('word', '중2', 14, 'income', '수입', '소득', '', ''),
('word', '중2', 14, 'increase', '증가하다', '늘리다', '', ''),
('word', '중2', 15, 'independent', '독립적인', '자립한', '', ''),
('word', '중2', 15, 'indicate', '나타내다', '가리키다', '', ''),
('word', '중2', 15, 'individual', '개인의', '개인', '', ''),
('word', '중2', 15, 'influence', '영향', '영향을 주다', '', ''),
('word', '중2', 15, 'inform', '알리다', '통지하다', '', ''),
('word', '중2', 15, 'innovation', '혁신', '새로운 변화', '', ''),
('word', '중2', 15, 'issue', '문제', '발행하다', '', ''),
('word', '중2', 15, 'justice', '정의', '공정함', '', ''),
('word', '중2', 15, 'labor', '노동', '일', '', ''),
('word', '중2', 15, 'landscape', '풍경', '경관', '', ''),
('word', '중2', 15, 'latest', '최신의', '가장 최근의', '', ''),
('word', '중2', 15, 'legal', '법적인', '합법의', '', ''),
('word', '중2', 15, 'limit', '한계', '제한하다', '', ''),
('word', '중2', 15, 'local', '지역의', '현지의', '', ''),
('word', '중2', 15, 'locate', '위치를 찾다', '위치시키다', '', ''),
('word', '중2', 15, 'maintain', '유지하다', '지속하다', '', ''),
('word', '중2', 15, 'major', '주요한', '전공', '', ''),
('word', '중2', 15, 'majority', '대다수', '과반수', '', ''),
('word', '중2', 15, 'manage', '관리하다', '해내다', '', ''),
('word', '중2', 15, 'manner', '방식', '태도', '', ''),
('word', '중2', 16, 'material', '재료', '물질', '', ''),
('word', '중2', 16, 'measure', '측정하다', '조치', '', ''),
('word', '중2', 16, 'medical', '의학의', '의료의', '', ''),
('word', '중2', 16, 'memory', '기억', '기억력', '', ''),
('word', '중2', 16, 'mental', '정신의', '마음의', '', ''),
('word', '중2', 16, 'method', '방법', '방식', '', ''),
('word', '중2', 16, 'middle', '중간', '가운데의', '', ''),
('word', '중2', 16, 'military', '군대의', '군사의', '', ''),
('word', '중2', 16, 'modern', '현대의', '근대의', '', ''),
('word', '중2', 16, 'moment', '순간', '때', '', ''),
('word', '중2', 16, 'monitor', '감시하다', '관찰하다', '', ''),
('word', '중2', 16, 'nation', '국가', '민족', '', ''),
('word', '중2', 16, 'native', '토착의', '원주민', '', ''),
('word', '중2', 16, 'nature', '자연', '본성', '', ''),
('word', '중2', 16, 'necessary', '필요한', '필수의', '', ''),
('word', '중2', 16, 'network', '망', '네트워크', '', ''),
('word', '중2', 16, 'notice', '알아차리다', '공지', '', ''),
('word', '중2', 16, 'object', '물체', '목표', '', ''),
('word', '중2', 16, 'observe', '관찰하다', '지켜보다', '', ''),
('word', '중2', 16, 'obtain', '얻다', '획득하다', '', ''),
('word', '중2', 17, 'occasion', '경우', '행사', '', ''),
('word', '중2', 17, 'occupy', '차지하다', '점령하다', '', ''),
('word', '중2', 17, 'offer', '제공하다', '제안하다', '', ''),
('word', '중2', 17, 'official', '공식적인', '공무원', '', ''),
('word', '중2', 17, 'operate', '작동하다', '운영하다', '', ''),
('word', '중2', 17, 'operation', '작업', '수술', '', ''),
('word', '중2', 17, 'opinion', '의견', '생각', '', ''),
('word', '중2', 17, 'opponent', '상대', '반대자', '', ''),
('word', '중2', 17, 'opportunity', '기회', '좋은 상황', '', ''),
('word', '중2', 17, 'option', '선택', '선택권', '', ''),
('word', '중2', 17, 'order', '순서', '명령', '', ''),
('word', '중2', 17, 'ordinary', '평범한', '보통의', '', ''),
('word', '중2', 17, 'organize', '조직하다', '정리하다', '', ''),
('word', '중2', 17, 'origin', '기원', '출신', '', ''),
('word', '중2', 17, 'output', '생산량', '출력', '', ''),
('word', '중2', 17, 'overall', '전체의', '전반적인', '', ''),
('word', '중2', 17, 'package', '꾸러미', '포장하다', '', ''),
('word', '중2', 17, 'panel', '판', '위원회', '', ''),
('word', '중2', 17, 'participate', '참여하다', '참가하다', '', ''),
('word', '중2', 17, 'pattern', '패턴', '양식', '', ''),
('word', '중2', 18, 'peace', '평화', '평온', '', ''),
('word', '중2', 18, 'perform', '수행하다', '공연하다', '', ''),
('word', '중2', 18, 'period', '기간', '시기', '', ''),
('word', '중2', 18, 'periodic', '주기적인', '정기적인', '', ''),
('word', '중2', 18, 'permit', '허가하다', '허가', '', ''),
('word', '중2', 18, 'personal', '개인의', '사적인', '', ''),
('word', '중2', 18, 'persuade', '설득하다', '납득시키다', '', ''),
('word', '중2', 18, 'phase', '단계', '국면', '', ''),
('word', '중2', 18, 'physical', '신체의', '물리적인', '', ''),
('word', '중2', 18, 'policy', '정책', '방침', '', ''),
('word', '중2', 18, 'portion', '부분', '일부', '', ''),
('word', '중2', 18, 'positive', '긍정적인', '확신하는', '', ''),
('word', '중2', 18, 'potential', '잠재적인', '잠재력', '', ''),
('word', '중2', 18, 'practical', '실용적인', '현실적인', '', ''),
('word', '중2', 18, 'precise', '정확한', '정밀한', '', ''),
('word', '중2', 18, 'predict', '예측하다', '예상하다', '', ''),
('word', '중2', 18, 'prefer', '선호하다', '더 좋아하다', '', ''),
('word', '중2', 18, 'prepare', '준비하다', '대비하다', '', ''),
('word', '중2', 18, 'principal', '교장', '주요한', '', ''),
('word', '중2', 18, 'principle', '원칙', '원리', '', ''),
('word', '중2', 19, 'priority', '우선순위', '우선사항', '', ''),
('word', '중2', 19, 'private', '개인의', '사적인', '', ''),
('word', '중2', 19, 'process', '과정', '처리하다', '', ''),
('word', '중2', 19, 'produce', '생산하다', '만들다', '', ''),
('word', '중2', 19, 'progress', '진행', '발전', '', ''),
('word', '중2', 19, 'project', '프로젝트', '계획된 일', '', ''),
('word', '중2', 19, 'protect', '보호하다', '지키다', '', ''),
('word', '중2', 19, 'provide', '제공하다', '공급하다', '', ''),
('word', '중2', 19, 'purpose', '목적', '의도', '', ''),
('word', '중2', 19, 'reduce', '줄이다', '감소시키다', '', ''),
('word', '중2', 19, 'reflect', '반영하다', '비추다', '', ''),
('word', '중2', 19, 'region', '지역', '지방', '', ''),
('word', '중2', 19, 'remain', '남다', '계속 있다', '', ''),
('word', '중2', 19, 'research', '연구', '조사', '', ''),
('word', '중2', 19, 'respond', '응답하다', '반응하다', '', ''),
('word', '중2', 19, 'result', '결과', '결과를 낳다', '', ''),
('word', '중2', 19, 'role', '역할', '임무', '', ''),
('word', '중2', 19, 'select', '선택하다', '고르다', '', ''),
('word', '중2', 19, 'share', '공유하다', '나누다', '', ''),
('word', '중2', 19, 'significant', '중요한', '의미 있는', '', ''),
('word', '중2', 20, 'similar', '비슷한', '유사한', '', ''),
('word', '중2', 20, 'solution', '해결책', '답', '', ''),
('word', '중2', 20, 'solve', '해결하다', '풀다', '', ''),
('word', '중2', 20, 'source', '원천', '출처', '', ''),
('word', '중2', 20, 'strategy', '전략', '계획', '', ''),
('word', '중2', 20, 'structure', '구조', '구성', '', ''),
('word', '중2', 20, 'suggest', '제안하다', '암시하다', '', ''),
('word', '중2', 20, 'support', '지지하다', '도와주다', '', ''),
('word', '중2', 20, 'system', '체계', '시스템', '', ''),
('word', '중2', 20, 'target', '목표', '대상', '', ''),
('word', '중2', 20, 'technology', '기술', '과학기술', '', ''),
('word', '중2', 20, 'temporary', '일시적인', '임시의', '', ''),
('word', '중2', 20, 'theory', '이론', '학설', '', ''),
('word', '중2', 20, 'tradition', '전통', '관습', '', ''),
('word', '중2', 20, 'transfer', '이동하다', '옮기다', '', ''),
('word', '중2', 20, 'transport', '운송하다', '수송하다', '', ''),
('word', '중2', 20, 'value', '가치', '중요성', '', ''),
('word', '중2', 20, 'various', '다양한', '여러 가지의', '', ''),
('word', '중2', 20, 'vehicle', '차량', '운송 수단', '', ''),
('word', '중2', 20, 'vision', '비전', '미래상', '', ''),
('word', '중3', 1, 'abandon', '버리다', '포기하다', '', ''),
('word', '중3', 1, 'absorb', '흡수하다', '몰두하게 하다', '', ''),
('word', '중3', 1, 'abstract', '추상적인', '요약', '', ''),
('word', '중3', 1, 'accelerate', '가속하다', '속도를 높이다', '', ''),
('word', '중3', 1, 'acclaim', '칭찬하다', '갈채', '', ''),
('word', '중3', 1, 'acknowledge', '인정하다', '감사 표시를 하다', '', ''),
('word', '중3', 1, 'acorn', '도토리', '참나무 열매', '', ''),
('word', '중3', 1, 'acquire', '얻다', '습득하다', '', ''),
('word', '중3', 1, 'addict', '중독자', '중독시키다', '', ''),
('word', '중3', 1, 'additional', '추가의', '덧붙인', '', ''),
('word', '중3', 1, 'adhesive', '접착제', '붙이는', '', ''),
('word', '중3', 1, 'adolescent', '청소년', '사춘기의', '', ''),
('word', '중3', 1, 'advise', '조언하다', '권고하다', '', ''),
('word', '중3', 1, 'aerobic', '유산소의', '에어로빅', '', ''),
('word', '중3', 1, 'affirm', '확인하다', '단언하다', '', ''),
('word', '중3', 1, 'affordable', '살 만한', '가격이 적당한', '', ''),
('word', '중3', 1, 'afterward', '그 후에', '나중에', '', ''),
('word', '중3', 1, 'aggressive', '공격적인', '적극적인', '', ''),
('word', '중3', 1, 'aisle', '통로', '복도', '', ''),
('word', '중3', 1, 'ambitious', '야망 있는', '원대한', '', ''),
('word', '중3', 2, 'anticipate', '예상하다', '기대하다', '', ''),
('word', '중3', 2, 'approximate', '대략의', '근사한', '', ''),
('word', '중3', 2, 'attribute', '속성', '~의 탓으로 돌리다', '', ''),
('word', '중3', 2, 'authorize', '허가하다', '권한을 주다', '', ''),
('word', '중3', 2, 'bacteria', '세균', '박테리아', '', ''),
('word', '중3', 2, 'badge', '배지', '신분증', '', ''),
('word', '중3', 2, 'balcony', '발코니', '난간 있는 공간', '', ''),
('word', '중3', 2, 'bamboo', '대나무', '대나무 재료', '', ''),
('word', '중3', 2, 'barber', '이발사', '이발소', '', ''),
('word', '중3', 2, 'barely', '간신히', '거의~않게', '', ''),
('word', '중3', 2, 'bargain', '흥정', '싼 물건', '', ''),
('word', '중3', 2, 'battery', '배터리', '전지', '', ''),
('word', '중3', 2, 'beard', '수염', '턱수염', '', ''),
('word', '중3', 2, 'beehive', '벌집', '양봉장', '', ''),
('word', '중3', 2, 'behave', '행동하다', '예의 있게 굴다', '', ''),
('word', '중3', 2, 'beneath', '~아래에', '~밑에서', '', ''),
('word', '중3', 2, 'betray', '배신하다', '드러내다', '', ''),
('word', '중3', 2, 'beverage', '음료', '마실 것', '', ''),
('word', '중3', 2, 'bilingual', '이중 언어의', '두 언어 사용자의', '', ''),
('word', '중3', 2, 'biscuit', '비스킷', '과자', '', ''),
('word', '중3', 3, 'blanket', '담요', '덮개', '', ''),
('word', '중3', 3, 'blend', '섞다', '혼합', '', ''),
('word', '중3', 3, 'cabin', '오두막', '객실', '', ''),
('word', '중3', 3, 'cactus', '선인장', '가시 식물', '', ''),
('word', '중3', 3, 'cafeteria', '식당', '구내식당', '', ''),
('word', '중3', 3, 'calculator', '계산기', '계산 도구', '', ''),
('word', '중3', 3, 'campfire', '모닥불', '야영 불', '', ''),
('word', '중3', 3, 'canoe', '카누', '좁은 배', '', ''),
('word', '중3', 3, 'capable', '유능한', '~할 수 있는', '', ''),
('word', '중3', 3, 'carpenter', '목수', '목공', '', ''),
('word', '중3', 3, 'carpet', '카펫', '양탄자', '', ''),
('word', '중3', 3, 'carriage', '마차', '객차', '', ''),
('word', '중3', 3, 'carrier', '운반자', '통신사', '', ''),
('word', '중3', 3, 'cartoon', '만화', '풍자 그림', '', ''),
('word', '중3', 3, 'cashier', '계산원', '출납원', '', ''),
('word', '중3', 3, 'catalog', '목록', '카탈로그', '', ''),
('word', '중3', 3, 'caterpillar', '애벌레', '유충', '', ''),
('word', '중3', 3, 'cautious', '조심스러운', '신중한', '', ''),
('word', '중3', 3, 'cease', '중단하다', '그만두다', '', ''),
('word', '중3', 3, 'ceiling', '천장', '상한', '', ''),
('word', '중3', 4, 'cellphone', '휴대전화', '핸드폰', '', ''),
('word', '중3', 4, 'circulate', '순환하다', '돌리다', '', ''),
('word', '중3', 4, 'coherent', '일관된', '조리 있는', '', ''),
('word', '중3', 4, 'coincide', '일치하다', '동시에 일어나다', '', ''),
('word', '중3', 4, 'collapse', '붕괴하다', '쓰러지다', '', ''),
('word', '중3', 4, 'commitment', '약속', '헌신', '', ''),
('word', '중3', 4, 'complicate', '복잡하게 하다', '곤란하게 하다', '', ''),
('word', '중3', 4, 'compose', '구성하다', '작곡하다', '', ''),
('word', '중3', 4, 'compromise', '타협', '타협하다', '', ''),
('word', '중3', 4, 'concentrate', '집중하다', '농축하다', '', ''),
('word', '중3', 4, 'conscious', '의식하는', '의식이 있는', '', ''),
('word', '중3', 4, 'conservation', '보존', '자원 절약', '', ''),
('word', '중3', 4, 'considerable', '상당한', '꽤 많은', '', ''),
('word', '중3', 4, 'constraint', '제약', '제한', '', ''),
('word', '중3', 4, 'consultation', '상담', '협의', '', ''),
('word', '중3', 4, 'consumption', '소비', '소모', '', ''),
('word', '중3', 4, 'contemplate', '숙고하다', '곰곰이 생각하다', '', ''),
('word', '중3', 4, 'convention', '관습', '대회', '', ''),
('word', '중3', 4, 'coordinate', '조정하다', '조직하다', '', ''),
('word', '중3', 4, 'correspondence', '서신', '일치', '', ''),
('word', '중3', 5, 'criterion', '기준', '표준', '', ''),
('word', '중3', 5, 'cultivate', '기르다', '함양하다', '', ''),
('word', '중3', 5, 'daily', '매일의', '일간', '', ''),
('word', '중3', 5, 'dairy', '유제품의', '낙농장', '', ''),
('word', '중3', 5, 'dandelion', '민들레', '들꽃', '', ''),
('word', '중3', 5, 'deadline', '마감', '기한', '', ''),
('word', '중3', 5, 'decent', '괜찮은', '예의 바른', '', ''),
('word', '중3', 5, 'decorate', '장식하다', '꾸미다', '', ''),
('word', '중3', 5, 'deeply', '깊이', '진심으로', '', ''),
('word', '중3', 5, 'defend', '방어하다', '변호하다', '', ''),
('word', '중3', 5, 'deficit', '적자', '부족', '', ''),
('word', '중3', 5, 'definitely', '분명히', '확실히', '', ''),
('word', '중3', 5, 'density', '밀도', '짙음', '', ''),
('word', '중3', 5, 'dentist', '치과의사', '치과', '', ''),
('word', '중3', 5, 'deposit', '예금', '맡기다', '', ''),
('word', '중3', 5, 'derive', '얻다', '유래하다', '', ''),
('word', '중3', 5, 'dessert', '디저트', '후식', '', ''),
('word', '중3', 5, 'detect', '발견하다', '감지하다', '', ''),
('word', '중3', 5, 'detective', '형사', '탐정', '', ''),
('word', '중3', 5, 'deviation', '일탈', '편차', '', ''),
('word', '중3', 6, 'devote', '바치다', '전념하다', '', ''),
('word', '중3', 6, 'diagnose', '진단하다', '원인을 규명하다', '', ''),
('word', '중3', 6, 'diagram', '도표', '그림으로 설명하다', '', ''),
('word', '중3', 6, 'differentiate', '구별하다', '차별화하다', '', ''),
('word', '중3', 6, 'dimension', '차원', '크기', '', ''),
('word', '중3', 6, 'discriminate', '구별하다', '차별하다', '', ''),
('word', '중3', 6, 'disposal', '처리', '폐기', '', ''),
('word', '중3', 6, 'diversity', '다양성', '다양함', '', ''),
('word', '중3', 6, 'earring', '귀걸이', '장식품', '', ''),
('word', '중3', 6, 'earthquake', '지진', '땅 흔들림', '', ''),
('word', '중3', 6, 'ebook', '전자책', '이북', '', ''),
('word', '중3', 6, 'economical', '경제적인', '절약되는', '', ''),
('word', '중3', 6, 'elaborate', '정교한', '자세히 설명하다', '', ''),
('word', '중3', 6, 'elderly', '연세 많은', '노인', '', ''),
('word', '중3', 6, 'elevator', '엘리베이터', '승강기', '', ''),
('word', '중3', 6, 'embarrass', '당황하게 하다', '창피하게 하다', '', ''),
('word', '중3', 6, 'emoji', '이모지', '그림 문자', '', ''),
('word', '중3', 6, 'emphasis', '강조', '중점', '', ''),
('word', '중3', 6, 'endanger', '위험에 빠뜨리다', '위협하다', '', ''),
('word', '중3', 6, 'endless', '끝없는', '무한한', '', ''),
('word', '중3', 7, 'enforce', '집행하다', '강제하다', '', ''),
('word', '중3', 7, 'enhancement', '향상', '개선', '', ''),
('word', '중3', 7, 'entity', '실체', '존재', '', ''),
('word', '중3', 7, 'envelope', '봉투', '우편 봉투', '', ''),
('word', '중3', 7, 'eraser', '지우개', '삭제 도구', '', ''),
('word', '중3', 7, 'essay', '에세이', '수필', '', ''),
('word', '중3', 7, 'everyday', '일상의', '매일의', '', ''),
('word', '중3', 7, 'exactly', '정확히', '바로', '', ''),
('word', '중3', 7, 'exclude', '제외하다', '배제하다', '', ''),
('word', '중3', 7, 'exhibit', '전시하다', '전시품', '', ''),
('word', '중3', 7, 'fable', '우화', '교훈 이야기', '', ''),
('word', '중3', 7, 'fairness', '공정함', '공평', '', ''),
('word', '중3', 7, 'fancy', '화려한', '원하다', '', ''),
('word', '중3', 7, 'fascinate', '매혹하다', '흥미를 끌다', '', ''),
('word', '중3', 7, 'fashion', '패션', '유행', '', ''),
('word', '중3', 7, 'fault', '결점', '잘못', '', ''),
('word', '중3', 7, 'feather', '깃털', '깃', '', ''),
('word', '중3', 7, 'fever', '열', '열병', '', ''),
('word', '중3', 7, 'filter', '거르다', '필터', '', ''),
('word', '중3', 7, 'financial', '재정의', '금융의', '', ''),
('word', '중3', 8, 'fingerprint', '지문', '손가락 자국', '', ''),
('word', '중3', 8, 'firework', '불꽃놀이', '폭죽', '', ''),
('word', '중3', 8, 'firmly', '단단히', '확고히', '', ''),
('word', '중3', 8, 'fisherman', '어부', '낚시꾼', '', ''),
('word', '중3', 8, 'flame', '불꽃', '화염', '', ''),
('word', '중3', 8, 'flashlight', '손전등', '플래시', '', ''),
('word', '중3', 8, 'flatten', '납작하게 하다', '평평하게 하다', '', ''),
('word', '중3', 8, 'flavor', '맛', '풍미', '', ''),
('word', '중3', 8, 'gadget', '작은 기계', '신기한 물건', '', ''),
('word', '중3', 8, 'galaxy', '은하', '은하계', '', ''),
('word', '중3', 8, 'gallery', '미술관', '갤러리', '', ''),
('word', '중3', 8, 'garage', '차고', '정비소', '', ''),
('word', '중3', 8, 'garbage', '쓰레기', '폐기물', '', ''),
('word', '중3', 8, 'garlic', '마늘', '향신 채소', '', ''),
('word', '중3', 8, 'gasoline', '휘발유', '가솔린', '', ''),
('word', '중3', 8, 'gateway', '출입구', '관문', '', ''),
('word', '중3', 8, 'generous', '관대한', '후한', '', ''),
('word', '중3', 8, 'genuine', '진짜의', '진품의', '', ''),
('word', '중3', 8, 'geography', '지리', '지리학', '', ''),
('word', '중3', 8, 'gesture', '몸짓', '제스처', '', ''),
('word', '중3', 9, 'ginger', '생강', '생강색', '', ''),
('word', '중3', 9, 'glance', '흘끗 보다', '짧은 시선', '', ''),
('word', '중3', 9, 'goose', '거위', '거위고기', '', ''),
('word', '중3', 9, 'gossip', '소문', '수다', '', ''),
('word', '중3', 9, 'gradual', '점진적인', '서서히', '', ''),
('word', '중3', 9, 'grammar', '문법', '언어 규칙', '', ''),
('word', '중3', 9, 'grandparent', '조부모', '할아버지·할머니', '', ''),
('word', '중3', 9, 'grasp', '붙잡다', '이해하다', '', ''),
('word', '중3', 9, 'hacker', '해커', '침입자', '', ''),
('word', '중3', 9, 'hamburger', '햄버거', '버거', '', ''),
('word', '중3', 9, 'handy', '편리한', '손쉬운', '', ''),
('word', '중3', 9, 'hardly', '거의~않다', '간신히', '', ''),
('word', '중3', 9, 'hardware', '하드웨어', '기계 장치', '', ''),
('word', '중3', 9, 'harmful', '해로운', '유해한', '', ''),
('word', '중3', 9, 'harmonize', '조화를 이루다', '화음을 맞추다', '', ''),
('word', '중3', 9, 'harvest', '수확', '거두다', '', ''),
('word', '중3', 9, 'helicopter', '헬리콥터', '회전익기', '', ''),
('word', '중3', 9, 'helmet', '헬멧', '보호모', '', ''),
('word', '중3', 9, 'heroine', '여주인공', '여성 영웅', '', ''),
('word', '중3', 9, 'hesitate', '망설이다', '주저하다', '', ''),
('word', '중3', 10, 'hobby', '취미', '여가 활동', '', ''),
('word', '중3', 10, 'hockey', '하키', '아이스하키', '', ''),
('word', '중3', 10, 'horizon', '지평선', '시야', '', ''),
('word', '중3', 10, 'iceberg', '빙산', '거대한 얼음덩이', '', ''),
('word', '중3', 10, 'illegal', '불법의', '위법의', '', ''),
('word', '중3', 10, 'illness', '병', '질병', '', ''),
('word', '중3', 10, 'immediate', '즉각적인', '직접의', '', ''),
('word', '중3', 10, 'ingredient', '재료', '성분', '', ''),
('word', '중3', 10, 'injure', '다치게 하다', '상처 입히다', '', ''),
('word', '중3', 10, 'inquire', '문의하다', '묻다', '', ''),
('word', '중3', 10, 'insect', '곤충', '벌레', '', ''),
('word', '중3', 10, 'insist', '주장하다', '고집하다', '', ''),
('word', '중3', 10, 'inspire', '영감을 주다', '고무하다', '', ''),
('word', '중3', 10, 'install', '설치하다', '임명하다', '', ''),
('word', '중3', 10, 'instance', '사례', '경우', '', ''),
('word', '중3', 10, 'instead', '대신에', '그 대신', '', ''),
('word', '중3', 10, 'intense', '강렬한', '치열한', '', ''),
('word', '중3', 10, 'internet', '인터넷', '온라인망', '', ''),
('word', '중3', 10, 'interpret', '해석하다', '통역하다', '', ''),
('word', '중3', 10, 'interrupt', '방해하다', '가로막다', '', ''),
('word', '중3', 11, 'interview', '면접', '인터뷰하다', '', ''),
('word', '중3', 11, 'invitation', '초대장', '초대', '', ''),
('word', '중3', 11, 'jellyfish', '해파리', '수중 생물', '', ''),
('word', '중3', 11, 'journalist', '기자', '언론인', '', ''),
('word', '중3', 11, 'judge', '판사', '판단하다', '', ''),
('word', '중3', 11, 'junior', '후배', '하급의', '', ''),
('word', '중3', 11, 'justify', '정당화하다', '옳음을 보여주다', '', ''),
('word', '중3', 11, 'kettle', '주전자', '물 끓이는 용기', '', ''),
('word', '중3', 11, 'keyboard', '키보드', '자판', '', ''),
('word', '중3', 11, 'kingdom', '왕국', '나라', '', ''),
('word', '중3', 11, 'kitchenware', '주방용품', '조리 도구', '', ''),
('word', '중3', 11, 'label', '라벨', '분류하다', '', ''),
('word', '중3', 11, 'landing', '착륙', '상륙', '', ''),
('word', '중3', 11, 'lantern', '랜턴', '등불', '', ''),
('word', '중3', 11, 'laptop', '노트북', '휴대용 컴퓨터', '', ''),
('word', '중3', 11, 'laundry', '세탁', '빨래', '', ''),
('word', '중3', 11, 'lawyer', '변호사', '법률가', '', ''),
('word', '중3', 11, 'leaflet', '전단지', '소책자', '', ''),
('word', '중3', 11, 'leisure', '여가', '한가함', '', ''),
('word', '중3', 11, 'lemonade', '레모네이드', '레몬 음료', '', ''),
('word', '중3', 12, 'length', '길이', '기간', '', ''),
('word', '중3', 12, 'lesson', '수업', '교훈', '', ''),
('word', '중3', 12, 'librarian', '사서', '도서관 직원', '', ''),
('word', '중3', 12, 'lifeguard', '인명구조원', '안전요원', '', ''),
('word', '중3', 12, 'lifelong', '평생의', '일생의', '', ''),
('word', '중3', 12, 'lighthouse', '등대', '신호탑', '', ''),
('word', '중3', 12, 'lightning', '번개', '번쩍임', '', ''),
('word', '중3', 12, 'limitless', '끝없는', '무한한', '', ''),
('word', '중3', 12, 'lipstick', '립스틱', '입술 화장품', '', ''),
('word', '중3', 12, 'machine', '기계', '장치', '', ''),
('word', '중3', 12, 'magnet', '자석', '끌어당기는 것', '', ''),
('word', '중3', 12, 'mailbox', '우편함', '사서함', '', ''),
('word', '중3', 12, 'makeup', '화장', '구성', '', ''),
('word', '중3', 12, 'manufacture', '제조하다', '조작하다', '', ''),
('word', '중3', 12, 'marathon', '마라톤', '장거리 경기', '', ''),
('word', '중3', 12, 'marble', '대리석', '구슬', '', ''),
('word', '중3', 12, 'marketplace', '시장', '장터', '', ''),
('word', '중3', 12, 'massage', '마사지', '안마', '', ''),
('word', '중3', 12, 'massive', '거대한', '대규모의', '', ''),
('word', '중3', 12, 'mathematics', '수학', '산수', '', ''),
('word', '중3', 13, 'mattress', '매트리스', '침대 깔개', '', ''),
('word', '중3', 13, 'mature', '성숙한', '익다', '', ''),
('word', '중3', 13, 'meaningful', '의미 있는', '중요한', '', ''),
('word', '중3', 13, 'meanwhile', '그동안에', '한편', '', ''),
('word', '중3', 13, 'measurements', '치수', '측정값', '', ''),
('word', '중3', 13, 'medal', '메달', '훈장', '', ''),
('word', '중3', 13, 'medicine', '약', '의학', '', ''),
('word', '중3', 13, 'mention', '언급하다', '말하다', '', ''),
('word', '중3', 13, 'narrative', '이야기', '서술의', '', ''),
('word', '중3', 13, 'narrow', '좁은', '좁히다', '', ''),
('word', '중3', 13, 'nationwide', '전국적인', '전국적으로', '', ''),
('word', '중3', 13, 'necklace', '목걸이', '목 장식', '', ''),
('word', '중3', 13, 'needle', '바늘', '바늘로 꿰다', '', ''),
('word', '중3', 13, 'negative', '부정적인', '음성의', '', ''),
('word', '중3', 13, 'negotiate', '협상하다', '교섭하다', '', ''),
('word', '중3', 13, 'nickname', '별명', '애칭', '', ''),
('word', '중3', 13, 'nightmare', '악몽', '나쁜 꿈', '', ''),
('word', '중3', 13, 'notebook', '공책', '노트북', '', ''),
('word', '중3', 13, 'novelty', '새로움', '신제품', '', ''),
('word', '중3', 13, 'occur', '일어나다', '발생하다', '', ''),
('word', '중3', 14, 'octopus', '문어', '문어 요리', '', ''),
('word', '중3', 14, 'offend', '기분 상하게 하다', '위반하다', '', ''),
('word', '중3', 14, 'officer', '장교', '공무원', '', ''),
('word', '중3', 14, 'online', '온라인의', '인터넷으로', '', ''),
('word', '중3', 14, 'opera', '오페라', '가극', '', ''),
('word', '중3', 14, 'orbit', '궤도', '궤도를 돌다', '', ''),
('word', '중3', 14, 'orchard', '과수원', '과일나무 밭', '', ''),
('word', '중3', 14, 'organ', '장기', '기관', '', ''),
('word', '중3', 14, 'orient', '방향을 잡다', '적응시키다', '', ''),
('word', '중3', 14, 'outline', '개요', '윤곽을 그리다', '', ''),
('word', '중3', 14, 'overcome', '극복하다', '이겨내다', '', ''),
('word', '중3', 14, 'overseas', '해외의', '외국에', '', ''),
('word', '중3', 14, 'packet', '소포', '봉지', '', ''),
('word', '중3', 14, 'paddle', '노', '노를 젓다', '', ''),
('word', '중3', 14, 'pamphlet', '팸플릿', '소책자', '', ''),
('word', '중3', 14, 'panic', '공황', '당황하다', '', ''),
('word', '중3', 14, 'paperwork', '서류 작업', '문서 처리', '', ''),
('word', '중3', 14, 'parade', '퍼레이드', '행진', '', ''),
('word', '중3', 14, 'paragraph', '문단', '절', '', ''),
('word', '중3', 14, 'parental', '부모의', '보호자의', '', ''),
('word', '중3', 15, 'parrot', '앵무새', '따라 말하는 사람', '', ''),
('word', '중3', 15, 'particular', '특정한', '까다로운', '', ''),
('word', '중3', 15, 'passionate', '열정적인', '열렬한', '', ''),
('word', '중3', 15, 'passport', '여권', '여행 증명서', '', ''),
('word', '중3', 15, 'password', '비밀번호', '암호', '', ''),
('word', '중3', 15, 'patch', '패치', '덧대다', '', ''),
('word', '중3', 15, 'pathway', '통로', '길', '', ''),
('word', '중3', 15, 'patience', '인내', '끈기', '', ''),
('word', '중3', 15, 'patient', '환자', '인내심 있는', '', ''),
('word', '중3', 15, 'peanut', '땅콩', '땅콩 열매', '', ''),
('word', '중3', 15, 'pearl', '진주', '진주빛', '', ''),
('word', '중3', 15, 'quake', '지진', '흔들림', '', ''),
('word', '중3', 15, 'quarter', '4분의 1', '분기', '', ''),
('word', '중3', 15, 'questionnaire', '설문지', '질문표', '', ''),
('word', '중3', 15, 'queue', '줄', '줄을 서다', '', ''),
('word', '중3', 15, 'quickly', '빨리', '신속하게', '', ''),
('word', '중3', 15, 'quietly', '조용히', '차분히', '', ''),
('word', '중3', 15, 'quote', '인용하다', '견적을 내다', '', ''),
('word', '중3', 15, 'racquet', '라켓', '테니스 라켓', '', ''),
('word', '중3', 15, 'railway', '철도', '기찻길', '', ''),
('word', '중3', 16, 'rainbow', '무지개', '오색', '', ''),
('word', '중3', 16, 'raise', '올리다', '기르다', '', ''),
('word', '중3', 16, 'random', '무작위의', '임의의', '', ''),
('word', '중3', 16, 'rapid', '빠른', '급속한', '', ''),
('word', '중3', 16, 'rarely', '드물게', '좀처럼~않게', '', ''),
('word', '중3', 16, 'realize', '깨닫다', '실현하다', '', ''),
('word', '중3', 16, 'reasonable', '합리적인', '적당한', '', ''),
('word', '중3', 16, 'receipt', '영수증', '수령', '', ''),
('word', '중3', 16, 'recognize', '알아보다', '인정하다', '', ''),
('word', '중3', 16, 'recycle', '재활용하다', '순환시키다', '', ''),
('word', '중3', 16, 'refill', '다시 채우다', '리필', '', ''),
('word', '중3', 16, 'refrigerator', '냉장고', '냉장 장치', '', ''),
('word', '중3', 16, 'refund', '환불', '환불하다', '', ''),
('word', '중3', 16, 'refuse', '거절하다', '거부하다', '', ''),
('word', '중3', 16, 'regularly', '규칙적으로', '정기적으로', '', ''),
('word', '중3', 16, 'reject', '거절하다', '기각하다', '', ''),
('word', '중3', 16, 'relax', '쉬다', '긴장을 풀다', '', ''),
('word', '중3', 16, 'relay', '릴레이', '중계하다', '', ''),
('word', '중3', 16, 'sacrifice', '희생', '희생하다', '', ''),
('word', '중3', 16, 'salad', '샐러드', '야채무침', '', ''),
('word', '중3', 17, 'salary', '급여', '월급', '', ''),
('word', '중3', 17, 'sandal', '샌들', '슬리퍼', '', ''),
('word', '중3', 17, 'satellite', '위성', '위성의', '', ''),
('word', '중3', 17, 'satisfy', '만족시키다', '충족하다', '', ''),
('word', '중3', 17, 'sauce', '소스', '양념', '', ''),
('word', '중3', 17, 'scanner', '스캐너', '스캔 장치', '', ''),
('word', '중3', 17, 'science', '과학', '학문', '', ''),
('word', '중3', 17, 'scientist', '과학자', '연구자', '', ''),
('word', '중3', 17, 'seafood', '해산물', '수산물', '', ''),
('word', '중3', 17, 'seasonal', '계절의', '철따라', '', ''),
('word', '중3', 17, 'secretary', '비서', '서기', '', ''),
('word', '중3', 17, 'secure', '안전한', '확보하다', '', ''),
('word', '중3', 17, 'security', '보안', '안전', '', ''),
('word', '중3', 17, 'semester', '학기', '반기', '', ''),
('word', '중3', 17, 'sensible', '분별 있는', '실용적인', '', ''),
('word', '중3', 17, 'sentence', '문장', '형량', '', ''),
('word', '중3', 17, 'separate', '분리하다', '별개의', '', ''),
('word', '중3', 17, 'tablet', '태블릿', '알약', '', ''),
('word', '중3', 17, 'tackle', '대처하다', '태클', '', ''),
('word', '중3', 17, 'takeoff', '이륙', '출발', '', ''),
('word', '중3', 18, 'talented', '재능 있는', '소질 있는', '', ''),
('word', '중3', 18, 'tangerine', '귤', '감귤', '', ''),
('word', '중3', 18, 'teammate', '팀원', '동료', '', ''),
('word', '중3', 18, 'tension', '긴장', '팽팽함', '', ''),
('word', '중3', 18, 'terrible', '끔찍한', '매우 나쁜', '', ''),
('word', '중3', 18, 'terrify', '겁주다', '무섭게 하다', '', ''),
('word', '중3', 18, 'textbook', '교과서', '교재', '', ''),
('word', '중3', 18, 'textile', '직물', '섬유의', '', ''),
('word', '중3', 18, 'thermometer', '온도계', '체온계', '', ''),
('word', '중3', 18, 'threat', '위협', '협박', '', ''),
('word', '중3', 18, 'thunder', '천둥', '우레', '', ''),
('word', '중3', 18, 'tighten', '조이다', '강화하다', '', ''),
('word', '중3', 18, 'tolerate', '참다', '용인하다', '', ''),
('word', '중3', 18, 'ultimate', '최후의', '궁극적인', '', ''),
('word', '중3', 18, 'unable', '~할 수 없는', '무능한', '', ''),
('word', '중3', 18, 'underwear', '속옷', '내의', '', ''),
('word', '중3', 18, 'unfair', '불공평한', '부당한', '', ''),
('word', '중3', 18, 'unhealthy', '건강하지 않은', '해로운', '', ''),
('word', '중3', 18, 'unique', '독특한', '유일한', '', ''),
('word', '중3', 18, 'unite', '결합하다', '단결하다', '', ''),
('word', '중3', 19, 'universal', '보편적인', '전 세계의', '', ''),
('word', '중3', 19, 'universe', '우주', '천체', '', ''),
('word', '중3', 19, 'unknown', '알려지지 않은', '미지의', '', ''),
('word', '중3', 19, 'update', '갱신하다', '최신 정보', '', ''),
('word', '중3', 19, 'upload', '업로드하다', '올려 보내다', '', ''),
('word', '중3', 19, 'urban', '도시의', '도심의', '', ''),
('word', '중3', 19, 'vacuum', '진공', '진공청소기', '', ''),
('word', '중3', 19, 'valid', '유효한', '타당한', '', ''),
('word', '중3', 19, 'valley', '계곡', '골짜기', '', ''),
('word', '중3', 19, 'vegetable', '채소', '야채', '', ''),
('word', '중3', 19, 'venture', '모험', '위험을 감수하다', '', ''),
('word', '중3', 19, 'video', '비디오', '영상', '', ''),
('word', '중3', 19, 'viewpoint', '관점', '견해', '', ''),
('word', '중3', 19, 'violinist', '바이올린 연주자', '연주자', '', ''),
('word', '중3', 19, 'virus', '바이러스', '감염원', '', ''),
('word', '중3', 19, 'visible', '눈에 보이는', '뚜렷한', '', ''),
('word', '중3', 19, 'vocabulary', '어휘', '단어', '', ''),
('word', '중3', 19, 'waffle', '와플', '격자무늬', '', ''),
('word', '중3', 19, 'wallet', '지갑', '돈지갑', '', ''),
('word', '중3', 19, 'wander', '헤매다', '방랑하다', '', ''),
('word', '중3', 20, 'wasteful', '낭비하는', '쓸데없는', '', ''),
('word', '중3', 20, 'waterfall', '폭포', '낙수', '', ''),
('word', '중3', 20, 'waterproof', '방수의', '물이 스며들지 않는', '', ''),
('word', '중3', 20, 'wealthy', '부유한', '돈이 많은', '', ''),
('word', '중3', 20, 'webcam', '웹캠', '화상 카메라', '', ''),
('word', '중3', 20, 'website', '웹사이트', '인터넷 사이트', '', ''),
('word', '중3', 20, 'weekday', '평일', '주중', '', ''),
('word', '중3', 20, 'weigh', '무게를 재다', '고려하다', '', ''),
('word', '중3', 20, 'wheelchair', '휠체어', '바퀴 의자', '', ''),
('word', '중3', 20, 'whisper', '속삭이다', '속삭임', '', ''),
('word', '중3', 20, 'whistle', '휘파람', '호루라기', '', ''),
('word', '중3', 20, 'widen', '넓히다', '확대하다', '', ''),
('word', '중3', 20, 'willing', '기꺼이 하는', '자발적인', '', ''),
('word', '중3', 20, 'winner', '승자', '우승자', '', ''),
('word', '중3', 20, 'wintertime', '겨울철', '겨울의 때', '', ''),
('word', '중3', 20, 'xenon', '제논', '기체 원소', '', ''),
('word', '중3', 20, 'xylitol', '자일리톨', '감미료', '', ''),
('word', '중3', 20, 'xylophone', '실로폰', '타악기', '', ''),
('word', '중3', 20, 'yearly', '매년의', '연간의', '', ''),
('word', '중3', 20, 'yield', '산출하다', '수확량', '', '');
